/* Native key-pose puppeteering. No geometry export or second renderer needed. */
(()=>{
const $=id=>document.getElementById(id),W=window.__world;if(!W||!$('fb'))return;
const button=document.createElement('button');button.id='butterOpen';button.textContent='Actor keys';button.title='Move actors and animate poses in this scene';$('fb').append(button);
const panel=document.createElement('section');panel.id='butterPanel';panel.hidden=true;panel.innerHTML=`<div class="butterRow"><strong>ACTOR KEYS <small>Pose → keep → move time → pose again</small></strong><button id="butterClose">Done</button></div><div class="butterRow"><label>Actor <select id="butterActor"></select></label><label>Time <input id="butterTime" type="range" min="0" max="6" step=".05" value="0"><output id="butterClock">0.00 s</output></label><button id="butterFocus">Frame actor</button><button id="butterKeep">Keep pose</button><button id="butterPreview">Play shot</button><button id="butterUndo">Undo key edit</button></div><div class="butterRow"><div id="butterPad" tabindex="0" role="slider" aria-label="Actor position: drag to move across the floor, arrow keys to nudge">✥ Drag to move actor<br><small>Left / right · near / far</small></div><div id="butterJoints"></div></div><div class="butterRow"><label>Pose <select id="butterPreset"><option value="">Choose a pose…</option><option value="neutral">Stand</option><option value="reach">Reach / push</option><option value="recoil">Recoil</option><option value="kneel">Kneel</option><option value="strike">Raise sword</option></select></label><label>Travel <select id="butterGait"><option value="hold">Slide / hold pose</option><option value="walk">Walk between keys</option></select></label><button id="butterDelete">Delete nearest key</button><button id="butterExport">Save motion file</button><button id="butterImport">Load motion file</button><input id="butterFile" type="file" accept=".json,application/json" hidden></div><p id="butterStatus" role="status">Select an actor. Poses stay in this scene; no throwing or physics release.</p>`;$('cin-shots').append(panel);
const fields=[['heading','Facing',-180,180],['armL','Left arm',-160,90],['armR','Right arm',-160,90],['head','Head',-85,85],['lean','Lean',-60,60],['legL','Left leg',-100,90],['legR','Right leg',-100,90],['height','Lift',-2,4]];
$('butterJoints').innerHTML=fields.map(([k,n,min,max])=>`<label>${n}<input data-butter="${k}" aria-label="${n}" type="range" min="${min}" max="${max}" step="${k==='height'?'.05':'1'}"><output></output></label>`).join('');
let doc=null,sceneName='',selectedShot=null,draft=null,editing=false,time=0,undo=[],priorWrapped=null,drag=null;
const F=()=>W.film,shot=()=>F()?.shots[F().sel],actor=()=>F()?.actors.get($('butterActor').value),rad=Math.PI/180;
const status=t=>$('butterStatus').textContent=t;
const storeKey=()=> 'cinerium-butter-v1:'+sceneName;
function persist(){try{localStorage.setItem(storeKey(),JSON.stringify(doc));}catch(e){status('Storage unavailable. Save motion file to keep your work.');}}
function tracks(){return doc?.shots[shot()?.name]||{};}
function keys(name=$('butterActor').value){return tracks()[name]||[];}
function sample(list,t){if(!list.length)return null;let a=list[0],b=list[list.length-1];for(const k of list){if(k.t<=t)a=k;if(k.t>=t){b=k;break;}}const u=b.t===a.t?0:Math.max(0,Math.min(1,(t-a.t)/(b.t-a.t))),v=u*u*(3-2*u),o={...a};for(const k of ['x','z',...fields.map(f=>f[0])]){let d=b[k]-a[k];if(k==='heading')d=((d+540)%360)-180;o[k]=a[k]+d*v;}o.moving=u>0&&u<1&&Math.hypot(b.x-a.x,b.z-a.z)>.01;return o;}
function read(a){const r=a.rig,M=r.M,sp=F().sceneSpawn||W.spawn||{x:0,z:0};return {t:time,x:(r.pos.x-sp.x)/M,z:(r.pos.z-sp.z)/M,height:(r.pos.y-W.G.h(r.pos.x,r.pos.z))/M,heading:((r.heading/rad+540)%360)-180,armL:r.armLP.rotation.x/rad,armR:r.armRP.rotation.x/rad,head:r.headP.rotation.y/rad,lean:r.torsoP.rotation.x/rad,legL:r.legLP.rotation.x/rad,legR:r.legRP.rotation.x/rad,gait:'hold'};}
function apply(a,p,t){if(!a?.rig||!p)return;const r=a.rig,M=r.M,sp=F().sceneSpawn||W.spawn||{x:0,z:0},x=sp.x+p.x*M,z=sp.z+p.z*M;r.pos.x=x;r.pos.z=z;r.pos.y=W.G.h(x,z)+p.height*M;r.heading=p.heading*rad;r.figure.position.copy(r.pos);r.figure.rotation.y=r.heading;r.armLP.rotation.x=p.armL*rad;r.armRP.rotation.x=p.armR*rad;r.headP.rotation.y=p.head*rad;r.torsoP.rotation.x=p.lean*rad;const gait=p.gait==='walk'&&p.moving?Math.sin(t*9)*.48:0;r.legLP.rotation.x=p.legL*rad+gait;r.legRP.rotation.x=p.legR*rad-gait;}
function renderInputs(){if(!draft)return;panel.querySelectorAll('[data-butter]').forEach(el=>{el.value=draft[el.dataset.butter];el.nextElementSibling.textContent=(+el.value).toFixed(el.dataset.butter==='height'?2:0)+(el.dataset.butter==='height'?' m':'°');});$('butterGait').value=draft.gait||'hold';$('butterClock').textContent=time.toFixed(2)+' s';$('butterPad').setAttribute('aria-valuetext',`X ${draft.x.toFixed(1)}, Z ${draft.z.toFixed(1)} metres`);status(`${keys().length} kept poses · ${shot()?.name||'Select a shot'} · changes become motion when you Keep pose`);}
function choose(){const a=actor();if(!a?.rig)return;draft=sample(keys(),time)||read(a);editing=true;renderInputs();}
function sync(){const f=F();if(!f?.scene?.ready)return;if(sceneName!==f.scene.name){sceneName=f.scene.name;doc={version:1,scene:sceneName,shots:{}};try{const old=JSON.parse(localStorage.getItem(storeKey()));if(old)doc=validate(old);}catch{}selectedShot=null;undo=[];}if(selectedShot!==shot()){selectedShot=shot();time=0;draft=null;const prev=$('butterActor').value;$('butterActor').replaceChildren();for(const [name,a]of f.actors){if(!a.rig)continue;const o=document.createElement('option');o.value=name;o.textContent=name;$('butterActor').append(o);}const on=shot()?.plan?.on;$('butterActor').value=f.actors.has(on)?on:f.actors.has(prev)?prev:$('butterActor').options[0]?.value||'';$('butterTime').max=shot()?.sec||6;$('butterTime').value=0;choose();}}
function open(){sync();panel.hidden=false;document.body.classList.add('butter-editing');editing=true;F().stop();if(F().sel<0)F().view(0);choose();window.dispatchEvent(new Event('resize'));}
button.onclick=()=>panel.hidden?open():close();function close(){panel.hidden=true;document.body.classList.remove('butter-editing');editing=false;draft=null;window.dispatchEvent(new Event('resize'));}$('butterClose').onclick=close;
$('butterFocus').onclick=()=>{const f=F(),a=actor();if(!a)return;f.stop();const k=f.stage({on:a.name,frame:'medium',from:'s',move:'hold',lens:45}).keys[0];f.setMode('free');f.free.pos.copy(k.pos);const d=k.tgt.clone().sub(k.pos).normalize();f.free.yaw=Math.atan2(-d.x,-d.z);f.free.pitch=Math.asin(d.y);f.free.fov=k.fov;};
$('butterActor').onchange=()=>{F().stop();choose();};
$('butterTime').oninput=()=>{F().stop();time=+$('butterTime').value;F().viewT=time;choose();};
panel.querySelectorAll('[data-butter]').forEach(el=>el.oninput=()=>{if(!draft)return;F().stop();editing=true;draft[el.dataset.butter]=+el.value;renderInputs();});
$('butterGait').onchange=()=>{if(draft)draft.gait=$('butterGait').value;};
const presets={neutral:[0,0,0,0,0,0,0],reach:[-85,-85,0,15,0,0,0],recoil:[-120,-100,-25,-25,-15,25,0],kneel:[-35,-35,0,15,-90,-25,-.5],strike:[-20,-150,20,-10,-20,20,0]};
$('butterPreset').onchange=()=>{const v=presets[$('butterPreset').value];if(!v||!draft)return;F().stop();editing=true;['armL','armR','head','lean','legL','legR','height'].forEach((k,i)=>draft[k]=v[i]);renderInputs();};
function before(){undo.push(JSON.stringify(doc));if(undo.length>30)undo.shift();}
$('butterKeep').onclick=()=>{if(!draft||!shot())return;before();doc.shots[shot().name]??={};const a=$('butterActor').value,list=keys().filter(k=>Math.abs(k.t-time)>.025);list.push({...draft,t:time});list.sort((a,b)=>a.t-b.t);doc.shots[shot().name][a]=list;persist();renderInputs();status(`Kept ${a} at ${time.toFixed(2)} s · ${list.length} poses. Add another time for movement.`);};
$('butterDelete').onclick=()=>{const list=keys();if(!list.length)return;before();const nearest=list.reduce((a,b)=>Math.abs(a.t-time)<Math.abs(b.t-time)?a:b);doc.shots[shot().name][$('butterActor').value]=list.filter(k=>k!==nearest);persist();choose();};
$('butterUndo').onclick=()=>{if(!undo.length)return;doc=JSON.parse(undo.pop());persist();choose();};
$('butterPreview').onclick=()=>{editing=false;draft=null;F().playShot(F().sel);};
const pad=$('butterPad');pad.onpointerdown=e=>{if(!draft)return;e.preventDefault();e.stopPropagation();F().stop();editing=true;drag={x:e.clientX,z:e.clientY,start:{...draft}};pad.setPointerCapture(e.pointerId);};pad.onpointermove=e=>{if(!drag)return;e.stopPropagation();draft.x=drag.start.x+(e.clientX-drag.x)/30;draft.z=drag.start.z+(e.clientY-drag.z)/30;renderInputs();};pad.onpointerup=pad.onpointercancel=()=>{drag=null;};pad.onkeydown=e=>{if(!draft||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();e.stopPropagation();draft[e.key.includes('Left')||e.key.includes('Right')?'x':'z']+=['ArrowLeft','ArrowUp'].includes(e.key)?-.25:.25;editing=true;renderInputs();};
function validate(o){if(o?.version!==1||o.scene!==sceneName||!o.shots||typeof o.shots!=='object')throw Error('This motion file belongs to another scene or format.');let n=0;for(const [s,actors]of Object.entries(o.shots)){if(!F().shots.some(q=>q.name===s))throw Error('Unknown shot: '+s);for(const [name,list]of Object.entries(actors)){if(!F().actors.has(name)||!Array.isArray(list))throw Error('Unknown actor or invalid track');for(const p of list){if(++n>10000||!['t','x','z',...fields.map(f=>f[0])].every(k=>Number.isFinite(p[k])&&Math.abs(p[k])<100000)||p.t<0||p.t>F().shots.find(q=>q.name===s).sec)throw Error('Invalid pose values');}list.sort((a,b)=>a.t-b.t);}}return o;}
$('butterExport').onclick=()=>{if(!doc)return;const u=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='odyssey-hand-butter-motion.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('butterImport').onclick=()=>$('butterFile').click();$('butterFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2e6)throw Error('Motion file too large');const next=validate(JSON.parse(await file.text()));before();doc=next;persist();choose();status('Motion loaded into this scene. Play shot to rehearse.');}catch(e){status(e.message);}finally{$('butterFile').value='';}};
setInterval(()=>{sync();const f=F();if(!f||f.late===priorWrapped)return;const prev=f.late;if(!panel.hidden&&!keys().length)choose();const wrapper=dt=>{prev(dt);if(!doc||sceneName!==f.scene?.name)return;const current=f.shots[f.play.on?f.play.i:f.sel],t=f.play.on?f.play.t:time;for(const [name,list]of Object.entries(doc.shots[current?.name]||{}))apply(f.actors.get(name),sample(list,t),t);if(document.body.dataset.workspace==='shots'&&!panel.hidden&&editing&&!f.play.on)apply(actor(),draft,time);};f.late=wrapper;priorWrapped=wrapper;},250);
})();
