/* Articulated visual segmentation of native horse meshes. Source parts remain unchanged. */
(function(){
async function rig(it){
 const T=THREE,g=it.group;g.updateMatrixWorld(true);const inv=new T.Matrix4().copy(g.matrixWorld).invert(),b=it.localBox,cut=b.min.y+30,cx=(b.min.x+b.max.x)/2,cz=(b.min.z+b.max.z)/2;
 const pivots=[[-1,-1],[1,-1],[-1,1],[1,1]].map(([x,z])=>{const p=new T.Group();p.position.set(cx+x*10,cut,cz+z*35);return p;}),body=new T.Group(),v=new T.Vector3();let counts=[0,0,0,0];
 g.traverse(o=>{if(!o.isMesh)return;const instances=o.isInstancedMesh?o.count:1;for(let j=0;j<instances;j++){const m=new T.Matrix4().multiplyMatrices(inv,o.matrixWorld);if(o.isInstancedMesh){const im=new T.Matrix4();o.getMatrixAt(j,im);m.multiply(im);}const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();geo.applyMatrix4(m);const p=geo.attributes.position,n=geo.attributes.normal,buckets=new Map();for(let k=0;k<p.count;k+=3){const y=Math.max(p.getY(k),p.getY(k+1),p.getY(k+2)),x=(p.getX(k)+p.getX(k+1)+p.getX(k+2))/3,z=(p.getZ(k)+p.getZ(k+1)+p.getZ(k+2))/3,leg=y<cut?((z>cz?2:0)+(x>cx?1:0)):-1,mi=geo.groups.find(q=>k>=q.start&&k<q.start+q.count)?.materialIndex||0,key=leg+':'+mi;if(!buckets.has(key))buckets.set(key,{leg,mi,p:[],n:[]});const a=buckets.get(key),pivot=leg<0?null:pivots[leg].position;for(let h=0;h<3;h++){a.p.push(p.getX(k+h)-(pivot?.x||0),p.getY(k+h)-(pivot?.y||0),p.getZ(k+h)-(pivot?.z||0));if(n)a.n.push(n.getX(k+h),n.getY(k+h),n.getZ(k+h));}if(leg>=0)counts[leg]++;}for(const a of buckets.values()){const gg=new T.BufferGeometry();gg.setAttribute('position',new T.Float32BufferAttribute(a.p,3));if(a.n.length)gg.setAttribute('normal',new T.Float32BufferAttribute(a.n,3));else gg.computeVertexNormals();const mesh=new T.Mesh(gg,Array.isArray(o.material)?o.material[a.mi]:o.material);mesh.castShadow=mesh.receiveShadow=true;(a.leg<0?body:pivots[a.leg]).add(mesh);}geo.dispose();}});
 if(counts.some(n=>n===0))throw Error('Horse leg segmentation failed');while(g.children.length)g.remove(g.children[0]);g.add(body,...pivots);it.horseRig={pivots,counts,phase:0};it.src.gait='walk';return counts;
}
function step(V,dt){const r=V.prop.horseRig;if(!r)return;const moving=Math.min(1,Math.abs(V.speed)/(V.M*2)),gallop=V.prop.src.gait==='gallop'||V.input.boost;r.phase+=Math.abs(V.speed)/V.M*dt*(gallop?2.1:3.2);const phase=gallop?[0,.3,Math.PI,Math.PI+.3]:[0,Math.PI,Math.PI,0];r.pivots.forEach((p,i)=>p.rotation.x=V.fly?-.55:Math.sin(r.phase+phase[i])*(gallop?.65:.32)*moving);V.bob=V.fly?0:Math.abs(Math.sin(r.phase))*(gallop?6:2)*moving;}
window.HorseMotion={rig,step};
})();
