/* world/scenes-trailer.js — the Odyssey trailer, patch by patch, in bricks: Film.SCENES['odyssey-trailer'].

   Version two, cut against the trailer's own frames (films/ref/odyssey-trailer): each shot lays its ground with a
   relief (dunes, a hill under the citadel, a slope, a swell, a shore), sets its own light (look: key, fill, the sun's
   height and bearing, exposure), places its camera by hand where the reference camera stands, and lights its night
   scenes with one fire or one candle that casts. The parts the brick library does not carry (helmets on spears, a
   sail, a horse) come through the loader as props. The takes are the halfworld's; the music its albums. */
(function () { if (!window.Film || !Film.SCENES) return;
const T = 'file:odyssey/music/', F = 'odyssey/';
const N = (text, file, from, sec, at) => ({ what: 'SPEAK', who: 'narrator', text, at, for: sec, file: F + file, from });
const ldr = (col, x, y, z, part, m) => `1 ${col} ${x} ${y} ${z} ${m || '1 0 0 0 1 0 0 0 1'} ${part}.dat`;
const mpd = (name, lines, x, z, w, d, facing) => ({ op: 'mpd', name, text: lines.join('\n'), x, z, y: 0, w: w || 1, d: d || 1, hp: 8, facing: facing || 's' });
/* ── the dune graves: helmets on spears in the wedge the camera sees, sixteen fallen in the sand between them; each its own build so it stands on its own dune ── */
const graveBuilds = []; { const hs = (i, k) => { const v = Math.sin(i * 127.1 + k * 311.7) * 43758.5453; return v - Math.floor(v); };
  /* the camera stands at (-108.3, 3.65) looking south-west along d; s along the look, l across it */
  const d = [-0.707, -0.707], r = [0.707, -0.707], at = (sd, l) => [+(-108.3 + d[0] * sd + r[0] * l).toFixed(2), +(3.65 + d[1] * sd + r[1] * l).toFixed(2)];
  for (let i = 0; i < 60; i++) { const sd = 5 + 32 * hs(i, 1), l = (hs(i, 2) - 0.5) * 1.15 * sd, [x, z] = at(sd, l), tall = i % 3 === 0; if (Math.hypot(x + 114, z + 2) < 1.3) continue;
    graveBuilds.push({ name: 'grave-' + i, x, z, program: { name: 'a grave', ops: [mpd('grave' + i, [ldr(308, 0, 48, 0, '4497'), ldr(0, 0, tall ? -42 : -30, 0, '3896')], 0, 0)] } }); }
  for (let i = 0; i < 16; i++) { const sd = 3.5 + 14 * hs(i, 3), l = (hs(i, 4) - 0.5) * 1.15 * sd, [x, z] = at(sd, l); if (Math.hypot(x + 114, z + 2) < 1.6) continue; graveBuilds.push({ name: 'fallen-' + i, x, z, program: { name: 'a fallen man', ops: [{ op: 'box', x: 0, z: 0, w: i % 2 ? 2 : 1, d: i % 2 ? 1 : 2, y: 0, h: 1, col: i % 3 ? 308 : 70 }] } }); }
  for (let i = 0; i < 6; i++) { const sd = 3 + 12 * hs(i, 5), l = (hs(i, 6) - 0.5) * 1.0 * sd, [x, z] = at(sd, l); graveBuilds.push({ name: 'shield-' + i, x, z, program: { name: 'a shield', ops: [mpd('shield' + i, [ldr(297, 0, -8, 0, '3876', '1 0 0 0 0 -1 0 1 0')], 0, 0, 2, 2)] } }); } }
const post = { name: 'a foreground post', ops: [{ op: 'column', x: 0, z: 0, y: 0, h: 9, col: 0 }, mpd('post-helm', [ldr(0, 0, -6, 0, '3896')], 0, 0)] };
/* ── galleys: a hull, a mast with a square sail ── */
const galley = (name, sailCol) => ({ name, ops: [{ op: 'group', name: 'hull', x: 0, z: 0, size: [4, 18, 12], ops: [
  { op: 'box', x: 0, z: 1, w: 4, d: 16, y: 0, h: 2, col: 0 }, { op: 'band', x: 0, z: 1, w: 4, d: 16, y: 1, h: 1, col: 308 }, { op: 'roof', x: 0, z: 0, w: 4, d: 3, y: 2, col: 0, style: 'gable' }, { op: 'column', x: 1, z: 0, y: 2, h: 6, col: 0 }, { op: 'column', x: 2, z: 9, y: 2, h: 11, col: 70 },
  mpd('sail', [ldr(sailCol || 320, 0, -240, 0, '36069a', '0 0 1 0 1 0 -1 0 0')], 1, 8, 2, 2)] }] });
/* ── the citadel on its hill ── */
const citadel = { name: 'the citadel', ops: [{ op: 'group', name: 'walls', x: 0, z: 0, size: [20, 10, 14], ops: [{ op: 'box', x: 0, z: 0, w: 20, d: 10, y: 0, h: 2, col: 72 }, { op: 'wall', from: [0, 9], to: [20, 9], y: 2, h: 6, col: 71 }, { op: 'wall', from: [0, 0], to: [20, 0], y: 2, h: 5, col: 71 }, { op: 'wall', from: [0, 0], to: [0, 10], y: 2, h: 5, col: 71 }, { op: 'wall', from: [19, 0], to: [19, 10], y: 2, h: 5, col: 71 }, { op: 'tower', x: 2, z: 2, r: 2, h: 11, y: 2, col: 72, round: false, crenels: true }, { op: 'tower', x: 17, z: 2, r: 2, h: 11, y: 2, col: 72, round: false, crenels: true }, { op: 'tower', x: 10, z: 4, r: 3, h: 14, y: 2, col: 72, round: false, crenels: true }, { op: 'arch', x: 7, z: 9, y: 2, facing: 's', h: 2, col: 72 }] }] };
/* ── the siege wreck, leaning, and the ropes ── */
const wreck = { name: 'the siege wreck', ops: [{ op: 'group', name: 'hull', x: 0, z: 0, size: [22, 12, 30], ops: [{ op: 'box', x: 12, z: 2, w: 8, d: 8, y: 0, h: 4, col: 308 }, { op: 'box', x: 9, z: 2, w: 8, d: 8, y: 4, h: 4, col: 308 }, { op: 'box', x: 6, z: 2, w: 8, d: 8, y: 8, h: 4, col: 70 }, { op: 'box', x: 3, z: 2, w: 8, d: 8, y: 12, h: 4, col: 70 }, { op: 'box', x: 0, z: 1, w: 7, d: 10, y: 16, h: 5, col: 70 }, { op: 'column', x: 2, z: 4, y: 21, h: 8, col: 308 }, { op: 'column', x: 5, z: 7, y: 21, h: 5, col: 308 }] },
  { op: 'group', name: 'ropes', x: -40, z: 2, size: [40, 6, 1], ops: [{ op: 'wall', from: [0, 0], to: [40, 2], y: 0, h: 1, col: 70 }, { op: 'wall', from: [0, 4], to: [40, 3], y: 0, h: 1, col: 70 }] }] };
const horse = { name: 'the white horse', ops: [mpd('horse', [ldr(15, 0, 0, 0, '4493c01')], 0, 0, 2, 5, 'e')] };
/* ── the cavern: staggered rock, a fire, bones, the giant against the back wall ── */
const cavern = { name: 'the cavern', ops: [
  { op: 'group', name: 'rock', x: 0, z: 0, size: [34, 26, 16], ops: [{ op: 'box', x: 0, z: 0, w: 34, d: 3, y: 0, h: 15, col: 72 }, { op: 'box', x: 4, z: 3, w: 6, d: 2, y: 0, h: 9, col: 71 }, { op: 'box', x: 20, z: 3, w: 8, d: 3, y: 0, h: 11, col: 72 }, { op: 'box', x: 0, z: 3, w: 3, d: 20, y: 0, h: 13, col: 72 }, { op: 'box', x: 3, z: 10, w: 3, d: 6, y: 0, h: 6, col: 71 }, { op: 'box', x: 31, z: 3, w: 3, d: 20, y: 0, h: 13, col: 72 }, { op: 'box', x: 28, z: 14, w: 3, d: 5, y: 0, h: 5, col: 71 }, { op: 'slab', x: 0, z: 0, w: 34, d: 24, y: 15, plates: 3, col: 72 }, { op: 'slab', x: 3, z: 3, w: 28, d: 5, y: 12, plates: 3, col: 72 }] },
  { op: 'group', name: 'fire', x: 15, z: 14, size: [3, 3, 3], ops: [{ op: 'part', part: '3941', col: 0, x: 0, y: 0, z: 0 }, { op: 'part', part: '85959', col: 57, x: 0, y: 1, z: 0 }, { op: 'part', part: '85959', col: 57, x: 1, y: 1, z: 1 }, { op: 'part', part: '85959', col: 57, x: 1, y: 1, z: 0 }, { op: 'part', part: '85959', col: 57, x: 0, y: 1, z: 1 }, { op: 'part', part: '85959', col: 25, x: 0, y: 2, z: 0 }, { op: 'part', part: '85959', col: 25, x: 1, y: 2, z: 1 }] },
  { op: 'group', name: 'bones', x: 8, z: 8, size: [14, 12, 1], ops: [{ op: 'part', part: '92691', col: 15, x: 0, y: 0, z: 0, rot: 1 }, { op: 'part', part: '92691', col: 15, x: 6, y: 0, z: 3, rot: 2 }, { op: 'part', part: '92691', col: 15, x: 10, y: 0, z: 9, rot: 0 }, { op: 'part', part: '93160', col: 15, x: 2, y: 0, z: 10 }] },
  { op: 'group', name: 'polyphemus', x: 22, z: 3, size: [10, 4, 16], ops: [{ op: 'box', x: 1, z: 0, w: 3, d: 4, y: 0, h: 7, col: 0 }, { op: 'box', x: 6, z: 0, w: 3, d: 4, y: 0, h: 7, col: 0 }, { op: 'box', x: 0, z: 0, w: 10, d: 4, y: 7, h: 6, col: 0 }, { op: 'box', x: -3, z: 0, w: 3, d: 4, y: 5, h: 8, col: 0 }, { op: 'box', x: 3, z: 0, w: 4, d: 4, y: 13, h: 3, col: 0 }] } ] };
const brazier = { name: 'the brazier', ops: [{ op: 'group', name: 'brazier', x: 0, z: 0, size: [2, 2, 3], ops: [{ op: 'part', part: '3062b', col: 0, x: 0, y: 0, z: 0 }, { op: 'part', part: '3062b', col: 0, x: 0, y: 1, z: 0 }, { op: 'part', part: '85959', col: 57, x: 0, y: 2, z: 0 }, { op: 'part', part: '85959', col: 57, x: 1, y: 1, z: 0 }] }] };
/* ── the galley at sea: a deck with sides, benches, a mast, a high prow ── */
const deck = { name: 'the galley', ops: [{ op: 'group', name: 'deck', x: 0, z: 0, size: [12, 28, 14], ops: [{ op: 'slab', x: 0, z: 2, w: 12, d: 26, y: 0, plates: 1, col: 308 }, { op: 'wall', from: [0, 2], to: [0, 28], y: 0, h: 2, col: 70 }, { op: 'wall', from: [11, 2], to: [11, 28], y: 0, h: 2, col: 70 }, { op: 'roof', x: 0, z: -1, w: 12, d: 3, y: 0, col: 70, style: 'gable' }, { op: 'column', x: 5, z: 0, y: 1, h: 7, col: 70 }, { op: 'column', x: 6, z: 0, y: 1, h: 7, col: 70 },
  ...[4, 9, 14, 19, 24].flatMap(z => [{ op: 'box', x: 1, z, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 9, z, w: 2, d: 1, y: 0, h: 1, col: 70 }]), { op: 'column', x: 6, z: 13, y: 0, h: 13, col: 70 }, mpd('sail', [ldr(320, 0, -250, 0, '36069a')], 5, 12, 2, 2)] }] };
const room = { name: 'the chamber', ops: [{ op: 'group', name: 'walls', x: 0, z: 0, size: [16, 12, 7], ops: [{ op: 'wall', from: [0, 0], to: [16, 0], y: 0, h: 7, col: 70 }, { op: 'wall', from: [0, 0], to: [0, 12], y: 0, h: 7, col: 70 }, { op: 'wall', from: [16, 0], to: [16, 12], y: 0, h: 7, col: 70 }, { op: 'slab', x: 0, z: 0, w: 16, d: 12, y: 7, plates: 1, col: 70 }] }] };
const bed = { name: 'the bed', ops: [{ op: 'group', name: 'bed', x: 0, z: 0, size: [6, 8, 2], ops: [{ op: 'box', x: 0, z: 0, w: 6, d: 8, y: 0, h: 1, col: 70 }, { op: 'slab', x: 0, z: 0, w: 6, d: 8, y: 1, plates: 1, col: 15 }] }, { op: 'group', name: 'candle', x: 8, z: 4, size: [1, 1, 2], ops: [{ op: 'part', part: '3062b', col: 19, x: 0, y: 0, z: 0 }, { op: 'part', part: '37775', col: 57, x: 0, y: 1, z: 0 }] }] };
/* ── the pine trunks on the ridge: tall columns either side of the corridor ── */
const pines = { name: 'the pines', ops: [] }; for (let i = 0; i < 90; i++) { const x = (i * 29) % 56 - 28, z = (i * 17) % 60 - 30; if (Math.abs(x) < 4) continue; pines.ops.push({ op: 'column', x: x + 30, z: z + 30, y: 0, h: 24 + (i % 4) * 3, col: i % 4 === 0 ? 70 : 308 }); }
const headland = { name: 'a headland', ops: [{ op: 'box', x: 0, z: 0, w: 60, d: 10, y: 0, h: 4, col: 0 }, { op: 'box', x: 10, z: 2, w: 30, d: 6, y: 4, h: 3, col: 0 }] };
/* ── the cast, a figure per place, one label per part ── */
const actors = [
  { name: 'odysseus-dunes', figure: 'odysseus-bronze', label: 'Odysseus', x: -114, z: -2, heading: 355, pose: 'crouch' },
  { name: 'odysseus-beach', figure: 'odysseus-bronze', label: 'Odysseus', x: 0, z: 0, heading: 90 }, { name: 'commander', figure: 'commander', label: 'Eurylochus', x: 1.4, z: -0.6, heading: 270 },
  { name: 'odysseus-ridge', figure: 'odysseus-bronze', label: 'Odysseus', x: 560, z: 164, heading: 0 },
  { name: 'telemachus', figure: 'telemachus-ithaca', label: 'Telemachus', x: 403, z: 153.5, heading: 180 }, { name: 'penelope-crag', figure: 'penelope-ithaca', label: 'Penelope', x: 409, z: 153.5, heading: 90 },
  { name: 'rider', figure: 'rider', label: 'the rider', x: 40, z: -3, heading: 90 },
  { name: 'odysseus-cave', figure: 'odysseus-sword', label: 'Odysseus', x: -205, z: -203.5, heading: 0 },
  { name: 'odysseus-ash', figure: 'odysseus-sword', label: 'Odysseus', x: -200, z: 200, heading: 180 },
  { name: 'odysseus-deck', figure: 'odysseus-wet', label: 'Odysseus', x: -3, z: 304.5, heading: 90 },
  { name: 'odysseus', figure: 'odysseus-wet', x: 199.7, z: 201, heading: 90 }, { name: 'penelope', figure: 'penelope-ithaca', x: 200.3, z: 201, heading: 270 },
];
for (let i = 0; i < 18; i++) actors.push({ name: 'phalanx-' + (i + 1), figure: 'hoplite', x: -4 - Math.floor(i / 6) * 1.8 - (i % 2) * 0.3, z: -8 + (i % 6) * 1.7 + Math.floor(i / 6) * 0.4, heading: 275 });
for (let i = 0; i < 6; i++) actors.push({ name: 'ridge-' + (i + 1), figure: 'hoplite', x: 557.5 + (i % 3) * 2.5, z: 168.5 + Math.floor(i / 3) * 3 + (i % 2), heading: 0 });
for (let i = 0; i < 4; i++) actors.push({ name: 'cave-' + (i + 1), figure: 'hoplite', x: -211 + i * 2.6, z: -206.5, heading: 180 });
for (let i = 0; i < 7; i++) actors.push({ name: 'ash-' + (i + 1), figure: 'hoplite', x: -206 + i * 2, z: 195.5 + (i % 2) * 1.2, heading: 180 });
for (let i = 0; i < 24; i++) actors.push({ name: 'hauler-' + (i + 1), figure: 'hauler', x: 44 + Math.floor(i / 2) * 1.7, z: -6.4 + (i % 2) * 1.8, heading: 270 });
for (let i = 0; i < 10; i++) actors.push({ name: 'rower-' + (i + 1), figure: 'sailor', x: i < 5 ? -4.6 : -2.4, z: 294.5 + (i % 5) * 2.5, heading: 180 });
const builds = [...graveBuilds,
  { name: 'galley a', x: -16, z: -13, program: galley('galley a') }, { name: 'galley b', x: -25, z: -9, program: galley('galley b') },
  { name: 'pines', x: 545, z: 140, program: pines }, { name: 'citadel', x: 401, z: 133, program: citadel },
  { name: 'ship a', x: 10, z: 198, program: galley('ship a') }, { name: 'ship b', x: -44, z: 196, program: galley('ship b') }, { name: 'headland', x: 26, z: 186, program: headland },
  { name: 'wreck', x: 82, z: -12, program: wreck }, { name: 'horse', x: 41.2, z: -4.3, program: horse },
  { name: 'cavern', x: -216, z: -210, program: cavern }, { name: 'brazier', x: -197, z: 198.5, program: brazier },
  { name: 'galley deck', x: -6, z: 292, program: deck }, { name: 'bed', x: 197, z: 197, program: bed }, { name: 'room', x: 196, z: 195, program: room }];
const story = { title: 'The Odyssey: a trailer in bricks', description: 'Thirteen patches of the trailer, each on its own ground and in its own light, cut against the trailer’s frames.', location: 'Troy, the Aegean, Ithaca',
  entities: [{ id: 'odysseus', type: 'character', name: 'Odysseus', traits: ['bronze', 'bearded', 'commander'], location: 'everywhere' }, { id: 'penelope', type: 'character', name: 'Penelope', traits: ['dark peplos', 'braided'], location: 'Ithaca' }, { id: 'telemachus', type: 'character', name: 'Telemachus', traits: ['grey tunic'], location: 'Ithaca' }, { id: 'hoplites', type: 'crowd', name: 'the phalanx', traits: ['bronze', 'spears'], location: 'Troy' }, { id: 'polyphemus', type: 'shadow', name: 'Polyphemus', traits: ['colossal'], location: 'the cavern' }],
  goals: [{ id: 'g1', name: 'home', owner: 'odysseus' }], obstacles: [{ id: 'o1', name: 'the sea', affects: ['odysseus'] }, { id: 'o2', name: 'the Cyclops', affects: ['odysseus', 'hoplites'] }, { id: 'o3', name: 'the dead', affects: ['odysseus'] }],
  shifts: [{ id: 'muster', name: 'Aftermath and beachhead', causes: 'the war is over', results_in: 'the fleet musters' }, { id: 'ridge', name: 'Inland and the overlook', causes: 'the march inland', results_in: 'Ithaca waits' }, { id: 'launch', name: 'Launch and salvage', causes: 'the fleet sails', results_in: 'the siege engine is dragged' }, { id: 'cavern', name: 'The cavern and the shore of the dead', causes: 'a hostile coast', results_in: 'a standoff in the mist' }, { id: 'tempest', name: 'Tempest, covenant, billing', causes: 'Poseidon strikes', results_in: 'a promise' }],
  relations: ['[commands] odysseus -> hoplites', '[waits for] penelope -> odysseus', '[looms over] polyphemus -> hoplites', '[promises] odysseus -> penelope'],
  timeline: [{ id: 'SQ1', description: 'Aftermath and Beachhead Assembly', scenes: [{ id: 'P002', description: 'the dune graves', entities: ['odysseus'] }, { id: 'P003', description: 'the beachhead', entities: ['odysseus', 'hoplites'] }] }, { id: 'SQ2', description: 'Inland Ridge and Domestic Counter-Overlook', scenes: [{ id: 'P004', description: 'the pine ridge', entities: ['odysseus', 'hoplites'] }, { id: 'P005', description: 'the citadel', entities: ['telemachus', 'penelope'] }] }, { id: 'SQ3', description: 'Maritime Launch and Shoreline Salvage', scenes: [{ id: 'P006', description: 'the galleys at dusk', entities: [] }, { id: 'P007', description: 'the tow', entities: ['hoplites'] }] }, { id: 'SQ4', description: 'Subterranean Ambush and Netherworld Shore', scenes: [{ id: 'P008', description: 'the cavern', entities: ['odysseus', 'polyphemus'] }, { id: 'P009', description: 'the ashen shore', entities: ['odysseus'] }] }, { id: 'SQ5', description: 'Ocean Tempest, Covenant, and Theatrical Billing', scenes: [{ id: 'P010', description: 'the tempest', entities: ['odysseus'] }, { id: 'P011', description: 'the deck', entities: ['odysseus'] }, { id: 'P012', description: 'the chamber vow', entities: ['odysseus', 'penelope'] }] }] };
const shots = [
  { title: 'THE ODYSSEY\nA TRAILER IN BRICKS', style: 'card', sec: 6, name: 'P001 the studio card', score: T + 'bronze-armor-clash.ogg', fade: 3, shift: 'muster' },
  { name: 'P002 the dune graves', on: 'odysseus-dunes', pos: [-108.3, 2.6, 3.65], tgt: [-115.06, 0.8, -0.94], lens: 36, sec: 10, shift: 'muster', set: { kind: 'dunes', centre: [-120, 0], r: 110, time: 'day', weather: 'clear' }, look: { hemi: 0.25, sun: 1.6, elev: 18, azim: 300, exposure: 0.65 }, handheld: 0.25,
    events: [{ what: 'PERFORM', who: 'odysseus-dunes', verb: 'LOOK', target: [-113.5, -0.5], at: 0.2, keepGaze: true }, { what: 'PHRASE', who: 'odysseus-dunes', name: 'grief', at: 0.5, enter: 0.8 }, { what: 'SET', who: 'odysseus-dunes', ch: 'arm.R.pitch', v: -0.9, at: 2, over: 1.2 }] },
  { name: 'P003 the beachhead', on: 'odysseus-beach', pos: [3.0, 1.9, 1.95], tgt: [0.13, 2.0, -0.15], lens: 32, sec: 8, shift: 'muster', set: { kind: 'shore', centre: [0, 0], r: 80, time: 'day', weather: 'clear' }, look: { hemi: 0.35, sun: 1.3, elev: 14, azim: 272, exposure: 0.9 },
    events: [{ what: 'PHRASE', who: 'commander', name: 'listen', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'odysseus-beach', name: 'command', at: 1.2, enter: 0.4 }, { what: 'PERFORM', who: 'commander', verb: 'LOOK', target: 'odysseus-beach', at: 0.3, keepGaze: true }, { what: 'PERFORM', who: 'odysseus-beach', verb: 'LOOK', target: 'commander', at: 0.2, keepGaze: true }, N('Odysseus begins the account of the disasters that followed Troy.', 'OD-B09-S01.mp3', 65.44, 6.24, 0.8)] },
  { name: 'P004 the pine ridge', on: 'odysseus-ridge', pos: [560.6, 1.45, 148], tgt: [560, 1.65, 156.5], lens: 40, sec: 9, shift: 'ridge', set: { kind: 'ridge', centre: [560, 160], r: 70, relief: 'slope', time: 'day', weather: 'clear', corridor: [[560, 176], [560, 134]] }, look: { hemi: 0.8, sun: 1.2, elev: 28, azim: 20, exposure: 1.0 }, handheld: 0.5,
    acts: [{ who: 'odysseus-ridge', to: [560, 144], walk: true }, { who: 'ridge-1', to: [558, 151], walk: true }, { who: 'ridge-2', to: [562, 151.5], walk: true }, { who: 'ridge-3', to: [560.5, 153], walk: true }, { who: 'ridge-4', to: [557.5, 154.5], walk: true }, { who: 'ridge-5', to: [562.5, 155], walk: true }, { who: 'ridge-6', to: [559.5, 157], walk: true }], events: [N('Odysseus describes Ithaca’s rugged beauty and his longing to return.', 'OD-B09-S01.mp3', 57.1, 8.04, 0.5), { what: 'PHRASE', who: 'odysseus-ridge', name: 'resolve', at: 2, enter: 0.5 }] },
  { name: 'P005 the citadel', on: [406, 140], pos: [434, 30, 176], tgt: [406, 4, 138], lens: 30, sec: 3, shift: 'ridge', set: { kind: 'crag', centre: [406, 140], r: 70, time: 'day', weather: 'cloudy' }, look: { hemi: 0.9, sun: 0.7, elev: 24, azim: 240, exposure: 0.9 } },
  { name: 'P005 Telemachus on the parapet', on: 'telemachus', pos: [403, 3.3, 156.1], tgt: [403, 1.75, 153.5], lens: 28, sec: 2.5, shift: 'ridge', look: { hemi: 1.1, sun: 1.3, elev: 30, azim: 150, exposure: 1.15 }, events: [{ what: 'PHRASE', who: 'telemachus', name: 'resolve', at: 0, enter: 0.3 }, { what: 'SET', who: 'telemachus', ch: 'head.yaw', v: 0.5, at: 0.1, over: 0.3 }, { what: 'SET', who: 'telemachus', ch: 'torso.lean', v: 0.12, at: 0.1, over: 0.3 }] },
  { name: 'P005 Penelope turns', on: 'penelope-crag', pos: [409.2, 3.5, 156.1], tgt: [409, 1.75, 153.5], lens: 28, sec: 3, shift: 'ridge', look: { hemi: 1.1, sun: 1.2, elev: 30, azim: 150, exposure: 1.1 }, events: [{ what: 'PHRASE', who: 'penelope-crag', name: 'guarded', at: 0, enter: 0.3 }, { what: 'PERFORM', who: 'penelope-crag', verb: 'LOOK', target: [411, 155.5], at: 0.7, keepGaze: true }, { what: 'SPEAK', who: 'penelope-crag', text: 'Odysseus.', at: 1.1, for: 2.2, file: F + 'OD-B23-S04.mp3', from: 30.5 }] },
  { name: 'P006 the galleys at dusk', on: [6, 214], pos: [-12, 1.6, 244], tgt: [10, 3.0, 206], lens: 26, sec: 8, shift: 'launch', set: { kind: 'sea', centre: [0, 220], r: 120, time: 'dusk', weather: 'clear' }, look: { hemi: 0.5, sun: 0.35, elev: 1, azim: 30, exposure: 0.8 }, events: [N('My child, how could I forget godlike Odysseus?', 'OD-B01-S01.mp3', 83.24, 4, 1.5)] },
  { title: 'FROM THE HALFWORLD', style: 'card', sec: 2, name: 'P007 the card', shift: 'launch' },
  { name: 'P007 the tow', on: [50, -5], pos: [34, 1.3, 2], tgt: [56, 1.0, -12], lens: 40, sec: 8, shift: 'launch', set: { kind: 'shore', centre: [50, 0], r: 80, time: 'day', weather: 'clear' }, look: { hemi: 0.35, sun: 1.2, elev: 11, azim: 300, exposure: 0.85 }, events: [{ what: 'PHRASE', who: 'rider', name: 'pointing', at: 1.5, enter: 0.5 }].concat(Array.from({ length: 24 }, (_, i) => ({ what: 'PHRASE', who: 'hauler-' + (i + 1), name: 'hold', at: 0.1 + i * 0.03, enter: 0.4, hold: 30 }))) },
  { name: 'P008 the cavern', on: 'odysseus-cave', pos: [-206.5, 1.2, -193], tgt: [-208, 1.3, -204.5], lens: 52, sec: 10, shift: 'cavern', score: T + 'cyclopean-pulse.ogg', fade: 2, set: { kind: 'cave', centre: [-200, -200], r: 60, time: 'night', weather: 'clear' }, look: { hemi: 0.03, sun: 0, exposure: 0.8 }, lamp: { at: [-208.5, 1.2, -203], color: 0xff7a2a, intensity: 8, distance: 30 }, handheld: 0.6,
    acts: [{ who: 'cave-1', to: [-214, -197], at: 3.6, run: true }, { who: 'cave-2', to: [-213, -194], at: 4.6, run: true }, { who: 'cave-3', to: [-200, -195], at: 4.1, run: true }, { who: 'cave-4', to: [-201, -198], at: 5.3, run: true }, { who: 'odysseus-cave', to: [-207, -200.5] }], events: [N('The Cyclops seizes two men, smashes them on the floor, and devours them raw.', 'OD-B09-S07.mp3', 73.04, 8.76, 0.6), { what: 'SHAKE', at: 3.2 }, { what: 'PHRASE', who: 'odysseus-cave', name: 'stop', at: 2.6, enter: 0.4 }] },
  { name: 'P009 the ashen shore', on: 'odysseus-ash', pos: [-200.4, 1.65, 206.5], tgt: [-200, 1.45, 200], lens: 40, sec: 10, shift: 'cavern', score: T + 'underworld-descent.ogg', fade: 2, set: { kind: 'ash', centre: [-200, 200], r: 80, time: 'dusk', weather: 'fog' }, look: { hemi: 0.32, sun: 0.08, elev: 3, azim: 200, exposure: 0.62 }, lamp: { at: [-196.5, 1.0, 199], color: 0xff8a30, intensity: 2.5, distance: 9 },
    events: [{ what: 'PHRASE', who: 'odysseus-ash', name: 'look down', at: 0, enter: 0.3 }, N('The dead gather in multitudes, crying around the blood.', 'OD-B11-S01.mp3', 34.22, 8.24, 0.5), { what: 'PHRASE', who: 'odysseus-ash', name: 'stop', at: 4.2, enter: 0.5 }].concat(Array.from({ length: 7 }, (_, i) => ({ what: 'PHRASE', who: 'ash-' + (i + 1), name: 'listen', at: 0.2, enter: 0.4 }))) },
  { title: 'THIS SUMMER', style: 'card', sec: 1.5, name: 'P010 the card', shift: 'tempest', score: T + 'hammer-and-lightning.ogg', fade: 1 },
  { name: 'P010 the tempest', on: 'odysseus-deck', pos: [-4.2, 2.4, 309.5], tgt: [-3.2, 1.5, 298], lens: 46, sec: 7.5, shift: 'tempest', roll: 9, handheld: 1.3, set: { kind: 'sea', centre: [0, 300], r: 120, time: 'day', weather: 'storm' }, look: { hemi: 0.55, sun: 0.15, elev: 20, azim: 30, exposure: 0.85 }, events: [{ what: 'SHAKE', at: 0.5 }, { what: 'SHAKE', at: 2.6 }, { what: 'SHAKE', at: 4.7 }, { what: 'SHAKE', at: 6.4 }, N('Poseidon sees him, gathers clouds, and strikes the sea with a four-wind storm.', 'OD-B05-S05.mp3', 18.12, 7, 0.3)].concat(Array.from({ length: 10 }, (_, i) => ({ what: 'PHRASE', who: 'rower-' + (i + 1), name: 'hold', at: 0.1, enter: 0.3 }))) },
  { name: 'P011 the deck command', on: 'odysseus-deck', pos: [-1.3, 2.05, 306.1], tgt: [-3, 1.8, 304.5], lens: 32, sec: 7, shift: 'tempest', roll: -12, handheld: 1.6, look: { hemi: 0.55, sun: 0.15, elev: 20, azim: 30, exposure: 0.8 }, events: [{ what: 'PHRASE', who: 'odysseus-deck', name: 'hold', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'odysseus-deck', name: 'look down', at: 0.2, enter: 0.4 }, { what: 'SET', who: 'odysseus-deck', ch: 'torso.lean', v: 0.45, at: 0.2, over: 0.5 }, { what: 'SET', who: 'odysseus-deck', ch: 'head.yaw', v: 0.7, at: 0.3, over: 0.5 }, { what: 'SHAKE', at: 1 }, { what: 'SPEAK', who: 'odysseus-deck', text: 'Hear me now, Polyphemus:', at: 1.2, for: 4.5, file: F + 'OD-B09-S11.mp3', from: 9.22 }, { what: 'PHRASE', who: 'odysseus-deck', name: 'command', at: 3.6, enter: 0.3 }, { what: 'SHAKE', at: 4.6 }] },
  { name: 'P012 the chamber vow', on: [200, 201], pos: [200, 1.78, 203.5], tgt: [200, 1.72, 201], lens: 30, sec: 13, shift: 'tempest', score: T + 'lament-of-penelope.ogg', fade: 2, set: { kind: 'chamber', centre: [200, 200], r: 40, time: 'night', weather: 'clear' }, look: { hemi: 0.02, sun: 0, exposure: 1.1 }, lamp: { at: [199.3, 1.5, 203.0], color: 0xffb060, intensity: 3.4, distance: 9 },
    events: [{ what: 'PHRASE', who: 'penelope', name: 'tenderness', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'odysseus', name: 'tenderness', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'penelope', name: 'hands near face', at: 0.5, enter: 0.6 }, { what: 'SET', who: 'odysseus', ch: 'blink', v: 1, at: 1.5, over: 0.4 }, { what: 'PERFORM', who: 'penelope', verb: 'LOOK', target: 'odysseus', at: 0.2, keepGaze: true }, { what: 'PERFORM', who: 'odysseus', verb: 'LOOK', target: 'penelope', at: 0.2, keepGaze: true }, { what: 'SPEAK', who: 'penelope', text: 'Do not be angry with me; of all men you were always the shrewdest. I was afraid some stranger would come with a smooth story and take me with it.', at: 0.8, for: 6.2, file: F + 'OD-B23-S04.mp3', from: 36.08 }, N('Athena holds back dawn while husband and wife weep and reunite.', 'OD-B23-S04.mp3', 42.64, 5.4, 7.4)] },
  { title: 'THE ODYSSEY', style: 'card', sec: 2.5, name: 'P012 the title', shift: 'tempest' },
  { title: '07 . 17 . 26\nSHOT ENTIRELY WITH LEGO BRICKS', style: 'card', sec: 5, name: 'P013 the release card', shift: 'tempest' },
];
Film.SCENES['odyssey-trailer'] = { name: 'The Odyssey: the trailer in bricks', time: 'day', weather: 'clear', ground: 'flat', me: 'off', set: { kind: 'dunes', r: 110, centre: { x: -120, z: 0 } }, story, actors, builds, shots };
})();
