'use strict';
const $=s=>document.querySelector(s),paneState={},params=new URLSearchParams(location.hash.slice(1));
let manifest,versions,comparing=params.get('compare')==='1',active=params.get('active')==='b'?'b':'a',notes={};
try{notes=JSON.parse(localStorage.getItem('ww-archive-reviews')||'{}');}catch{}
const node=(tag,text,attrs={})=>{const e=document.createElement(tag);if(text!=null)e.textContent=text;for(const [k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
const short=s=>s.slice(0,7);
const time=d=>new Date(d).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false});
function saveNotes(){try{localStorage.setItem('ww-archive-reviews',JSON.stringify(notes));}catch{$('#notice').textContent='Browser storage unavailable. Export notes before leaving.';}}
function updateLink(){const q=new URLSearchParams({a:paneState.a.version.sha,b:paneState.b.version.sha,view:$('#size').value,compare:comparing?'1':'0',active});history.replaceState(null,'','#'+q);}
function snapshotURL(sha,id){return 'time-machine/snapshots/'+sha+'.html?noloc=1&lease=share&mute=1&pane='+id;}
function fit(s){if(!s.wrap)return;const r=s.viewport.getBoundingClientRect(),kind=$('#size').value;let w=kind==='phone'?390:kind==='desktop'?1280:Math.max(1,r.width),h=kind==='phone'?740:kind==='desktop'?800:Math.max(1,r.height);const scale=Math.min(r.width/w,r.height/h,1);Object.assign(s.wrap.style,{width:w+'px',height:h+'px',transform:`translate(${-w*scale/2}px,${-h*scale/2}px) scale(${scale})`});}
function stop(s){if(s.iframe){s.iframe.remove();s.iframe=null;}if(s.wrap){s.wrap.remove();s.wrap=null;}s.running=false;s.placeholder.hidden=false;s.status.textContent='Stopped';s.status.dataset.state='stopped';s.run.textContent='Run version';}
function run(s){stop(s);s.placeholder.hidden=true;s.running=true;s.wrap=node('div',null,{class:'frameWrap'});s.iframe=node('iframe',null,{title:`${s.id.toUpperCase()} · ${short(s.version.sha)} · ${s.version.message}`,allow:'camera; microphone; fullscreen',sandbox:'allow-scripts allow-same-origin allow-forms allow-downloads allow-pointer-lock allow-popups'});s.iframe.src=snapshotURL(s.version.sha,s.id);s.wrap.append(s.iframe);s.viewport.append(s.wrap);s.status.textContent='Starting…';s.status.dataset.state='loading';s.run.textContent='Stop';fit(s);}
function select(s,index){const wasRunning=s.running;stop(s);s.index=Math.max(0,Math.min(versions.length-1,index));s.version=versions[s.index];const v=s.version;s.select.value=v.sha;s.slider.value=s.index;s.count.textContent=(s.index+1)+' / '+versions.length;s.prev.disabled=s.index===0;s.next.disabled=s.index===versions.length-1;s.commit.href='https://github.com/hartswf0/tractor-dce-gyo/commit/'+v.sha;s.commit.textContent=short(v.sha);s.when.textContent=time(v.date);s.deployed.textContent=v.baseline?'Pre-change baseline':v.deployment?.conclusion==='success'?'Pages succeeded':v.mainline?'Intermediate commit':'Merged branch';s.source.href='https://github.com/hartswf0/tractor-dce-gyo/blob/'+v.sha+'/word-to-world.html';s.open.href=snapshotURL(v.sha,s.id);s.title.textContent=v.message;s.review.value=notes[v.sha]?.verdict||'';s.note.value=notes[v.sha]?.note||'';s.status.textContent='Not running';if(paneState.a?.version&&paneState.b?.version)updateLink();if(wasRunning)run(s);}
function createPane(id,index){const s={id,running:false};paneState[id]=s;s.el=node('section',null,{class:'pane', 'aria-label':'Revision '+id.toUpperCase()});const row=node('div',null,{class:'versionRow'}),label=node('label',id.toUpperCase(),{for:'version-'+id});s.select=node('select',null,{id:'version-'+id,'aria-label':'Revision '+id.toUpperCase()});versions.forEach((v,i)=>s.select.append(node('option',`${String(i+1).padStart(2,'0')} · ${time(v.date)} · ${v.message}`,{value:v.sha})));row.append(label,s.select);
 const meta=node('div',null,{class:'meta'});s.commit=node('a');s.commit.target='_blank';s.commit.rel='noopener';s.when=node('time');s.deployed=node('span');s.status=node('span','Not running',{class:'state',role:'status'});meta.append(s.commit,s.when,s.deployed,s.status);
 s.viewport=node('div',null,{class:'viewport'});s.placeholder=node('div',null,{class:'placeholder'});s.title=node('strong');const info=node('p','Run this revision to try its original controls. The current demo and its saves stay separate.');const start=node('button','Run this revision');start.onclick=()=>run(s);s.placeholder.append(s.title,info,start);s.viewport.append(s.placeholder);
 const scrub=node('div',null,{class:'scrub'});s.slider=node('input',null,{type:'range',min:0,max:versions.length-1,value:index,'aria-label':'Scrub revision '+id.toUpperCase()});s.count=node('output');scrub.append(s.slider,s.count);
 const actions=node('div',null,{class:'actions'}),steps=node('div',null,{class:'step'});s.prev=node('button','← Older');s.next=node('button','Newer →');steps.append(s.prev,s.next);s.run=node('button','Run version');s.open=node('a','Open ↗',{target:'_blank',rel:'noopener'});s.source=node('a','Source ↗',{target:'_blank',rel:'noopener'});actions.append(steps,s.run,s.open,s.source);
 const review=node('div',null,{class:'review'});s.review=node('select',null,{'aria-label':'Verdict for revision '+id.toUpperCase()});for(const [v,t]of [['','Not reviewed'],['usable','Usable'],['broken','Broken'],['mixed','Partly works']])s.review.append(node('option',t,{value:v}));s.note=node('input',null,{placeholder:'What works or breaks?','aria-label':'Review note for revision '+id.toUpperCase(),maxlength:2000});review.append(s.review,s.note);
 s.el.append(row,meta,s.viewport,actions,scrub,review);$('#panes').append(s.el);s.select.onchange=()=>select(s,versions.findIndex(v=>v.sha===s.select.value));s.slider.oninput=()=>{s.count.textContent=(+s.slider.value+1)+' / '+versions.length;};s.slider.onchange=()=>select(s,+s.slider.value);s.prev.onclick=()=>select(s,s.index-1);s.next.onclick=()=>select(s,s.index+1);s.run.onclick=()=>s.running?stop(s):run(s);s.review.onchange=s.note.oninput=()=>{notes[s.version.sha]={verdict:s.review.value,note:s.note.value};saveNotes();};new ResizeObserver(()=>fit(s)).observe(s.viewport);select(s,index);return s;}
function layout(){document.body.classList.toggle('comparing',comparing);$('#compare').setAttribute('aria-pressed',comparing);$('#mobileTabs').hidden=!comparing;paneState.b.el.hidden=!comparing;for(const s of Object.values(paneState)){s.el.classList.toggle('active',s.id===active);fit(s);}document.querySelectorAll('[data-pane]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pane===active));if(!comparing&&paneState.b.running)stop(paneState.b);updateLink();}
function list(){const table=node('table'),head=node('tr');for(const t of ['Time / revision','Change','Files changed','Load'])head.append(node('th',t));table.append(head);versions.forEach((v,i)=>{const tr=node('tr');tr.append(node('td',`${time(v.date)} · ${short(v.sha)}`),node('td',v.message+(v.sameAs?' · same code as '+short(v.sameAs):'')),node('td',v.changed.join(', ')||'No Word to World change'));const td=node('td');for(const id of ['a','b']){const b=node('button',id.toUpperCase());b.onclick=()=>{if(id==='b')comparing=true;active=id;select(paneState[id],i);$('#revisionList').hidden=true;$('#history').setAttribute('aria-expanded','false');layout();};td.append(b);}tr.append(td);table.append(tr);});$('#revisionList').append(table);}
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='ww-archive-status')return;const s=paneState[e.data.pane];if(!s||s.iframe?.contentWindow!==e.source||s.version.sha!==e.data.sha)return;s.status.dataset.state=e.data.state;s.status.textContent=e.data.state==='ready'?'World ready':e.data.state==='fault'?'Startup failed':'Loading world…';s.status.title=e.data.message||'';});
$('#compare').onclick=()=>{comparing=!comparing;if(!comparing)active='a';layout();};
$('#size').value=['phone','desktop','fit'].includes(params.get('view'))?params.get('view'):'phone';$('#size').onchange=()=>{Object.values(paneState).forEach(fit);updateLink();};
document.querySelectorAll('[data-pane]').forEach(b=>b.onclick=()=>{active=b.dataset.pane;layout();});
for(const [button,panel]of [['#history','#revisionList'],['#about','#explanation']])$(button).onclick=()=>{const opening=$(panel).hidden;$('#revisionList').hidden=true;$('#explanation').hidden=true;$('#history').setAttribute('aria-expanded','false');$('#about').setAttribute('aria-expanded','false');$(panel).hidden=!opening;$(button).setAttribute('aria-expanded',opening);};
$('#share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('#notice').textContent='Comparison link copied.';}catch{$('#notice').textContent='Copy the address bar to share this comparison.';}};
$('#export').onclick=()=>{const data=JSON.stringify({generated:new Date().toISOString(),archive:manifest.head,comparison:location.href,notes},null,2),url=URL.createObjectURL(new Blob([data],{type:'application/json'})),a=node('a',null,{href:url,download:'word-to-world-review.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);};
(async()=>{const r=await fetch('time-machine/manifest.json');if(!r.ok)throw Error('History could not load: '+r.status);manifest=await r.json();versions=manifest.versions;const find=(id,fallback)=>{const i=versions.findIndex(v=>v.sha===params.get(id));return i<0?fallback:i;};createPane('a',find('a',0));createPane('b',find('b',versions.length-1));list();layout();$('#range').textContent=time(manifest.since)+' – '+time(manifest.generated)+' · local time';$('#notice').textContent=`${versions.length-1} commits + preceding baseline · ${new Set(versions.map(v=>v.signature)).size} distinct code states · ${manifest.branch}`;})().catch(e=>{$('#notice').textContent=e.message;});
