const fs=require('fs'),path=require('path'),assert=require('assert/strict'),vm=require('vm'),crypto=require('crypto');
const root=__dirname,m=JSON.parse(fs.readFileSync(path.join(root,'manifest.json')));
let refs=0;
for(const v of m.versions){const html=fs.readFileSync(path.join(root,'snapshots',v.sha+'.html'),'utf8');assert(html.includes('<base href="../../">'));assert(html.includes('data-version="'+v.sha+'"'));for(const f of v.files){const ext=path.extname(f.path),data=fs.readFileSync(path.join(root,'objects',f.blob+ext));assert.equal(crypto.createHash('sha1').update('blob '+data.length+'\0').update(data).digest('hex'),f.blob);assert(html.includes('objects/'+f.blob+ext));refs++;}}
function storage(){const s={};Object.defineProperties(s,{getItem:{value:k=>Object.hasOwn(s,k)?s[k]:null},setItem:{value:(k,v)=>{s[k]=String(v);}},removeItem:{value:k=>delete s[k]}});return s;}
const native=storage();native.setItem('world.build','original');native.setItem('openai.key','test-key-not-a-real-credential');
function context(pane){const channels=[],databases=[],w={indexedDB:{open:name=>databases.push(name)},localStorage:native,sessionStorage:storage(),BroadcastChannel:class{constructor(name){channels.push(name);}}};const c={window:w,document:{baseURI:'https://example.test/tractor/',currentScript:{dataset:{version:'historical'}}},location:{search:'?pane='+pane,origin:'https://example.test'},URL,URLSearchParams,console,setInterval(){},parent:{postMessage(){}}};vm.runInNewContext(fs.readFileSync(path.join(root,'isolate.js'),'utf8'),c);return {w,channels,databases};}
const a=context('a'),b=context('b');assert.equal(a.w.localStorage.getItem('openai.key'),null);a.w.localStorage.setItem('world.build','test');assert.equal(native.getItem('world.build'),'original');assert.equal(b.w.localStorage.getItem('world.build'),null);a.w.localStorage.clear();assert.equal(native.getItem('world.build'),'original');assert.equal(native.getItem('openai.key'),'test-key-not-a-real-credential');new a.w.BroadcastChannel('world-lease');new b.w.BroadcastChannel('world-lease');assert.notEqual(a.channels[0],b.channels[0]);
a.w.indexedDB.open('world.receipts');b.w.indexedDB.open('world.receipts');assert.notEqual(a.databases[0],b.databases[0]);assert.notEqual(a.databases[0],'world.receipts');assert.equal(a.w.__soundBase,'https://example.test/tractor/world/');
console.log(JSON.stringify({snapshots:m.versions.length,pinnedScriptAndStyleReferences:refs,storageAndLeaseIsolation:'passed',distinctStates:new Set(m.versions.map(v=>v.signature)).size}));
