import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {LDrawLoader} from 'three/addons/loaders/LDrawLoader.js';
import {LDrawConditionalLineMaterial} from 'three/addons/materials/LDrawConditionalLineMaterial.js';
import {WORLDS,FIGURES} from './figures.js';
const $=x=>document.getElementById(x),S={world:'simpsons',fig:null,root:null,spin:false,error:null,last:null};
const Q=new URLSearchParams(location.search);const powerpuffHeadY=Number.isFinite(Number(Q.get('headY')))?Number(Q.get('headY')):-72;
const host=$('host'),renderer=new THREE.WebGLRenderer({antialias:false,powerPreference:'high-performance'});renderer.setPixelRatio(1);renderer.setClearColor(0xf2f0e9);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,10000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;scene.add(new THREE.HemisphereLight(0xffffff,0x777777,2.4));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(180,240,170);scene.add(key);const grid=new THREE.GridHelper(300,15,0x8c8c8c,0xd4d1c8);scene.add(grid);const loader=new LDrawLoader();loader.setConditionalLineMaterial(LDrawConditionalLineMaterial);loader.setPartsLibraryPath('./ldraw/');
function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function tick(){requestAnimationFrame(tick);resize();controls.update();if(S.spin&&S.root)S.root.rotation.y+=.008;renderer.render(scene,camera)}requestAnimationFrame(tick);
function clear(){if(S.root){scene.remove(S.root);S.root=null}}function line(c,x,y,z,f,m='1 0 0 0 1 0 0 0 1'){return`1 ${c??16} ${x} ${y} ${z} ${m} parts/${f}`}
function torso(p){const c=p.color??16;return[line(c,0,-60,0,p.file),line(c,-15.552,-51,0,'3818.dat','0.985 -0.17 0 0.17 0.985 0 0 0 1'),line(c,15.552,-51,0,'3819.dat','0.985 0.17 0 -0.17 0.985 0 0 0 1'),line(14,-23.6904,-33.226,-9.8982,'3820.dat','0.985 -0.1202 0.1202 0.17 0.6964 -0.6964 0 0.707 0.707'),line(14,23.6904,-33.226,-9.8982,'3820.dat','0.985 0.1202 -0.1202 -0.17 0.6964 -0.6964 0 0.707 0.707')]}
function mpd(f){const a=[`0 FILE movieator_${f.id}.mpd`,`0 Name: ${f.name}`,'0 !LDRAW_ORG Model','0 BFC CERTIFY CCW',''];for(const p of f.parts){const c=p.color??16;switch(p.slot){case'HEAD':a.push(line(c,0,p.y??-84,0,p.file));break;case'HEAD_SHORTCUT':a.push(line(c,0,p.y??powerpuffHeadY,0,p.file));break;case'HEADGEAR':a.push(line(c,0,p.y??-84,0,p.file));break;case'UPPER':a.push(line(c,0,-60,0,p.file));break;case'TORSO':a.push(...torso(p));break;case'LOWER':a.push(line(c,0,-28,0,p.file));break;case'HIPWEAR':a.push(line(c,0,-28,0,p.file));break}a.push('')}return a.join('\n')}
function preflight(f){const problems=[],seen=new Set();for(const p of f.parts){if(seen.has(p.slot)&&p.slot!=='HEADGEAR')problems.push('duplicate '+p.slot);seen.add(p.slot);if(/^~/.test(p.description))problems.push('subpart '+p.file);if(/obsolete/i.test(p.description))problems.push('obsolete '+p.file);if(p.profile==='sculpt20'&&p.y!==-64)problems.push('bad sculpt mount '+p.file);if(p.profile==='powerpuff-shortcut'&&p.slot!=='HEAD_SHORTCUT')problems.push('bad shortcut slot '+p.file)}return problems}
function fit(r){const b=new THREE.Box3().setFromObject(r);if(b.isEmpty())return null;const s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z,55);controls.target.copy(c);camera.position.set(c.x+d*1.25,c.y+d*.65,c.z+d*1.7);camera.near=.1;camera.far=d*50;camera.updateProjectionMatrix();grid.position.y=b.min.y-.8;return{s,c,b}}
function sniff(f,fd){const problems=preflight(f);if(S.error)problems.push('loader '+S.error);if(!fd)problems.push('empty geometry');else{const s=fd.s;if(s.x>145||s.y>180||s.z>145)problems.push('oversize');if(s.x<20||s.y<35)problems.push('undersize');if(s.x/s.y>1.75)problems.push('too-wide')}const r={id:f.id,name:f.name,pass:!problems.length,problems,size:fd?{x:+fd.s.x.toFixed(1),y:+fd.s.y.toFixed(1),z:+fd.s.z.toFixed(1)}:null,powerpuffHeadY};S.last=r;window.__MOVIEATOR_SNIFF=r;$('badge').textContent=r.pass?'SNIFF PASS':'SNIFF FAIL';$('badge').className=r.pass?'ok':'bad';return r}
function render(){return new Promise(resolve=>{window.__MOVIEATOR_READY=false;S.error=null;loader.parse(mpd(S.fig),g=>{clear();S.root=new THREE.Group();S.root.rotation.x=Math.PI;S.root.add(g);scene.add(S.root);const r=sniff(S.fig,fit(S.root));renderer.render(scene,camera);window.__MOVIEATOR_READY=true;resolve(r)},e=>{S.error=String(e?.message||e);clear();const r=sniff(S.fig,null);window.__MOVIEATOR_READY=true;resolve(r)})})}
const wf=()=>FIGURES.filter(f=>f.world===S.world);function ui(){const used=WORLDS.filter(([id])=>FIGURES.some(f=>f.world===id));$('world').innerHTML=used.map(([id,n])=>`<option value="${id}">${n}</option>`).join('');$('world').value=S.world;$('figure').innerHTML=wf().map(f=>`<option value="${f.id}">${f.name}</option>`).join('');$('figure').value=S.fig.id;$('count').textContent=wf().length+' FIGS';$('figs').innerHTML=wf().map(f=>`<button class="fig ${f.id===S.fig.id?'active':''}" data-f="${f.id}"><b>${f.name}</b><small>${f.note}</small></button>`).join('');document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>select(FIGURES.find(f=>f.id===b.dataset.f)));$('pieces').innerHTML=S.fig.parts.map((p,i)=>`<div class="piece"><b>${String(i+1).padStart(2,'0')} · ${p.file}</b><small>${p.description}</small><small class="${p.exact?'exact':'context'}">${p.exact?'EXACT':'CONTEXT'} · ${p.slot}</small></div>`).join('')}
async function select(f){S.fig=f;S.world=f.world;$('name').textContent=f.name;$('note').textContent=f.note;ui();await render()}function shift(n){const a=wf(),i=a.findIndex(f=>f.id===S.fig.id);select(a[(i+n+a.length)%a.length])}$('world').onchange=e=>{S.world=e.target.value;select(wf()[0])};$('figure').onchange=e=>select(FIGURES.find(f=>f.id===e.target.value));$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('spin').onclick=()=>{S.spin=!S.spin;$('spin').textContent=S.spin?'STOP':'SPIN'};window.__MOVIEATOR_FIGURES=FIGURES;
try{await loader.preloadMaterials('./ldraw/LDConfig.ldr');$('ready').textContent='LDRAW READY';$('ready').className='chip ok'}catch(e){S.error=String(e);$('ready').textContent='LDRAW ERROR';$('ready').className='chip bad'}const wanted=Q.get('figure'),start=FIGURES.find(f=>f.id===wanted)||FIGURES[0];await select(start);