const P=(slot,file,description,extra={})=>({slot,file,description,exact:true,...extra});
export const WORLDS=[['simpsons','The Simpsons'],['star-wars','Star Wars'],['powerpuff','The Powerpuff Girls'],['scooby-doo','Scooby-Doo'],['gremlins','Gremlins']];
export const FIGURES=[
{id:'homer',world:'simpsons',name:'Homer Simpson',note:'exact head + printed upper',parts:[P('HEAD','15527p02.dat','Homer Simpson head',{color:14,y:-64,profile:'sculpt20'}),P('UPPER','16360p87.dat','Homer office upper'),P('LOWER','3815c01.dat','plain blue lower',{exact:false,color:1})]},
{id:'marge',world:'simpsons',name:'Marge Simpson',note:'formed skirt; flat source excluded',parts:[P('HEAD','15522p02.dat','Marge Simpson head',{color:14,y:-64,profile:'sculpt20'}),P('UPPER','76382pd13.dat','Marge dress upper'),P('HIPWEAR','u9209c01.dat','Marge formed skirt',{color:2})]},
{id:'bart',world:'simpsons',name:'Bart Simpson',note:'exact head + slingshot torso + short legs',parts:[P('HEAD','15523p02.dat','Bart Simpson head',{color:14,y:-64,profile:'sculpt20'}),P('TORSO','973pd12.dat','Bart slingshot torso',{color:4}),P('LOWER','16709p02.dat','Bart short hips + legs')]},
{id:'lisa',world:'simpsons',name:'Lisa Simpson',note:'exact head + beads upper',parts:[P('HEAD','15524p02.dat','Lisa Simpson head',{color:14,y:-64,profile:'sculpt20'}),P('UPPER','76382pd14.dat','Lisa beads upper'),P('LOWER','3815c01.dat','plain red lower',{exact:false,color:4})]},
{id:'ned',world:'simpsons',name:'Ned Flanders',note:'exact head + apron body',parts:[P('HEAD','15529p01.dat','Ned Flanders head',{color:14,y:-64,profile:'sculpt20'}),P('UPPER','76382p89.dat','Ned apron upper'),P('LOWER','73200p89.dat','Ned apron hips + legs')]},
{id:'vader',world:'star-wars',name:'Darth Vader',note:'one minifig helmet; branded objects excluded',parts:[P('HEAD','3626b.dat','black head context',{exact:false,color:0}),P('HEADGEAR','30368.dat','Darth Vader minifig helmet',{color:0}),P('UPPER','76382ps7.dat','Darth Vader printed upper',{color:0}),P('LOWER','3815c01.dat','black lower context',{exact:false,color:0})]},
{id:'yoda',world:'star-wars',name:'Yoda',note:'one complete patterned head; alternates excluded',parts:[P('HEAD','13195p01.dat','Yoda patterned head',{y:-64,profile:'sculpt20'}),P('UPPER','973c01.dat','tan upper context',{exact:false,color:19}),P('LOWER','3815c01.dat','tan lower context',{exact:false,color:19})]},
{id:'blossom',world:'powerpuff',name:'Blossom',note:'Light Nougat shortcut head + exact stripe upper + short white legs',parts:[P('HEAD_SHORTCUT','28946.dat','Blossom complete head shortcut',{color:78,profile:'powerpuff-shortcut'}),P('UPPER','76382px2.dat','Powerpuff Girls black-stripe upper',{color:13}),P('LOWER','41879ap01.dat','Powerpuff Girls short legs with black shoes',{color:15})]},
{id:'bubbles',world:'powerpuff',name:'Bubbles',note:'Light Nougat shortcut head + exact stripe upper + short white legs',parts:[P('HEAD_SHORTCUT','28948.dat','Bubbles complete head shortcut',{color:78,profile:'powerpuff-shortcut'}),P('UPPER','76382px2.dat','Powerpuff Girls black-stripe upper',{color:9}),P('LOWER','41879ap01.dat','Powerpuff Girls short legs with black shoes',{color:15})]},
{id:'buttercup',world:'powerpuff',name:'Buttercup',note:'Light Nougat shortcut head + exact stripe upper + short white legs',parts:[P('HEAD_SHORTCUT','28949.dat','Buttercup complete head shortcut',{color:78,profile:'powerpuff-shortcut'}),P('UPPER','76382px2.dat','Powerpuff Girls black-stripe upper',{color:10}),P('LOWER','41879ap01.dat','Powerpuff Girls short legs with black shoes',{color:15})]},
{id:'shaggy',world:'scooby-doo',name:'Shaggy Rogers',note:'exact Shaggy Rogers hair; adjective matches excluded',parts:[P('HEAD','3626b.dat','head context',{exact:false,color:78}),P('HEADGEAR','21787.dat','Shaggy Rogers hair',{color:84}),P('UPPER','973c01.dat','lime upper context',{exact:false,color:27}),P('LOWER','3815c01.dat','dark-red lower context',{exact:false,color:320})]},
{id:'fred',world:'scooby-doo',name:'Fred Jones',note:'exact Fred hair + ascot torso',parts:[P('HEAD','3626b.dat','head context',{exact:false,color:78}),P('HEADGEAR','21788.dat','Fred Jones hair',{color:14}),P('TORSO','973px3.dat','Fred sweater + orange ascot',{color:15}),P('LOWER','3815c01.dat','blue lower context',{exact:false,color:1})]},
{id:'gremlin',world:'gremlins',name:'Mogwai / Gremlin',note:'patterned Mogwai head; blank base sculpt excluded',parts:[P('HEAD','26056px0.dat','patterned Mogwai / Gremlin head',{y:-64,profile:'sculpt20'}),P('UPPER','973c01.dat','neutral upper context',{exact:false,color:0}),P('LOWER','3815c01.dat','neutral lower context',{exact:false,color:0})]}
];