/* world/scenes-cases.js — the cases: the repository's own scene builds made into films that can be played, staged,
   rehearsed and inspected on the hand table, each held to the standard of the Odyssey trailer.

   A case is a scene program (world/film.js) standing on one of the repository's builds laid as a donor set
   (world/donors.js: the MPD packed with every part, parsed once, stood on the ground at the figures' scale), with
   marks on the floor, a cast of figure definitions, beats with their reasons and directions, a shot list that mixes
   hand keys on the set with semantic frames on the actors, lines with voices, a score and foley, a part the player
   can take, and a floor plan for the hand table (tools/play-plan.js writes play/<key>.ldr at one stud to the metre).
   `Film.CASES` is the sheet of all nine candidates: three carry programs here (the grocery checkout, the forest
   skirmish, the cave); the other six are registered with their set, size, cast and beat outline so the same
   machinery lays them and draws their plans, and they wait for their shots. */
(function () { if (!window.Film || !Film.SCENES) return;
const SAY = (who, text, at, sec) => ({ what: 'LINE', who, text, at, for: sec });   // spoken by the lines tool's voice in an export, by the browser live
const BEAT = (id, who, from, to, why, direct) => ({ what: 'BEAT', id, who, from, to, why, direct, at: from });
const P = (who, name, at, enter) => ({ what: 'PHRASE', who, name, at, enter: enter || 0.4 });
const FACE = (who, name, at) => ({ what: 'FACE', who, name, at });
const LOOK = (who, target, at, keepGaze) => ({ what: 'PERFORM', who, verb: 'LOOK', target, at, keepGaze: !!keepGaze });
const SET = (who, ch, v, at, over) => ({ what: 'SET', who, ch, v, at, over: over || 0.5 });
const SND = (who, at) => ({ what: 'SOUND', who, at });

/* ── 1. The List: the Simpsons shopping scene, on The Supermarket (world/models/supermarket.js) ──
   A shopping list is a partial future-state language (Hartsoe, 'The Shopping List', working paper, 2026): it says what should become
   true, not how; the store's plan, the shopper and the world supply the rest. Anscombe's pair is in the store: Homer shops by the list
   (a mistake is in the performance), Ned Flanders follows him down the aisles writing down what goes in the cart (a mistake is in the
   record). Two notes ride the frame: the list top left (style 'list': '~' struck, '+' added), Ned's record top right (RECORD: '?' a
   guess where a shelf hid the taking). At the belt the receipt meets both: the flour Ned guessed plain was organic, and the baby scans.
   The same store is the game (world/shop.js, ?film=case-grocery&shop): the five things are where the shopper finds them.
   The store is 124 × 95 studs laid at heading 180, built mirrored so produce is the left wall as you walk in; SM turns a built stud
   (x, z) to scene metres. The door x 57..67 on the front wall z 8..9; the banana stand x 102..116 × z 15..19 (green bananas the west
   half); aisle 3 x 63..69 between gondolas 3 (x 69..74) and 4 (x 58..63), z 32..78, the olive oil on gondola 3's face at z 44..51; the
   frozen doors on x 5, the hash browns at z 40..46; checkout lane 1's counter x 44..46 × z 14..22, its register x 42..44 × z 19..22,
   the customer's side x 46..50. */
const LIST = (...items) => ['the list', ...items].join('\n');
const SM = (x, z) => [Math.round((x - 62) / 2 * 100) / 100, Math.round((z - 47.5) / 2 * 100) / 100];
const STORE = { hemi: 1.05, sun: 1.0, elev: 62, azim: 150, exposure: 1.05 };   /* no ceiling on a film set: the sun stands high so the walls' shadows are short, the fill up so the aisles read like a lit store */
const ALL5 = ['five red apples', 'green bananas', 'black berries', 'extra virgin olive oil', 'organic flour', 'southwest style hash browns'];
const STRUCK = n => ALL5.map((x, i) => (i < n ? '~' : '') + x);
Film.SCENES['case-grocery'] = { name: 'The List', time: 'day', weather: 'clear', ground: 'flat', me: 'off', part: 'homer', set: { kind: 'stage', r: 120, seed: 2 }, marksHidden: true,
  story: { title: 'The List', description: 'Marge wrote the list; Homer carries it into the supermarket: five red apples, green bananas, black berries, extra virgin olive oil, organic flour, southwest style hash browns. Maggie rides in the cart. Ned Flanders sees the list and keeps a record of what goes in the cart. At the apples Homer runs the shopkeeper\'s three routines: the crate marked APPLES, the sample RED, the count to five. At the oil he takes the cheaper light oil and offers to change the list; Lisa tells him to change the basket (the mistake is in the performance). At the belt the receipt meets the record: the flour Ned guessed plain was organic, and Ned changes his record (the mistake is in the record). The baby scans.', location: 'the Springfield supermarket',
    entities: [{ id: 'homer', type: 'character', name: 'Homer', traits: ['the list', 'the cart', 'the shopper'] }, { id: 'flanders', type: 'character', name: 'Ned Flanders', traits: ['the record', 'the detective', 'the neighbour'] }, { id: 'maggie', type: 'character', name: 'Maggie', traits: ['in the cart', 'on neither'] }, { id: 'bart', type: 'character', name: 'Bart', traits: ['the objection'] }, { id: 'lisa', type: 'character', name: 'Lisa', traits: ['reads the list right'] }, { id: 'clerk', type: 'character', name: 'the clerk', traits: ['the scanner', 'the receipt'] }, { id: 'list', type: 'object', name: 'the list', traits: ALL5 }, { id: 'record', type: 'object', name: 'Ned\'s record', traits: ['what went in the cart'] }],
    goals: ['make the list true', 'keep a true record'], obstacles: ['the cheaper oil', 'a shelf between the detective and the cart', 'a procedure that acquires everything at the belt'], shifts: [{ id: 'store', name: 'The store' }, { id: 'list', name: 'The list' }, { id: 'apples', name: 'Five red apples' }, { id: 'oil', name: 'The wrong oil' }, { id: 'frozen', name: 'Caught' }, { id: 'belt', name: 'The belt' }, { id: 'record', name: 'The record' }], why: 'the list says what should be made true; the record says what was done; the receipt answers to neither', direction: 'deadpan' },
  donors: [{ name: 'the store', set: 'supermarket', x: 0, z: 0, heading: 180, scale: 1, y: -0.18 }],
  marks: {
    street: [...SM(62, 1), null, 180], 'cart-street': [...SM(62, 5.2), null, 180], 'lisa-street': [...SM(59.5, -0.5), null, 180], 'bart-street': [...SM(64.5, -0.5), null, 180],
    apples: [...SM(113.5, 24.4), null, 180], crate: SM(113.5, 28), 'cart-apples': [...SM(116.9, 28), null, 180], 'ned-apples': [...SM(117.4, 32.5), null, 0], 'lisa-apples': [...SM(116.4, 23.6), null, 270], 'bart-apples': [...SM(118.2, 20.5), null, 270],
    'lisa-oil2': [...SM(65.2, 44.6), null, 0], 'cart-oil2': [...SM(65.4, 51), null, 0], 'bart-oil2': [...SM(64.6, 58.5), null, 0], 'ned-aisle2': [...SM(65.8, 30.6), null, 180],
    in: [...SM(62, 17), null, 180], 'cart-in': [...SM(64.6, 20.5), null, 180], 'list-look': SM(62, 30), 'bart-in': [...SM(58, 14), null, 180], 'lisa-in': [...SM(66.5, 15), null, 180], 'ned-desk': [...SM(77, 20), null, 270],
    'prod-in': [...SM(100, 23), null, 90], bananas: [...SM(111.5, 22), null, 0], stand: SM(111.5, 17), 'cart-prod': [...SM(106, 22.5), null, 90], 'bart-prod': [...SM(106.5, 25.5), null, 90], 'lisa-prod': [...SM(103.5, 25), null, 90], 'ned-prod': [...SM(108.5, 32.5), null, 0],
    oil: [...SM(67.3, 47.5), null, 90], shelf3: SM(70, 47.5), 'cart-oil': [...SM(65.4, 43.5), null, 180], 'bart-oil': [...SM(64.6, 29.5), null, 180], 'lisa-oil': [...SM(66.8, 29), null, 180], 'ned-aisle': [...SM(64.2, 80.5), null, 0],
    frozen: [...SM(8.6, 43.5), null, 270], doors: SM(5, 43.5), 'cart-frozen': [...SM(10.8, 39.8), null, 180], 'bart-frozen': [...SM(12.6, 27), null, 180], 'lisa-frozen': [...SM(10.2, 26), null, 180], 'ned-frozen': [...SM(9.2, 55), null, 270],
    belt: [...SM(48.4, 19.5), null, 0], 'cart-belt': [...SM(48, 16.2), null, 0], clerk: [...SM(42.8, 16.6), null, 90], 'ned-belt': [...SM(39.6, 20), null, 0], 'bart-belt': [...SM(53, 22.5), null, 0], 'lisa-belt': [...SM(54.5, 20.5), null, 0] },
  actors: [
    { name: 'homer', figure: 'homer', label: 'Homer', x: SM(62, 1)[0], z: SM(62, 1)[1], heading: 180 },
    { name: 'cart', kind: 'cart', len: 4, col: 4, rider: 'maggie', label: 'the cart', x: SM(62, 5.2)[0], z: SM(62, 5.2)[1], heading: 180 },   /* Maggie rides in the basket; the cart is kept a step ahead of Homer */
    { name: 'lisa', figure: 'lisa', label: 'Lisa', x: SM(59.5, -0.5)[0], z: SM(59.5, -0.5)[1], heading: 180 },
    { name: 'bart', figure: 'bart', label: 'Bart', x: SM(64.5, -0.5)[0], z: SM(64.5, -0.5)[1], heading: 180 },
    { name: 'flanders', figure: 'flanders', label: 'Ned', x: SM(77, 20)[0], z: SM(77, 20)[1], heading: 270 },
    { name: 'clerk', figure: 'citizen', label: 'the clerk', x: SM(42.8, 16.6)[0], z: SM(42.8, 16.6)[1], heading: 90 }],
  /* Cut to 'Trouttown Working Day' (Silt Wire & Mountain Current, m1; world/music/cues.json): its bars fall at 0.21 s + 1.973 s k, and every cut is on
     one (bars 2, 6, 8, 12, 15, 19, 23, 27, 29); the scanner pings on the beat (0.493 s). Each shot starts its cast on marks (FROM): the film cuts
     from the door to produce to aisle three to frozen to the belt, as the game's player walks it. */
  shots: [
    { score: 'file:../music/m1-trouttown-working-day.ogg', title: 'THE LIST', style: 'card', sec: 4.16, events: [SAY('narrator', 'Marge wrote the list. Homer carries it.', 0.4, 2.8)] },
    { name: 'The store', on: 'homer', title: LIST(...ALL5), style: 'list', pos: [-3.4, 3.0, -18.4], pos2: [-3.0, 3.0, -17.6], tgt: [5.2, 1.4, -13.2], lens: 40, sec: 7.84, shift: 'store', look: STORE,
      acts: [{ who: 'homer', from: 'street', to: 'in', walk: true, at: 0.4 }, { who: 'cart', from: 'cart-street', lead: 'homer', ahead: 2.2 }, { who: 'lisa', from: 'lisa-street', follow: 'homer', behind: 1.6, walk: true }, { who: 'bart', from: 'bart-street', follow: 'homer', behind: 2.0, walk: true }, { who: 'flanders', from: 'ned-desk', look: 'homer', pose: 'stand' }, { who: 'clerk', from: 'clerk', look: 'cart-belt' }],
      events: [BEAT('store', 'homer', 0, 7.84, 'the shopper has an order; the neighbour will keep a record', 'neutral'), SND('footstep', 1.2), SND('footstep', 1.7), SND('footstep', 2.2), SND('clatter', 2.6), SAY('flanders', 'Hi-diddly-ho, Homer! Got a list, have we?', 3.0, 2.0), P('flanders', 'joy', 2.9), SAY('homer', 'Flanders.', 5.1, 0.8), P('homer', 'skepticism', 5.0), SAY('flanders', 'I\'ll just keep a little record.', 6.0, 1.7)] },
    { name: 'The list', on: 'homer', title: LIST(...ALL5), style: 'list', record: [], pos: [1.4, 2.9, -11.6], tgt: [0, 2.1, -15.4], lens: 36, sec: 3.95, shift: 'list', look: STORE,
      acts: [{ who: 'homer', from: 'in', look: 'list-look' }, { who: 'cart', from: 'cart-in', brake: true }, { who: 'bart', from: 'bart-in', look: 'homer' }, { who: 'lisa', from: 'lisa-in', look: 'homer' }, { who: 'flanders', look: 'homer', pose: 'stand' }],
      events: [BEAT('list', 'homer', 0, 3.95, 'the list says what should become true, not how', 'resolve'), P('homer', 'resolve', 0.2), SAY('homer', 'Six things. How hard can it be?', 0.5, 2.6)] },
    { name: 'Five red apples', on: 'homer', title: LIST(...ALL5), style: 'list', record: [], pos: [21.6, 3.3, -15.4], tgt: [26.0, 1.1, -10.2], lens: 50, sec: 7.89, shift: 'apples', look: STORE,
      acts: [{ who: 'homer', from: 'apples', look: 'crate' }, { who: 'cart', from: 'cart-apples', brake: true }, { who: 'lisa', from: 'lisa-apples', look: 'homer' }, { who: 'bart', from: 'bart-apples', look: 'cart' }, { who: 'flanders', from: 'ned-apples', look: 'homer', pose: 'stand' }],
      events: [BEAT('apples', 'homer', 0, 7.89, 'the words are three routines: the crate marked APPLES, the sample RED, the count to five', 'resolve'), SAY('homer', 'Apples.', 0.5, 0.7), P('homer', 'command', 0.4), SAY('homer', 'Red.', 1.6, 0.6), SAY('homer', 'One, two, three, four, five.', 2.6, 2.6), SND('click', 3.0), SND('click', 3.5), SND('click', 4.0), SND('click', 4.5), SND('click', 5.0), SAY('flanders', 'Five red apples. Noted.', 5.8, 1.7), P('flanders', 'joy', 5.7)] },
    { name: 'The wrong oil', on: 'homer', title: LIST('~five red apples', '~green bananas', '~black berries', 'extra virgin olive oil', 'organic flour', 'southwest style hash browns'), style: 'list', record: ['five red apples', 'green bananas', 'black berries'], pos: [2.1, 2.7, 4.25], tgt: [2.5, 1.6, -0.75], lens: 38, sec: 7.89, shift: 'oil', look: STORE,
      fit: [{ at: 5.0, for: 2.8, dir: 'list', a: 'extra virgin', b: 'light goes back', say: 'the list stays right: the basket is changed to fit it' }],
      acts: [{ who: 'homer', from: 'oil', look: 'shelf3' }, { who: 'cart', from: 'cart-oil2', brake: true }, { who: 'lisa', from: 'lisa-oil2', look: 'homer' }, { who: 'bart', from: 'bart-oil2', look: 'homer' }, { who: 'flanders', from: 'ned-aisle2', look: 'homer', pose: 'stand' }],
      events: [BEAT('oil', 'homer', 0, 7.89, 'a mistake in the performance: the basket is wrong, not the list', 'irony'), SAY('homer', 'Light olive oil. It\'s cheaper.', 0.3, 1.8), SND('click', 1.6), SAY('lisa', 'Dad, the list says extra virgin.', 2.2, 1.6), LOOK('homer', 'lisa', 2.3, true), SAY('homer', 'So I\'ll change the list.', 3.9, 1.3), P('homer', 'resolve', 3.8), SAY('lisa', 'No! Change the basket.', 5.3, 1.4), P('lisa', 'concern', 5.2), LOOK('homer', 'shelf3', 6.6, true), SND('click', 7.0)] },
    { name: 'Caught', on: 'homer', title: LIST('~five red apples', '~green bananas', '~black berries', '~extra virgin olive oil', '~organic flour', 'southwest style hash browns'), style: 'list', record: ['five red apples', 'green bananas', 'black berries', 'extra virgin olive oil', '?plain flour'], pos: [-24.6, 3.1, -9.6], tgt: [-27.0, 1.5, 1.2], lens: 38, sec: 5.91, shift: 'frozen', look: STORE,
      acts: [{ who: 'homer', from: 'frozen', look: 'doors' }, { who: 'cart', from: 'cart-frozen', brake: true }, { who: 'bart', from: 'bart-frozen', look: 'homer' }, { who: 'lisa', from: 'lisa-frozen', look: 'homer' }, { who: 'flanders', from: 'ned-frozen', look: 'doors', pose: 'stand' }],
      events: [BEAT('frozen', 'homer', 0, 5.91, 'the shopper turns and finds the detective', 'surprise'), SAY('homer', 'Southwest style hash browns.', 0.3, 1.6), SND('click', 1.7), SAY('flanders', 'Southwest style! Noted!', 2.0, 1.3), LOOK('homer', 'flanders', 3.2, true), P('homer', 'wonder', 3.2), SAY('homer', 'Flanders?!', 3.4, 0.8), LOOK('flanders', 'doors', 4.1, true), SAY('flanders', 'Just reading the labels!', 4.3, 1.5)] },
    { name: 'The belt', on: 'cart', title: LIST(...STRUCK(6)), style: 'list', record: ['five red apples', 'green bananas', 'black berries', 'extra virgin olive oil', '?plain flour', 'southwest hash browns'], pos: [-6.4, 3.6, -18.9], tgt: [-8.4, 1.2, -13.4], lens: 40, sec: 7.89, shift: 'belt', look: STORE,
      acts: [{ who: 'homer', from: 'belt', look: 'clerk' }, { who: 'cart', from: 'cart-belt', brake: true }, { who: 'bart', from: 'bart-belt', look: 'cart' }, { who: 'lisa', from: 'lisa-belt', look: 'homer' }, { who: 'flanders', from: 'ned-belt', look: 'clerk', pose: 'stand' }, { who: 'clerk', from: 'clerk', look: 'cart' }],
      events: [BEAT('belt', 'clerk', 0, 7.89, 'the receipt says what was bought; the record checks itself against it', 'deadpan'), SND('servo', 0.3), SND('ping', 0.95), SAY('clerk', 'Five red apples.', 1.0, 1.1), SAY('flanders', 'Check.', 2.2, 0.6), SND('ping', 2.93), SAY('clerk', 'Green bananas.', 2.98, 1.0), SAY('flanders', 'Check.', 4.1, 0.6), SND('ping', 4.9), SAY('clerk', 'Extra virgin olive oil.', 4.95, 1.4), SAY('flanders', 'Check-diddly-eck.', 6.5, 1.1), P('flanders', 'joy', 6.4)] },
    { name: 'The record', on: 'flanders', title: LIST(...STRUCK(6), '+Maggie'), style: 'list', record: ['five red apples', 'green bananas', 'black berries', 'extra virgin olive oil', '~plain flour', '+organic flour', 'southwest hash browns'], pos: [-3.2, 3.4, -17.9], tgt: [-10.6, 1.3, -14.6], lens: 36, sec: 7.89, shift: 'record', look: STORE,
      fit: [{ at: 1.3, for: 3.2, dir: 'record', a: 'organic flour', b: 'plain is crossed out', say: 'the flour stays organic: the record is changed to fit it' }],
      acts: [{ who: 'homer', look: 'clerk' }, { who: 'cart', brake: true }, { who: 'flanders', look: 'clerk', pose: 'stand' }, { who: 'clerk', look: 'cart' }],
      events: [BEAT('record', 'flanders', 0, 7.89, 'a mistake in the record: the record is wrong, not the flour; the baby is on neither', 'deadpan'), SND('ping', 0.2), SAY('clerk', 'Organic flour.', 0.25, 0.9), SAY('flanders', 'Organic? I wrote plain.', 1.3, 1.3), P('flanders', 'concern', 1.2), SAY('flanders', 'My record\'s wrong, not the flour.', 2.7, 1.8), SND('ping', 4.6), SAY('clerk', 'Baby.', 4.65, 0.6), SAY('homer', 'She\'s not on the list!', 5.4, 1.4), P('homer', 'concern', 5.3), SAY('clerk', 'It scanned.', 6.9, 0.9), P('clerk', 'weariness', 6.7)] },
    { score: null, fade: 3.6, title: 'THE LIST', style: 'card', sec: 3.95, name: 'the card' }] };

/* ── 2. The forest skirmish: Ewoks against robots (ewoks.mpd), the middle of the stage kept clear ── */
Film.SCENES['case-ewoks'] = { name: 'The Forest Skirmish', time: 'day', weather: 'clear', ground: 'flat', me: 'off', part: 'ewok-1', set: { kind: 'stage', r: 120, seed: 1 },   /* a bare stage under the set: the author calls its rim a soundstage horizon; the valley's houses and trees go */
  story: { title: 'The Forest Skirmish', description: 'Two lines in a forest with a fallen log between them: an intrusion, an ambush, a train that both sides take for the enemy, and the reversal when the plane comes over.', location: 'a redwood clearing with a track through it',
    entities: [{ id: 'ewoks', type: 'crowd', name: 'the Ewoks', traits: ['cover', 'spears'] }, { id: 'robots', type: 'crowd', name: 'the robots', traits: ['the line', 'blasters'] }, { id: 'train', type: 'vehicle', name: 'the train', traits: ['the crease', 'the horn'] }, { id: 'plane', type: 'vehicle', name: 'the plane', traits: ['overhead'] }, { id: 'clearing', type: 'location', name: 'the clearing', traits: ['the log', 'the crates'] }],
    goals: ['hold the clearing'], obstacles: ['the wrong enemy'], shifts: [{ id: 'lines', name: 'The lines' }, { id: 'intrusion', name: 'The intrusion' }, { id: 'ambush', name: 'The ambush' }, { id: 'train', name: 'The train' }, { id: 'reversal', name: 'The reversal' }, { id: 'aerial', name: 'From above' }], why: 'a mistaken enemy ends a fight nobody could win', direction: 'confrontation' },
  donors: [{ name: 'the clearing', set: 'forest-clearing', x: 0, z: 0, heading: 180, scale: 1 }],   /* the real model (world/models/forest-clearing.js), at minifig scale */
  marks: { 'ewok-cover': [-10, -3], 'robot-cover': [5, 4], 'middle': [-1, -2], 'ewok-rush': [-5, -1.5], 'robot-rush': [3, -1.5], 'track': [13, -1], 'back': [-12, -1] },   /* stud (x, z) halved and centred: the log at 22..41 × 31..32, the platform at 8..15 × 12..19, the fire at 6..9 × 28..31, the bunker at 44..55 × 36..45 with its door on the west, the track at 61..62 with the locomotive at z 26..33 */
  actors: [
    { name: 'ewok-1', figure: 'ewok', label: 'an Ewok', x: -11, z: -3, heading: 90 }, { name: 'ewok-2', figure: 'ewok', label: 'an Ewok', x: -9.5, z: -1.5, heading: 90 }, { name: 'ewok-3', figure: 'ewok', label: 'an Ewok', x: -11.5, z: -0.5, heading: 90 },
    { name: 'robot-1', figure: 'robot', label: 'a robot', x: 5, z: 3, heading: 270 }, { name: 'robot-2', figure: 'robot', label: 'a robot', x: 5.5, z: 4.5, heading: 270 }, { name: 'robot-3', figure: 'robot', label: 'a robot', x: 4, z: 1.5, heading: 270 }],
  /* The cameras stand where the set is clear: the middle of the stage is empty by design (the author's "keep center clear"), the trees are on the north edge at z -16, the plane hangs at 32 m. The set's own six MENTO cameras are kept in the file's header for reference; four of them stood inside its trunks and canopy at this scale. */
  shots: [
    { score: 'march', title: 'THE FOREST SKIRMISH', style: 'card', sec: 2, events: [SAY('narrator', 'The forest skirmish.', 0.3, 1.4)] },
    { name: 'Skirmish wide', on: 'the clearing', pos: [-6, 7, 14], tgt: [0, 1, -1], lens: 36, sec: 6, shift: 'lines', events: [BEAT('lines', 'ewok-1', 0, 6, 'two lines, a log between them, nobody moving first', 'guarded'), SND('chirp', 1.0), SND('chirp', 2.8), SAY('narrator', 'Two lines. Ewoks by the train to the west, robots by the stumps to the east.', 0.8, 3.6)] },
    { name: 'Ewok line', on: 'ewok-1', pos: [-3, 1.6, -3], tgt: [-10.5, 1, -2], lens: 36, sec: 4, shift: 'lines', events: [P('ewok-1', 'guarded', 0.3), P('ewok-2', 'listen', 0.5), LOOK('ewok-1', 'robot-1', 0.4, true), SAY('ewok-1', 'Yub nub.', 1.6, 1.0), SND('chirp', 2.6)] },
    { name: 'Robot line', on: 'robot-1', pos: [1, 1.6, 3], tgt: [5, 1.2, 3.5], lens: 40, sec: 4, shift: 'intrusion', acts: [{ who: 'robot-1', to: 'robot-rush', walk: true }], events: [BEAT('intrusion', 'robot-1', 0, 4, 'one robot steps over the line', 'resolve'), P('robot-1', 'resolve', 0.3), SND('servo', 0.6), SND('servo', 1.8), SAY('robot-1', 'Advancing.', 1.0, 1.2)] },
    { name: "No man's land", on: 'middle', pos: [-1, 2.4, 2.5], tgt: [-1, 1, -2], lens: 35, sec: 6, shift: 'ambush', handheld: 0.5,
      acts: [{ who: 'ewok-1', to: 'ewok-rush' }, { who: 'ewok-2', to: 'middle' }, { who: 'ewok-3', to: 'ewok-rush' }],
      events: [BEAT('ambush', 'ewok-1', 0, 6, 'the Ewoks rush the one who crossed', 'confrontation'), SND('roar', 0.5), SND('swing', 2.4), SND('clash', 2.9), SND('thud', 3.4), { what: 'SHAKE', at: 3.0 }, P('robot-1', 'panic', 3.2), P('ewok-2', 'angry', 2.8)] },
    { name: 'Train vector', on: 'track', pos: [7, 2.8, -7], tgt: [14.75, 1.2, -2.5], lens: 40, sec: 5, shift: 'train', events: [BEAT('train', 'robot-2', 0, 5, 'the train comes down the crease and both sides take it for the enemy', 'fear'), SND('static', 0.4), SND('clatter', 1.6), SND('clatter', 2.8), P('robot-2', 'fear', 1.2), P('robot-3', 'fear', 1.6), LOOK('robot-2', 'track', 0.6, true), SAY('narrator', 'A train on the west rim. Both lines take it for the enemy.', 1.0, 3.0)] },
    { name: 'The reversal', on: 'the clearing', pos: [0, 6, -12], tgt: [0, 1, 0], lens: 40, sec: 6, shift: 'reversal',
      acts: [{ who: 'robot-1', to: 'robot-cover', walk: true }, { who: 'robot-2', to: 'robot-cover', walk: true }, { who: 'robot-3', to: 'robot-cover', walk: true }, { who: 'ewok-1', to: 'ewok-cover', walk: true }, { who: 'ewok-2', to: 'ewok-cover', walk: true }, { who: 'ewok-3', to: 'ewok-cover', walk: true }],
      events: [BEAT('reversal', 'ewok-1', 0, 6, 'both lines pull back; the log keeps the peace', 'weariness'), P('robot-3', 'panic', 0.3), SND('clatter', 1.0), SAY('narrator', 'Both sides withdrew. The train did not notice.', 2.0, 3.2)] },
    { name: 'Aerial map', on: 'the clearing', pos: [-14, 16, 14], tgt: [1, 0, -1], lens: 42, sec: 5, shift: 'aerial', events: [SND('whoosh', 0.8), SND('whoosh', 2.6), SAY('narrator', 'From above: the whole stage, the train, the stumps, the palms.', 0.8, 2.6)] },
    { score: 'end', title: 'THE FOREST SKIRMISH\nA CASE TO REHEARSE', style: 'card', sec: 3, name: 'the card' }] };

/* ── 3. The cave: Plato's Republic VII on the four-zone construct (platos-cave.mpd) ── */
const CAVE = { hemi: 4, sun: 0, exposure: 1.2 };   /* the cave shots at night: the look's hemi is a multiplier on the night's ambient (four times it reads), no sun, the exposure up; the fire is a lamp close to what it lights */
const FIRE = { at: [-0.25, 2.4, 1.75], color: 0xff7a2a, intensity: 20, distance: 30 };
Film.SCENES['case-plato'] = { name: "The Cave", time: 'night', weather: 'clear', ground: 'flat', me: 'off', part: 'freed', set: { kind: 'hall', r: 60, seed: 1 },   /* a dark hall round the construct: nothing of the valley shows past the cave walls */
  story: { title: 'The Cave', description: 'Captives face a wall of shadows; behind them on the parapet the puppeteers carry shapes before a fire. One captive is loosed, turns, and sees who makes the shadows; the climb to the light; the return to people who prefer the wall.', location: "Plato's cave: the pit, the screen, the parapet, the fire, the ascent",
    entities: [{ id: 'captives', type: 'crowd', name: 'the captives', traits: ['bound', 'facing the wall'] }, { id: 'freed', type: 'character', name: 'the freed one', traits: ['turns', 'climbs'] }, { id: 'puppeteers', type: 'crowd', name: 'the puppeteers', traits: ['the parapet', 'the shapes'] }, { id: 'fire', type: 'location', name: 'the fire', traits: ['the false light'] }, { id: 'sun', type: 'location', name: 'the ascent', traits: ['the true light'] }],
    goals: ['see what makes the shadows'], obstacles: ['the bonds', 'the climb', 'the people who will not turn'], shifts: [{ id: 'shadows', name: 'The shadows' }, { id: 'puppeteers', name: 'The puppeteers' }, { id: 'turn', name: 'The turn' }, { id: 'climb', name: 'The climb' }, { id: 'sun', name: 'The sun' }, { id: 'return', name: 'The return' }], why: 'the one who turns around', direction: 'wonder' },
  donors: [{ name: 'the cave', set: 'cave-of-shadows', x: 0, z: 0, heading: 180, scale: 1 }],   /* the real model (world/models/cave-of-shadows.js), at minifig scale */
  marks: { row: [-0.25, -8], screen: [-0.25, -11.5], parapet: [-0.25, -2.5], fire: [-0.25, 1.75], slope: [7, -1], out: [14.5, 1.5], side: [-2, -8] },
  /* stud (x, z) halved and centred: the wall of shadows at z 0..1, the bench at z 12..13, the parapet at z 18..21 (1.8 m), the fire at 30..33 × 26..29, the stairs at 46..51 × 24..27 rising to the lookout, the way out past them at z 20..23 to the ledge at x 58..63 under the sun on its column at 60..61 × 23..24 */
  actors: [
    { name: 'captive-1', figure: 'shade', label: 'a captive', x: -1.5, z: -8, heading: 0 }, { name: 'captive-2', figure: 'shade', label: 'a captive', x: 1, z: -8, heading: 0 },
    { name: 'freed', figure: 'citizen', label: 'the freed one', x: -0.25, z: -8, heading: 0 },
    { name: 'puppeteer-1', figure: 'hauler', label: 'a puppeteer', x: -6, z: -0.5, heading: 0 }, { name: 'puppeteer-2', figure: 'hauler', label: 'a puppeteer', x: 5, z: -0.5, heading: 0 }],   /* the captives stand before the bench facing the wall; the puppeteers stand behind the parapet by the fire, out of the captives' sight */
  shots: [
    { score: 'dread', title: 'THE CAVE', style: 'card', sec: 2, events: [SAY('narrator', 'The cave. Republic, book seven.', 0.3, 2.0)] },
    { name: 'The shadows', on: 'screen', pos: [-0.25, 2.6, -4], tgt: [-0.25, 2.2, -11.5], lens: 40, sec: 7, shift: 'shadows', look: CAVE, lamp: { at: [-0.25, 3, -6.5], color: 0xff7a2a, intensity: 8, distance: 30 },
      events: [BEAT('shadows', 'freed', 0, 7, 'shapes cross the wall; the captives name them', 'wonder'), SND('static', 0.5), SAY('narrator', 'They have been here since childhood, and see only the shadows.', 1.2, 4.2), P('captive-1', 'listen', 0.4), P('captive-2', 'listen', 0.6), P('freed', 'wonder', 2.0)] },
    { name: 'The puppeteers', on: 'parapet', pos: [6, 1.8, 3.5], tgt: [-0.25, 1.4, -1.5], lens: 38, sec: 6, shift: 'puppeteers', look: CAVE, lamp: FIRE,
      events: [BEAT('puppeteers', 'puppeteer-1', 0, 6, 'behind the wall, the people who carry the shapes', 'deadpan'), SET('puppeteer-1', 'arm.R.pitch', -2.8, 0.6, 0.8), SET('puppeteer-2', 'arm.L.pitch', -2.8, 1.0, 0.8), SND('servo', 1.2), SND('servo', 3.6), SAY('narrator', 'Behind them a fire, and between the fire and the captives a wall, along which men carry figures.', 0.8, 4.6)] },
    { name: 'The turn', on: 'freed', pos: [2, 1.7, -7], tgt: [-0.25, 1.5, -8], lens: 32, sec: 7, shift: 'turn', look: CAVE, lamp: { at: [1, 2.5, -6.5], color: 0xff7a2a, intensity: 6, distance: 30 },
      events: [BEAT('turn', 'freed', 0, 7, 'loosed, he turns his head and sees the fire', 'recognition'), SET('freed', 'head.yaw', 2.4, 1.0, 1.4), SET('freed', 'torso.twist', 0.6, 1.4, 1.2), P('freed', 'wonder', 2.4), LOOK('freed', 'fire', 2.6, true), SND('breath', 3.0), SAY('narrator', 'Suppose one were freed, and made to turn his head.', 1.4, 3.0)] },
    { name: 'The climb', on: 'freed', pos: [4, 2, 5], tgt: [7.5, 1.5, 1], lens: 40, sec: 8, shift: 'climb', look: CAVE, lamp: { at: [6, 3, 3], color: 0xff7a2a, intensity: 6, distance: 30 },
      acts: [{ who: 'freed', to: 'slope', walk: true }],
      events: [BEAT('climb', 'freed', 0, 8, 'the rough ascent toward a light that hurts', 'resolve'), P('freed', 'resolve', 0.4), SND('footstep', 1.0), SND('footstep', 2.0), SND('footstep', 3.0), SND('breath', 5.0), SAY('narrator', 'Dragged up the steep way, he would be pained and dazzled.', 1.0, 3.6)] },
    { name: 'The sun', on: 'out', pos: [20, 1.4, 7], tgt: [14, 5.5, 0], lens: 44, sec: 6, shift: 'sun', set: { kind: 'desert', r: 40, seed: 5, time: 'dawn' }, look: { hemi: 0.5, sun: 1.2, elev: 12, azim: 180, exposure: 1.0 },
      acts: [{ who: 'freed', to: 'out', walk: true }],
      events: [BEAT('sun', 'freed', 0, 6, 'the thing itself, not its shadow', 'wonder'), P('freed', 'wonder', 1.0), { what: 'FLASH', at: 0.4 }, SAY('narrator', 'Last of all he would see the sun, not in the water, but itself, in its own place.', 1.0, 4.4)] },
    { name: 'The return', on: 'row', pos: [-3.5, 2.4, -4.5], tgt: [-0.25, 1.4, -8], lens: 40, sec: 7, shift: 'return', set: { kind: 'hall', r: 60, seed: 1, time: 'night' }, look: CAVE, lamp: { at: [1, 2.5, -6.5], color: 0xff7a2a, intensity: 6, distance: 30 },
      acts: [{ who: 'freed', to: 'side', walk: true }],
      events: [BEAT('return', 'freed', 0, 7, 'he comes back down to tell them, and they laugh at his ruined eyes', 'hurt'), P('freed', 'appeal', 1.0), P('captive-1', 'contempt', 3.0), P('captive-2', 'skepticism', 3.4), SAY('narrator', 'Would they not say his eyes were ruined by the climb, and that it was not worth even trying?', 1.0, 4.6)] },
    { score: 'end', title: 'THE CAVE\nA CASE TO REHEARSE', style: 'card', sec: 3, name: 'the card' }] };

/* ── 4. The Searchers: the homecoming, on The Homestead (world/models/homestead.js) under The Buttes (world/models/buttes.js) ── */
/* Studs to metres: the homestead is 48 × 48 studs laid at heading 180, so world metres = (stud − 24) / 2 on both axes; it is laid a plate down
   (y −0.18) so its floors, porch and path are the ground the figures stand on. The door frame is at studs x 22..25 on the wall line z 19
   (x −1..1, z −2.5..−2); the room x 13..34 × z 5..18 (x −5.5..5.5, z −9.5..−2.5); the porch boards z 20..28 (z −2..2.5), its posts at
   x 12, 18, 28, 34 on z 27, z 1.5..2.5 (the gap before the door x −2..2); the table x 15..20 × z 11..14 (x −4.5..−1.5, z −6.5..−4.5); the bed x 29..33 × z 5..7
   (x 2.5..5, z −9.5..−8); the path x 21..26 south from z 29 (x −1.5..1.5, z 2.5..12); the hitching rail and horse at x 4..8, z 3..4.5.
   The buttes (studs 2..87 × 2..29, centre 44.5, 15.5) are laid at x 41, z 62: the mitten at (24.75, 61.5), south-east of the door and off its line (through the door the flat runs to the horizon, as in the film); the spire at (40.75, 57.25); the east butte at (56.5, 65).
   Every walk into the room starts on the porch and passes the door plane (z −2.25) within half a metre of x 0, and ends out of the inside camera's frame (east of it).
   The sun stands east-south-east at 26 degrees (look.azim 115), so the yard and the buttes are lit and the room under its ceiling is not. */
const SUN = { hemi: 0.9, sun: 1.35, elev: 40, azim: 115, exposure: 1.22, tone: 'aces' };   /* ACES: the highlights roll off like a print's, the reds of the earth hold */
const AGAINST = { hemi: 0.06, sun: 1.8, elev: 38, azim: 200, exposure: 1.35, tone: 'aces' };   /* the take, as the original lights it: the sun out over the desert facing the door, low enough to reach under the porch roof, so the boards are lit, whoever stands on them is a dark shape with a lit edge, and the shadows run back toward the house */
const DOORLAMP = { at: [0.1, 2.1, -7.4], aim: [0.1, 1.2, -0.6], color: 0xffd6a0, intensity: 2.2, distance: 16, angle: 0.16, penumbra: 0.8 };   /* a narrow warm spot from behind the camera through the door, onto his face as he looks back in: the room around it stays dark */   /* a low warm light just inside the door: enough on his face, as he looks back in, to see him */   /* the doorway at the end: no fill in the room, the desert burnt bright, so whoever stands in the door is a black shape against it */
const HARD = { contrast: 1.22, sat: 1.12, sepia: 0.04, warm: 0.08, halation: 0.3, halBright: 1.15, skyBlue: [0.5, 0.3], vignette: 0.55, grain: 0.06 };   /* hard at the edges, soft in the light: the outside keeps its range */   /* the camera by the back wall, and the middle of the door it looks at */
/* Cut shot for shot to the film's own ending (the reference clip, 0 to 114.95 s): eight set-ups, each as long as the original's, the last one
   the long take that starts on the porch looking out, pulls back through the door into the dark room, holds the doorway while the family and
   then the young couple go in past the man, and ends when the door closes on him walking away. Here that take is three shots with no cut
   between them (a hold on the porch, the pull back, the hold inside): the camera's position carries straight across. Lars Jorgensen is Aaron,
   Mrs Jorgensen is Martha, Laurie is Lucy; Martin rides in with Ethan.
     1  0.00- 3.88  the porch, low: the old man in the rocker, the women at the edge, looking out
     2  3.88-10.47  the pool: loose horses drinking, the riders far off under the mesas
     3 10.47-16.47  the porch again: Lucy breaks and runs
     4 16.47-33.41  the flat: she runs out to Martin; Ethan rides on toward us with Debbie
     5 33.41-41.50  Martha and Aaron at the post, watching him come
     6 41.50-49.17  under the mitten: he lifts her down
     7 49.17-55.18  Mose in his rocker, the hat in the air
     8 55.18-108.50 the doorway (8a porch 55.18-68.50, 8b the pull back 68.50-75.00, 8c the hold 75.00-95.00 and, on the same camera, his walk
                    95.00-108.50; the door shuts 106.5-107.5 and the frame stays black a second, as the original's does) */
const PORCHCAM = [0.1, 1.8, -1.9], OUTAIM = [0.1, 1.8, 12], ROOMCAM = [0.1, 1.7, -8.7], ROOMAIM = [0.1, 1.7, -2.25];   /* inside, a long lens: the doorway fills the frame's height, black either side, as the original frames it */
const PORCHLOW = [-7.6, 1.1, 0.0], PORCHAIM = [0, 1.8, -0.8];   /* on the porch between the rocker and the posts, looking east: the old man in the rocker at the left, the posts and the desert at the right */
const SHADE = { hemi: 0.9, sun: 1.35, elev: 40, azim: 115, exposure: 1.3, tone: 'aces' };   /* under the porch roof in full day: the fill lets the faces read */
const INTO = [[0.1, -1.4], [0.7, -3.3]];   /* through the door, then off the camera's line so the walk passes it on the side */
Film.SCENES['case-searchers'] = { name: 'The Searchers', time: 'day', weather: 'clear', ground: 'flat', me: 'off', part: 'ethan',
  grade: { contrast: 1.12, sat: 1.2, sepia: 0.03, warm: 0.1, halation: 0.2, skyBlue: [0.6, 0.4], vignette: 0.35, grain: 0.06 },   /* a Technicolor print: warm and contrasty, a glow round the bright door, the sky a deep blue at the top, dark corners, grain */
  set: { kind: 'monument', r: 200, seed: 3, corridor: [[-1, -14], [1, 12], [3, 40], [3, 70]], keepOut: [[-13, -13, 13, 13], [-17.5, 28.5, -0.5, 39.5], [18.5, 53, 63.5, 71]] },   /* the LEGO strewn on the flat stays off the homestead, the pool and the buttes */
  story: { title: 'The Searchers', description: 'The family on the porch sees riders coming in past the pool under the buttes. The girl runs out to the young man. The other man rides on to the house with the girl the Comanche took, and lifts her down. The family takes her in, and the young couple go in after them. He stays on the porch, and walks back into the desert, and the door shuts.', location: 'a homestead under the buttes',
    entities: [{ id: 'ethan', type: 'character', name: 'Ethan', traits: ['the hat', 'five years searching', 'the door he does not go through'] }, { id: 'debbie', type: 'character', name: 'Debbie', traits: ['taken', 'brought home'] }, { id: 'martha', type: 'character', name: 'Martha', traits: ['the porch', 'the one who waited'] }, { id: 'aaron', type: 'character', name: 'Aaron', traits: ['the rocker', 'the house'] }, { id: 'martin', type: 'character', name: 'Martin', traits: ['rode with him'] }, { id: 'lucy', type: 'character', name: 'Lucy', traits: ['runs out to Martin'] }, { id: 'mose', type: 'character', name: 'Mose', traits: ['the rocker', 'the hat'] }, { id: 'door', type: 'location', name: 'the door', traits: ['the dark room', 'the bright desert'] }],
    goals: ['bring Debbie home'], obstacles: ['the man who brings her is not a man for houses'], shifts: [{ id: 'porch', name: 'The porch' }, { id: 'sighting', name: 'The pool' }, { id: 'run', name: 'Lucy runs' }, { id: 'approach', name: 'The approach' }, { id: 'recognition', name: 'Martha' }, { id: 'lift', name: 'Down from the horse' }, { id: 'mose', name: 'Mose' }, { id: 'home', name: 'Home' }, { id: 'inside', name: 'Inside' }, { id: 'leaving', name: 'The leaving' }], why: 'the one who brings them home cannot come in', direction: 'restraint' },
  donors: [{ name: 'the homestead', set: 'homestead', x: 0, z: 0, heading: 180, scale: 1, y: -0.18 }, { name: 'the buttes', set: 'buttes', x: 41, z: 62, heading: 180, scale: 1 }, { name: 'the waterhole', set: 'waterhole', x: -9, z: 34, heading: 180, scale: 1, y: -0.12 }],
  marksHidden: true,
  marks: { 'porch-m': [-3.4, 0.9, 0, 160], 'porch-l': [-0.6, -0.3, 0, 175], run: [-1.6, 24.5], 'post-m': [-3.6, 1.7, 0, 175], 'post-a': [-1.4, 1.7, 0, 185],
    'far-e': [-7.5, 58, 0, 0], 'far-t': [-4.8, 59.5, 0, 0], 'flat-e': [0.8, 40, 0, 0], 'flat-t': [-2.4, 41, 0, 0], meet: [-2.0, 27], 'ride-in': [1.1, 11], lift: [5.5, 16.0, 0, 247], 'e-lift': [6.7, 14.2, 0, 214], 'd-lift': [5.8, 13.6, 0, 200],
    'e-path': [0.4, 7.2, 0, 0], 'd-path': [1.3, 7.6, 0, 0], 'e-step': [0.4, 3.3], 'd-step': [-0.1, 2.8], 'a-edge': [1.1, 2.4, 0, 180], 'm-edge': [-0.9, 2.3, 0, 180],
    't-yard': [-2.2, 15.5, 0, 0], 'l-yard': [-1.4, 15.2, 0, 0], 't-near': [-0.8, 5.0], 'l-near': [-0.1, 5.3], 'e-door': [-0.7, 0.3, 0, 0], 'e-in': [-0.15, 0.7, 0, 0],
    'room-d': [3.4, -6.4], 'room-m': [1.8, -8.6], 'room-a': [4.8, -7.4], 'room-l': [3.6, -8.9], 'room-t': [5.0, -5.4], desert: [1.6, 30], pasture: [-7.0, 8.5] },
  actors: [
    { name: 'martha', figure: 'martha', label: 'Martha', x: -3.4, z: 0.9, heading: 160 },
    { name: 'aaron', figure: 'aaron', label: 'Aaron', x: -4.5, z: -1.0, heading: 180, pose: 'sit', sitLift: 10 },   /* Lars Jorgensen's rocker, at the west end of the porch */
    { name: 'lucy', figure: 'lucy', label: 'Lucy', x: -0.6, z: -0.3, heading: 175 },
    { name: 'mose', figure: 'mose', label: 'Mose Harper', x: 4.0, z: -1.0, heading: 180, pose: 'sit', sitLift: 10 },
    { name: 'ethan', figure: 'ethan', label: 'Ethan', x: -7.5, z: 58, heading: 0 },
    { name: 'debbie', figure: 'debbie', label: 'Debbie', x: -7.0, z: 58.6, heading: 0 },
    { name: 'martin', figure: 'martin', label: 'Martin', x: -4.8, z: 59.5, heading: 0 },
    { name: 'ethan-horse', kind: 'horse', len: 7, col: 70, label: "Ethan's horse", x: -7.5, z: 58, heading: 0 },
    { name: 'martin-horse', kind: 'horse', len: 7, col: 0, label: "Martin's horse", x: -4.8, z: 59.5, heading: 0 }],   /* the loose horses at the pool are the waterhole model's own three */
  shots: [
    { name: 'The porch', on: 'martha', pos: PORCHLOW, tgt: PORCHAIM, lens: 56, sec: 3.88, shift: 'porch', look: SHADE, score: 'file:../music/searchers-score.ogg',
      acts: [{ who: 'ethan', ride: 'ethan-horse' }, { who: 'debbie', ride: 'ethan-horse' }, { who: 'martin', ride: 'martin-horse' }, { who: 'martha', from: 'porch-m', look: 'ethan' }, { who: 'lucy', from: 'porch-l', look: 'martin' }],
      events: [BEAT('porch', 'martha', 0, 3.88, 'the family on the porch, looking out', 'wonder'), LOOK('martha', 'ethan', 0.2, true), LOOK('lucy', 'martin', 0.3, true), LOOK('aaron', 'ethan', 0.5, true)] },
    { name: 'The pool', on: 'ethan', pos: [-9, 2.0, 17], tgt: [-7, 1.5, 55], lens: 40, sec: 6.59, shift: 'sighting', look: SUN,
      acts: [{ who: 'ethan-horse', from: 'far-e', to: 'flat-e', speed: 0.62 }, { who: 'martin-horse', from: 'far-t', to: 'flat-t', speed: 0.62 }],
      events: [BEAT('sighting', 'ethan', 0, 6.59, 'riders under the mesas, past the loose horses at the pool', 'wonder'), { ...SND('snort', 1.2), k: 0.35 }, { ...SND('hooves', 3.0), k: 0.25 }, { ...SND('whinny', 5.2), k: 0.3 }] },
    { name: 'Lucy runs', on: 'lucy', pos: PORCHLOW, tgt: PORCHAIM, lens: 56, sec: 6.01, shift: 'run', look: SHADE,
      acts: [{ who: 'lucy', to: 'run', run: true, at: 3.3 }, { who: 'martha', look: 'ethan' }],
      events: [BEAT('run', 'lucy', 0, 6.01, 'she knows the second rider, and breaks for him', 'joy'), P('lucy', 'joy', 2.6), P('martha', 'wonder', 1.0), SND('footstep', 3.4), SND('footstep', 3.7), SND('footstep', 4.0)] },
    { name: 'The approach', on: 'ethan', pos: [-2.2, 1.4, 3.6], tgt: [-0.6, 2.0, 40], lens: 30, sec: 16.93, shift: 'approach', look: SUN,
      acts: [{ who: 'lucy', from: 'porch-l', to: 'meet', run: true }, { who: 'ethan-horse', from: 'flat-e', to: 'ride-in', speed: 0.7 }, { who: 'martin-horse', from: 'flat-t', to: 'meet', speed: 0.5 }, { who: 'martin', leave: true, to: 'meet', at: 9.5 }],
      events: [BEAT('approach', 'ethan', 0, 16.93, 'she reaches Martin; Ethan rides on toward the house with the girl', 'weariness'), SND('footstep', 0.3), SND('footstep', 0.6), SND('footstep', 0.9), { ...SND('hooves', 4.0), k: 0.3 }, { ...SND('hooves', 8.0), k: 0.45 }, { ...SND('whinny', 10.4), k: 0.4 }, { ...SND('hooves', 12.0), k: 0.6 }, { ...SND('hooves', 14.0), k: 0.7 }, { ...SND('snort', 15.6), k: 0.6 }, P('ethan', 'weariness', 11.0)] },
    { name: 'Martha', on: 'martha', pos: [-2.3, 1.7, 8.8], tgt: [-2.5, 1.7, 1.7], lens: 30, sec: 8.09, shift: 'recognition', look: SUN,
      acts: [{ who: 'martha', from: 'post-m', look: 'ethan' }, { who: 'aaron', from: 'post-a', pose: 'stand', look: 'ethan' }],
      events: [BEAT('recognition', 'martha', 0, 8.09, 'she sees who he has with him', 'recognition'), LOOK('martha', 'ethan', 0.2, true), LOOK('aaron', 'ethan', 0.4, true), P('martha', 'recognition', 1.2), SND('breath', 2.6), P('aaron', 'joy', 4.2), SET('martha', 'head.yaw', -0.5, 5.6, 0.8)] },
    { name: 'Down from the horse', on: 'debbie', pos: [-0.6, 0.9, 4.0], tgt: [9, 2.4, 28], lens: 30, sec: 7.67, shift: 'lift', look: SUN,
      acts: [{ who: 'ethan-horse', from: 'lift', halt: true }, { who: 'ethan', leave: true, to: 'e-lift', walk: true, look: 'debbie' }, { who: 'debbie', leave: true, to: 'd-lift', walk: true, at: 2.6 }],
      events: [BEAT('lift', 'ethan', 0, 7.67, 'he lifts her down from the saddle', 'tenderness'), SET('ethan', 'arm.R.pitch', -1.9, 0.8, 0.6), SET('ethan', 'arm.L.pitch', -1.9, 0.8, 0.6), SET('ethan', 'arm.R.pitch', -0.9, 3.0, 0.8), SET('ethan', 'arm.L.pitch', -0.9, 3.0, 0.8), { ...SND('snort', 1.4), k: 0.5 }, SND('footstep', 3.1), P('debbie', 'guarded', 3.6)] },
    { name: 'Mose', on: 'mose', pos: [4.0, 1.35, 3.4], tgt: [4.0, 1.3, -1.3], lens: 36, sec: 6.01, shift: 'mose', look: SHADE,
      acts: [{ who: 'mose', look: 'ethan' }],
      events: [BEAT('mose', 'mose', 0, 6.01, 'the old man in his rocker, his hat off to them', 'joy'), P('mose', 'joy', 0.3), SET('mose', 'arm.R.pitch', -2.7, 0.5, 0.5), SET('mose', 'arm.R.pitch', -2.2, 1.3, 0.4), SET('mose', 'arm.R.pitch', -2.8, 2.0, 0.4), SET('mose', 'arm.R.pitch', -2.2, 2.7, 0.4), SET('mose', 'arm.R.pitch', -2.8, 3.4, 0.4), SET('mose', 'arm.R.pitch', 0, 5.0, 0.8)] },
    { name: 'Home', on: 'debbie', pos: PORCHCAM, tgt: OUTAIM, lens: 44, sec: 13.32, shift: 'home', look: AGAINST, grade: HARD,
      acts: [{ who: 'ethan', from: 'e-path', to: 'e-step', walk: true, at: 0.2 }, { who: 'debbie', from: 'd-path', to: 'd-step', walk: true, at: 0.4 }, { who: 'aaron', from: 'a-edge', look: 'debbie' }, { who: 'martha', from: 'm-edge', look: 'debbie' }, { who: 'lucy', from: 'l-yard', to: 'l-near', walk: true, at: 1.5 }, { who: 'martin', from: 't-yard', to: 't-near', walk: true, at: 1.2 }, { who: 'ethan-horse', from: 'lift', to: 'pasture', speed: 0.3, at: 2.0 }],
      events: [BEAT('home', 'debbie', 0, 13.32, 'he brings her up to the porch; the two who waited meet her at the edge', 'tenderness'), SND('footstep', 0.8), SND('footstep', 1.4), SND('footstep', 2.0), SND('footstep', 2.6), LOOK('martha', 'debbie', 0.4, true), P('martha', 'tenderness', 3.8), LOOK('aaron', 'debbie', 0.6, true)] },
    { name: 'Home, in', on: 'martha', pos: PORCHCAM, pos2: ROOMCAM, tgt: OUTAIM, tgt2: ROOMAIM, lens: 44, lens2: 27, sec: 6.5, shift: 'home', look: AGAINST, grade: HARD,
      acts: [{ who: 'martha', to: 'room-m', via: INTO, walk: true, at: 0.1 }, { who: 'debbie', to: 'room-d', via: INTO, walk: true, at: 0.3 }, { who: 'aaron', to: 'room-a', via: INTO, walk: true, at: 0.8 }, { who: 'ethan', to: 'e-door', walk: true, at: 5.0 }, { who: 'lucy', to: 'l-near', walk: true }, { who: 'martin', to: 't-near', walk: true }],
      events: [SND('footstep', 0.6), SND('footstep', 1.1), SND('footstep', 1.6), SND('footstep', 2.1), SND('footstep', 2.6), SND('footstep', 3.1)] },
    { name: 'The door', on: 'ethan', pos: ROOMCAM, tgt: ROOMAIM, lens: 27, sec: 20.0, shift: 'inside', look: AGAINST, grade: HARD, lamp: DOORLAMP,
      acts: [{ who: 'ethan', to: 'e-in', walk: true, at: 10.5, look: 'room-m' }, { who: 'lucy', to: 'room-l', via: [[0.5, 1.6], [0.4, -1.4], [0.9, -3.3]], walk: true, at: 1.5 }, { who: 'martin', to: 'room-t', via: [[0.7, 1.4], [0.4, -1.4], [0.9, -3.3]], walk: true, at: 2.7 }],
      events: [BEAT('inside', 'ethan', 0, 20.0, 'he stands aside in the door; the young couple go in past him', 'restraint'), SND('footstep', 3.7), SND('footstep', 4.3), SND('footstep', 5.3), SND('footstep', 5.9), LOOK('ethan', 'room-m', 10.5, true), P('ethan', 'weariness', 11.5), SET('ethan', 'arm.L.pitch', -1.1, 13.0, 0.8), SET('ethan', 'arm.R.pitch', -0.35, 13.2, 0.8), SET('ethan', 'arm.L.pitch', 0, 19.0, 0.6), SET('ethan', 'arm.R.pitch', 0, 19.0, 0.6)] },
    { name: 'The leaving', on: 'ethan', pos: ROOMCAM, tgt: ROOMAIM, lens: 27, sec: 13.5, shift: 'leaving', look: AGAINST, grade: HARD, lamp: DOORLAMP, close: [11.5, 1.0],   /* the same camera as the shot before: no cut, the take goes on */
      acts: [{ who: 'ethan', to: 'desert', walk: true, at: 0.2 }],
      events: [BEAT('leaving', 'ethan', 0, 13.5, 'he turns, and walks back into the desert; the door shuts', 'restraint'), SND('footstep', 0.6), SND('footstep', 1.2), SND('footstep', 1.8), { ...SND('whinny', 6.0), k: 0.25 }, { ...SND('whoosh', 11.5), k: 0.5 }] },
    { title: 'THE SEARCHERS', style: 'card', sec: 3.0, name: 'the card' }] };   /* the score's last chord rings out over the card */

/* ── The sheet of nine: every candidate registered with its set, so it can be laid, planned and inspected now. The three with programs stand on real models
   (world/models/*.js, built and audited by tools/model.js: every piece stud-connected, a manual at play/manual.html?model=<model>); the other six still stand on the scene files they came from. ── */
Film.CASES = [
  { key: 'case-grocery', name: 'The List', source: 'world/models/supermarket.js', set: 'supermarket', model: 'supermarket', size: '62 x 47.5 m', cast: ['homer', 'maggie', 'flanders', 'bart', 'lisa', 'citizen'], status: 'program', beats: ['the store', 'the list', 'five red apples', 'the wrong oil', 'caught', 'the belt', 'the record'], play: 'cinerium.html?film=case-grocery&shop' },
  { key: 'case-ewoks', name: 'The Forest Skirmish', source: 'world/models/forest-clearing.js', set: 'forest-clearing', model: 'forest-clearing', size: '32 x 32 m', cast: ['ewok', 'robot'], status: 'program', beats: ['the lines', 'the intrusion', 'the ambush', 'the train', 'the reversal', 'from above'] },
  { key: 'case-plato', name: 'The Cave', source: 'world/models/cave-of-shadows.js', set: 'cave-of-shadows', model: 'cave-of-shadows', size: '32 x 24 m', cast: ['shade', 'citizen', 'hauler'], status: 'program', beats: ['the shadows', 'the puppeteers', 'the turn', 'the climb', 'the sun', 'the return'] },
  { key: 'case-band', name: 'Band Class', source: 'simpsons_scene_06_band.mpd', set: 'simpsons-band', size: '10 x 5 m', cast: ['lisa', 'bart', 'citizen'], status: 'planned', beats: ['the count-in', 'the wrong tempo', 'the interruption', 'the solo', 'the reaction', 'the downbeat'] },
  { key: 'case-searchers', name: 'The Searchers', source: 'world/models/homestead.js', set: 'homestead', model: 'homestead', models: ['homestead', 'buttes'], size: '24 x 24 m', cast: ['ethan', 'martha', 'aaron', 'debbie', 'martin', 'lucy', 'mose'], status: 'program', beats: ['the porch', 'the pool', 'Lucy runs', 'the approach', 'Martha', 'down from the horse', 'Mose', 'home', 'the door', 'the leaving'] },
  { key: 'case-undaunted', name: 'Fort Mandan', source: 'Brickfilm_Studio_Kit/undaunted_scene_2_ohio_fort_mandan.mpd', set: 'undaunted-fort-mandan', size: '13 x 16 m', cast: ['hauler', 'commander', 'rider'], status: 'planned', beats: ['the boats', 'the palisade', 'the winter', 'the guide', 'the map', 'the river again'], note: 'one of seven Undaunted files; the others are the title, Jefferson, Great Falls, the Bitterroot, the Pacific and the credits' },
  { key: 'case-ithaca-cove', name: 'Ithaca Cove', source: 'odyssey-production/locations/ithaca-cove.mpd', set: 'ithaca-cove', size: '70 x 60 m', cast: ['odysseus-wet', 'athena', 'sailor'], status: 'planned', beats: ['the arrival asleep', 'the Phaeacians gone', 'the mist', 'the goddess', 'the concealment of the goods', 'the road up'] },
  { key: 'case-ogygia', name: 'Ogygia Grove', source: 'odyssey-production/locations/ogygia-grove.mpd', set: 'ogygia-grove', size: '70 x 60 m', cast: ['odysseus', 'calypso', 'hermes'], status: 'planned', beats: ['the shore', 'the messenger', 'the order', 'the axe', 'the raft', 'the leaving'], note: 'the raft scene in the play set covers the same beats on the Enchanted Island; this is the authored grove' },
  { key: 'case-rocket', name: 'The Launch', source: 'rocket_launch_scene.ldr', set: 'rocket-launch', size: '13 x 9 m', cast: ['citizen', 'pilot', 'c3po'], status: 'planned', beats: ['the countdown', 'the hold', 'the small problem', 'the fix', 'the launch', 'the unexpectedly small departure'] },
];
Film.PLAY_SCENES = (Film.PLAY_SCENES || []).concat(['case-grocery', 'case-ewoks', 'case-plato', 'case-searchers']);
})();
