/* world/scenes-trailer.js — the Odyssey trailer, patch by patch, in bricks: Film.SCENES['odyssey-trailer'].

   The genome names thirteen patches (a studio card, the dune graves, the beachhead, the pine ridge, the citadel
   overlook, the twilight galleys, the shoreline tow, the cavern, the ashen shore, the tempest, the deck command,
   the chamber vow, the release card). Each is a shot on its own ground, in one scene: a shot's set names the kind
   of ground it stands on (dunes, shore, forest, crag, sea, ash, cave, chamber) and the centre it is laid about,
   the light it wants (day, dusk, night; clear, cloudy, fog, storm) and whether a lamp (firelight, a candle) is on.
   The part is played in each place by its own figure (a bronze Odysseus on the beach, a sword Odysseus in the
   cave, a wet one at the tiller), all captioned by one label. The voices are the halfworld's own takes where a
   take says what the patch needs; the music its albums. */
(function () { if (!window.Film || !Film.SCENES) return;
const T = 'file:odyssey/music/';
/* ── the builds, in studs (a stud is half a metre, a brick 0.24 m) ── */
const graves = { name: 'the dune graves', ops: [] };   /* helmets on posts, shields and spears strewn over forty by twenty-four studs */
for (let i = 0; i < 22; i++) { const x = (i * 11) % 40 + (i % 3), z = (i * 7) % 24; graves.ops.push({ op: 'column', x, z, y: 0, h: 2 + (i % 2), col: 70 }, { op: 'part', part: '3062b', col: 297, x, y: 2 + (i % 2), z }); }   // a bronze round on each post: a helmet at the distance the camera keeps
for (let i = 0; i < 12; i++) graves.ops.push({ op: 'part', part: '3941', col: 297, x: (i * 13 + 3) % 40, y: 0, z: (i * 5 + 2) % 24 });   // bronze rounds on the sand: the shields
const galley = (name, x, z) => ({ name, ops: [{ op: 'group', name: 'hull', x: 0, z: 0, size: [4, 16, 3], ops: [{ op: 'box', x: 0, z: 0, w: 4, d: 16, y: 0, h: 2, col: 308 }, { op: 'band', x: 0, z: 0, w: 4, d: 16, y: 1, h: 1, col: 0 }, { op: 'roof', x: 0, z: 0, w: 4, d: 3, y: 2, col: 308, style: 'gable' }, { op: 'column', x: 2, z: 8, y: 2, h: 9, col: 70 }, { op: 'slab', x: 0, z: 6, w: 4, d: 5, y: 8, plates: 1, col: 15 }] }] });
const citadel = { name: 'the citadel', ops: [{ op: 'group', name: 'crag', x: 0, z: 0, size: [24, 12, 3], ops: [{ op: 'box', x: 0, z: 0, w: 24, d: 12, y: 0, h: 3, col: 72 }] }, { op: 'group', name: 'walls', x: 0, z: 0, size: [24, 12, 12], ops: [{ op: 'wall', from: [2, 10], to: [22, 10], y: 3, h: 5, col: 71 }, { op: 'wall', from: [2, 2], to: [22, 2], y: 3, h: 4, col: 71 }, { op: 'tower', x: 3, z: 6, r: 2, h: 9, y: 3, col: 72, round: false, crenels: true }, { op: 'tower', x: 21, z: 6, r: 2, h: 9, y: 3, col: 72, round: false, crenels: true }, { op: 'tower', x: 12, z: 4, r: 3, h: 12, y: 3, col: 72, round: false, crenels: true }, { op: 'arch', x: 9, z: 10, y: 3, facing: 's', h: 2, col: 72 }] }] };
const horse = { name: 'the white horse', ops: [{ op: 'part', part: '4493c01', col: 15, x: 0, y: 0, z: 0, rot: 1 }] };
const wreck = { name: 'the siege wreck', ops: [{ op: 'group', name: 'tower', x: 0, z: 0, size: [8, 8, 10], ops: [{ op: 'tower', x: 4, z: 4, r: 3, h: 9, col: 70, round: false, crenels: false }, { op: 'box', x: 0, z: 8, w: 12, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 8, z: 3, w: 6, d: 1, y: 0, h: 1, col: 70 }] }, { op: 'group', name: 'ropes', x: 3, z: 9, size: [10, 30, 1], ops: [{ op: 'wall', from: [0, 0], to: [-4, 28], y: 0, h: 1, col: 70 }, { op: 'wall', from: [2, 0], to: [2, 30], y: 0, h: 1, col: 70 }, { op: 'wall', from: [4, 0], to: [9, 27], y: 0, h: 1, col: 70 }] }] };
const cavern = { name: 'the cavern', ops: [
  { op: 'group', name: 'rock', x: 0, z: 0, size: [30, 22, 15], ops: [{ op: 'box', x: 0, z: 0, w: 30, d: 3, y: 0, h: 15, col: 72 }, { op: 'box', x: 0, z: 3, w: 3, d: 18, y: 0, h: 12, col: 72 }, { op: 'box', x: 27, z: 3, w: 3, d: 18, y: 0, h: 12, col: 72 }, { op: 'box', x: 3, z: 3, w: 8, d: 3, y: 0, h: 7, col: 71 }, { op: 'box', x: 19, z: 3, w: 8, d: 4, y: 0, h: 5, col: 71 }, { op: 'box', x: 3, z: 6, w: 6, d: 14, y: 0, h: 2, col: 71 }, { op: 'arch', x: 12, z: 20, y: 0, facing: 's', h: 4, col: 72 }, { op: 'slab', x: 0, z: 0, w: 30, d: 21, y: 15, plates: 3, col: 72 }, { op: 'slab', x: 3, z: 3, w: 24, d: 4, y: 12, plates: 3, col: 72 }] },
  { op: 'group', name: 'fire', x: 14, z: 12, size: [3, 3, 3], ops: [{ op: 'part', part: '3062b', col: 0, x: 0, y: 0, z: 0 }, { op: 'part', part: '3062b', col: 0, x: 1, y: 0, z: 1 }, { op: 'part', part: '85959', col: 57, x: 0, y: 1, z: 0 }, { op: 'part', part: '85959', col: 57, x: 1, y: 1, z: 1 }, { op: 'part', part: '85959', col: 57, x: 1, y: 1, z: 0 }] },
  { op: 'group', name: 'bones', x: 9, z: 8, size: [12, 12, 1], ops: [{ op: 'part', part: '92691', col: 15, x: 0, y: 0, z: 0, rot: 1 }, { op: 'part', part: '92691', col: 15, x: 5, y: 0, z: 3, rot: 2 }, { op: 'part', part: '92691', col: 15, x: 9, y: 0, z: 9, rot: 0 }, { op: 'part', part: '93160', col: 15, x: 2, y: 0, z: 10 }, { op: 'part', part: '93160', col: 15, x: 11, y: 0, z: 2, rot: 1 }] },
  { op: 'group', name: 'polyphemus', x: 14, z: 3, size: [9, 3, 16], ops: [{ op: 'box', x: 1, z: 0, w: 2, d: 3, y: 0, h: 6, col: 0 }, { op: 'box', x: 5, z: 0, w: 2, d: 3, y: 0, h: 6, col: 0 }, { op: 'box', x: 0, z: 0, w: 8, d: 3, y: 6, h: 6, col: 0 }, { op: 'box', x: -2, z: 0, w: 2, d: 3, y: 7, h: 6, col: 0 }, { op: 'box', x: 8, z: 0, w: 2, d: 3, y: 5, h: 7, col: 0 }, { op: 'box', x: 2, z: 0, w: 4, d: 3, y: 12, h: 4, col: 0 }] } ] };
const braziers = { name: 'the braziers', ops: [0, 1, 2].map(i => ({ op: 'group', name: 'brazier', x: [0, 9, 17][i], z: [0, 6, -2][i], size: [1, 1, 2], ops: [{ op: 'part', part: '3062b', col: 0, x: 0, y: 0, z: 0 }, { op: 'part', part: '85959', col: 57, x: 0, y: 1, z: 0 }] })) };
const deck = { name: 'the galley', ops: [{ op: 'group', name: 'deck', x: 0, z: 0, size: [12, 26, 12], ops: [{ op: 'slab', x: 0, z: 0, w: 12, d: 26, y: 0, plates: 1, col: 308 }, { op: 'wall', from: [0, 0], to: [0, 26], y: 0, h: 1, col: 70 }, { op: 'wall', from: [11, 0], to: [11, 26], y: 0, h: 1, col: 70 }, { op: 'roof', x: 0, z: -3, w: 12, d: 3, y: 0, col: 70, style: 'gable' }, { op: 'box', x: 1, z: 4, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 1, z: 9, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 1, z: 14, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 1, z: 19, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 9, z: 4, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 9, z: 9, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 9, z: 14, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'box', x: 9, z: 19, w: 2, d: 1, y: 0, h: 1, col: 70 }, { op: 'column', x: 6, z: 12, y: 0, h: 11, col: 70 }] }] };
const room = { name: 'the chamber', ops: [{ op: 'group', name: 'walls', x: 0, z: 0, size: [16, 12, 7], ops: [{ op: 'wall', from: [0, 0], to: [16, 0], y: 0, h: 7, col: 70 }, { op: 'wall', from: [0, 0], to: [0, 12], y: 0, h: 7, col: 70 }, { op: 'wall', from: [16, 0], to: [16, 12], y: 0, h: 7, col: 70 }, { op: 'column', x: 4, z: 1, y: 0, h: 7, col: 19 }, { op: 'column', x: 12, z: 1, y: 0, h: 7, col: 19 }, { op: 'slab', x: 0, z: 0, w: 16, d: 12, y: 7, plates: 1, col: 70 }] }] };
const bed = { name: 'the bed', ops: [{ op: 'group', name: 'bed', x: 0, z: 0, size: [6, 8, 2], ops: [{ op: 'box', x: 0, z: 0, w: 6, d: 8, y: 0, h: 1, col: 70 }, { op: 'slab', x: 0, z: 0, w: 6, d: 8, y: 1, plates: 1, col: 15 }, { op: 'column', x: 0, z: 0, y: 1, h: 3, col: 70 }, { op: 'column', x: 5, z: 0, y: 1, h: 3, col: 70 }] }, { op: 'group', name: 'candle', x: 8, z: 3, size: [1, 1, 2], ops: [{ op: 'part', part: '3062b', col: 19, x: 0, y: 0, z: 0 }, { op: 'part', part: '37775', col: 57, x: 0, y: 1, z: 0 }] }] };
/* ── the cast, a figure per place, one label per part ── */
const actors = [
  { name: 'odysseus-dunes', figure: 'odysseus-bronze', label: 'Odysseus', x: -110, z: 3, heading: 290 },
  { name: 'odysseus-beach', figure: 'odysseus-bronze', label: 'Odysseus', x: -0.8, z: 2, heading: 90 }, { name: 'commander', figure: 'commander', label: 'Eurylochus', x: 1, z: 2, heading: 270 }, { name: 'phalanx', crowd: true, kind: 'hoplite', n: 14, x: 0, z: -4.5, r: 3.5 },
  { name: 'odysseus-ridge', figure: 'odysseus-bronze', label: 'Odysseus', x: 110, z: 8, heading: 0 }, { name: 'ridge-1', figure: 'hoplite', x: 108, z: 10, heading: 0 }, { name: 'ridge-2', figure: 'hoplite', x: 112, z: 10.5, heading: 0 }, { name: 'ridge-3', figure: 'hoplite', x: 109.5, z: 12, heading: 0 }, { name: 'ridge-4', figure: 'hoplite', x: 111, z: 13, heading: 0 },
  { name: 'telemachus', figure: 'telemachus-ithaca', label: 'Telemachus', x: 209, z: -1, heading: 180 }, { name: 'penelope-crag', figure: 'penelope-ithaca', label: 'Penelope', x: 213, z: -1.5, heading: 180 },
  { name: 'galley-1', kind: 'boat', len: 10, col: 0, x: -26, z: 222, heading: 90 }, { name: 'galley-2', kind: 'boat', len: 10, col: 0, x: -32, z: 229, heading: 90 },
  { name: 'rider', figure: 'commander', label: 'the rider', x: 47.5, z: -6.5, heading: 180 },
  { name: 'odysseus-cave', figure: 'odysseus-sword', label: 'Odysseus', x: -201, z: -193.5, heading: 0 }, { name: 'cave-1', figure: 'hoplite', x: -204, z: -197, heading: 0 }, { name: 'cave-2', figure: 'hoplite', x: -198.5, z: -196.5, heading: 0 }, { name: 'cave-3', figure: 'hoplite', x: -205.5, z: -195, heading: 0 }, { name: 'cave-4', figure: 'hoplite', x: -197, z: -194.5, heading: 0 },
  { name: 'odysseus-ash', figure: 'odysseus-sword', label: 'Odysseus', x: -200, z: 200, heading: 0 },
  { name: 'odysseus-deck', figure: 'odysseus-wet', label: 'Odysseus', x: -3, z: 304.5, heading: 0 },
  { name: 'odysseus', figure: 'odysseus', x: 199.3, z: 201, heading: 90 }, { name: 'penelope', figure: 'penelope-ithaca', x: 200.7, z: 201, heading: 270 },
];
for (let i = 0; i < 10; i++) { const a = i / 10 * Math.PI * 2, r = 6; actors.push({ name: 'shade-' + (i + 1), figure: 'shade', x: +(-200 + Math.sin(a) * r).toFixed(2), z: +(200 - Math.cos(a) * r).toFixed(2), heading: Math.round((a * 180 / Math.PI + 180) % 360) }); }
for (let i = 0; i < 12; i++) actors.push({ name: 'hauler-' + (i + 1), figure: 'sailor', x: 42.5 + (i % 2) * 3, z: 4 + Math.floor(i / 2) * 1.6, heading: 0 });   // two files on the rope, facing the wreck in the surf
for (let i = 0; i < 8; i++) actors.push({ name: 'rower-' + (i + 1), figure: 'sailor', x: i < 4 ? -4.6 : -2.4, z: 294.2 + (i % 4) * 2.5, heading: 180 });
const builds = [{ name: 'graves', x: -130, z: -10, program: graves }, { name: 'galley a', x: -12, z: -16, program: galley('galley a') }, { name: 'galley b', x: 6, z: -14, program: galley('galley b') }, { name: 'citadel', x: 200, z: -12, program: citadel }, { name: 'wreck', x: 40, z: -30, program: wreck }, { name: 'cavern', x: -214, z: -206, program: cavern }, { name: 'braziers', x: -204, z: 195, program: braziers }, { name: 'galley deck', x: -6, z: 292, program: deck }, { name: 'bed', x: 197, z: 197, program: bed }, { name: 'room', x: 196, z: 195, program: room }];
const F = 'odyssey/', N = (text, file, from, sec, at) => ({ what: 'SPEAK', who: 'narrator', text, at, for: sec, file: F + file, from });
const story = { title: 'The Odyssey: a trailer in bricks', description: 'Thirteen patches of the trailer, each on its own ground: the graves in the dunes, the beachhead, the ridge, the citadel, the galleys at dusk, the tow, the cavern, the ashen shore, the tempest, the deck, the chamber, the cards.', location: 'Troy, the Aegean, Ithaca',
  entities: [{ id: 'odysseus', type: 'character', name: 'Odysseus', traits: ['bronze', 'bearded', 'commander'], location: 'everywhere' }, { id: 'penelope', type: 'character', name: 'Penelope', traits: ['dark peplos', 'braided'], location: 'Ithaca' }, { id: 'telemachus', type: 'character', name: 'Telemachus', traits: ['grey tunic'], location: 'Ithaca' }, { id: 'hoplites', type: 'crowd', name: 'the phalanx', traits: ['bronze', 'spears'], location: 'Troy' }, { id: 'polyphemus', type: 'shadow', name: 'Polyphemus', traits: ['colossal'], location: 'the cavern' }],
  goals: [{ id: 'g1', name: 'home', owner: 'odysseus' }], obstacles: [{ id: 'o1', name: 'the sea', affects: ['odysseus'] }, { id: 'o2', name: 'the Cyclops', affects: ['odysseus', 'hoplites'] }, { id: 'o3', name: 'the dead', affects: ['odysseus'] }],
  shifts: [{ id: 'muster', name: 'Aftermath and beachhead', causes: 'the war is over', results_in: 'the fleet musters' }, { id: 'ridge', name: 'Inland and the overlook', causes: 'the march inland', results_in: 'Ithaca waits' }, { id: 'launch', name: 'Launch and salvage', causes: 'the fleet sails', results_in: 'the siege engine is dragged' }, { id: 'cavern', name: 'The cavern and the shore of the dead', causes: 'a hostile coast', results_in: 'a standoff with shades' }, { id: 'tempest', name: 'Tempest, covenant, billing', causes: 'Poseidon strikes', results_in: 'a promise' }],
  relations: ['[commands] odysseus -> hoplites', '[waits for] penelope -> odysseus', '[looms over] polyphemus -> hoplites', '[promises] odysseus -> penelope'],
  timeline: [{ id: 'SQ1', description: 'Aftermath and Beachhead Assembly', scenes: [{ id: 'P002', description: 'the dune graves', entities: ['odysseus'] }, { id: 'P003', description: 'the beachhead', entities: ['odysseus', 'hoplites'] }] }, { id: 'SQ2', description: 'Inland Ridge and Domestic Counter-Overlook', scenes: [{ id: 'P004', description: 'the pine ridge', entities: ['odysseus', 'hoplites'] }, { id: 'P005', description: 'the citadel', entities: ['telemachus', 'penelope'] }] }, { id: 'SQ3', description: 'Maritime Launch and Shoreline Salvage', scenes: [{ id: 'P006', description: 'the galleys at dusk', entities: [] }, { id: 'P007', description: 'the tow', entities: ['hoplites'] }] }, { id: 'SQ4', description: 'Subterranean Ambush and Netherworld Shore', scenes: [{ id: 'P008', description: 'the cavern', entities: ['odysseus', 'polyphemus'] }, { id: 'P009', description: 'the ashen shore', entities: ['odysseus'] }] }, { id: 'SQ5', description: 'Ocean Tempest, Covenant, and Theatrical Billing', scenes: [{ id: 'P010', description: 'the tempest', entities: ['odysseus'] }, { id: 'P011', description: 'the deck', entities: ['odysseus'] }, { id: 'P012', description: 'the chamber vow', entities: ['odysseus', 'penelope'] }] }] };
const shots = [
  { title: 'THE ODYSSEY\nA TRAILER IN BRICKS', style: 'card', sec: 6, name: 'P001 the studio card', score: T + 'bronze-armor-clash.ogg', fade: 3, shift: 'muster' },
  { name: 'P002 the dune graves', on: 'odysseus-dunes', pos: [-121, 2.2, 6], tgt: [-113, 0.9, -3], lens: 50, sec: 10, shift: 'muster', set: { kind: 'dunes', centre: [-120, 0], time: 'day', weather: 'cloudy' }, acts: [{ who: 'odysseus-dunes', to: [-117, 0] }], events: [{ what: 'PHRASE', who: 'odysseus-dunes', name: 'look down', at: 5.5, enter: 0.6 }] },
  { name: 'P003 the beachhead', on: 'odysseus-beach', frame: 'medium', from: 's', lens: 45, sec: 8, shift: 'muster', set: { kind: 'shore', centre: [0, 0], time: 'day', weather: 'clear' }, events: [{ what: 'PHRASE', who: 'commander', name: 'listen', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'odysseus-beach', name: 'command', at: 1.2, enter: 0.4 }, { what: 'PERFORM', who: 'commander', verb: 'LOOK', target: 'odysseus-beach', at: 0.3, keepGaze: true }, { what: 'PERFORM', who: 'odysseus-beach', verb: 'LOOK', target: 'commander', at: 0.2, keepGaze: true }, N('Odysseus begins the account of the disasters that followed Troy.', 'OD-B09-S01.mp3', 65.44, 6.24, 0.8)] },
  { name: 'P004 the pine ridge', on: 'odysseus-ridge', frame: 'medium', from: 'front', lens: 40, sec: 9, follow: true, shift: 'ridge', set: { kind: 'forest', centre: [110, 0], time: 'day', weather: 'clear', corridor: [[110, 14], [110, -22]] }, acts: [{ who: 'odysseus-ridge', to: [110, -16] }, { who: 'ridge-1', to: [108, -14] }, { who: 'ridge-2', to: [112, -13.5] }, { who: 'ridge-3', to: [109.5, -12] }, { who: 'ridge-4', to: [111, -11] }], events: [N('Odysseus describes Ithaca’s rugged beauty and his longing to return.', 'OD-B09-S01.mp3', 57.1, 8.04, 0.5), { what: 'PHRASE', who: 'odysseus-ridge', name: 'resolve', at: 2, enter: 0.5 }] },
  { name: 'P005 the citadel', on: [206, -8], pos: [214, 9, 26], tgt: [206, 3, -8], lens: 32, sec: 3, shift: 'ridge', set: { kind: 'crag', centre: [206, -6], time: 'day', weather: 'fog' } },
  { name: 'P005 Telemachus on the parapet', on: 'telemachus', frame: 'medium', from: 's', lens: 45, sec: 2.5, shift: 'ridge', events: [{ what: 'PHRASE', who: 'telemachus', name: 'resolve', at: 0, enter: 0.3 }, { what: 'PERFORM', who: 'telemachus', verb: 'LOOK', target: [206, 40], at: 0.2, keepGaze: true }] },
  { name: 'P005 Penelope turns', on: 'penelope-crag', frame: 'close', from: 'se', lens: 45, sec: 3, shift: 'ridge', events: [{ what: 'PHRASE', who: 'penelope-crag', name: 'guarded', at: 0, enter: 0.3 }, { what: 'SET', who: 'penelope-crag', ch: 'head.yaw', v: 1.1, at: 0.7, over: 0.25 }, { what: 'SET', who: 'penelope-crag', ch: 'torso.twist', v: 0.4, at: 0.8, over: 0.3 }, { what: 'SPEAK', who: 'penelope-crag', text: 'Odysseus.', at: 1.1, for: 2.2, file: F + 'OD-B23-S04.mp3', from: 30.5 }] },
  { name: 'P006 the galleys at dusk', on: 'galley-1', pos: [-4, 1.2, 246], tgt: [4, 1.5, 224], lens: 26, sec: 8, shift: 'launch', set: { kind: 'sea', centre: [0, 220], time: 'dusk', weather: 'clear' }, acts: [{ who: 'galley-1', to: [30, 222], speed: 4 }, { who: 'galley-2', to: [24, 229], speed: 4 }], events: [N('My child, how could I forget godlike Odysseus?', 'OD-B01-S01.mp3', 83.24, 4, 1.5)] },
  { title: 'FROM THE HALFWORLD', style: 'card', sec: 2, name: 'P007 the card', shift: 'launch' },
  { name: 'P007 the tow', on: [44, 0], pos: [52, 2.6, 16], tgt: [44, 0.8, -12], lens: 40, sec: 8, shift: 'launch', set: { kind: 'shore', centre: [44, 0], time: 'day', weather: 'clear' }, events: [{ what: 'PHRASE', who: 'rider', name: 'pointing', at: 1.5, enter: 0.5 }].concat(Array.from({ length: 12 }, (_, i) => ({ what: 'PHRASE', who: 'hauler-' + (i + 1), name: 'hold', at: 0.2 + i * 0.05, enter: 0.4 }))) },
  { name: 'P008 the cavern', on: 'odysseus-cave', pos: [-200.5, 0.9, -188.5], tgt: [-204, 1.6, -199], lens: 52, sec: 10, lamp: 'warm', shift: 'cavern', score: T + 'cyclopean-pulse.ogg', fade: 2, set: { kind: 'cave', centre: [-200, -200], time: 'night', weather: 'clear' }, acts: [{ who: 'odysseus-cave', to: [-201, -198.5] }, { who: 'cave-1', to: [-204, -184], at: 5.2, run: true }, { who: 'cave-2', to: [-198, -183], at: 5.4, run: true }, { who: 'cave-3', to: [-206, -185], at: 5.6, run: true }, { who: 'cave-4', to: [-196, -184], at: 5.3, run: true }], events: [N('The Cyclops seizes two men, smashes them on the floor, and devours them raw.', 'OD-B09-S07.mp3', 73.04, 8.76, 0.6), { what: 'SHAKE', at: 5.2 }, { what: 'PHRASE', who: 'odysseus-cave', name: 'fear', at: 5.4, enter: 0.3 }] },
  { name: 'P009 the ashen shore', on: 'odysseus-ash', frame: 'wide', from: 'se', lens: 40, sec: 10, move: 'track', shift: 'cavern', score: T + 'underworld-descent.ogg', fade: 2, set: { kind: 'ash', centre: [-200, 200], time: 'day', weather: 'fog' }, events: [{ what: 'PHRASE', who: 'odysseus-ash', name: 'look down', at: 0, enter: 0.3 }, N('The dead gather in multitudes, crying around the blood.', 'OD-B11-S01.mp3', 34.22, 8.24, 0.5), { what: 'PHRASE', who: 'odysseus-ash', name: 'stop', at: 4.5, enter: 0.4 }] },
  { title: 'THIS SUMMER', style: 'card', sec: 1.5, name: 'P010 the card', shift: 'tempest', score: T + 'hammer-and-lightning.ogg', fade: 1 },
  { name: 'P010 the tempest', on: 'odysseus-deck', frame: 'wide', from: 'sw', lens: 45, sec: 7.5, shift: 'tempest', set: { kind: 'sea', centre: [0, 300], time: 'day', weather: 'storm' }, events: [{ what: 'SHAKE', at: 0.5 }, { what: 'SHAKE', at: 2.6 }, { what: 'SHAKE', at: 4.7 }, { what: 'SHAKE', at: 6.4 }, N('Poseidon sees him, gathers clouds, and strikes the sea with a four-wind storm.', 'OD-B05-S05.mp3', 18.12, 7, 0.3)] },
  { name: 'P011 the deck command', on: 'odysseus-deck', frame: 'close', from: 'front', lens: 40, sec: 7, shift: 'tempest', events: [{ what: 'PHRASE', who: 'odysseus-deck', name: 'command', at: 0.3, enter: 0.4 }, { what: 'SHAKE', at: 1 }, { what: 'SPEAK', who: 'odysseus-deck', text: 'Hear me now, Polyphemus:', at: 1.2, for: 4.5, file: F + 'OD-B09-S11.mp3', from: 9.22 }, { what: 'PHRASE', who: 'odysseus-deck', name: 'pointing', at: 3.8, enter: 0.3 }, { what: 'SHAKE', at: 4.6 }] },
  { name: 'P012 the chamber vow', on: [200, 201], pos: [200, 1.35, 204.2], tgt: [200, 1.25, 201], lens: 42, sec: 13, lamp: 'warm', shift: 'tempest', score: T + 'lament-of-penelope.ogg', fade: 2, set: { kind: 'chamber', centre: [200, 200], time: 'night', weather: 'clear' }, events: [{ what: 'PHRASE', who: 'penelope', name: 'tenderness', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'odysseus', name: 'tenderness', at: 0, enter: 0.3 }, { what: 'PHRASE', who: 'penelope', name: 'hands near face', at: 0.5, enter: 0.6 }, { what: 'PERFORM', who: 'penelope', verb: 'LOOK', target: 'odysseus', at: 0.2, keepGaze: true }, { what: 'PERFORM', who: 'odysseus', verb: 'LOOK', target: 'penelope', at: 0.2, keepGaze: true }, { what: 'SPEAK', who: 'penelope', text: 'Do not be angry with me; of all men you were always the shrewdest. I was afraid some stranger would come with a smooth story and take me with it.', at: 0.8, for: 6.2, file: F + 'OD-B23-S04.mp3', from: 36.08 }, N('Athena holds back dawn while husband and wife weep and reunite.', 'OD-B23-S04.mp3', 42.64, 5.4, 7.4)] },
  { title: 'THE ODYSSEY', style: 'card', sec: 2.5, name: 'P012 the title', shift: 'tempest' },
  { title: '07 . 17 . 26\nSHOT ENTIRELY WITH LEGO BRICKS', style: 'card', sec: 5, name: 'P013 the release card', shift: 'tempest' },
];
Film.SCENES['odyssey-trailer'] = { name: 'The Odyssey: the trailer in bricks', time: 'day', weather: 'clear', ground: 'flat', me: 'off', set: { kind: 'dunes', r: 90, centre: { x: -120, z: 0 } }, story, actors, builds, shots };
})();
