const assert=require('assert'),fs=require('fs'),path=require('path');const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'/tmp/film-chromium',headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../production/Film-Butter-Readymades.html'));await p.waitForFunction(()=>window.ShopGame&&ButterFilms.current&&!ButterFilms.busy,{timeout:120000});await p.evaluate(()=>{window.liveRender=renderer.render.bind(renderer);renderer.render=()=>{}});await p.evaluate(()=>ShopGame.start(true));await p.evaluate(()=>ShopGame.manual=true);
assert.strictEqual((await p.evaluate(()=>ShopGame.interact('carrot'))).ok,false);
const nav=await p.evaluate(()=>{const nodes=[];for(let z=-100;z<=130;z+=4)for(let x=-104;x<=160;x+=4){const y=ShopGame.surface(x,z);if(y!==null)nodes.push([x,y,z]);}return {nodes,stock:ShopGame.stock};});const nodes=new Map(nav.nodes.map(p=>[[p[0],p[2]].join(','),p]));
function route(from,goals){const start=[...nodes.keys()].sort((a,b)=>{const A=nodes.get(a),B=nodes.get(b);return Math.hypot(A[0]-from[0],A[2]-from[2])-Math.hypot(B[0]-from[0],B[2]-from[2])})[0];const queue=[start],prev=new Map([[start,null]]);for(let i=0;i<queue.length;i++){const k=queue[i];if(goals.has(k)){const out=[];for(let q=k;q!==null;q=prev.get(q))out.unshift(nodes.get(q));return out;}const [x,,z]=nodes.get(k);for(const n of [[x+4,z],[x-4,z],[x,z+4],[x,z-4]].map(q=>q.join(',')))if(nodes.has(n)&&!prev.has(n)){prev.set(n,k);queue.push(n);}}throw Error('No route');}
async function follow(points){return p.evaluate(points=>{let yaw=ShopGame.state.yaw;for(const target of points){for(let i=0;i<200;i++){const s=ShopGame.state,dx=target[0]-s.position[0],dz=target[2]-s.position[2],d=Math.hypot(dx,dz);if(d<.15)break;const desired=Math.atan2(dx,dz);let turn=((desired-yaw+Math.PI*3)%(Math.PI*2))-Math.PI;yaw+=Math.max(-.09,Math.min(.09,turn));ShopGame.look(yaw,.12,false);const n=Math.min(d,1.6);ShopGame.step(dx/d*n,dz/d*n,.05);if(i===199)throw Error('Movement blocked en route');}}return ShopGame.state;},points);}
const checkoutGoals=new Set(nav.nodes.filter(v=>Math.hypot(v[0]+22,v[2]-3)<27).map(v=>[v[0],v[2]].join(',')));await follow(route((await p.evaluate(()=>ShopGame.state)).position,checkoutGoals));assert.strictEqual((await p.evaluate(()=>ShopGame.interact('checkout'))).reason,'incomplete-list');
const evidence=[];for(const id of ['banana','bread','carrot']){const candidates=await p.evaluate(({nodes,id})=>nodes.filter(v=>ShopGame.canCollectAt(id,...v)),{nodes:nav.nodes,id});assert(candidates.length>0,'No visible reachable point for '+id);const goal=new Set(candidates.map(v=>[v[0],v[2]].join(',')));await follow(route((await p.evaluate(()=>ShopGame.state)).position,goal));await p.evaluate(id=>{const s=ShopGame.stock.find(i=>i.id===id),a=ShopGame.state.position,dx=s.position[0]-a[0],dz=s.position[2]-a[2];ShopGame.look(Math.atan2(dx,dz),Math.atan2(a[1]+48-s.position[1],Math.hypot(dx,dz)));for(let i=0;i<15;i++)ShopGame.step(0,0,.1);},id);await p.click('#shopAction');assert((await p.evaluate(()=>ShopGame.state.collected)).includes(id));assert.strictEqual((await p.evaluate(id=>ShopGame.interact(id),id)).reason,'already-collected');await p.evaluate(()=>{for(let i=0;i<8;i++)ShopGame.step(0,0,.1)});evidence.push(await p.evaluate(()=>ShopGame.state));console.log('Collected',id);}
await follow(route((await p.evaluate(()=>ShopGame.state)).position,checkoutGoals));await p.evaluate(()=>{const a=ShopGame.state.position;ShopGame.look(Math.atan2(-45-a[0],3-a[2]),.12);for(let i=0;i<15;i++)ShopGame.step(0,0,.1)});await p.click('#shopAction');const state=await p.evaluate(()=>ShopGame.state);assert(state.paid);assert.strictEqual(state.receipt.total,400);assert.strictEqual((await p.evaluate(()=>ShopGame.interact('checkout'))).ok,false);const run=await p.evaluate(()=>ShopGame.finishHold(4));fs.writeFileSync(path.join(__dirname,'completed-run.json'),JSON.stringify(run,null,2));await p.evaluate(()=>liveRender(scene,camera));await p.screenshot({path:path.join(__dirname,'receipt.png'),timeout:120000});const replay=await p.evaluate(async run=>{await ShopGame.replay(run);ShopGame.seek(run.duration);return ShopGame.state;},run);assert(replay.paid);assert.deepStrictEqual(replay.collected,state.collected);assert.deepStrictEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'test-report.json'),JSON.stringify({errors,outOfReachRejected:true,incompleteCheckoutRejected:true,duplicatesRejected:true,receipt:state.receipt,replayMatches:true,events:run.events,duration:run.duration,evidence},null,2));console.log('Complete',run.duration,'seconds');await b.close()})().catch(e=>{console.error(e);process.exit(1)});
