/* Native door panels, hinge poses, nearby hand use, and exterior continuation. */
let shopDoors=[],doorBusy=false;
function doorBuild(){shopDoors=(filmAsset().doors||[]).map(d=>{const p=S.parts.find(p=>p.part===d.part);p.mesh.updateMatrixWorld(true);return {...d,p,angle:0,closed:p.mesh.matrixWorld.clone(),box:new THREE.Box3(V(...d.bounds[0]),V(...d.bounds[1]))};});}
function doorPose(d,angle){d.angle=angle;const h=V(...d.hinge),delta=new THREE.Matrix4().makeTranslation(...h.toArray()).multiply(new THREE.Matrix4().makeRotationY(angle)).multiply(new THREE.Matrix4().makeTranslation(-h.x,-h.y,-h.z));d.delta=delta;d.p.mesh.matrixAutoUpdate=false;d.p.mesh.matrix.copy(delta).multiply(d.closed);d.p.mesh.matrixWorld.copy(d.p.mesh.matrix);delete d.p.mesh.userData.armBounds;d.p.mesh.updateMatrixWorld(true);}
const doorCacheBefore=walkCache;walkCache=function(){doorCacheBefore();if(!shopActive)return;
 const expanded=[];for(const o of walkGround){let frame=null;for(const d of shopDoors){if(o.mesh===d.p.mesh)continue;const a=o.box.getSize(V()),b=d.box.getSize(V()),c=o.box.getCenter(V()),e=d.box.getCenter(V()),axis=b.x>b.z?'x':'z',thin=axis==='x'?'z':'x';if(a.y>b.y&&a.y<b.y+18&&a[axis]>b[axis]&&a[axis]<b[axis]+18&&a[thin]<22&&Math.abs(c.x-e.x)<9&&Math.abs(c.z-e.z)<9){frame={axis};break;}}
 if(!frame){expanded.push(o);continue;}const axis=frame.axis,b=o.box;for(const edge of ['min','max']){const box=b.clone();if(edge==='min')box.max[axis]=box.min[axis]+3;else box.min[axis]=box.max[axis]-3;expanded.push({...o,box});}const top=b.clone();top.min.y=top.max.y-4.5;expanded.push({...o,box:top});const sill=b.clone();sill.max.y=sill.min.y+4.5;expanded.push({...o,box:sill});}walkGround=expanded;
 for(const d of shopDoors){if(!d.delta)continue;for(const o of walkGround)if(o.mesh===d.p.mesh)o.box.applyMatrix4(d.delta);}};
function doorDuckAt(x,z){return shopDoors.some(d=>Math.hypot(x-d.box.getCenter(V()).x,z-d.box.getCenter(V()).z)<44);}
const doorCastBefore=visualCast;visualCast=function(){doorCastBefore();if(!visualOwn)return;const torso=visualOwn.getObjectByName('torsoP');if(torso){const distance=Math.min(...shopDoors.map(d=>Math.hypot(walkRig.pos.x-d.box.getCenter(V()).x,walkRig.pos.z-d.box.getCenter(V()).z)));torso.rotation.x=1.15*Math.max(0,Math.min(1,(44-distance)/14));}visualOwn.updateMatrixWorld(true);};
async function doorUse(d){if(doorBusy)return {ok:false,reason:'Door is moving'};const side=['right','left'].find(s=>!embodied[s].held);if(!side)return armReport('right','Free one hand to open the door');const mesh=d.p.mesh,proxy={name:'door',meshes:[],box:new THREE.Box3().setFromObject(mesh)};mesh.updateMatrixWorld(true);mesh.traverse(m=>{if(m.isMesh&&m.geometry.index)proxy.meshes.push({geometry:m.geometry,matrix:m.matrixWorld.clone()});});proxy.position=proxy.box.getCenter(V());if(proxy.position.distanceTo(walkRig.pos.clone().add(V(0,50,0)))>80)return armReport(side,'Walk closer to the door');
 window.filmDoorContact=d.p;let result;try{result=armFoodReach(proxy,side,false);if(!result.ok||!(armItemDistance(proxy,armGripPoint(side))<=3||armNativeContact(side,proxy)))return armReport(side,'Face the door and move your hand closer');}finally{window.filmDoorContact=null;}
 const opening=Math.abs(d.angle)<.3,target=opening?Math.PI/2:0,from=d.angle;
 if(!opening&&d.box.clone().expandByScalar(14).containsPoint(walkRig.pos.clone().add(V(0,45,0))))return armReport(side,'Step out of the doorway before closing');
 doorBusy=true;try{for(let n=1;n<=18;n++){doorPose(d,from+(target-from)*n/18);walkCache();shopTime+=.05;shopCamera();shopRecord(true);if(!shopManual)await new Promise(r=>setTimeout(r,35));}embodied[side].status=opening?'Door open · walk through':'Door closed';document.getElementById('armStatus').textContent=embodied[side].status;shopEvent(opening?'door-open':'door-close',d.part);return {ok:true};}finally{doorBusy=false;}}
const doorTapBefore=armTap;armTap=function(x,y){if(!shopActive||shopReplay)return {ok:false};shopCamera();const ray=new THREE.Raycaster();ray.setFromCamera({x:x*2-1,y:1-y*2},camera);const hits=ray.intersectObjects(S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh),true);if(hits[0]){const d=shopDoors.find(d=>hits[0].object===d.p.mesh||hits[0].object.parent===d.p.mesh);if(d)return doorUse(d);}return doorTapBefore(x,y);};ShopHands.tap=armTap;
const doorOperatorBefore=ShopOperators.act;ShopOperators.act=async action=>{if(action.verb==='tap'){const result=await armTap(Number(action.x),Number(action.y));return {result,observation:ShopOperators.observe()};}return doorOperatorBefore(action);};
const doorStartBefore=shopStart;shopStart=async function(fresh=false){const saved=!fresh&&shopRead();doorReset();shopDoors=[];await doorStartBefore(fresh);doorBuild();if(saved?.source===filmAsset().hash)for(const d of shopDoors)doorPose(d,saved.current?.doors?.[d.part]||0);shopLayout();walkCache();shopCamera();shopRecord(true);};ShopGame.start=shopStart;
const doorStateBefore=shopState;shopState=function(){const s=doorStateBefore();s.doors=Object.fromEntries(shopDoors.map(d=>[d.part,d.angle]));return s;};
const doorReplayBefore=shopReplayAt;shopReplayAt=function(t){if(shopRun){let f=shopRun.frames[0];for(const next of shopRun.frames){if(next.t>t)break;f=next;}for(const d of shopDoors)doorPose(d,f.doors?.[d.part]||0);walkCache();}const previous=walkRig?.pos.clone(),result=doorReplayBefore(t);if(previous){visualGait(visualOwn,previous.distanceTo(walkRig.pos));if((previous.x>170)!==(walkRig.pos.x>170))shopLayout();}return result;};ShopGame.seek=shopReplayAt;
window.ShopDoors={tryTap(x,y){shopCamera();const ray=new THREE.Raycaster();ray.setFromCamera({x:x*2-1,y:1-y*2},camera);const hit=ray.intersectObjects(S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh),true)[0],d=hit&&shopDoors.find(d=>hit.object===d.p.mesh||hit.object.parent===d.p.mesh);if(!d)return false;doorUse(d);return true;},get list(){return shopDoors.map(d=>({id:d.part,center:d.box.getCenter(V()).toArray(),hinge:d.hinge,angle:d.angle}));},use:id=>doorUse(shopDoors.find(d=>d.part===id)),blockers(x,z){return walkGround.filter(o=>o.box.max.y>9&&o.box.min.y<100&&o.box.distanceToPoint(V(x,50,z))<16).map(o=>({min:o.box.min.toArray(),max:o.box.max.toArray()}));},get busy(){return doorBusy}};

const doorPeerBefore=peerReceive;peerReceive=function(data){doorPeerBefore(data);if(peerRole==='detective'&&data?.type==='state'&&data.shopper?.doors){for(const d of shopDoors)doorPose(d,data.shopper.doors[d.part]||0);walkCache();}};
const doorMoveBefore=shopMove;shopMove=function(...args){const wasOutside=walkRig&&walkRig.pos.x>170&&walkRig.pos.z>110,result=doorMoveBefore(...args),outside=walkRig&&walkRig.pos.x>170&&walkRig.pos.z>110;if(wasOutside!==outside)shopLayout();if(!wasOutside&&outside&&!shopReplay){shopEvent('exit','main-entrance');document.getElementById('shopHint').textContent='Outside · walk back through the entrance to return';}return result;};ShopGame.step=shopMove;

function doorReset(){for(const d of shopDoors){doorPose(d,0);d.p.mesh.matrixAutoUpdate=true;d.p.mesh.updateMatrix();}}
const doorLeaveBefore=shopLeave;shopLeave=async function(){doorReset();shopDoors=[];return doorLeaveBefore();};
