/* Shared native-arm controller: pixel aim, rigid shoulder motion, grip and supported release. */
const embodied={left:{held:null,status:'Open'},right:{held:null,status:'Open'},selected:'right',tracks:new Map(),lastSeen:0};
const handPanel=document.createElement('div');handPanel.id='embodiedHands';handPanel.innerHTML='<button data-arm="left" aria-label="Left hand">L</button><button data-arm="right" aria-label="Right hand">R</button><button id="armGrip">Grip / place</button><span id="armStatus">Tap food to reach and grab. Tap a surface to place.</span>';stage.append(handPanel);
function armParts(side){visualCast();const r=visualOwn?.userData.rig;return r?{pivot:r[side==='left'?'armLP':'armRP'],hand:r[side==='left'?'handL':'handR']}:null;}
function armGripPoint(side){const r=armParts(side);visualOwn.updateMatrixWorld(true);return r.hand.localToWorld(V(0,-.8229,-9.8948));}
function armClear(side){const r=armParts(side);visualOwn.updateMatrixWorld(true);const key=(window.filmDoorContact?.id||'')+r.hand.matrixWorld.elements.join(',');if(r.pivot.userData.armClear?.key===key)return r.pivot.userData.armClear.value;const start=r.pivot.getWorldPosition(V()),end=armGripPoint(side),delta=end.clone().sub(start),distance=delta.length(),direction=delta.normalize();for(const offset of [V(),V(1.5,0,0),V(-1.5,0,0),V(0,1.5,0),V(0,-1.5,0),V(0,0,1.5),V(0,0,-1.5)]){const ray=new THREE.Raycaster(start.clone().add(offset),direction,0,distance+1),candidates=S.parts.filter(p=>p.mesh.visible&&p!==window.filmDoorContact&&ray.ray.intersectBox(p.mesh.userData.armBounds||(p.mesh.userData.armBounds=new THREE.Box3().setFromObject(p.mesh)),V())).map(p=>p.mesh);if(ray.intersectObjects(candidates,true).length){r.pivot.userData.armClear={key,value:false};return false;}}r.pivot.userData.armClear={key,value:true};return true;}
function armReport(side,text){embodied[side].status=text;document.getElementById('armStatus').textContent=side+' · '+text;return {ok:false,reason:text};}
// Surface crossing test. Coplanar contact is allowed; this is not solid containment.
function armTrianglesCross(a,b){for(const pair of [[a,b],[b,a]]){const t=pair[0],other=pair[1],points=[t.a,t.b,t.c];for(let n=0;n<3;n++){const start=points[n],delta=points[(n+1)%3].clone().sub(start),length=delta.length();if(length<1e-6)continue;const hit=new THREE.Ray(start,delta.divideScalar(length)).intersectTriangle(other.a,other.b,other.c,false,V());if(hit){const distance=hit.distanceTo(start);if(distance>.02&&distance<length-.02)return true;}}}return false;}
function armTriangleInTree(node,triangle,box){if(!node.box.intersectsBox(box))return false;if(node.items)return node.items.some(t=>t.box.intersectsBox(box)&&armTrianglesCross(triangle,t.triangle));return armTriangleInTree(node.left,triangle,box)||armTriangleInTree(node.right,triangle,box);}
function armHeldClear(side){const h=embodied[side].held;if(!h)return true;armUpdateHeld(side);const key=armParts(side).hand.matrixWorld.elements.join(',');if(h.clearCache?.key===key)return h.clearCache.value;for(const p of S.parts){if(!p.mesh.visible)continue;let blocked=false;p.mesh.traverse(m=>{if(blocked||!m.isMesh||!m.visible)return;m.updateWorldMatrix(true,false);const inverse=m.matrixWorld.clone().invert(),tree=contactMeshData(m.geometry),localBox=h.item.box.clone().applyMatrix4(inverse);if(!tree.box.intersectsBox(localBox))return;for(const held of h.item.meshes){const g=held.geometry,matrix=inverse.clone().multiply(held.matrix);for(let n=0;n<g.index.count;n+=3){const points=[0,1,2].map(j=>new THREE.Vector3().fromBufferAttribute(g.attributes.position,g.index.getX(n+j)).applyMatrix4(matrix));if(armTriangleInTree(tree,new THREE.Triangle(...points),new THREE.Box3().setFromPoints(points))){blocked=true;return;}}}});if(blocked){h.clearCache={key,value:false};armHeldClear.lastCollision={part:p.part,name:catalog.get(p.part)?.name};return false;}}h.clearCache={key,value:true};armHeldClear.lastCollision=null;return true;}
function armMoveTarget(side,target){const r=armParts(side);if(!r)return armReport(side,'No character arm');visualOwn.updateMatrixWorld(true);const start=r.pivot.getWorldPosition(V()),length=start.distanceTo(armGripPoint(side)),old=r.pivot.rotation.clone();let best=armGripPoint(side).distanceToSquared(target);const limits={x:[-2.8,1.2],y:[-1.1,1.1],z:[-.65,.65]};for(const step of [.6,.3,.15,.075,.035])for(let pass=0;pass<2;pass++)for(const axis of ['x','y','z']){const base=r.pivot.rotation[axis];let angle=base;for(const sign of [-1,1]){r.pivot.rotation[axis]=Math.max(limits[axis][0],Math.min(limits[axis][1],base+sign*step));visualOwn.updateMatrixWorld(true);const error=armGripPoint(side).distanceToSquared(target);if(error<best){best=error;angle=r.pivot.rotation[axis];}}r.pivot.rotation[axis]=angle;}const proposed=r.pivot.rotation.clone();let accepted=old.clone();const samples=Math.max(1,Math.ceil(Math.max(Math.abs(proposed.x-old.x),Math.abs(proposed.y-old.y),Math.abs(proposed.z-old.z))/.04));for(let n=1;n<=samples;n++){r.pivot.rotation.set(old.x+(proposed.x-old.x)*n/samples,old.y+(proposed.y-old.y)*n/samples,old.z+(proposed.z-old.z)*n/samples);if(!armClear(side)||!armHeldClear(side)){r.pivot.rotation.copy(accepted);armUpdateHeld(side);visualOwn.updateMatrixWorld(true);if(n>1&&embodied[side].held){embodied[side].status='Surface reached · open to place';shopRecord(true);return {ok:true,limited:true};}return armReport(side,'Reach blocked by shop geometry');}accepted=r.pivot.rotation.clone();}armUpdateHeld(side);embodied[side].status=best>16?'Arm aimed · align your body to touch':'Reach accepted';shopRecord(true);return {ok:true};}
function armAim(side,x,y){if(!['left','right'].includes(side)||![x,y].every(Number.isFinite))return {ok:false,reason:'Invalid hand aim'};shopCamera();const ray=new THREE.Raycaster();ray.setFromCamera({x:Math.max(0,Math.min(1,x))*2-1,y:1-Math.max(0,Math.min(1,y))*2},camera);const stock=shopStock.filter(i=>!shopCollected.has(i.id)&&!Object.values(embodied).some(h=>h?.held?.item===i)).flatMap(i=>i.meshes);const hits=ray.intersectObjects([...stock,...S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh)],true);if(!hits.length)return armReport(side,'Nothing under the pointer');const food=shopStock.find(i=>i.meshes.includes(hits[0].object));if(food&&!embodied[side].held){armSelectedItem=food;return armFoodReach(food,side,false);}return armMoveTarget(side,hits[0].point);}
function armItemDistance(item,p){const key=item.meshes.map(m=>m.matrix.elements.join(',')).join('|');if(item.armTriangles?.key!==key){const triangles=[];for(const mesh of item.meshes){const g=mesh.geometry;for(let n=0;n<g.index.count;n+=3)triangles.push(new THREE.Triangle(...[0,1,2].map(j=>new THREE.Vector3().fromBufferAttribute(g.attributes.position,g.index.getX(n+j)).applyMatrix4(mesh.matrix))));}item.armTriangles={key,triangles};}let distance=Infinity;const closest=V();for(const t of item.armTriangles.triangles)distance=Math.min(distance,t.closestPointToPoint(p,closest).distanceToSquared(p));return Math.sqrt(distance);}
// Contact may occur anywhere on the native C-hand, not only its hollow center.
function armNativeContact(side,item){const r=armParts(side);visualOwn.updateMatrixWorld(true);const group=r.pivot.children.filter(o=>o.children.some(c=>c.isMesh)).at(-1);if(!group)return false;let contact=false;group.traverse(m=>{if(contact||!m.isMesh)return;const a=m.geometry.attributes.position;for(let n=0;n<a.count;n++){const point=new THREE.Vector3().fromBufferAttribute(a,n).applyMatrix4(m.matrixWorld);if(armItemDistance(item,point)<=1.5){contact=true;break;}}});return contact;}
function armUpdateHeld(side){const h=embodied[side].held;if(!h)return;const r=armParts(side);visualOwn.updateMatrixWorld(true);const delta=r.hand.matrixWorld.clone().multiply(h.inverse);for(let n=0;n<h.item.meshes.length;n++){const m=h.item.meshes[n];m.matrix.copy(delta).multiply(h.matrices[n]);m.matrixWorld.copy(m.matrix);}h.item.position.copy(h.position).applyMatrix4(delta);h.item.box.copy(h.box).applyMatrix4(delta);}
function armClose(side){if(peerRole==='detective')return armReport(side,'Observer hands cannot take shopper stock');if(embodied[side].held)return armOpen(side);if(!armClear(side))return armReport(side,'Hand obstructed');const p=armGripPoint(side),candidates=shopStock.filter(i=>!shopCollected.has(i.id)&&!['left','right'].some(s=>embodied[s].held?.item===i)).map(item=>({item,d:armItemDistance(item,p)})).sort((a,b)=>a.d-b.d);if(!candidates[0]||(candidates[0].d>3&&!(candidates[0].d<=12&&armNativeContact(side,candidates[0].item))))return armReport(side,'Grip is not touching a vegetable');const item=candidates[0].item,r=armParts(side);embodied[side].held={item,inverse:r.hand.matrixWorld.clone().invert(),matrices:item.meshes.map(m=>m.matrix.clone()),position:item.position.clone(),box:item.box.clone()};embodied[side].status='Holding';document.getElementById('armStatus').textContent=side+' · Holding';shopEvent('grasp',item.id);shopBeep(620);return {ok:true};}
function armOpen(side){const h=embodied[side].held;if(!h)return {ok:true};armUpdateHeld(side);const item=h.item,box=item.box;const origin=item.position.clone();origin.y=box.min.y+.1;const hits=new THREE.Raycaster(origin,V(0,-1,0),0,24).intersectObjects(S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh),true);if(!hits.length)return armReport(side,'Lower onto a surface before opening');const dy=hits[0].point.y-box.min.y+.08,landed=box.clone().translate(V(0,dy,0));for(const m of item.meshes){m.matrix.elements[13]+=dy;m.matrixWorld.copy(m.matrix);}item.position.y+=dy;item.box.copy(landed);embodied[side].held=null;const receiver=S.parts.find(p=>p.mesh===hits[0].object||p.mesh.children.includes(hits[0].object));const atRegister=(receiver&&/desk/i.test(catalog.get(receiver.part)?.name||''))||(Math.hypot(item.position.x-shopCheckout.x,item.position.z-shopCheckout.z)<34&&item.box.min.y>30);if(atRegister){shopCollected.add(item.id);shopEvent('deposit',item.id);embodied[side].status='Placed in checkout basket';}else{shopEvent('release',item.id);embodied[side].status='Placed on surface';}document.getElementById('armStatus').textContent=side+' · '+embodied[side].status;shopPaint();return {ok:true};}
const armPaintBefore=shopPaint;shopPaint=function(){armPaintBefore();if(!shopActive)return;document.getElementById('shopAction').textContent=shopPaid?'Shop again':shopCollected.size===3?'Pay at register':'Use hands · aim, close, carry, place';document.getElementById('shopAction').disabled=shopCollected.size!==3;document.getElementById('shopAction').hidden=shopCollected.size!==3||shopReplay;if(!shopPaid&&peerRole!=='detective')document.getElementById('shopHint').textContent='Tap food to grab · carry to register · tap counter to place';};
const armInteractBefore=shopInteract;shopInteract=function(id){if(id==='checkout'||(!id&&shopCollected.size===3))return armInteractBefore('checkout');return {ok:false,reason:'Use the character hands to grasp and place produce'};};ShopGame.interact=shopInteract;
const armGaitBefore=visualGait;visualGait=function(figure,distance){if(figure===visualOwn){const saved=figure.userData.joints;figure.userData.joints=saved.map((j,i)=>i<2?null:j);armGaitBefore(figure,distance);figure.userData.joints=saved;}else armGaitBefore(figure,distance);};
const armMoveBefore=shopMove;shopMove=function(...args){const before=walkRig?.pos.clone(),count=shopFrames.length,result=armMoveBefore(...args);if(before&&['left','right'].some(s=>embodied[s].held&&(!armClear(s)||!armHeldClear(s)))){walkRig.pos.copy(before);shopFrames.length=count;shopCamera();shopRecord(true);return false;}for(const side of ['left','right'])armUpdateHeld(side);return result;};ShopGame.step=shopMove;
const armStateBefore=shopState;shopState=function(){const s=armStateBefore();if(shopActive&&visualOwn){s.arms={};for(const side of ['left','right']){const r=armParts(side);s.arms[side]={rotation:r.pivot.rotation.toArray(),holding:embodied[side].held?.item.id||null};}s.stockPoses=shopStock.map(i=>({id:i.id,matrices:i.meshes.map(m=>m.matrix.toArray())}));}return s;};
const armCameraBefore=shopCamera;shopCamera=function(){armCameraBefore();if(shopActive)for(const side of ['left','right'])armUpdateHeld(side);};
const armLeaveBefore=shopLeave;shopLeave=async function(){embodied.left.held=embodied.right.held=null;embodied.left.status=embodied.right.status='Open';armSelectedItem=null;armLastBody=null;embodied.tracks.clear();return armLeaveBefore();};
handPanel.querySelectorAll('[data-arm]').forEach(b=>b.onclick=()=>{embodied.selected=b.dataset.arm;document.getElementById('armStatus').textContent='Aim '+embodied.selected+' hand';});document.getElementById('armGrip').onclick=()=>{const s=embodied.selected;const r=armSelectedItem&&!embodied[s].held?armFoodReach(armSelectedItem,s):armClose(s);if(r.ok)document.getElementById('armStatus').textContent=s+' · '+embodied[s].status;};
// Pixel selection uses the visible food, then searches contact on its native surface.
let armSelectedItem=null;
function armFoodReach(item,side,close=true){
 if((armItemDistance(item,armGripPoint(side))<=3||armNativeContact(side,item))&&armClear(side)){const r=close?armClose(side):{ok:true};if(r.ok){if(close)armSelectedItem=null;return r;}}
 const r=armParts(side),old=r.pivot.rotation.clone(),choices=[];
 let best=armItemDistance(item,armGripPoint(side));
 for(const step of [.4,.2,.1,.05,.025])for(let pass=0;pass<2;pass++)for(const axis of ['x','y','z']){
  const base=r.pivot.rotation[axis];let angle=base;
  for(const sign of [-1,1]){r.pivot.rotation[axis]=Math.max(axis==='x'?-2.8:axis==='y'?-1.1:-.65,Math.min(axis==='x'?1.2:axis==='y'?1.1:.65,base+sign*step));visualOwn.updateMatrixWorld(true);const d=armItemDistance(item,armGripPoint(side));if(d<best){best=d;angle=r.pivot.rotation[axis];}}
  r.pivot.rotation[axis]=angle;visualOwn.updateMatrixWorld(true);
 }
 const target=armGripPoint(side).clone();choices.push({d:best});r.pivot.rotation.copy(old);visualOwn.updateMatrixWorld(true);
 const reached=armMoveTarget(side,target);
 if(best<=12&&reached.ok){const result=close?armClose(side):{ok:true};if(result.ok){if(close)armSelectedItem=null;return result;}}

 return armReport(side,choices[0].d>3?'Move closer or turn toward '+item.name+' · hand gap '+Math.ceil(choices[0].d)+'':'Reach blocked · step back from the display');
}
function armTap(x,y){
 if(!shopActive||shopReplay||shopPaid||peerRole==='detective')return {ok:false,reason:'Not shopping'};
 shopCamera();const ray=new THREE.Raycaster();ray.setFromCamera({x:x*2-1,y:1-y*2},camera);
 const available=shopStock.filter(i=>!shopCollected.has(i.id)&&!['left','right'].some(s=>embodied[s].held?.item===i));
 const hits=ray.intersectObjects([...available.flatMap(i=>i.meshes),...S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh)],true),hit=hits[0];
 if(!hit)return armReport(embodied.selected,'Tap the food itself');
 const side=embodied.selected;
 if(embodied[side].held){const aimed=armMoveTarget(side,hit.point);return aimed.ok?armOpen(side):aimed;}
 const item=available.find(i=>i.meshes.includes(hit.object));
 if(!item)return armAim(side,x,y);
 armSelectedItem=item;let result=armFoodReach(item,side);
 if(!result.ok){const other=side==='left'?'right':'left';if(!embodied[other].held){const alternate=armFoodReach(item,other);if(alternate.ok){embodied.selected=other;result=alternate;}}}
 return result;
}
stage.addEventListener('pointerdown',e=>{if(!shopActive||shopReplay||e.target.closest('button,input,summary,details,.filmStick'))return;const rect=renderer.domElement.getBoundingClientRect();if(e.clientY<rect.top||e.clientY>rect.bottom)return;armTap((e.clientX-rect.left)/rect.width,(e.clientY-rect.top)/rect.height);},true);
const armProcessBefore=processHands;processHands=function(marks,now){if(!shopActive)return armProcessBefore(marks,now);const tracks=trackHands(marks,now);embodied.lastSeen=now;for(const t of tracks){if(!embodied.tracks.has(t.id)){const used=[...embodied.tracks.values()];embodied.tracks.set(t.id,used.includes('right')?'left':'right');}const side=embodied.tracks.get(t.id);armAim(side,t.point.x,t.point.y);if(t.justClosed&&!window.ShopDoors?.tryTap(t.point.x,t.point.y))armClose(side);if(t.justOpened)armOpen(side);}for(const id of embodied.tracks.keys())if(!tracks.some(t=>t.id===id)){embodied.tracks.delete(id);document.getElementById('armStatus').textContent='Tracking lost · held poses stay fixed';}};
const armOperatorBefore=ShopOperators.act;ShopOperators.act=async function(action){visualEyes=true;shopCamera();if(['tap','aim','grip','release'].includes(action.verb)){const side=action.hand==='left'?'left':'right',result=action.verb==='tap'?armTap(Number(action.x),Number(action.y)):action.verb==='aim'?armAim(side,Number(action.x),Number(action.y)):action.verb==='grip'?armClose(side):armOpen(side);visualActions.push({role:peerRole,time:shopTime,action,result});return {result,observation:ShopOperators.observe()};}if(action.verb==='interact')return {result:{ok:false,reason:'Aim and grip with a character hand'},observation:ShopOperators.observe()};return armOperatorBefore(action);};
const armObserveBefore=ShopOperators.observe;ShopOperators.observe=function(){const o=armObserveBefore();o.actions=['tap','move','turn','aim','grip','release','checkout','note','wait'];o.hands={left:embodied.left.status,right:embodied.right.status};return o;};
setInterval(()=>{handPanel.hidden=!shopActive||shopReplay;},200);
window.ShopHands={tap:armTap,aim:armAim,grip:armClose,release:armOpen,get state(){return {left:embodied.left.status,right:embodied.right.status}},measure(side='right'){const r=armParts(side);return {shoulder:r.pivot.getWorldPosition(V()).toArray(),grip:armGripPoint(side).toArray(),clear:armClear(side),rotation:r.pivot.rotation.toArray(),stock:shopStock.map(i=>({id:i.id,distance:armItemDistance(i,armGripPoint(side)),min:i.box.min.toArray(),max:i.box.max.toArray()}))};}};
const armPeerReceiveBefore=peerReceive;peerReceive=function(data){armPeerReceiveBefore(data);if(peerRole!=='detective'||data?.type!=='state')return;const state=data.shopper;if(state?.arms&&peerAvatar?.userData.rig){for(const side of ['left','right']){const r=peerAvatar.userData.rig[side==='left'?'armLP':'armRP'],a=state.arms[side]?.rotation;if(r&&a?.length===4)r.rotation.fromArray(a);}peerAvatar.updateMatrixWorld(true);}for(const pose of state?.stockPoses||[]){const item=shopStock.find(i=>i.id===pose.id);if(!item)continue;pose.matrices.forEach((a,n)=>{if(a.length===16&&a.every(Number.isFinite)&&item.meshes[n]){item.meshes[n].matrix.fromArray(a);item.meshes[n].matrixWorld.copy(item.meshes[n].matrix);}});}};
const armReplayBefore=shopReplayAt;shopReplayAt=function(t){armReplayBefore(t);if(!shopRun)return;let frame=shopRun.frames[0];for(const f of shopRun.frames){if(f.t>t)break;frame=f;}if(frame.arms)for(const side of ['left','right']){const a=frame.arms[side]?.rotation;if(a)armParts(side).pivot.rotation.fromArray(a);}for(const pose of frame.stockPoses||[]){const item=shopStock.find(i=>i.id===pose.id);if(item)pose.matrices.forEach((m,n)=>{item.meshes[n].matrix.fromArray(m);item.meshes[n].matrixWorld.copy(item.meshes[n].matrix);});}visualOwn?.updateMatrixWorld(true);};ShopGame.seek=shopReplayAt;
let armLastBody=null;
const armGuardCameraBefore=shopCamera;shopCamera=function(){armGuardCameraBefore();if(!shopActive||shopReplay||!walkRig)return;const changed=!armLastBody||walkRig.pos.distanceToSquared(armLastBody.position)>.0001||Math.abs(walkYaw-armLastBody.yaw)>.0001;if(changed&&armLastBody&&['left','right'].some(s=>embodied[s].held&&(!armClear(s)||!armHeldClear(s)))){walkRig.pos.copy(armLastBody.position);walkYaw=armLastBody.yaw;armGuardCameraBefore();document.getElementById('armStatus').textContent='Carried vegetable blocked · reposition the arm';}armLastBody={position:walkRig.pos.clone(),yaw:walkYaw};};

ShopHands.sweep=function(side='right'){const r=armParts(side),old=r.pivot.rotation.clone(),samples=[];for(let a=-2.8;a<=1.2;a+=.1){r.pivot.rotation.x=a;visualOwn.updateMatrixWorld(true);samples.push({angle:a,grip:armGripPoint(side).toArray(),distances:shopStock.map(i=>({id:i.id,d:armItemDistance(i,armGripPoint(side))}))});}r.pivot.rotation.copy(old);visualOwn.updateMatrixWorld(true);return samples;};

window.addEventListener('keydown',e=>{if(!shopActive||shopReplay||e.target.closest('input,textarea'))return;if(e.code==='KeyG'){e.preventDefault();const side=embodied.selected;if(armSelectedItem&&!embodied[side].held)armFoodReach(armSelectedItem,side);else armClose(side);}if(e.code==='Digit1'||e.code==='Digit2'){embodied.selected=e.code==='Digit1'?'left':'right';document.getElementById('armStatus').textContent=embodied.selected+' hand selected';}});

function armRefreshBounds(item){const box=new THREE.Box3();for(const mesh of item.meshes){const g=mesh.geometry;for(let n=0;n<g.index.count;n++)box.expandByPoint(new THREE.Vector3().fromBufferAttribute(g.attributes.position,g.index.getX(n)).applyMatrix4(mesh.matrix));}item.box.copy(box);item.position.copy(box.getCenter(V()));}
const armStartBefore=shopStart;shopStart=async function(fresh=false){const saved=!fresh?shopRead():null;await armStartBefore(fresh);if(saved?.source!==filmAsset().hash||!saved?.current?.arms)return;walkRig.pos.fromArray(saved.current.position);walkYaw=saved.current.yaw;walkPitch=saved.current.pitch;visualCast();for(const pose of saved.current.stockPoses||[]){const item=shopStock.find(i=>i.id===pose.id);if(!item)continue;pose.matrices.forEach((m,n)=>{item.meshes[n].matrix.fromArray(m);item.meshes[n].matrixWorld.copy(item.meshes[n].matrix);});armRefreshBounds(item);}for(const side of ['left','right']){const a=saved.current.arms[side],r=armParts(side);if(a?.holding&&a?.rotation)r.pivot.rotation.fromArray(a.rotation);visualOwn.updateMatrixWorld(true);const item=shopStock.find(i=>i.id===a?.holding);if(item){embodied[side].held={item,inverse:r.hand.matrixWorld.clone().invert(),matrices:item.meshes.map(m=>m.matrix.clone()),position:item.position.clone(),box:item.box.clone()};embodied[side].status='Holding';}}shopCamera();shopPaint();};ShopGame.start=shopStart;

ShopHands.contact=()=>({clear:armHeldClear("right"),hit:armHeldClear.lastCollision});

const armReplayStartBefore=shopStartReplay;shopStartReplay=async function(run){embodied.left.held=embodied.right.held=null;visualEyes=false;const result=await armReplayStartBefore(run);shopCamera();return result;};ShopGame.replay=shopStartReplay;
