/* Structured public actions; no provider keys, hidden reasoning, or direct inventory writes. */
let operatorLog=[],operatorBusy=false,operatorNodes=null;
function operatorObserve(){const o=ShopPeers.observe();return {...o,availableActions:peerRole==='detective'?['follow','look','note','undo','wait']:['go','collect','checkout','look','wait'],register:[-22,49,3],lastActions:operatorLog.slice(-6)};}
function operatorGrid(){if(operatorNodes)return operatorNodes;operatorNodes=new Map();for(let z=-100;z<=130;z+=4)for(let x=-104;x<=160;x+=4){const y=walkSurface(x,z,8.64);if(y!==null)operatorNodes.set(x+','+z,[x,y,z]);}return operatorNodes;}
function operatorRoute(target){const nodes=operatorGrid(),from=walkRig.pos.toArray(),other=peerRemote?.position,allowed=([x,y,z])=>!other||Math.hypot(x-other[0],z-other[2])>=28;let goals;if(target==='follow'){if(!other)throw Error('Shopper is not connected');goals=new Set([...nodes].filter(([k,v])=>allowed(v)&&Math.hypot(v[0]-other[0],v[2]-other[2])<60&&peerPositionVisible(v,other)).map(([k])=>k));}else if(target==='checkout')goals=new Set([...nodes].filter(([k,v])=>Math.hypot(v[0]+22,v[2]-3)<27&&allowed(v)).map(([k])=>k));else{const item=shopStock.find(i=>i.id===target);if(!item)throw Error('Unknown destination');goals=new Set([...nodes].filter(([k,v])=>allowed(v)&&Math.hypot(v[0]-item.position.x,v[2]-item.position.z)<=shopReach&&shopCanSee(item,V(...v))).map(([k])=>k));}const start=[...nodes].sort((a,b)=>Math.hypot(a[1][0]-from[0],a[1][2]-from[2])-Math.hypot(b[1][0]-from[0],b[1][2]-from[2]))[0][0],queue=[start],prev=new Map([[start,null]]);for(let i=0;i<queue.length;i++){const k=queue[i];if(goals.has(k)){const route=[];for(let q=k;q!==null;q=prev.get(q))route.unshift(nodes.get(q));return route;}const[x,,z]=nodes.get(k);for(const key of [[x+4,z],[x-4,z],[x,z+4],[x,z-4]].map(v=>v.join(',')))if(nodes.has(key)&&allowed(nodes.get(key))&&!prev.has(key)){prev.set(key,k);queue.push(key);}}throw Error('No collision-free route from this position');}
async function operatorAction(action){if(operatorBusy)return {ok:false,reason:'operator-busy'};operatorBusy=true;const entry={role:peerRole,time:shopTime,action:JSON.parse(JSON.stringify(action))};operatorLog.push(entry);try{const reason=String(action.reason||'').slice(0,240);entry.action.reason=reason;let result;if(action.verb==='go'||action.verb==='follow'){if(peerRole==='detective'&&action.verb!=='follow')throw Error('Detective follows observed shopper, not the private list');const route=operatorRoute(action.verb==='follow'?'follow':action.target);for(const point of route){for(let n=0;n<150;n++){const dx=point[0]-walkRig.pos.x,dz=point[2]-walkRig.pos.z,d=Math.hypot(dx,dz);if(d<.2)break;const turn=((Math.atan2(dx,dz)-walkYaw+Math.PI*3)%(Math.PI*2))-Math.PI;walkYaw+=Math.max(-.12,Math.min(.12,turn));walkPitch=.1;const amount=Math.min(1.6,d);const moved=shopMove(dx/d*amount,dz/d*amount,.05);await new Promise(r=>setTimeout(r,50));if(!moved||n===149)throw Error('Movement blocked; observe and revise destination');}}if(action.verb==='go'){const target=shopStock.find(i=>i.id===action.target)?.position||shopCheckout;const d=target.clone().sub(walkRig.pos);walkYaw=Math.atan2(d.x,d.z);walkPitch=Math.atan2(48-d.y,Math.hypot(d.x,d.z));shopCamera();shopRecord(true);}result={ok:true,position:walkRig.pos.toArray()};}else if(action.verb==='collect')result=shopInteract(action.target);else if(action.verb==='checkout')result=shopInteract('checkout');else if(action.verb==='note')result=peerNote(action.target,reason);else if(action.verb==='undo'){peerSend({type:'undo'});result={ok:true};}else if(action.verb==='look'){if(!Number.isFinite(action.yaw))throw Error('Finite yaw required');ShopGame.look(action.yaw,Math.max(-1.2,Math.min(1.2,Number(action.pitch)||0)));result={ok:true};}else if(action.verb==='wait'){const duration=Math.max(.1,Math.min(5,Number(action.seconds)||1));for(let t=0;t<duration;t+=.1){shopMove(0,0,.1);await new Promise(r=>setTimeout(r,100));}result={ok:true};}else throw Error('Unknown action');entry.result=result;return {...result,observation:operatorObserve()};}catch(e){entry.result={ok:false,reason:e.message};return {...entry.result,observation:operatorObserve()};}finally{operatorBusy=false;}}
window.ShopOperators={get busy(){return operatorBusy},observe:operatorObserve,act:operatorAction,get log(){return operatorLog},export(){return {actions:operatorLog,run:ShopGame.recording,detective:ShopPeers.journal}}};
const operatorReplayPanel=document.createElement('div');operatorReplayPanel.id='operatorReplayPanel';operatorReplayPanel.hidden=true;stage.append(operatorReplayPanel);
function operatorReplayText(){if(!shopReplay||!shopRun?.notebook)return null;const notes=shopRun.notebook.filter(n=>n.time<=shopReplayTime),actions=(shopRun.operatorActions||[]).filter(a=>a.time<=shopReplayTime),action=actions.at(-1);return {notes:notes.map(n=>n.item).join(' · ')||'No entries yet',action:action?`${action.action.verb} ${action.action.target||''}`:'Observe',reason:action?.action.reason||''};}
setInterval(()=>{const text=operatorReplayText();operatorReplayPanel.hidden=!text;if(text)operatorReplayPanel.textContent='ARCHIVED ASSISTED TEST · event-fed notes: '+text.notes+'\nSHOPPER: '+text.action+'\n'+text.reason;},200);
const operatorDrawBefore=shopDrawHUD;shopDrawHUD=function(ctx,w,h){operatorDrawBefore(ctx,w,h);const text=operatorReplayText();if(!text)return;ctx.save();ctx.scale(w/1280,w/1280);ctx.fillStyle='#10231fea';ctx.fillRect(24,99,690,72);ctx.fillStyle='#f4e8cc';ctx.font='18px sans-serif';ctx.fillText('MAGGIE’S NOTEBOOK: '+text.notes,42,124);ctx.fillStyle='#c4f46a';ctx.fillText('ASSISTED SHOPPER: '+text.action,42,151);ctx.restore();};
