/* One authoritative shopper; one independently situated detective. */
let peerRole='solo',peerNode=null,peerConnection=null,peerToken='',peerSeq=0,peerLastSeq=-1,peerBudget=0,peerBudgetTime=0,peerRemote=null,peerAvatar=null,peerNotes=[],peerWitness=[],peerJournal=[],peerSeenEvents=0,peerApplying=false;
const peerPanel=document.createElement('details');peerPanel.id='shopPeers';peerPanel.innerHTML='<summary>Two players · Maggie detective</summary><button id="peerHost">Invite Maggie</button><button id="peerLeave">Disconnect</button><p id="peerStatus">Shopper and detective keep separate records.</p><div id="peerQR"></div><input id="peerLink" readonly aria-label="Invitation link"><div id="peerNotebook" hidden><b>Maggie’s notebook</b><p id="peerSight">No pickup witnessed yet.</p><div id="peerEntries"></div><button data-note="banana">Record bananas</button><button data-note="bread">Record bread</button><button data-note="carrot">Record carrots</button><button id="peerUndo">Undo note</button></div>';stage.append(peerPanel);
const pe=id=>document.getElementById(id),peerSay=s=>pe('peerStatus').textContent=s;
function peerSend(data){if(peerConnection?.open)peerConnection.send(data);}
function peerSnapshot(){return {type:'state',shopper:shopState(),detective:peerRemote,notes:peerNotes,witness:[]};}
function peerPositionVisible(from,to){const eye=V(...from).add(V(0,32,0)),target=V(...to).add(V(0,32,0)),delta=target.sub(eye),distance=delta.length();return distance<125&&!new THREE.Raycaster(eye,delta.normalize(),0,Math.max(0,distance-2)).intersectObjects(S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh),true).length;}
function peerMakeAvatar(kind){if(peerAvatar){scene.remove(peerAvatar);peerAvatar=null;}const entry=ButterCast.cast.find(a=>a.kind===kind);if(!entry)return;const original=entry.rig.headP.position.y;if(kind==='movieator-maggie')entry.rig.headP.position.y+=18;const model=entry.rig.figure.clone(true);entry.rig.headP.position.y=original;model.visible=true;model.position.set(0,0,0);model.rotation.set(0,0,0);model.scale.setScalar(1);model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(V()),scale=Math.min((kind==='movieator-maggie'?30:44)/size.y,22/Math.max(size.x,size.z));model.scale.setScalar(scale);model.position.set(-(box.min.x+box.max.x)*scale/2,-box.min.y*scale,-(box.min.z+box.max.z)*scale/2);peerAvatar=new THREE.Group();peerAvatar.add(model);scene.add(peerAvatar);}
function peerShowAvatar(position,yaw){if(!peerAvatar||!position)return;peerAvatar.position.fromArray(position);peerAvatar.rotation.y=yaw||0;peerAvatar.visible=shopActive;}
function peerMovePosition(position,dx,dz,other){const p=V(...position),steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/2));const valid=(x,z)=>{if(other&&Math.hypot(x-other[0],z-other[2])<26)return null;return walkSurface(x,z,p.y);};for(let n=0;n<steps;n++){const x=p.x+dx/steps,z=p.z+dz/steps;let y=valid(x,z);if(y!==null)p.set(x,y,z);else{y=valid(x,p.z);if(y!==null)p.set(x,y,p.z);else{y=valid(p.x,z);if(y!==null)p.set(p.x,y,z);}}}return p.toArray();}
function peerPaint(){pe('peerNotebook').hidden=peerRole!=='detective';if(peerRole==='detective'){pe('shopList').textContent='MAGGIE · DETECTIVE';pe('shopAction').hidden=true;pe('shopHint').textContent='Follow the shopper. Record what you observe.';pe('shopReceipt').hidden=true;pe('peerEntries').textContent=peerNotes.length?peerNotes.map(n=>n.item).join(' · '):'Nothing recorded';pe('peerSight').textContent=peerWitness.length?peerWitness.map(w=>w.item+' at '+w.time.toFixed(1)+'s').join(' · '):'No pickup witnessed yet.';if(shopPaid){pe('shopHint').textContent='Checkout complete · compare your notebook with the receipt';pe('peerSight').textContent+=' | Receipt: '+shopReceipt.lines.map(l=>l.name).join(', ');}}}
const peerPaintBefore=shopPaint;shopPaint=function(){peerPaintBefore();peerPaint();};
const peerMoveBefore=shopMove;shopMove=function(dx,dz,dt=.05){if(peerRole==='detective'&&!shopReplay){const old=walkRig.pos.toArray(),next=peerMovePosition(old,dx,dz,peerRemote?.position);walkRig.pos.fromArray(next);shopTime+=dt;shopCamera();peerShowAvatar(peerRemote?.position,peerRemote?.yaw);if(Math.hypot(dx,dz)>0||peerSeq%5===0)peerSend({type:'move',seq:++peerSeq,dx,dz,yaw:walkYaw,pitch:walkPitch});else peerSeq++;peerPaint();return Math.hypot(next[0]-old[0],next[2]-old[2])>.001;}if(peerRole==='shopper'&&peerRemote){const next=peerMovePosition(walkRig.pos.toArray(),dx,dz,peerRemote.position);dx=next[0]-walkRig.pos.x;dz=next[2]-walkRig.pos.z;}return peerMoveBefore(dx,dz,dt);};ShopGame.step=shopMove;
const peerInteractBefore=shopInteract;shopInteract=function(id){if(peerRole==='detective')return {ok:false,reason:'detective-cannot-shop'};const result=peerInteractBefore(id);if(result.ok&&peerRole==='shopper'){const event=shopEvents.at(-1);if(event.type==='collect'&&peerRemote&&peerPositionVisible(peerRemote.position,walkRig.pos.toArray()))peerWitness.push({...event,position:walkRig.pos.toArray()});peerJournal.push({type:'accepted',event,detective:peerRemote?JSON.parse(JSON.stringify(peerRemote)):null});peerSend(peerSnapshot());}return result;};ShopGame.interact=shopInteract;
function peerNote(item,reason=''){if(!['banana','bread','carrot'].includes(item))return {ok:false,reason:'unknown-item'};if(peerRole==='detective'){peerSend({type:'note',item,reason:String(reason).slice(0,240)});return {ok:true,pending:true};}return {ok:false,reason:'not-detective'};}
function peerReceive(data){if(!data||typeof data!=='object')return;if(peerRole==='shopper'){if(data.type==='move'&&Number.isSafeInteger(data.seq)&&data.seq>peerLastSeq&&[data.dx,data.dz,data.yaw,data.pitch].every(Number.isFinite)){peerLastSeq=data.seq;const now=performance.now();peerBudget=Math.min(8,peerBudget+(now-peerBudgetTime)*.045);peerBudgetTime=now;const distance=Math.hypot(data.dx,data.dz);if(distance<=peerBudget+.01&&distance<=4){peerBudget-=distance;peerRemote.position=peerMovePosition(peerRemote.position,data.dx,data.dz,walkRig.pos.toArray());peerRemote.yaw=data.yaw;peerRemote.pitch=Math.max(-1.2,Math.min(1.2,data.pitch));peerShowAvatar(peerRemote.position,peerRemote.yaw);}peerSend(peerSnapshot());}else if(data.type==='note'&&typeof data.item==='string'&&data.item.length>0&&data.item.length<=64&&peerNotes.length<100){peerNotes.push({time:shopTime,item:data.item,reason:String(data.reason||'').slice(0,240)});peerJournal.push({type:'note',note:peerNotes.at(-1)});peerSend(peerSnapshot());}else if(data.type==='undo'){peerNotes.pop();peerSend(peerSnapshot());}}else if(peerRole==='detective'&&data.type==='state'&&data.shopper&&data.detective){peerRemote=data.shopper;peerNotes=data.notes||[];peerWitness=data.witness||[];shopCollected=new Set(data.shopper.collected);shopPaid=data.shopper.paid;shopReceipt=data.shopper.receipt;walkRig.pos.fromArray(data.detective.position);peerShowAvatar(peerRemote.position,peerRemote.yaw);shopCamera();shopPaint();}}
function peerDisconnect(){peerConnection?.close();peerNode?.destroy();peerConnection=null;peerNode=null;peerRole='solo';peerRemote=null;if(peerAvatar)scene.remove(peerAvatar);peerAvatar=null;pe('peerNotebook').hidden=true;pe('peerQR').replaceChildren();pe('peerLink').value='';peerSay('Disconnected. Local shopping remains available.');if(shopActive)shopPaint();}
function peerCreate(){if(typeof Peer!=='function')throw Error('PeerJS did not load.');return new Peer(undefined,window.FilmPeerOptions||{});}
async function peerHost(){if(!shopActive)await shopStart(true);peerDisconnect();peerRole='shopper';peerToken=crypto.randomUUID();peerNotes=[];peerWitness=[];peerJournal=[];peerNode=peerCreate();peerSay('Opening invitation…');peerNode.on('open',id=>{const url=new URL(location.href);url.search='';url.hash='maggie='+encodeURIComponent(id)+'&token='+encodeURIComponent(peerToken);pe('peerLink').value=url.href;if(/^https?:$/.test(url.protocol)&&!['localhost','127.0.0.1'].includes(url.hostname)){const qr=qrcode(0,'M');qr.addData(url.href);qr.make();pe('peerQR').innerHTML=qr.createSvgTag(4,4);peerSay('Scan to join as Maggie. Keep this shopper tab open.');}else peerSay('Room open. Phone scanning needs this page hosted at a reachable HTTPS address. Copy the link for a second local tab.');});peerNode.on('connection',connection=>{if(connection.metadata?.token!==peerToken||peerConnection){connection.on('open',()=>connection.close());return;}peerConnection=connection;connection.on('open',()=>{const current=walkRig.pos.toArray();let spawn=null;for(let z=-60;z<110&&!spawn;z+=8)for(let x=-80;x<120;x+=8){const y=walkSurface(x,z,current[1]);if(y!==null&&Math.hypot(x-current[0],z-current[2])>=28&&Math.hypot(x-current[0],z-current[2])<65){spawn=[x,y,z];break;}}if(!spawn){connection.close();peerConnection=null;peerSay('Move into a wider area, then invite Maggie again.');return;}peerRemote={position:spawn,yaw:0,pitch:.05};peerBudgetTime=performance.now();peerBudget=8;peerLastSeq=-1;peerMakeAvatar('movieator-maggie');peerShowAvatar(spawn,0);peerSay('Maggie joined · two independent records');peerSend(peerSnapshot());});connection.on('data',peerReceive);connection.on('close',()=>{peerConnection=null;peerRemote=null;if(peerAvatar)peerAvatar.visible=false;peerSay('Maggie disconnected; the shopper can continue.');});connection.on('error',e=>peerSay(e.message));});peerNode.on('error',e=>peerSay('Connection: '+e.message));return true;}
async function peerJoin(id,token){await shopStart(true);peerDisconnect();peerRole='detective';peerPanel.open=true;peerNode=peerCreate();peerSay('Joining as Maggie…');peerMakeAvatar('citizen');peerNode.on('open',()=>{peerConnection=peerNode.connect(id,{reliable:true,serialization:'json',metadata:{token}});peerConnection.on('open',()=>peerSay('Connected · Maggie detective'));setTimeout(()=>{if(peerRole==='detective'&&!peerConnection?.open)peerSay('WebRTC did not connect. Check signaling, network and relay access; local two-tab play is available.');},20000);peerConnection.on('data',peerReceive);peerConnection.on('close',()=>peerSay('Disconnected · observations kept in this tab'));peerConnection.on('error',e=>peerSay(e.message));});peerNode.on('error',e=>peerSay('Connection: '+e.message));peerPaint();}
pe('peerHost').onclick=()=>peerHost().catch(e=>peerSay(e.message));pe('peerLeave').onclick=peerDisconnect;pe('peerUndo').onclick=()=>peerSend({type:'undo'});peerPanel.querySelectorAll('[data-note]').forEach(b=>b.onclick=()=>peerNote(b.dataset.note));
setInterval(()=>{peerPanel.hidden=!shopActive||shopReplay;if(peerRole==='shopper'&&peerConnection?.open){peerShowAvatar(peerRemote?.position,peerRemote?.yaw);peerSend(peerSnapshot());}},150);
const peerBoot=setInterval(()=>{const h=new URLSearchParams(location.hash.slice(1));if(window.ShopGame&&isLocation()&&!filmBusy){clearInterval(peerBoot);if(h.has('maggie'))peerJoin(h.get('maggie'),h.get('token')).catch(e=>peerSay(e.message));}},500);
window.ShopPeers={host:peerHost,join:peerJoin,disconnect:peerDisconnect,note:peerNote,get role(){return peerRole},get connected(){return !!peerConnection?.open},get invitation(){return pe('peerLink').value},get journal(){return {notes:peerNotes,witness:[],events:peerJournal}},observe(){return peerRole==='detective'?{role:peerRole,position:walkRig.pos.toArray(),shopper:peerRemote?{position:peerRemote.position}:null,witness:peerWitness,notebook:peerNotes,paid:shopPaid,receipt:shopPaid?shopReceipt:null}:{role:peerRole,state:shopState(),stock:ShopGame.stock};}};
const peerStateBefore=shopState;shopState=function(){const s=peerStateBefore();if(peerRole==='shopper'&&peerRemote)s.detective={position:[...peerRemote.position],yaw:peerRemote.yaw};return s;};
const peerReplayBefore=shopReplayAt;shopReplayAt=function(t){peerReplayBefore(t);if(!shopRun)return;let a=shopRun.frames[0],b=a;for(const f of shopRun.frames){b=f;if(f.t>t)break;a=f;}if(a.detective){if(!peerAvatar)peerMakeAvatar('movieator-maggie');const u=b.t>a.t?Math.max(0,Math.min(1,(t-a.t)/(b.t-a.t))):0,position=V(...a.detective.position);if(b.detective)position.lerp(V(...b.detective.position),u);peerShowAvatar(position.toArray(),a.detective.yaw);}else if(peerAvatar)peerAvatar.visible=false;};ShopGame.seek=shopReplayAt;
const peerReplayStartBefore=shopStartReplay;shopStartReplay=async function(run){if(peerRole!=='solo')peerDisconnect();return peerReplayStartBefore(run);};ShopGame.replay=shopStartReplay;
const peerLeaveBefore=shopLeave;shopLeave=async function(){if(peerRole!=='solo'||peerAvatar)peerDisconnect();return peerLeaveBefore();};
/* Explicit offline transport for same-browser experiments; never labelled WebRTC. */
let localChannel=null;
const peerDisconnectNetwork=peerDisconnect;peerDisconnect=function(){localChannel?.close();localChannel=null;peerDisconnectNetwork();};ShopPeers.disconnect=peerDisconnect;
async function localHost(){if(!shopActive)await shopStart(true);peerDisconnect();peerRole='shopper';peerNotes=[];peerWitness=[];peerJournal=[];const room=crypto.randomUUID();localChannel=new BroadcastChannel('film-butter-'+room);localChannel.onmessage=({data})=>{if(data.type==='hello'&&!peerConnection){const current=walkRig.pos.toArray();let spawn;for(let z=-60;z<110&&!spawn;z+=8)for(let x=-80;x<120;x+=8){const y=walkSurface(x,z,current[1]);if(y!==null&&Math.hypot(x-current[0],z-current[2])>=28&&Math.hypot(x-current[0],z-current[2])<65){spawn=[x,y,z];break;}}if(!spawn)return;peerRemote={position:spawn,yaw:0,pitch:.05};peerBudget=8;peerBudgetTime=performance.now();peerLastSeq=-1;peerConnection={open:true,send:data=>localChannel.postMessage(data),close(){this.open=false}};peerMakeAvatar('movieator-maggie');peerShowAvatar(spawn,0);peerSay('Local two-tab experiment · BroadcastChannel, not WebRTC');peerSend(peerSnapshot());}else peerReceive(data);};return room;}
async function localJoin(room){await shopStart(true);peerDisconnect();peerRole='detective';peerPanel.open=true;localChannel=new BroadcastChannel('film-butter-'+room);peerConnection={open:true,send:data=>localChannel.postMessage(data),close(){this.open=false}};localChannel.onmessage=({data})=>peerReceive(data);peerMakeAvatar('citizen');peerSend({type:'hello'});peerSay('Local two-tab experiment · Maggie detective');peerPaint();}
ShopPeers.localHost=localHost;ShopPeers.localJoin=localJoin;
const localButton=document.createElement('button');localButton.textContent='Open local Maggie tab';localButton.onclick=async()=>{const tab=window.open('','_blank');try{const room=await localHost(),url=new URL(location.href);url.search='';url.hash='local='+encodeURIComponent(room);pe('peerLink').value=url.href;peerSay('Local two-tab session · same browser only');if(tab)tab.location.href=url.href;}catch(e){tab?.close();peerSay(e.message);}};peerPanel.insertBefore(localButton,pe('peerStatus'));
const localBoot=setInterval(()=>{const h=new URLSearchParams(location.hash.slice(1));if(isLocation()&&!filmBusy){clearInterval(localBoot);if(h.has('local'))localJoin(h.get('local')).catch(e=>peerSay(e.message));}},400);
