/* Shopping actions operate on native stock instances and an accepted-run journal. */
const shopHUD=document.createElement('div');shopHUD.id='shopHUD';shopHUD.hidden=true;shopHUD.innerHTML='<div id="shopList"></div><p id="shopHint"></p><button id="shopAction">Collect</button><div id="shopReceipt" hidden></div>';stage.append(shopHUD);
let shopActive=false,shopReplay=false,shopManual=false,shopSaved=null,shopStock=[],shopGeometry=[],shopTime=0,shopLast=0,shopFrames=[],shopEvents=[],shopCollected=new Set(),shopPaid=false,shopReceipt=null,shopReplayTime=0,shopRun=null,shopLastRecord=-1;
const shopKey='film-butter-shopping-hands-v2',shopCheckout=V(-22,49,3),shopRadius=12,shopReach=44;
const shopMoney=n=>'$'+(n/100).toFixed(2);
function shopRead(){try{return JSON.parse(localStorage.getItem(shopKey)||'null')}catch{return null}}
function shopState(){return {t:+shopTime.toFixed(3),position:walkRig.pos.toArray(),yaw:walkYaw,pitch:walkPitch,collected:[...shopCollected],paid:shopPaid,receipt:shopReceipt};}
function shopSave(){if(!shopActive||shopReplay)return;try{const old=shopRead();localStorage.setItem(shopKey,JSON.stringify({source:filmAsset().hash,current:shopState(),frames:shopFrames,events:shopEvents,completed:shopPaid?{frames:shopFrames,events:shopEvents,receipt:shopReceipt,duration:shopTime}:old?.completed}));}catch(e){$('#shopHint').textContent='Progress is held in this tab; browser storage is unavailable.';}}
function shopRecord(force=false){if(!shopActive||shopReplay)return;if(force||shopTime-shopLastRecord>=.09){shopFrames.push(shopState());shopLastRecord=shopTime;}if(force)shopSave();}
function shopEvent(type,item){shopEvents.push({time:+shopTime.toFixed(3),type,item});shopRecord(true);}
function shopLayout(){for(const p of S.parts){const d=catalog.get(p.part);if(!d?.layer)continue;locationUseWholePieces(p,false);p.mesh.visible=d.layer==='shop'||(walkRig?.pos.x>170&&d.layer==='upper');const saved=shopGeometry.find(g=>g.p===p);if(saved)p.mesh.geometry=saved.remainder;}for(const a of ButterCast.cast)a.rig.figure.visible=false;}
function shopBuildStock(){
 const grouped=new Map();
 for(const p of S.parts){const d=catalog.get(p.part);if(!d?.collectibles?.length)continue;const removed=new Set();
  for(const item of d.collectibles){let entry=grouped.get(item.id);if(!entry){entry={id:item.id,name:item.name,cents:item.cents,meshes:[],sources:[]};grouped.set(item.id,entry);}const idx=[];for(let t=item.start;t<item.start+item.count;t++){removed.add(t);idx.push(t*3,t*3+1,t*3+2);}const g=new THREE.BufferGeometry();for(const[k,a]of Object.entries(d.geometry.attributes))g.setAttribute(k,a);g.setIndex(idx);const mesh=new THREE.Mesh(g,p.mesh.material.clone());mesh.material.clippingPlanes=[];mesh.matrixAutoUpdate=false;p.mesh.updateMatrixWorld(true);mesh.matrix.copy(p.mesh.matrixWorld);mesh.matrixWorld.copy(mesh.matrix);scene.add(mesh);entry.meshes.push(mesh);entry.sources.push({instance:p.id,ref:item.ref,sourceIndex:item.sourceIndex});}
  const idx=[];for(let t=0;t<d.geometry.attributes.position.count/3;t++)if(!removed.has(t))idx.push(t*3,t*3+1,t*3+2);const g=new THREE.BufferGeometry();for(const[k,a]of Object.entries(d.geometry.attributes))g.setAttribute(k,a);g.setIndex(idx);shopGeometry.push({p,original:p.mesh.geometry,remainder:g});p.mesh.geometry=g;
 }
 shopStock=[...grouped.values()];for(const item of shopStock){const box=new THREE.Box3();for(const mesh of item.meshes){const pos=mesh.geometry.attributes.position,idx=mesh.geometry.index;for(let n=0;n<idx.count;n++)box.expandByPoint(new THREE.Vector3().fromBufferAttribute(pos,idx.getX(n)).applyMatrix4(mesh.matrix));}item.box=box;item.position=box.getCenter(V());}
 if(shopStock.length!==3)throw Error('Shopping stock did not resolve to three native items.');
}
const shopSurfaceBefore=walkSurface;walkSurface=function(x,z,previous,spawn=false){if(!shopActive)return shopSurfaceBefore(x,z,previous,spawn);if(x<-220||x>220||z<-230||z>225)return null;let y=-Infinity;for(const{box:b}of walkGround){const fx=x-Math.max(b.min.x,Math.min(x,b.max.x)),fz=z-Math.max(b.min.z,Math.min(z,b.max.z));if(fx*fx+fz*fz<=36&&b.max.y<=previous+8.7)y=Math.max(y,b.max.y);}if(!Number.isFinite(y)||y-previous>8.7||previous-y>24)return null;for(const{box:b}of walkGround){if(b.max.y<=y+8.7||b.min.y>=y+(typeof doorDuckAt==='function'&&doorDuckAt(x,z)?92:112))continue;const dx=x-Math.max(b.min.x,Math.min(x,b.max.x)),dz=z-Math.max(b.min.z,Math.min(z,b.max.z));const radius=b.max.y<=y+24?6:b.max.y>y+66?15:shopRadius;if(dx*dx+dz*dz<radius*radius)return null;}return y;};
function shopCamera(){if(!walkRig)return;walkRig.figure.visible=false;const eye=walkRig.pos.clone().add(V(0,48,0)),look=V(Math.sin(walkYaw)*Math.cos(walkPitch),-Math.sin(walkPitch),Math.cos(walkYaw)*Math.cos(walkPitch));camera.position.copy(eye);camera.up.set(0,1,0);controls.target.copy(eye).addScaledVector(look,100);camera.lookAt(controls.target);camera.near=1;camera.far=1500;camera.fov=65;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);}
function shopCanSee(item,position=walkRig.pos){const eye=position.clone().add(V(0,48,0)),obstacles=S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh);const points=[item.position];for(const mesh of item.meshes){const g=mesh.geometry,idx=g.index;for(let n=0;n<idx.count;n+=Math.max(1,Math.floor(idx.count/24)))points.push(new THREE.Vector3().fromBufferAttribute(g.attributes.position,idx.getX(n)).applyMatrix4(mesh.matrix));}return points.some(point=>{const delta=point.clone().sub(eye),distance=delta.length(),ray=new THREE.Raycaster(eye,delta.normalize(),0,Math.max(0,distance-.15));return !ray.intersectObjects(obstacles,true).length;});}

function shopNear(item){return Math.hypot(item.position.x-walkRig.pos.x,item.position.z-walkRig.pos.z)<=shopReach&&shopCanSee(item);}
function shopTarget(){return shopStock.filter(i=>!shopCollected.has(i.id)&&shopNear(i)).sort((a,b)=>a.position.distanceTo(walkRig.pos)-b.position.distanceTo(walkRig.pos))[0];}
function shopAtCheckout(){return Math.hypot(shopCheckout.x-walkRig.pos.x,shopCheckout.z-walkRig.pos.z)<32;}
function shopPaint(){if(!shopActive)return;for(const item of shopStock)for(const m of item.meshes){m.visible=!shopCollected.has(item.id);if(m.material.emissive){m.material.emissive.setHex(0x254411);m.material.emissiveIntensity=(m.visible&&shopNear(item)) ? .22 : 0;}}$('#shopList').innerHTML=shopStock.map(i=>'<span class="'+(shopCollected.has(i.id)?'done':'')+'">'+(shopCollected.has(i.id)?'✓ ':'○ ')+i.name+'</span>').join('');const target=shopTarget(),button=$('#shopAction');button.hidden=shopReplay;button.disabled=false;
 if(shopReplay){$('#shopHint').textContent=(shopRun.label||'Recorded run')+' · '+shopReplayTime.toFixed(1)+' / '+shopRun.duration.toFixed(1)+'s';}
 else if(shopPaid){button.textContent='Shop again';$('#shopHint').textContent='Shopping complete · receipt saved';}
 else if(target){button.textContent='Collect '+target.name+' · E';$('#shopHint').textContent='In reach · '+shopMoney(target.cents);}
 else if(shopAtCheckout()){button.textContent=shopCollected.size===3?'Check out '+shopMoney(400)+' · E':'Checkout · '+(3-shopCollected.size)+' items still needed';button.disabled=shopCollected.size!==3;$('#shopHint').textContent='Register';}
 else{button.textContent='Find an item';button.disabled=true;$('#shopHint').textContent=shopCollected.size===3?'Return to the register on the left.':'Bread and fruit are in the produce crates on the right.';}
 $('#shopReceipt').hidden=!shopPaid||!shopAtCheckout();$('#shopReceipt').innerHTML=shopPaid?'<strong>PAID · '+shopMoney(shopReceipt.total)+'</strong><br>'+shopReceipt.lines.map(l=>l.name+' '+shopMoney(l.cents)).join(' · ')+'<br><button id="shopReplayRun">Watch this run</button> <button id="shopSaveRun">Save run</button>':'';if(shopPaid){$('#shopReplayRun').onclick=()=>shopStartReplay();$('#shopSaveRun').onclick=()=>download(JSON.stringify(shopRead()?.completed||{frames:shopFrames,events:shopEvents,receipt:shopReceipt,duration:shopTime},null,2),'shopping-run.json','application/json');}}
function shopInteract(id){if(!shopActive||shopReplay||shopPaid)return {ok:false,reason:'not-shopping'};if(id==='checkout'||(!id&&shopAtCheckout()&&shopCollected.size===3)){if(!shopAtCheckout())return {ok:false,reason:'too-far'};if(shopCollected.size!==3)return {ok:false,reason:'incomplete-list'};shopPaid=true;shopReceipt={id:'grocer-'+shopEvents.length,lines:shopStock.map(i=>({id:i.id,name:i.name,cents:i.cents})),total:400};shopEvent('checkout',null);shopBeep(880);shopPaint();return {ok:true,receipt:shopReceipt};}
 const item=id?shopStock.find(i=>i.id===id):shopTarget();if(!item)return {ok:false,reason:'nothing-in-reach'};if(shopCollected.has(item.id))return {ok:false,reason:'already-collected'};if(!shopNear(item))return {ok:false,reason:'out-of-reach-or-occluded'};shopCollected.add(item.id);shopEvent('collect',item.id);shopBeep(520+shopCollected.size*110);shopPaint();return {ok:true,item:item.id};}
let shopAudio;function shopBeep(hz){try{shopAudio??=new(window.AudioContext||window.webkitAudioContext)();shopAudio.resume();const o=shopAudio.createOscillator(),g=shopAudio.createGain();o.frequency.value=hz;g.gain.setValueAtTime(.06,shopAudio.currentTime);g.gain.exponentialRampToValueAtTime(.001,shopAudio.currentTime+.14);o.connect(g);g.connect(shopAudio.destination);o.start();o.stop(shopAudio.currentTime+.15);}catch{}}
function shopMove(dx,dz,dt=.05){if(!shopActive||shopReplay)return false;const before=walkRig.pos.clone(),steps=Math.max(1,Math.ceil(Math.hypot(dx,dz)/2));for(let i=0;i<steps;i++){const p=walkRig.pos,x=p.x+dx/steps,z=p.z+dz/steps;let y=walkSurface(x,z,p.y);if(y!==null)p.set(x,y,z);else{y=walkSurface(x,p.z,p.y);if(y!==null)p.set(x,y,p.z);else{y=walkSurface(p.x,z,p.y);if(y!==null)p.set(p.x,y,z);}}}shopTime+=dt;const moved=before.distanceToSquared(walkRig.pos)>.0001;if(moved)walkRig.heading=Math.atan2(dx,dz);shopCamera();shopRecord();shopPaint();return moved;}
const shopTickBefore=walkTick;walkTick=function(now){if(!shopActive)return shopTickBefore(now);const dt=Math.min(.05,Math.max(0,(now-(shopLast||now))/1000));shopLast=now;if(shopManual)return;if(shopReplay){if(shopReplayTime<shopRun.duration){shopReplayTime=Math.min(shopRun.duration,shopReplayTime+dt);shopReplayAt(shopReplayTime);}return;}walkYaw-=walkLook.x*dt*2;walkPitch=Math.max(-.65,Math.min(1.2,walkPitch+walkLook.y*dt));let f=-walkMove.y+(walkKeys.has('KeyW')||walkKeys.has('ArrowUp')?1:0)-(walkKeys.has('KeyS')||walkKeys.has('ArrowDown')?1:0),r=walkMove.x+(walkKeys.has('KeyD')||walkKeys.has('ArrowRight')?1:0)-(walkKeys.has('KeyA')||walkKeys.has('ArrowLeft')?1:0);const mag=Math.max(1,Math.hypot(f,r));f/=mag;r/=mag;shopMove((Math.sin(walkYaw)*f-Math.cos(walkYaw)*r)*36*dt,(Math.cos(walkYaw)*f+Math.sin(walkYaw)*r)*36*dt,dt);};
async function shopStart(fresh=false){if(!isLocation())return;if(shopActive)await shopLeave();shopSaved={view:locationView,visible:ButterCast.cast.map(a=>({a,visible:a.rig.figure.visible})),performer:ButterPerformer.state.on};shopActive=true;shopReplay=false;shopManual=false;ButterPerformer.state.on=false;locationView='exterior';await shopModeBefore('walk');shopLayout();shopBuildStock();walkCache();const data=!fresh&&shopRead(),saved=data?.source===filmAsset().hash?data:null;shopCollected=new Set(saved?.current?.collected||[]);shopPaid=!!saved?.current?.paid;shopReceipt=saved?.current?.receipt||null;shopTime=saved?.current?.t||0;shopFrames=saved?.frames||[];shopEvents=saved?.events||[];shopLastRecord=-1;
 let spawn=saved?.current?.position;const candidates=spawn?[spawn]:[];for(let z=-60;z<=90;z+=10)for(const x of [0,20,-20,40])candidates.push([x,8.64,z]);spawn=candidates.find(([x,y,z])=>walkSurface(x,z,y)!==null);if(!spawn)throw Error('No traversable shop entry');walkRig.pos.set(spawn[0],walkSurface(spawn[0],spawn[2],spawn[1]),spawn[2]);walkYaw=saved?.current?.yaw??1.0;walkPitch=saved?.current?.pitch??.05;walkFirst=true;shopHUD.hidden=false;document.body.classList.add('shopping');shopLast=0;shopCamera();shopRecord(true);shopPaint();}
async function shopLeave(){if(!shopActive)return;shopSave();shopActive=false;shopReplay=false;shopHUD.hidden=true;document.body.classList.remove('shopping','shop-replay');for(const s of shopStock)for(const m of s.meshes){scene.remove(m);m.geometry.dispose();m.material.dispose();}for(const g of shopGeometry){g.p.mesh.geometry=g.original;g.remainder.dispose();}shopStock=[];shopGeometry=[];for(const v of shopSaved.visible)if(ButterCast.cast.includes(v.a))v.a.rig.figure.visible=v.visible;ButterPerformer.state.on=shopSaved.performer;locationView=shopSaved.view;locationApply();}
async function shopStartReplay(run){run=run||shopRead()?.completed||window.FilmHandRecording;if(!run?.receipt){note('Complete a shopping trip first.','SHOP');return false;}if(!shopActive)await shopStart();shopRun=JSON.parse(JSON.stringify(run));shopReplay=true;shopReplayTime=0;walkResetInput();document.body.classList.add('shop-replay');shopReplayAt(0);return true;}
function shopReplayAt(t){if(!shopRun)return;shopReplayTime=Math.min(shopRun.duration,Math.max(0,t));const frames=shopRun.frames;let a=frames[0],b=a;for(let i=1;i<frames.length;i++){b=frames[i];if(b.t>shopReplayTime)break;a=b;}const u=b.t>a.t?Math.max(0,Math.min(1,(shopReplayTime-a.t)/(b.t-a.t))):0;walkRig.pos.fromArray(a.position).lerp(V(...b.position),u);if(walkSurface(walkRig.pos.x,walkRig.pos.z,walkRig.pos.y)===null)walkRig.pos.fromArray(a.position);walkYaw=a.yaw+(b.yaw-a.yaw)*u;walkPitch=a.pitch+(b.pitch-a.pitch)*u;shopCollected=new Set(a.collected);shopPaid=a.paid;shopReceipt=a.receipt;shopCamera();shopPaint();}
function shopDrawHUD(ctx,w,h){const k=w/1280;ctx.save();ctx.scale(k,k);ctx.fillStyle='#10231fe8';ctx.fillRect(24,24,1232,65);ctx.fillStyle='#f4e8cc';ctx.font='bold 22px sans-serif';ctx.fillText('THE SHOPPING LIST · GREEN GROCER',42,50);ctx.font='19px sans-serif';ctx.fillText(shopStock.map(i=>(shopCollected.has(i.id)?'✓ ':'○ ')+i.name).join('     '),42,77);ctx.fillStyle='#10231fed';ctx.fillRect(24,646,1232,50);ctx.fillStyle='#f4e8cc';ctx.font='20px sans-serif';ctx.fillText(shopPaid?'PAID  $4.00 · Shopping complete':$('#shopHint').textContent+'   '+($('#shopAction').disabled?'':$('#shopAction').textContent),42,678);ctx.restore();}
const shopModeBefore=filmSetMode;filmSetMode=async function(mode){if(isLocation()&&mode==='walk')return shopStart();if(isLocation()&&mode==='film')return shopStartReplay();if(shopActive)await shopLeave();return shopModeBefore(mode);};modeBar.querySelectorAll('button').forEach(b=>b.onclick=()=>filmSetMode(b.dataset.filmMode));window.FilmButter.setMode=filmSetMode;
$('#shopAction').onclick=()=>shopPaid?shopStart(true):shopInteract();window.addEventListener('keydown',e=>{if(shopActive&&!shopReplay&&e.code==='KeyE'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();if(!e.repeat)shopInteract();}});window.addEventListener('pagehide',shopSave);
const shopLocationBefore=locationApply;locationApply=function(){shopLocationBefore();shopModeLabels();if(shopActive)shopLayout();};
const shopSwitchBefore=switchTo;switchTo=async function(...args){if(shopActive)await shopLeave();return shopSwitchBefore(...args);};ButterFilms.switchTo=switchTo;
window.ShopGame={start:shopStart,interact:shopInteract,step:shopMove,look:(yaw,pitch=.05,record=true)=>{walkYaw=yaw;walkPitch=pitch;shopCamera();if(record)shopRecord(true);},canCollectAt:(id,x,y,z)=>{const item=shopStock.find(i=>i.id===id),p=V(x,y,z);return item&&Math.hypot(item.position.x-x,item.position.z-z)<=shopReach&&shopCanSee(item,p);},get state(){return shopActive?shopState():null},get stock(){return shopStock.map(i=>({id:i.id,name:i.name,position:i.position.toArray(),sources:i.sources,near:shopNear(i)}))},get active(){return shopActive},set manual(v){shopManual=v},surface:(x,z,y=8.64)=>walkSurface(x,z,y),replay:shopStartReplay,seek:shopReplayAt,get recording(){return {frames:shopFrames,events:shopEvents,receipt:shopReceipt,duration:shopTime}},finishHold(seconds=3){shopTime+=seconds;shopRecord(true);return this.recording},frame(t){shopReplayAt(t);const size=renderer.getSize(new THREE.Vector2()),ratio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(1280,720,false);camera.aspect=16/9;camera.updateProjectionMatrix();renderer.render(scene,camera);const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d');x.drawImage(renderer.domElement,0,0);shopDrawHUD(x,1280,720);const result=c.toDataURL('image/png').split(',')[1];renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false);return result;}};
const shopBoot=setInterval(()=>{if(isLocation()&&!filmBusy){clearInterval(shopBoot);shopModeLabels();const query=new URLSearchParams(location.search);if(!shopActive&&!query.has('inspect')&&!query.has('operators')&&!query.has('build'))shopStart().catch(filmError);if(query.has('inspect'))ShopGame.inspectArchivedTake().catch(filmError);if(query.has('operators')&&window.FilmOperatorRecording)shopStartReplay(window.FilmOperatorRecording).catch(filmError);}},300);

function shopModeLabels(){modeBar.querySelectorAll('button').forEach(b=>{if(b.dataset.filmMode==='walk')b.textContent=isLocation()?'Play':'Walk';if(b.dataset.filmMode==='film')b.textContent=isLocation()?'Replay':'Film';});}
ShopGame.inspectArchivedTake=async()=>{if(shopActive)await shopLeave();return shopModeBefore('film');};GrocerTake.enter=ShopGame.inspectArchivedTake;
