/* Visible native cast and a pixels-only agent contract. Ground truth stays in evaluator APIs. */
let visualOwn=null,visualCash=null,visualKind='',visualEyes=false,visualBusy=false,visualActions=[];
function visualFigure(kind){const entry=ButterCast.cast.find(a=>a.kind===kind);if(!entry)return null;const original=entry.rig.headP.position.y;const model=entry.rig.figure.clone(true),mapping=new Map();function match(a,b){mapping.set(a,b);a.children.forEach((c,i)=>match(c,b.children[i]));}match(entry.rig.figure,model);entry.rig.headP.position.y=original;model.visible=true;model.position.set(0,0,0);model.rotation.set(0,0,0);model.scale.setScalar(1);model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(V()),scale=.72;model.scale.setScalar(scale);model.position.set(-(box.min.x+box.max.x)*scale/2,-box.min.y*scale,-(box.min.z+box.max.z)*scale/2);const group=new THREE.Group();group.name=kind+' playable native minifig';group.add(model);group.userData.kind=kind;group.userData.rig={armLP:mapping.get(entry.rig.armLP),armRP:mapping.get(entry.rig.armRP),head:mapping.get(entry.rig.headP),handL:mapping.get(entry.rig.slots.handL),handR:mapping.get(entry.rig.slots.handR)};group.userData.joints=['armLP','armRP','legLP','legRP'].map(k=>{const o=mapping.get(entry.rig[k]);return o?{o,base:o.rotation.x}:null;});if(kind==='movieator-marge'){group.userData.rig.armLP.rotation.x=-.95;group.userData.rig.armRP.rotation.x=-.95;}scene.add(group);return group;}
function visualCast(){if(!shopActive)return;const kind=peerRole==='detective'?'movieator-maggie':'movieator-marge';if(kind!==visualKind||!visualOwn){if(visualOwn)scene.remove(visualOwn);visualOwn=visualFigure(kind);visualKind=kind;}if(!visualCash){visualCash=visualFigure('citizen');visualCash.position.set(-89.28,8.64,-21.6);visualCash.rotation.y=Math.PI/2;}visualCash.visible=true;if(visualOwn){visualOwn.position.copy(walkRig.pos);visualOwn.rotation.y=walkYaw;visualOwn.visible=true;if(visualOwn.userData.rig.head)visualOwn.userData.rig.head.visible=!visualEyes;}}
const visualCameraBefore=shopCamera;shopCamera=function(){if(!shopActive)return visualCameraBefore();visualCast();walkRig.figure.visible=false;const forward=V(Math.sin(walkYaw),0,Math.cos(walkYaw));let eye,target;if(visualEyes){eye=walkRig.pos.clone().add(V(0,peerRole==='detective'?48:76,0)).addScaledVector(forward,9);target=eye.clone().add(V(Math.sin(walkYaw)*Math.cos(walkPitch),-Math.sin(walkPitch),Math.cos(walkYaw)*Math.cos(walkPitch)).multiplyScalar(100));}else{target=walkRig.pos.clone().add(V(0,44,0)).addScaledVector(forward,12);eye=walkRig.pos.clone().add(V(0,145+walkPitch*25,0)).addScaledVector(forward,-74);const start=walkRig.pos.clone().add(V(0,125,0)),delta=eye.clone().sub(start),ray=new THREE.Raycaster(start,delta.clone().normalize(),0,delta.length()),hits=ray.intersectObjects(S.parts.filter(p=>p.mesh.visible).map(p=>p.mesh),true);if(hits.length)eye.copy(start).addScaledVector(ray.ray.direction,Math.max(2,hits[0].distance-3));}camera.position.copy(eye);controls.target.copy(target);camera.up.set(0,1,0);camera.lookAt(target);camera.near=.5;camera.far=1500;camera.fov=64;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);};
const visualLeaveBefore=shopLeave;shopLeave=async function(){if(visualOwn)scene.remove(visualOwn);if(visualCash)scene.remove(visualCash);visualOwn=visualCash=null;visualKind='';return visualLeaveBefore();};
// Reuse Marge as the remote shopper, not an anonymous citizen.
const visualPeerBefore=peerMakeAvatar;peerMakeAvatar=function(kind){if(peerAvatar)scene.remove(peerAvatar);peerAvatar=visualFigure(kind==='citizen'?'movieator-marge':kind);};
const viewButton=document.createElement('button');viewButton.id='shopViewToggle';viewButton.textContent='Marge · Eyes';viewButton.onclick=()=>{visualEyes=!visualEyes;viewButton.textContent=visualEyes?'Show minifig':(peerRole==='detective'?'Maggie':'Marge')+' · Eyes';shopCamera();};stage.append(viewButton);setInterval(()=>viewButton.hidden=!shopActive||shopReplay,200);
// A grocery must be in front of the player, in reach and unobstructed.
const visualNearBefore=shopNear;shopNear=function(item){const d=item.position.clone().sub(walkRig.pos);return (d.x*Math.sin(walkYaw)+d.z*Math.cos(walkYaw))/Math.max(.01,Math.hypot(d.x,d.z))>.55&&visualNearBefore(item);};
peerPanel.querySelectorAll('[data-note]').forEach(b=>b.remove());const noteInput=document.createElement('input');noteInput.id='visualNote';noteInput.placeholder='What did you see?';noteInput.maxLength=64;const noteButton=document.createElement('button');noteButton.textContent='Record observation';noteButton.onclick=()=>{const value=noteInput.value.trim();if(value){peerNote(value,'Human visual observation');noteInput.value='';}};pe('peerNotebook').append(noteInput,noteButton);
peerNote=function(item,reason=''){if(typeof item!=='string'||!item.trim()||item.length>64)return {ok:false,reason:'Write an observation'};if(peerRole!=='detective')return {ok:false,reason:'not-detective'};peerSend({type:'note',item:item.trim(),reason:String(reason).slice(0,240)});return {ok:true,pending:true};};ShopPeers.note=peerNote;
const visualPeerPaintBefore=peerPaint;peerPaint=function(){visualPeerPaintBefore();if(peerRole==='detective'){pe('peerSight').textContent='Use your view. Pickups are not announced here.';pe('shopHint').textContent=shopPaid?'Shopper checked out. Compare your notes when ready.':'Watch Marge and write what you see.';}};
window.AssistedShopOperators=window.ShopOperators;
function visualObserve(){if(!shopActive)throw Error('Enter Play first');const saved=visualEyes;visualEyes=true;shopCamera();const render=window.liveRender||renderer.render.bind(renderer);render(scene,camera);const canvas=document.createElement('canvas');canvas.width=960;canvas.height=600;canvas.getContext('2d').drawImage(renderer.domElement,0,0,960,600);const image=canvas.toDataURL('image/png').split(',')[1];visualEyes=saved;shopCamera();return {role:peerRole==='detective'?'detective':'shopper',image,goal:peerRole==='detective'?'Observe purchases and keep your own notebook.': 'Buy bananas, a croissant and carrots; return to the register.',inventory:peerRole==='detective'?undefined:[...shopCollected],notebook:peerRole==='detective'?peerNotes.map(n=>({text:n.item,reason:n.reason})):undefined,finished:shopPaid,actions:['move','turn','interact','checkout','note','wait'],lastResult:visualActions.at(-1)?.result||null};}
async function visualAct(action){if(visualBusy)return {ok:false,reason:'busy'};visualBusy=true;const entry={role:peerRole,time:shopTime,action:JSON.parse(JSON.stringify(action))};visualActions.push(entry);let result;try{if(action.verb==='move'){const seconds=Math.max(.05,Math.min(.6,Number(action.seconds)||.3)),f=Math.max(-1,Math.min(1,Number(action.forward)||0)),r=Math.max(-1,Math.min(1,Number(action.strafe)||0)),norm=Math.max(1,Math.hypot(f,r));let moved=false;for(let t=0;t<seconds;t+=.05){moved=shopMove((Math.sin(walkYaw)*f-Math.cos(walkYaw)*r)*36*.05/norm,(Math.cos(walkYaw)*f+Math.sin(walkYaw)*r)*36*.05/norm,.05)||moved;await new Promise(r=>setTimeout(r,50));}result={ok:true,moved};}else if(action.verb==='turn'){const delta=Math.max(-90,Math.min(90,Number(action.degrees)||0))*Math.PI/180,n=Math.max(1,Math.ceil(Math.abs(delta)/.035));let blocked=false;for(let i=0;i<n;i++){const before=walkYaw;walkYaw+=delta/n;shopCamera();if(Math.abs(walkYaw-before)<1e-8&&Math.abs(delta)>1e-8){blocked=true;break;}}walkPitch=Math.max(-.6,Math.min(1.2,walkPitch+(Number(action.pitchDegrees)||0)*Math.PI/180));shopCamera();shopRecord(true);result={ok:!blocked,reason:blocked?'Turn blocked by carried geometry':undefined};}else if(action.verb==='interact'){const r=shopInteract();result={ok:r.ok,reason:r.ok?'Interaction accepted':r.reason};}else if(action.verb==='checkout'){const r=shopInteract('checkout');result={ok:r.ok,reason:r.ok?'Paid':r.reason};}else if(action.verb==='note')result=peerNote(String(action.text||''),String(action.reason||''));else if(action.verb==='wait'){shopMove(0,0,.25);result={ok:true};}else result={ok:false,reason:'Use bounded movement, turning and interaction; destination lookup is unavailable.'};entry.result=result;return {result,observation:visualObserve()};}finally{visualBusy=false;}}
window.ShopOperators={observe:visualObserve,act:visualAct,get busy(){return visualBusy},get log(){return visualActions},export(){return {protocol:'visual-v2',actions:visualActions,run:ShopGame.recording,groundTruth:ShopPeers.journal}}};
window.ShopVisual={setEyes(v){visualEyes=!!v;shopCamera();},measure(){return [visualOwn,visualCash].filter(Boolean).map(o=>{o.updateMatrixWorld(true);const r=o.userData.rig;return {kind:o.userData.kind,bounds:new THREE.Box3().setFromObject(o).getSize(V()).toArray(),shoulder:r.armRP.getWorldPosition(V()).toArray(),grip:r.handR.localToWorld(V(0,-.8229,-9.8948)).toArray(),hand:r.handR.getWorldPosition(V()).toArray()};});},get cast(){return [visualOwn,visualCash,peerAvatar].filter(Boolean).map(o=>({kind:o.userData.kind||o.name,visible:o.visible,position:o.position.toArray()}));}};

function visualGait(figure,distance){if(!figure)return;figure.userData.phase=(figure.userData.phase||0)+distance*.16;for(const [i,j]of (figure.userData.joints||[]).entries())if(j)j.o.rotation.x=j.base+(distance>.001?Math.sin(figure.userData.phase+(i%2?Math.PI:0))*.48:0);}
const visualMoveBefore=shopMove;shopMove=function(...args){const before=walkRig?.pos.clone(),result=visualMoveBefore(...args);if(before&&walkRig)visualGait(visualOwn,before.distanceTo(walkRig.pos));return result;};ShopGame.step=shopMove;
const visualShowBefore=peerShowAvatar;peerShowAvatar=function(position,yaw){const previous=peerAvatar?.position.clone();visualShowBefore(position,yaw);if(previous&&peerAvatar)visualGait(peerAvatar,previous.distanceTo(peerAvatar.position));};
