export const ID=[1,0,0,0,1,0,0,0,1],RY90=[0,0,1,0,1,0,-1,0,0],RY180=[-1,0,0,0,1,0,0,0,-1],RY270=[0,0,-1,0,1,0,1,0,0];
export const DESIGN={name:'BEAVER STARSHIP I',site:'64×32 stud orbital yard / two real 3811 baseplates',ship:'36×12 stud pressure hull · seven brick courses',systems:'three keel rails · two bearing spines · sealed cabin · high wings · four VTOL engine stacks · airlock · sensor mast',principle:'The ship is not done when it resembles a ship. Support, pressure, access and thrust must all go quiet.'};
const X=i=>-630+i*20,Z=i=>-310+i*20,CX=(a,b)=>(X(a)+X(b))/2,CZ=(a,b)=>(Z(a)+Z(b))/2,range=(a,b)=>Array.from({length:b-a+1},(_,i)=>a+i),K=p=>p.map(v=>Math.round(v*1000)).join('|');let serial=0;
const P1={1:['3005.dat','Brick 1 x 1'],2:['3004.dat','Brick 1 x 2'],3:['3622.dat','Brick 1 x 3'],4:['3010.dat','Brick 1 x 4'],6:['3009.dat','Brick 1 x 6'],8:['3008.dat','Brick 1 x 8']};
const cells=(x0,x1,z0,z1,y)=>{const a=[];for(let x=x0;x<=x1;x++)for(let z=z0;z<=z1;z++)a.push([X(x),y,Z(z)]);return a};
const A=o=>({placed:false,requires:[],anchors:[],signal:'STRUCTURE',severity:50,weight:1,color:15,cover:[],kind:'structure',...o,id:o.id||`ship-${++serial}`});
function rect({id,file,name,x0,x1,z0,z1,topY,height=24,r=ID,color=15,minContacts,spread=0,signal='STRUCTURE',severity=60,weight=1,label,requires=[],cover=[]}){const bottom=cells(x0,x1,z0,z1,topY+height),top=cells(x0,x1,z0,z1,topY);return A({id,file,name,t:[CX(x0,x1),topY,CZ(z0,z1)],r,color,bottom,top,minContacts:minContacts??bottom.length,minSpread:spread,signal,severity,weight,label,requires,cover})}
function contiguous(vals){if(!vals.length)return[];const a=[...vals].sort((x,y)=>x-y),out=[];let s=a[0],p=a[0];for(let i=1;i<a.length;i++){if(a[i]===p+1){p=a[i];continue}out.push([s,p]);s=p=a[i]}out.push([s,p]);return out}
function tile(a,b,course,max=8){const allowed=[8,6,4,3,2,1],out=[];let p=a;while(p<=b){let n=allowed.find(n=>n<=max&&p+n-1<=b);if(course%2&&n===8&&p+5<=b)n=6;if(!n)n=1;out.push([p,p+n-1]);p+=n}return out}
const PK=(side,c,i)=>`P|${side}|${c}|${i}`;
function keel(z,c){const out=[];for(const [s,e] of tile(14,49,c,8)){const p=P1[e-s+1];out.push(rect({id:`keel-${z}-${c}-${s}`,file:p[0],name:p[1],x0:s,x1:e,z0:z,z1:z,topY:-c*24,color:72,signal:'GRAVITY',severity:150,weight:e-s+1,label:`KEEL z${z} · lift ${c}`}))}return out}
function plate48({id,x0,z0,topY,signal='STRUCTURE',severity=100,weight=28,label='4×8 PLATE',color=71,minContacts=8,spread=60,cover=[]}){return rect({id,file:'3035.dat',name:'Plate 4 x 8',x0,x1:x0+3,z0,z1:z0+7,topY,height:8,color,signal,severity,weight,label,minContacts,spread,cover})}
function plate44({id,x0,z0,topY,signal='STRUCTURE',severity=100,weight=20,label='4×4 PLATE',color=71,minContacts=4,spread=60,cover=[]}){return rect({id,file:'3031.dat',name:'Plate 4 x 4',x0,x1:x0+3,z0,z1:z0+3,topY,height:8,color,signal,severity,weight,label,minContacts,spread,cover})}
function wall(side,course,openings=[]){const isSide=side==='port'||side==='starboard',fixed=side==='port'?10:side==='starboard'?21:side==='bow'?14:49,start=isSide?14:10,end=isSide?49:21,blocked=new Set(openings.filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b))),vals=range(start,end).filter(v=>!blocked.has(v)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,8)){const n=e-s+1,p=P1[n],cover=range(s,e).map(i=>PK(side,course,i));if(isSide)out.push(rect({id:`hull-${side}-${course}-${s}`,file:p[0],name:p[1],x0:s,x1:e,z0:fixed,z1:fixed,topY:-104-course*24,color:15,signal:'PRESSURE',severity:112,weight:n,label:`${side.toUpperCase()} HULL · course ${course}`,cover}));else out.push(rect({id:`hull-${side}-${course}-${s}`,file:p[0],name:p[1],x0:fixed,x1:fixed,z0:s,z1:e,topY:-104-course*24,r:RY90,color:15,signal:'PRESSURE',severity:114,weight:n,label:`${side.toUpperCase()} BULKHEAD · course ${course}`,cover}))}return out}
function spine(z,course){const hole={a:27,b:30,from:1,to:3},blocked=new Set(course>=hole.from&&course<=hole.to?range(hole.a,hole.b):[]),vals=range(16,47).filter(x=>!blocked.has(x)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,8)){const p=P1[e-s+1];out.push(rect({id:`spine-${z}-${course}-${s}`,file:p[0],name:p[1],x0:s,x1:e,z0:z,z1:z,topY:-104-course*24,color:71,signal:'STRUCTURE',severity:108,weight:e-s+1,label:`BEARING / PRESSURE SPINE z${z} · course ${course}`}))}return out}
function windowPair(id,side,a,b){const z=side==='port'?10:21,r=side==='port'?ID:RY180,t=[CX(a,b),-200,Z(z)],frame=A({id:`${id}-frame`,file:'60593.dat',name:'Window 1 x 2 x 3',t,r,color:71,bottom:cells(a,b,z,z,-128),top:cells(a,b,z,z,-200),minContacts:2,signal:'STRUCTURE',severity:130,weight:8,label:`${side.toUpperCase()} WINDOW FRAME`}),cover=[];for(let c=2;c<=4;c++)for(const x of range(a,b))cover.push(PK(side,c,x));const glass=A({id:`${id}-glass`,file:'60602.dat',name:'Window Glass 1 x 2 x 3',t,r,color:47,bottom:[],top:[],minContacts:0,signal:'PRESSURE',severity:170,weight:34,label:`${side.toUpperCase()} PRESSURE GLASS`,kind:'fit',requires:[frame.id],cover});return[frame,glass]}
function airlock(){const a=31,b=34,z=21,t=[CX(a,b),-248,Z(z)],anchors=[[X(a),-272,Z(z)],[X(b),-272,Z(z)]],frame=A({id:'airlock-frame',file:'60596.dat',name:'Door 1 x 4 x 6 Frame',t,r:RY180,color:71,bottom:[],top:[],minContacts:0,signal:'ACCESS',severity:180,weight:38,label:'STARBOARD AIRLOCK FRAME',kind:'fit',anchors}),cover=[];for(let c=1;c<=6;c++)for(const x of range(a,b))cover.push(PK('starboard',c,x));const leaf=A({id:'airlock-leaf',file:'60616b.dat',name:'Door 1 x 4 x 6 Smooth',t:[t[0]+32,t[1],t[2]-5],r:RY180,color:4,bottom:[],top:[],minContacts:0,signal:'PRESSURE',severity:190,weight:60,label:'AIRLOCK LEAF / PRESSURE SEAL',kind:'fit',requires:[frame.id],cover});return[frame,leaf]}
function wing(side){const port=side==='port',z0=port?4:20,ez=port?5:25,out=[];for(const x0 of [24,28,32,36])out.push(plate48({id:`${side}-wing-${x0}`,x0,z0,topY:-288,color:4,signal:'STRUCTURE',severity:82,weight:24,label:`${side.toUpperCase()} HIGH WING`,minContacts:8,spread:60}));for(const x of [28,36]){out.push(rect({id:`${side}-engine-base-${x}`,file:'3003.dat',name:'Brick 2 x 2',x0:x,x1:x+1,z0:ez,z1:ez+1,topY:-312,color:72,signal:'THRUST',severity:80,weight:12,label:`${side.toUpperCase()} ENGINE MOUNT`,minContacts:4}));for(let c=1;c<=3;c++)out.push(rect({id:`${side}-engine-${x}-${c}`,file:'3941.dat',name:'Brick 2 x 2 Round',x0:x,x1:x+1,z0:ez,z1:ez+1,topY:-312-c*24,color:c===3?4:15,signal:'THRUST',severity:76-c,weight:18,label:`${side.toUpperCase()} VTOL ENGINE · stage ${c}`,minContacts:4}))}return out}
function noseAndSystems(){const out=[];for(const side of ['port','starboard']){const z=side==='port'?10:20,r=side==='port'?ID:RY180;for(const x of [14,16,18])out.push(A({id:`nose-${side}-${x}`,file:'3039.dat',name:'Slope Brick 45 2 x 2',t:[CX(x,x+1),-304,Z(z)],r,color:15,bottom:cells(x,x+1,z,z+1,-280),top:[],minContacts:4,signal:'STRUCTURE',severity:62,weight:6,label:`ANGULAR COCKPIT CLADDING · ${side}`}))}out.push(rect({id:'tail-base',file:'3001.dat',name:'Brick 2 x 4',x0:45,x1:48,z0:14,z1:15,topY:-304,color:4,signal:'STRUCTURE',severity:58,weight:10,label:'DORSAL TAIL BASE',minContacts:8}),A({id:'tail-fin',file:'3039.dat',name:'Slope Brick 45 2 x 2',t:[CX(46,47),-328,CZ(14,15)],r:RY90,color:4,bottom:cells(46,47,14,15,-304),top:[],minContacts:4,signal:'STRUCTURE',severity:54,weight:6,label:'DORSAL TAIL FIN'}),rect({id:'sensor-mast',file:'3941.dat',name:'Brick 2 x 2 Round',x0:25,x1:26,z0:15,z1:16,topY:-304,color:71,signal:'SYSTEMS',severity:44,weight:5,label:'SENSOR MAST',minContacts:4}));return out}
export function pressureTargets(){const set=new Set;for(let c=1;c<=7;c++){for(const x of range(14,49)){set.add(PK('port',c,x));set.add(PK('starboard',c,x))}for(const z of range(10,21)){set.add(PK('bow',c,z));set.add(PK('stern',c,z))}}for(let b=0;b<9;b++){set.add(`P|floorA|${b}`);set.add(`P|floorB|${b}`);set.add(`P|roofA|${b}`);set.add(`P|roofB|${b}`)}return set}
export function makePlan(){serial=0;const a=[];for(const z of [12,15,18])for(let c=1;c<=4;c++)a.push(...keel(z,c));const bays=[14,18,22,26,30,34,38,42,46];for(const [bi,x0] of bays.entries())a.push(plate48({id:`floor-a-${x0}`,x0,z0:10,topY:-104,signal:'PRESSURE',severity:142,weight:32,label:'PRESSURE FLOOR PORT',minContacts:8,spread:60,cover:[`P|floorA|${bi}`]}),plate44({id:`floor-b-${x0}`,x0,z0:18,topY:-104,signal:'PRESSURE',severity:140,weight:24,label:'PRESSURE FLOOR STARBOARD',minContacts:4,spread:60,cover:[`P|floorB|${bi}`]}));
 const portOpen=[{a:23,b:24,from:2,to:4},{a:39,b:40,from:2,to:4}],starOpen=[{a:23,b:24,from:2,to:4},{a:31,b:34,from:1,to:6},{a:39,b:40,from:2,to:4}];for(let c=1;c<=7;c++)a.push(...wall('port',c,portOpen),...wall('starboard',c,starOpen),...wall('bow',c),...wall('stern',c),...spine(15,c),...spine(19,c));for(const [id,s,x0,x1] of [['p1','port',23,24],['p2','port',39,40],['s1','starboard',23,24],['s2','starboard',39,40]])a.push(...windowPair(id,s,x0,x1));a.push(...airlock());for(const [bi,x0] of bays.entries())a.push(plate48({id:`roof-a-${x0}`,x0,z0:10,topY:-280,signal:'PRESSURE',severity:124,weight:36,label:'PRESSURE ROOF PORT',minContacts:8,spread:100,cover:[`P|roofA|${bi}`]}),plate44({id:`roof-b-${x0}`,x0,z0:18,topY:-280,signal:'PRESSURE',severity:122,weight:28,label:'PRESSURE ROOF STARBOARD',minContacts:8,spread:40,cover:[`P|roofB|${bi}`]}));a.push(...wing('port'),...wing('starboard'),...noseAndSystems());return a}
function seed(){const m=new Map;for(let ix=0;ix<64;ix++)for(let iz=0;iz<32;iz++){const p=[X(ix),0,Z(iz)];m.set(K(p),{p,owner:'ORBITAL-YARD'})}return m}
export function stateFor(plan=makePlan()){return{plan,supports:seed(),placedIds:new Set,placements:[],clicks:0,covers:new Set}}
function contacts(action,state){const out=[];for(const p of action.bottom||[]){const s=state.supports.get(K(p));if(s)out.push({p,s})}return out}
export function seat(action,state){if(action.requires.some(id=>!state.placedIds.has(id)))return{ok:false,contacts:[],need:action.minContacts||0,spread:0,reason:'requires'};if(action.kind!=='structure'){if(action.anchors?.length){const ok=action.anchors.every(p=>state.supports.has(K(p)));return{ok,contacts:[],need:action.anchors.length,spread:0,reason:ok?'fit-anchor':'missing-anchor'}}return{ok:true,contacts:[],need:0,spread:0,reason:'fit'};const hits=contacts(action,state),need=action.minContacts||1,xs=hits.map(h=>h.p[0]),zs=hits.map(h=>h.p[2]),spread=Math.max(xs.length?Math.max(...xs)-Math.min(...xs):0,zs.length?Math.max(...zs)-Math.min(...zs):0);return{ok:hits.length>=need&&spread>=(action.minSpread||0),contacts:hits,need,spread,reason:hits.length>=need?'spread':'contacts'}}
export function commit(action,state){const s=seat(action,state);if(!s.ok)return null;state.placedIds.add(action.id);state.placements.push(action);for(const p of action.top||[])state.supports.set(K(p),{p,owner:action.id});for(const c of action.cover||[])state.covers.add(c);if(action.kind==='structure')state.clicks+=s.contacts.length;return{action,contacts:s.contacts,clicks:action.kind==='structure'?s.contacts.length:0}}
export const unresolved=state=>state.plan.filter(a=>!state.placedIds.has(a.id));
export function hear(state){const open=unresolved(state).sort((a,b)=>b.severity-a.severity||b.weight-a.weight),raw=open[0]||null;let choice=null;for(const action of open){const s=seat(action,state);if(s.ok){choice={action,seat:s};break}}return{open,raw,choice}}
export const signalLoad=(state,signal)=>unresolved(state).filter(a=>a.signal===signal).reduce((s,a)=>s+a.weight,0);
export const pressureMissing=state=>[...pressureTargets()].filter(k=>!state.covers.has(k));
export function simulate(plan=makePlan(),limit=5000){const state=stateFor(plan);let moves=0;while(moves<limit){const h=hear(state);if(!h.raw||!h.choice)break;commit(h.choice.action,state);moves++}return{state,moves,remaining:unresolved(state),clicks:state.clicks,pressureMissing:pressureMissing(state)}}
export function toLDraw(state,title='BEAVER-STARSHIP-I'){const f=n=>Math.abs(n)<1e-9?'0':Number(n.toFixed(6)).toString(),lines=[`0 ${title}`,`0 Name: ${title}.mpd`,`0 !LDRAW_ORG Model`,`0 // Actual Beaver loop: support -> pressure -> access -> thrust.`,`1 2 -320 0 0 1 0 0 0 1 0 0 0 1 3811.dat`,`1 2 320 0 0 1 0 0 0 1 0 0 0 1 3811.dat`];for(const a of state.placements)lines.push(`1 ${a.color??16} ${f(a.t[0])} ${f(a.t[1])} ${f(a.t[2])} ${(a.r||ID).map(f).join(' ')} ${a.file}`);return lines.join('\n')+'\n'}
