export const ID=[1,0,0,0,1,0,0,0,1],RY90=[0,0,1,0,1,0,-1,0,0],RY180=[-1,0,0,0,1,0,0,0,-1],RY270=[0,0,-1,0,1,0,1,0,0];
export const DESIGN={name:'BEAVER STARSHIP I',site:'64×32 stud orbital yard / two 3811 baseplates',ship:'36×12 stud pressure hull · six brick courses',systems:'central keel · pressure spine · twin wings · twin engine pods · cockpit glazing · airlock',principle:'No spaceship likeness completion. Gravity/support, pressure, access and thrust must all go quiet through physically reachable parts.'};
const X=i=>-630+i*20,Z=i=>-310+i*20,CX=(a,b)=>(X(a)+X(b))/2,CZ=(a,b)=>(Z(a)+Z(b))/2,range=(a,b)=>Array.from({length:b-a+1},(_,i)=>a+i),key=p=>p.map(v=>Math.round(v*1000)).join('|');
let serial=0;
const P1={1:['3005.dat','Brick 1 x 1'],2:['3004.dat','Brick 1 x 2'],3:['3622.dat','Brick 1 x 3'],4:['3010.dat','Brick 1 x 4'],6:['3009.dat','Brick 1 x 6'],8:['3008.dat','Brick 1 x 8']},P2={1:['3004.dat','Brick 1 x 2'],2:['3003.dat','Brick 2 x 2'],3:['3002.dat','Brick 2 x 3'],4:['3001.dat','Brick 2 x 4']};
const cells=(x0,x1,z0,z1,y)=>{const out=[];for(let x=x0;x<=x1;x++)for(let z=z0;z<=z1;z++)out.push([X(x),y,Z(z)]);return out};
const base=o=>({placed:false,requires:[],signal:'STRUCTURE',severity:50,weight:1,color:15,cover:[],kind:'structure',...o,id:o.id||`s${++serial}`});
function rect({id,file,name,x0,x1,z0,z1,topY,height=24,r=ID,color=15,minContacts,spread=0,signal='STRUCTURE',severity=60,weight=1,label,requires=[],cover=[]}){const bottom=cells(x0,x1,z0,z1,topY+height),top=cells(x0,x1,z0,z1,topY);return base({id,file,name,t:[CX(x0,x1),topY,CZ(z0,z1)],r,color,bottom,top,minContacts:minContacts??bottom.length,minSpread:spread,signal,severity,weight,label,requires,cover});}
function contiguous(vals){if(!vals.length)return[];const a=[...vals].sort((x,y)=>x-y),out=[];let s=a[0],p=a[0];for(let i=1;i<a.length;i++){if(a[i]===p+1){p=a[i];continue}out.push([s,p]);s=p=a[i]}out.push([s,p]);return out}
function tile(a,b,course,max=4){const out=[];let p=a,first=course%2?3:4;while(p<=b){let n=[first,max,4,3,2,1].find(n=>n<=max&&p+n-1<=b);if(!n)n=1;out.push([p,p+n-1]);p+=n;first=max}return out}
const pressureKey=(side,course,i)=>`P|${side}|${course}|${i}`;
function sideWall({side,z,course,x0=14,x1=49,openings=[],color=15}){const blocked=new Set(openings.filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b))),vals=range(x0,x1).filter(x=>!blocked.has(x)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,4)){const n=e-s+1,p=P1[n],cover=range(s,e).map(i=>pressureKey(side,course,i));out.push(rect({file:p[0],name:p[1],x0:s,x1:e,z0:z,z1:z,topY:-104-course*24,color,signal:'PRESSURE',severity:90,weight:n,label:`${side.toUpperCase()} PRESSURE HULL · course ${course}`,cover}))}return out}
function endWall({side,x,course,z0=10,z1=21,openings=[],color=15}){const blocked=new Set(openings.filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b))),vals=range(z0,z1).filter(z=>!blocked.has(z)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,4)){const n=e-s+1,p=P1[n],cover=range(s,e).map(i=>pressureKey(side,course,i));out.push(rect({file:p[0],name:p[1],x0:x,x1:x,z0:s,z1:e,topY:-104-course*24,r:RY90,color,signal:'PRESSURE',severity:92,weight:n,label:`${side.toUpperCase()} PRESSURE BULKHEAD · course ${course}`,cover}))}return out}
function plate48({id,x0,z0,topY,signal='STRUCTURE',severity=100,weight=28,label='PLATE 4×8',color=71,minContacts=8,spread=60,r=ID,cover=[]}){return rect({id,file:'3035.dat',name:'Plate 4 x 8',x0,x1:x0+3,z0,z1:z0+7,topY,height:8,r,color,signal,severity,weight,label,minContacts,spread,cover})}
function keelRail(z,course){const out=[];for(const [a,b] of tile(14,49,course,8)){const p=P1[b-a+1];out.push(rect({id:`keel-${z}-${course}-${a}`,file:p[0],name:p[1],x0:a,x1:b,z0:z,z1:z,topY:-course*24,color:72,signal:'GRAVITY',severity:130,weight:b-a+1,label:`KEEL RAIL z${z} · course ${course}`}))}return out}
function centerSpine(course){const holes=[{a:27,b:30,from:1,to:3}],blocked=new Set(holes.filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b))),vals=range(16,47).filter(x=>!blocked.has(x)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,8)){const p=P1[e-s+1];out.push(rect({id:`spine-${course}-${s}`,file:p[0],name:p[1],x0:s,x1:e,z0:15,z1:15,topY:-104-course*24,color:71,signal:'STRUCTURE',severity:98,weight:e-s+1,label:`PRESSURE / ROOF SPINE · course ${course}`}))}return out}
function windowPair({id,side,a,b,bottomY=-128}){const z=side==='port'?10:21,r=side==='port'?ID:RY180,t=[CX(a,b),bottomY-72,Z(z)],bottom=cells(a,b,z,z,bottomY),top=cells(a,b,z,z,bottomY-72),frame=base({id:`${id}-frame`,file:'60593.dat',name:'Window 1 x 2 x 3',t,r,color:71,bottom,top,minContacts:2,signal:'STRUCTURE',severity:110,weight:6,label:`${side.toUpperCase()} CABIN WINDOW FRAME`}),cover=[];for(let c=2;c<=4;c++)for(const i of range(a,b))cover.push(pressureKey(side,c,i));const glass=base({id:`${id}-glass`,file:'60602.dat',name:'Window Glass 1 x 2 x 3',t,r,color:47,bottom:[],top:[],minContacts:0,signal:'PRESSURE',severity:136,weight:30,label:`${side.toUpperCase()} CABIN GLAZING`,kind:'fit',requires:[frame.id],cover});return[frame,glass]}
function airlock({a=31,b=34}){const z=21,frameT=[CX(a,b),-248,Z(z)],frame=base({id:'airlock-frame',file:'60596.dat',name:'Door 1 x 4 x 6 Frame',t:frameT,r:RY180,color:71,bottom:[],top:[],minContacts:0,signal:'ACCESS',severity:140,weight:32,label:'STARBOARD AIRLOCK FRAME',kind:'fit',requires:['airlock-lintel']}),cover=[];for(let c=1;c<=6;c++)for(const i of range(a,b))cover.push(pressureKey('starboard',c,i));const leaf=base({id:'airlock-leaf',file:'60616b.dat',name:'Door 1 x 4 x 6 Smooth',t:[frameT[0]+32,frameT[1],frameT[2]-5],r:RY180,color:4,bottom:[],top:[],minContacts:0,signal:'PRESSURE',severity:150,weight:50,label:'AIRLOCK LEAF / PRESSURE SEAL',kind:'fit',requires:[frame.id],cover});return[frame,leaf]}
function wing({side}){const port=side==='port',zRoot=port?7:22,zOuter=port?0:26,out=[];for(const x0 of [24,28,32,36])out.push(plate48({id:`${side}-wing-${x0}`,x0,z0:port?0:22,topY:-120,color:4,signal:'STRUCTURE',severity:85,weight:22,label:`${side.toUpperCase()} WING PANEL`,minContacts:4,spread:40,r:ID}));for(const x of [26,34])out.push(rect({id:`${side}-root-${x}`,file:'3001.dat',name:'Brick 2 x 4',x0:x,x1:x+3,z0:port?8:20,z1:port?9:21,topY:-128,color:72,signal:'STRUCTURE',severity:104,weight:16,label:`${side.toUpperCase()} WING ROOT`,minContacts:8}));for(const x of [28,36]){out.push(rect({id:`${side}-engine-base-${x}`,file:'3003.dat',name:'Brick 2 x 2',x0:x,x1:x+1,z0:port?2:27,z1:port?3:28,topY:-144,color:72,signal:'THRUST',severity:72,weight:10,label:`${side.toUpperCase()} ENGINE PYLON`,minContacts:4}));for(let c=1;c<=3;c++)out.push(rect({id:`${side}-engine-${x}-${c}`,file:'3941.dat',name:'Brick 2 x 2 Round',x0:x,x1:x+1,z0:port?2:27,z1:port?3:28,topY:-144-c*24,color:c===3?4:15,signal:'THRUST',severity:70,weight:14,label:`${side.toUpperCase()} ENGINE POD · stage ${c}`,minContacts:4}))}return out}
function slopeCladding(){const out=[];for(const side of ['port','starboard']){const z=side==='port'?10:20,r=side==='port'?ID:RY180;for(const x of [14,16,18])out.push(base({id:`nose-${side}-${x}`,file:'3039.dat',name:'Slope Brick 45 2 x 2',t:[CX(x,x+1),-272,Z(z)],r,color:15,bottom:cells(x,x+1,z,z+1,-248),top:[],minContacts:4,signal:'PRESSURE',severity:75,weight:6,label:`COCKPIT NOSE CLADDING · ${side}`,kind:'structure'}))}return out}
function antennaAndTail(){return[
 rect({id:'tail-base',file:'3001.dat',name:'Brick 2 x 4',x0:45,x1:48,z0:14,z1:15,topY:-280,color:4,signal:'STRUCTURE',severity:54,weight:10,label:'DORSAL TAIL BASE',minContacts:8}),
 base({id:'tail-slope-a',file:'3039.dat',name:'Slope Brick 45 2 x 2',t:[CX(46,47),-304,CZ(14,15)],r:RY90,color:4,bottom:cells(46,47,14,15,-280),top:[],minContacts:4,signal:'STRUCTURE',severity:50,weight:5,label:'DORSAL TAIL FIN',kind:'structure'}),
 rect({id:'sensor-mast',file:'3941.dat',name:'Brick 2 x 2 Round',x0:25,x1:26,z0:15,z1:16,topY:-280,color:71,signal:'SYSTEMS',severity:42,weight:4,label:'SENSOR MAST BASE',minContacts:4})
]}
export function pressureTargets(){const set=new Set,openPort=[{a:23,b:24,from:2,to:4},{a:39,b:40,from:2,to:4}],openStar=[{a:23,b:24,from:2,to:4},{a:31,b:34,from:1,to:6},{a:39,b:40,from:2,to:4}];for(let c=1;c<=6;c++){for(const x of range(14,49)){if(!openPort.some(h=>c>=h.from&&c<=h.to&&x>=h.a&&x<=h.b))set.add(pressureKey('port',c,x));if(!openStar.some(h=>c>=h.from&&c<=h.to&&x>=h.a&&x<=h.b))set.add(pressureKey('starboard',c,x))}for(const z of range(10,21)){set.add(pressureKey('bow',c,z));set.add(pressureKey('stern',c,z))}}for(const h of openPort)for(let c=h.from;c<=h.to;c++)for(const x of range(h.a,h.b))set.add(pressureKey('port',c,x));for(const h of openStar)for(let c=h.from;c<=h.to;c++)for(const x of range(h.a,h.b))set.add(pressureKey('starboard',c,x));for(const bay of range(0,8))set.add(`P|roof|${bay}`);return set}
export function makePlan(){serial=0;const a=[];for(const z of [12,15,18])for(let c=1;c<=4;c++)a.push(...keelRail(z,c));for(const x0 of [14,18,22,26,30,34,38,42,46]){a.push(plate48({id:`floor-a-${x0}`,x0,z0:10,topY:-104,signal:'GRAVITY',severity:118,weight:30,label:'PRESSURE FLOOR A',minContacts:8,spread:60}),plate48({id:`floor-b-${x0}`,x0,z0:14,topY:-104,signal:'GRAVITY',severity:116,weight:30,label:'PRESSURE FLOOR B',minContacts:8,spread:60}))}
 const portOpen=[{a:23,b:24,from:2,to:4},{a:39,b:40,from:2,to:4}],starOpen=[{a:23,b:24,from:2,to:4},{a:31,b:34,from:1,to:6},{a:39,b:40,from:2,to:4}];for(let c=1;c<=6;c++){a.push(...sideWall({side:'port',z:10,course:c,openings:portOpen}),...sideWall({side:'starboard',z:21,course:c,openings:starOpen}),...endWall({side:'bow',x:14,course:c}),...endWall({side:'stern',x:49,course:c}),...centerSpine(c))}
 for(const spec of [['p1','port',23,24],['p2','port',39,40],['s1','starboard',23,24],['s2','starboard',39,40]])a.push(...windowPair({id:spec[0],side:spec[1],a:spec[2],b:spec[3]}));a.push(rect({id:'airlock-lintel',file:'3008.dat',name:'Brick 1 x 8',x0:29,x1:36,z0:21,z1:21,topY:-272,color:71,signal:'STRUCTURE',severity:126,weight:18,label:'AIRLOCK LINTEL / BOTH JAMBS',minContacts:4,spread:120}),...airlock());
 for(const x0 of [14,18,22,26,30,34,38,42]){a.push(plate48({id:`roof-a-${x0}`,x0,z0:10,topY:-256,signal:'PRESSURE',severity:108,weight:34,label:'PRESSURE ROOF PORT',minContacts:8,spread:60,cover:[`P|roof|${(x0-14)/4}`]}),plate48({id:`roof-b-${x0}`,x0,z0:14,topY:-256,signal:'PRESSURE',severity:106,weight:34,label:'PRESSURE ROOF STARBOARD',minContacts:8,spread:60}))}
 a.push(...slopeCladding(),...wing({side:'port'}),...wing({side:'starboard'}),...antennaAndTail());return a}
function seedSupports(){const m=new Map;for(let ix=0;ix<64;ix++)for(let iz=0;iz<32;iz++)m.set(key([X(ix),0,Z(iz)]),{p:[X(ix),0,Z(iz)],owner:'YARD',used:false});return m}
export function stateFor(plan=makePlan()){return{plan,supports:seedSupports(),placedIds:new Set,placements:[],clicks:0,covers:new Set}}
function contactSet(action,state){const hits=[];for(const p of action.bottom||[]){const s=state.supports.get(key(p));if(s)hits.push({p,s})}return hits}
export function seat(action,state){if(action.kind!=='structure')return{ok:action.requires.every(id=>state.placedIds.has(id)),contacts:[],need:0,spread:0};if(action.requires.some(id=>!state.placedIds.has(id)))return{ok:false,contacts:[],need:action.minContacts||1,spread:0};const hits=contactSet(action,state),need=action.minContacts||1,xs=hits.map(h=>h.p[0]),zs=hits.map(h=>h.p[2]),spread=Math.max(xs.length?Math.max(...xs)-Math.min(...xs):0,zs.length?Math.max(...zs)-Math.min(...zs):0);return{ok:hits.length>=need&&spread>=(action.minSpread||0),contacts:hits,need,spread}}
export function commit(action,state){const s=seat(action,state);if(!s.ok)return null;action.placed=true;state.placedIds.add(action.id);state.placements.push(action);for(const p of action.top||[])state.supports.set(key(p),{p,owner:action.id,used:false});for(const c of action.cover||[])state.covers.add(c);if(action.kind==='structure'){state.clicks+=s.contacts.length}return{action,clicks:action.kind==='structure'?s.contacts.length:0,contacts:s.contacts}}
export function unresolved(state){return state.plan.filter(a=>!state.placedIds.has(a.id))}
export function hear(state){const open=unresolved(state).sort((a,b)=>b.severity-a.severity||b.weight-a.weight),raw=open[0]||null;let choice=null;for(const action of open){const s=seat(action,state);if(s.ok){choice={action,seat:s};break}}return{open,raw,choice}}
export function signalLoad(state,signal){return unresolved(state).filter(a=>a.signal===signal).reduce((s,a)=>s+a.weight,0)}
export function pressureMissing(state){return[...pressureTargets()].filter(k=>!state.covers.has(k))}
export function simulate(plan=makePlan(),limit=5000){const state=stateFor(plan);let moves=0;while(moves<limit){const h=hear(state);if(!h.raw)break;if(!h.choice)break;commit(h.choice.action,state);moves++}return{state,moves,remaining:unresolved(state),clicks:state.clicks,pressureMissing:pressureMissing(state)}}
export function toLDraw(state,title='BEAVER-STARSHIP-I'){const fmt=n=>Math.abs(n)<1e-9?'0':Number(n.toFixed(6)).toString(),lines=[`0 ${title}`,`0 Name: ${title}.mpd`,`0 !LDRAW_ORG Model`,`0 // Beaver-built spaceship: real LDraw parts, live support graph, pressure/access/thrust signals.`,'1 2 -320 0 0 1 0 0 0 1 0 0 0 1 3811.dat','1 2 320 0 0 1 0 0 0 1 0 0 0 1 3811.dat'];for(const a of state.placements){lines.push(`1 ${a.color??16} ${fmt(a.t[0])} ${fmt(a.t[1])} ${fmt(a.t[2])} ${(a.r||ID).map(fmt).join(' ')} ${a.file}`)}return lines.join('\n')+'\n'}
