/* Unidentified Item: the existing short retargeted into the authored Butter shop. */
const takeClamp=x=>Math.max(0,Math.min(1,x));
const takeEase=x=>{x=takeClamp(x);return x*x*(3-2*x)};
const takeU=(t,a,b)=>takeEase((t-a)/(b-a));
const takeMix=(a,b,u)=>a+(b-a)*u;
const takeP=(x,y,z)=>V(x*.72,(y+4)*.72,(z+10)*.72);
const takeLerp=(a,b,u)=>a.clone().lerp(b,u);
function takeTrack(t,keys){if(t<=keys[0][0])return keys[0][1];for(let i=1;i<keys.length;i++)if(t<=keys[i][0])return takeMix(keys[i-1][1],keys[i][1],takeU(t,keys[i-1][0],keys[i][0]));return keys.at(-1)[1];}
const takeShots=[
 {start:0,end:3,name:'Everyday, on the corner',pos:[1160,700,1030],target:[0,380,0],fov:36,wide:true},
 {start:3,end:7,name:'One item, one beep',pos:[140,195,-250],target:[-48,86,0],fov:37},
 {start:7,end:10,name:'Next item',pos:[15,112,-128],target:[-61,62,-25],fov:34},
 {start:10,end:14,name:'The first refusal',pos:[65,135,-157],target:[-88,81,-40],fov:34},
 {start:14,end:18,name:'A professional considers',pos:[20,127,-155],target:[-96,85,-55],fov:33},
 {start:18,end:23,name:'Try the other way',pos:[30,125,-145],target:[-72,73,-31],fov:33},
 {start:23,end:27,name:'Someone else understands',pos:[-140,165,-175],target:[-4,95,25],fov:37},
 {start:27,end:32,name:'A small intervention',pos:[-65,118,-66],target:[-30,81,45],fov:34},
 {start:32,end:35,name:'Accepted',pos:[85,116,-85],target:[-38,88,-30],fov:32},
 {start:35,end:39,name:'The lesson',pos:[110,180,-200],target:[-45,85,5],fov:37},
 {start:39,end:43,name:'Business resumes',pos:[140,195,-250],target:[-48,86,0],fov:37},
 {start:43,end:46,name:'The wrong lesson',pos:[30,125,-145],target:[-89,75,-36],fov:34},
 {start:46,end:48,name:'End',pos:[1160,700,1030],target:[0,380,0],fov:36,wide:true}
];
const takePanel=document.createElement('div');takePanel.id='takePanel';takePanel.hidden=true;takePanel.innerHTML='<div><button id="takePlay" aria-label="Play Unidentified Item">Play film</button><select id="takeShot" aria-label="Film shot"></select><button id="takeSound" aria-label="Mute film sound" aria-pressed="false">Sound on</button></div><div><input id="takeTime" type="range" min="0" max="48" step="0.04" value="0" aria-label="Film time"><output id="takeClock">0:00 / 0:48</output></div>';chat.prepend(takePanel);
for(const [i,s]of takeShots.entries())$('#takeShot').add(new Option((i+1)+' · '+s.name,i));
const takeTitle=document.createElement('canvas');takeTitle.id='takeTitle';takeTitle.width=1280;takeTitle.height=720;stage.append(takeTitle);
const takeAudio=new Audio(window.GrocerTakeSound);takeAudio.preload='auto';
let takeActive=false,takePlaying=false,takeTime=0,takeStarted=0,takeOffset=0,takeSaved=null,takeCast=null,takeAssets=null,takeLastWide=null,takeAudioPending=false;
const takeGroup=new THREE.Group();takeGroup.name='Unidentified Item performance props';takeGroup.visible=false;scene.add(takeGroup);
const takeMaterials=new Map();function takeMat(hex){if(!takeMaterials.has(hex))takeMaterials.set(hex,new THREE.MeshStandardMaterial({color:new THREE.Color(hex).convertSRGBToLinear(),roughness:.57,metalness:0}));return takeMaterials.get(hex);}
function takeMesh(geometry,color,parent=takeGroup){const m=new THREE.Mesh(geometry,takeMat(color));parent.add(m);return m;}
function takeBox(w,h,d,color,x,y,z,parent){const m=takeMesh(new THREE.BoxGeometry(w,h,d),color,parent);m.position.set(x,y,z);return m;}
function takeNative(name){const d=window.GrocerTakeAssets[name],b=Uint8Array.from(atob(d.vertices),c=>c.charCodeAt(0)),p=new Float32Array(b.buffer),rgb=Uint8Array.from(atob(d.colors),c=>c.charCodeAt(0)),col=new Float32Array(p.length);for(let i=0;i<rgb.length/3;i++){const c=new THREE.Color(rgb[i*3]/255,rgb[i*3+1]/255,rgb[i*3+2]/255).convertSRGBToLinear();for(let j=0;j<3;j++)col.set([c.r,c.g,c.b],i*9+j*3);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(col,3));g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.6,side:THREE.DoubleSide}));m.scale.setScalar(.72);takeGroup.add(m);return m;}
function takeLabel(){const c=document.createElement('canvas');c.width=512;c.height=192;const ctx=c.getContext('2d'),tex=new THREE.CanvasTexture(c),m=new THREE.Mesh(new THREE.PlaneGeometry(35*.72,13.125*.72),new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide}));takeGroup.add(m);m.position.copy(takeP(-38,88,-30));m.rotation.y=Math.PI/2;m.userData.draw=word=>{ctx.fillStyle='#12302b';ctx.fillRect(0,0,512,192);ctx.fillStyle=word==='UNKNOWN'?'#ffbb72':'#c7efd0';ctx.font='bold 55px monospace';ctx.textAlign='center';ctx.fillText(word,256,115);tex.needsUpdate=true;};return m;}
function takeMakeAssets(){if(takeAssets)return;const buggy=takeNative('buggy'),apple=takeNative('apple'),apple2=takeNative('apple');apple.scale.multiplyScalar(.5);apple2.scale.multiplyScalar(.5);buggy.position.copy(takeP(15,8,57));buggy.rotation.y=-Math.PI/2;
 const duck=new THREE.Group();takeGroup.add(duck);const body=takeMesh(new THREE.SphereGeometry(19,16,12),'#efba25',duck);body.scale.set(1,.68,.68);body.position.y=12;const head=takeMesh(new THREE.SphereGeometry(12,16,12),'#efba25',duck);head.position.set(10,31,0);takeBox(15,5,14,'#eb732c',23,28,0,duck);const tail=takeBox(12,6,10,'#efba25',-15,21,0,duck);tail.rotation.z=-.3;for(const z of [-10.1,10.1]){const e=takeMesh(new THREE.SphereGeometry(1.8,8,6),'#22292d',duck);e.position.set(13,34,z);}duck.scale.setScalar(.72*.43);
 const scanner=takeMesh(new THREE.PlaneGeometry(15*.72,22*.72),'#ed7c54');scanner.rotation.x=-Math.PI/2;scanner.position.copy(takeP(-50,64.1,-28));const display=takeLabel();const housing=takeBox(3*.72,16*.72,38*.72,'#21352c',0,0,0);housing.position.copy(takeP(-40,88,-30));const stem=takeBox(4*.72,17*.72,4*.72,'#21352c',0,0,0);stem.position.copy(takeP(-42,72,-30));
 const drops=[];for(let i=0;i<7;i++)drops.push(takeMesh(new THREE.SphereGeometry(1.1*.72,6,4),'#e8b650'));
 takeAssets={buggy,apple,apple2,duck,scanner,display,housing,stem,drops};
}
function takeRememberRig(entry){const rig=entry.rig,joints={};for(const key of ['hipsP','torsoP','headP','armLP','armRP','legLP','legRP']){const p=rig[key];joints[key]={pos:p.position.clone(),rot:p.rotation.clone()};}return {entry,rig,pos:rig.pos.clone(),heading:rig.heading,scale:rig.figure.scale.clone(),rotation:rig.figure.rotation.clone(),visible:rig.figure.visible,joints};}
function takeResetRig(a){const r=a.rig;for(const [k,b]of Object.entries(a.joints)){r[k].position.copy(b.pos);r[k].rotation.copy(b.rot);}r.figure.rotation.set(0,r.heading,0);r.figure.visible=true;}
function takeRestoreRig(a){takeResetRig(a);a.rig.pos.copy(a.pos);a.rig.heading=a.heading;a.rig.figure.rotation.copy(a.rotation);a.rig.figure.scale.copy(a.scale);a.rig.figure.visible=a.visible;}
function takeStart(){if(takeActive)return;const get=kind=>ButterCast.cast.find(a=>a.kind===kind);const cash=get('citizen'),marge=get('movieator-marge'),baby=get('movieator-maggie');if(!cash||!marge||!baby)throw Error('The take needs the cashier, Marge and Maggie. Open an unmodified copy of the grocery location.');takeMakeAssets();takeSaved={helpers:ButterSpatialRuntime.plate.children.filter(o=>!S.parts.some(p=>p.mesh===o)&&!ButterCast.cast.some(a=>a.rig.figure===o)).map(o=>({o,visible:o.visible})),actors:ButterCast.cast.map(takeRememberRig),performer:{on:ButterPerformer.state.on,destination:ButterPerformer.state.destination,follow:ButterPerformer.state.follow},view:locationView,camera:filmCamera(),background:scene.background.clone(),toneMapping:renderer.toneMapping,exposure:renderer.toneMappingExposure};takeCast={cash:takeSaved.actors.find(a=>a.entry===cash),marge:takeSaved.actors.find(a=>a.entry===marge),baby:takeSaved.actors.find(a=>a.entry===baby)};takeActive=true;takeMakeFace(cash.rig);takeLastWide=null;ButterPerformer.state.on=false;ButterPerformer.state.destination=null;ButterPerformer.state.follow=false;takeGroup.visible=true;document.body.classList.add('take-active');takePanel.hidden=false;takeTitle.hidden=false;$('#filmPanel').hidden=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;takeSeek(takeTime);}
function takeStop(){takePlaying=false;takeAudio.pause();$('#takePlay').textContent=takeTime>=48?'Replay':'Play film';}
function takeLeave(){if(!takeActive)return;takeStop();for(const a of takeSaved.actors)if(ButterCast.cast.includes(a.entry))takeRestoreRig(a);Object.assign(ButterPerformer.state,takeSaved.performer);if(takeFace){takeFace.parent?.remove(takeFace);takeFace.geometry.dispose();takeFace.material.map.dispose();takeFace.material.dispose();takeFace=null;}for(const h of takeSaved.helpers)h.o.visible=h.visible;takeActive=false;takeGroup.visible=false;takePanel.hidden=true;takeTitle.hidden=true;document.body.classList.remove('take-active');locationView=takeSaved.view;locationSelect.value=locationView;for(const p of S.parts){p.mesh.material.clipIntersection=false;p.mesh.material.clippingPlanes=[];}locationApply();renderer.toneMapping=takeSaved.toneMapping;renderer.toneMappingExposure=takeSaved.exposure;scene.background.copy(takeSaved.background);filmSetCamera(takeSaved.camera);takeSaved=null;takeCast=null;}
function takeRoom(wide){if(takeLastWide===wide)return;takeLastWide=wide;for(const p of S.parts){const d=catalog.get(p.part);if(!d?.layer)continue;p.mesh.visible=wide||d.layer==='shop';p.mesh.material.vertexColors=true;p.mesh.material.color.setHex(0xffffff);p.mesh.material.emissive?.setHex(0);locationUseWholePieces(p,!wide);}}

function takeHand(rig){rig.figure.updateMatrixWorld(true);return rig.slots.handR.localToWorld(V(0,-.8229,-9.8948));}
function takeAt(object,p){object.position.copy(p);}
function takePose(t){const {cash,marge,baby}=takeCast;for(const a of [cash,marge,baby])takeResetRig(a);const c=cash.rig,m=marge.rig,b=baby.rig;
 c.pos.copy(takeP(-124,8,t<23?-30:takeMix(-30,42,takeU(t,23,27))));if(t>=35)c.pos.z=takeP(0,0,takeMix(42,-30,takeU(t,35,39))).z;c.heading=Math.PI/2;c.figure.rotation.y=c.heading;c.figure.scale.setScalar(.72);
 m.pos.copy(takeP(4,8,-25));m.heading=-Math.PI/2;m.figure.rotation.y=m.heading;m.figure.scale.setScalar(.72);
 b.pos.copy(takeP(15,43,57));b.heading=-Math.PI/2;b.figure.rotation.y=b.heading;b.figure.scale.setScalar(.72*.62);b.headP.position.y+=18;
 // Hinged reaches and held props derive from the same hand frame, not independent trajectories.
 c.armRP.rotation.x=takeTrack(t,[[0,-.1],[3.1,-.1],[3.6,-.95],[5.7,-.95],[7,-.1],[8,-.1],[9.5,-.95],[13.8,-.95],[14.5,-2.1],[17.7,-2.1],[18.2,-1.65],[22.5,-1.65],[24,-1.05],[31.7,-1.05],[33,-.85],[35,-.85],[36,-.35],[39,-.35],[40,-.95],[42.7,-.95],[43.3,-2.0]]);if(t>=18&&t<23)c.armRP.rotation.x-=.18*Math.sin((t-18)*Math.PI*2);
 c.armLP.rotation.x=t>=43?-.5:t>=35&&t<39?-.45:0;c.headP.rotation.y=t>=23&&t<35?-.28:0;c.headP.rotation.z=t>=14&&t<18?.15:t>=43?.13:0;
 if(t>=14&&t<18)c.headP.rotation.x=.1;
 if(t>=23&&t<27){m.headP.rotation.z=-.13*takeU(t,23,24);m.armLP.rotation.x=-.7*takeU(t,23,24);b.headP.rotation.y=.22*takeU(t,24,25);}
 if(t>=27&&t<32){b.armRP.rotation.x=-1.2*takeU(t,27.5,28.8);b.torsoP.rotation.x=-.12*takeU(t,27,29);b.headP.rotation.x=.15;}
 if(t>=35&&t<39){m.headP.rotation.z=.12*Math.sin((t-35)*2);m.armLP.rotation.x=-.35;c.headP.rotation.x=-.12;}
 if(t>=43){b.headP.rotation.z=.12*Math.sin((t-44)*3)*takeU(t,44,45);m.headP.rotation.z=-.12*takeU(t,44,45);}
 const hand=takeHand(c),{apple,apple2,duck,scanner,display,drops}=takeAssets;
 const held=hand.clone().add(V(0,-42.71*.36,0));
 apple.visible=t<7;apple.rotation.set(0,0,0);takeAt(apple,t<3.6?takeP(-65,64,25):t<5.7?held:takeLerp(held,takeP(-65,64.5,25),takeU(t,5.7,7)));
 apple2.visible=true;apple2.scale.set(.36,.36*(t>=44?takeMix(1,.35,takeU(t,44.15,44.5)):1),.36);takeAt(apple2,t<42?takeP(-65,64,5):held);apple2.rotation.z=t>=44?.15:0;
 duck.visible=t<40.6;duck.rotation.set(0,0,0);duck.scale.set(.72*.43,.72*.43*(t>=29&&t<29.6?.8:1),.72*.43);
 const duckHeld=hand.clone().add(V(7*.72,-5*.72,0));
 if(t<8)takeAt(duck,takeP(-65,64.5,-15));else if(t<9.5)takeAt(duck,takeLerp(takeP(-65,64.5,-15),duckHeld,takeU(t,8,9.5)));else if(t<27)takeAt(duck,duckHeld);else if(t<28.8)takeAt(duck,takeLerp(duckHeld,takeP(-40,58,48),takeU(t,27,28.8)));else if(t<31.7)takeAt(duck,takeP(-40,58,48));else if(t<33)takeAt(duck,takeLerp(takeP(-40,58,48),duckHeld,takeU(t,31.7,33)));else if(t<39)takeAt(duck,duckHeld);else takeAt(duck,takeLerp(duckHeld,takeP(-65,64.5,25),takeU(t,39,40.6)));
 if(t>=18&&t<23)duck.rotation.y=Math.PI*Math.sin((t-18)*1.7);
 for(const [i,o]of drops.entries()){const u=t-44.2;o.visible=u>0&&u<.65;o.position.copy(held).add(V((i-3)*u*10,u*20-u*u*65,u*15*(i%2?1:-1)));}
 const word=t<5.3?'READY':t<10.6?'1.20':t<29.9?'UNKNOWN':t<40?'0.50':'READY';if(display.userData.word!==word){display.userData.word=word;display.userData.draw(word);}scanner.material=takeMat(t>=10.6&&t<29.9?'#d35132':'#85c47a');
 takeDrawFace(t);return {hand:hand.toArray(),heldApple:t>=3.5&&t<5.7||t>=42,heldDuck:t>=9.5&&t<27||t>=33&&t<39};
}
function takeTitles(t,ctx,w=1280,h=720){ctx.clearRect(0,0,w,h);const scale=w/1280;ctx.save();ctx.scale(scale,scale);if(t<3){const a=Math.min(takeU(t,0,.4),1-takeU(t,2.4,3));ctx.globalAlpha=a;ctx.fillStyle='#102019bb';ctx.fillRect(48,610,455,75);ctx.fillStyle='#f5e8cc';ctx.font='14px system-ui';ctx.fillText('FILM BUTTER',66,635);ctx.font='600 29px system-ui';ctx.fillText('UNIDENTIFIED ITEM',64,671);}if(t>=46){ctx.globalAlpha=takeU(t,46,46.25);ctx.fillStyle='#122720';ctx.fillRect(0,0,1280,720);ctx.fillStyle='#f5e8cc';ctx.textAlign='center';ctx.font='600 37px system-ui';ctx.fillText('UNIDENTIFIED ITEM',640,310);ctx.font='18px system-ui';ctx.fillText('Film Butter · Watson Hartsoe',640,359);ctx.font='14px system-ui';ctx.fillText('Green Grocer model: Max Martin Richter and credited revisers',640,409);ctx.fillText('LDraw contributors · Existing cast and original synthesized sound',640,438);}ctx.restore();}
function takePaint(){const shot=takeShots.findIndex(s=>takeTime>=s.start&&takeTime<s.end);$('#takeShot').value=shot<0?takeShots.length-1:shot;$('#takeTime').value=takeTime;$('#takeClock').textContent='0:'+String(Math.floor(takeTime)).padStart(2,'0')+' / 0:48';$('#takePlay').textContent=takePlaying?'Pause':takeTime>=48?'Replay':'Play film';}
function takeSeek(t){if(!takeActive)return;for(const h of takeSaved.helpers)h.o.visible=false;takeTime=Math.max(0,Math.min(48,t));const shot=takeShots.find(s=>takeTime>=s.start&&takeTime<s.end)||takeShots.at(-1);takeRoom(!!shot.wide);takePose(takeTime);camera.aspect=16/9;camera.fov=shot.fov;camera.near=2;camera.far=3000;camera.position.copy(takeP(...shot.pos));controls.target.copy(takeP(...shot.target));camera.up.set(0,1,0);camera.lookAt(controls.target);camera.updateProjectionMatrix();camera.updateMatrixWorld(true);controls.enabled=false;scene.background.setHex(0x15231e);takeTitles(takeTime,takeTitle.getContext('2d'));takePaint();}
async function takePlay(){if(!takeActive)return;if(takePlaying){takeStop();return;}if(takeTime>=48)takeSeek(0);takeAudio.currentTime=takeTime;takeOffset=takeTime;takeStarted=performance.now();takePlaying=true;takeAudioPending=true;try{await takeAudio.play();}catch{note('Sound could not start. Use Sound on to retry.','FILM');}finally{takeAudioPending=false;}takePaint();}
$('#takePlay').onclick=takePlay;$('#takeTime').oninput=e=>{takeStop();takeSeek(+e.target.value);};$('#takeShot').onchange=e=>{takeStop();takeSeek(takeShots[+e.target.value].start);};$('#takeSound').onclick=()=>{takeAudio.muted=!takeAudio.muted;$('#takeSound').textContent=takeAudio.muted?'Sound off':'Sound on';$('#takeSound').setAttribute('aria-pressed',String(takeAudio.muted));if(!takeAudio.muted&&takePlaying)takeAudio.play().catch(()=>{});};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&takeActive)takeStop();});
const takeModeBefore=filmSetMode;filmSetMode=async function(mode){if(takeActive)takeLeave();await takeModeBefore(mode);if(isLocation()&&mode==='film')takeStart();};modeBar.querySelectorAll('button').forEach(b=>b.onclick=()=>filmSetMode(b.dataset.filmMode).catch(filmError));window.FilmButter.setMode=filmSetMode;
const takeSwitchBefore=switchTo;switchTo=async function(id){takeLeave();await takeSwitchBefore(id);};window.ButterFilms.switchTo=switchTo;
const takeSpatialBefore=ButterSpatialRuntime.frame;ButterSpatialRuntime.frame=function(now){takeSpatialBefore(now);if(takeActive){const t=takePlaying?(takeAudio.paused?takeOffset+(now-takeStarted)/1000:takeAudio.currentTime):takeTime;takeSeek(t);if(t>=48)takeStop();}};
// Keep saved workspace snapshots independent of a temporary performance pose.
const takeCaptureBefore=capture;capture=function(){const result=takeCaptureBefore();if(takeActive&&takeSaved){result.scene.actors=takeSaved.actors.map(a=>({kind:a.entry.kind,x:a.pos.x,y:a.pos.y,z:a.pos.z,heading:a.heading}));result.actor.on=takeSaved.performer.on;result.actor.follow=takeSaved.performer.follow;result.actor.destination=takeSaved.performer.destination?.toArray()||null;}return result;};
const takeRawRender=renderer.render.bind(renderer);renderer.render=function(s,c){if(!takeActive||s!==scene||c!==camera)return takeRawRender(s,c);const size=renderer.getSize(new THREE.Vector2()),w=size.x,h=size.y,fw=Math.min(w,h*16/9),fh=fw*9/16,x=(w-fw)/2,y=(h-fh)/2;renderer.setScissorTest(false);renderer.setViewport(0,0,w,h);renderer.clear();renderer.setViewport(x,y,fw,fh);renderer.setScissor(x,y,fw,fh);renderer.setScissorTest(true);takeRawRender(s,c);renderer.setScissorTest(false);renderer.setViewport(0,0,w,h);Object.assign(takeTitle.style,{left:x+'px',top:y+'px',width:fw+'px',height:fh+'px'});};
const takeCanvas=document.createElement('canvas');takeCanvas.width=1280;takeCanvas.height=720;const takeContext=takeCanvas.getContext('2d');
window.GrocerTake={shots:takeShots,duration:48,get active(){return takeActive},get playing(){return takePlaying},get time(){return takeTime},get props(){return takeAssets},get cast(){return takeCast},seek:t=>{takeStop();takeSeek(t)},play:takePlay,pause:takeStop,async enter(){await filmSetMode('film')},leave:()=>filmSetMode('build'),frame(t){if(!takeActive)throw Error('Enter film mode first.');takeStop();takeSeek(t);const size=renderer.getSize(new THREE.Vector2()),ratio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(1280,720,false);renderer.render(scene,camera);takeContext.clearRect(0,0,1280,720);takeContext.drawImage(renderer.domElement,0,0,1280,720);takeContext.drawImage(takeTitle,0,0,1280,720);const result=takeCanvas.toDataURL('image/png').split(',')[1];renderer.setPixelRatio(ratio);renderer.setSize(size.x,size.y,false);return result;},state(){const {cash,marge,baby}=takeCast;return {time:takeTime,shot:takeShots.find(s=>takeTime>=s.start&&takeTime<s.end)?.name||'End',cash:cash.rig.pos.toArray(),marge:marge.rig.pos.toArray(),baby:baby.rig.pos.toArray(),hand:takeHand(cash.rig).toArray(),apple:takeAssets.apple.position.toArray(),duck:takeAssets.duck.position.toArray(),audioTime:takeAudio.currentTime}}};
takeTitle.hidden=true;
const takeFrameStepBefore=runFrameStep;runFrameStep=function(name,fn){if(takeActive&&['hand-input','release','physics'].includes(name))return;return takeFrameStepBefore(name,fn);};

let takeFace=null;
function takeMakeFace(rig){const c=document.createElement('canvas');c.width=512;c.height=256;takeFace=new THREE.Mesh(new THREE.PlaneGeometry(19,18),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));rig.figure.updateMatrixWorld(true);const inv=rig.headP.matrixWorld.clone().invert(),bb=new THREE.Box3();rig.slots.head.traverse(o=>{if(o.isMesh){o.geometry.computeBoundingBox();bb.union(o.geometry.boundingBox.clone().applyMatrix4(inv.clone().multiply(o.matrixWorld)));}});const center=bb.getCenter(V());takeFace.position.set(center.x,center.y,bb.min.z-.15);takeFace.rotation.x=Math.PI;rig.headP.add(takeFace);}
function takeDrawFace(t){if(!takeFace)return;const mood=t<10.6?'calm':t<29.9?'puzzled':t<35?'surprise':t<43?'calm':'puzzled';const blink=[6.7,15.4,34.3,41.5].some(x=>Math.abs(t-x)<.09);const key=mood+blink;if(takeFace.userData.key===key)return;takeFace.userData.key=key;const c=takeFace.material.map.image,x=c.getContext('2d');x.clearRect(0,0,512,256);x.fillStyle=x.strokeStyle='#18221a';x.lineWidth=12;for(const a of [170,342]){x.beginPath();x.ellipse(a,93,22,blink?3:mood==='surprise'?37:30,0,0,Math.PI*2);x.fill();}x.beginPath();if(mood==='calm')x.arc(256,128,70,.15,Math.PI-.15);else if(mood==='surprise')x.ellipse(256,183,25,28,0,0,Math.PI*2);else{x.moveTo(220,181);x.lineTo(295,181);x.moveTo(139,35);x.lineTo(195,47);x.moveTo(319,47);x.lineTo(370,25);}x.stroke();takeFace.material.map.needsUpdate=true;}

if(new URLSearchParams(location.search).has('watch')){const boot=setInterval(()=>{if(isLocation()&&!filmBusy&&ButterCast.cast.length===3){clearInterval(boot);filmSetMode('film').catch(filmError);}},250);}
