(function(){
 const stage=$('#stage'),R=ButterSpatialRuntime,eye={active:false,saved:null};
 const back=document.createElement('button');back.id='eyeBack';back.textContent='← Back';back.hidden=true;back.setAttribute('aria-label','Return to building');stage.appendChild(back);
 function exit(){if(!eye.active)return;const saved=eye.saved;eye.active=false;back.hidden=true;const actor=ButterPerformer.state;if(actor.rig)actor.rig.figure.visible=actor.on;camera.position.copy(saved.position);camera.quaternion.copy(saved.quaternion);camera.fov=saved.fov;camera.near=saved.near;controls.target.copy(saved.target);camera.updateProjectionMatrix();camera.updateMatrixWorld(true);H.mustOpen=true;ButterMobile.fit();note('Aim at a brick. Pinch to pick up.','READY');}
 function update(){if(!eye.active)return;const a=ButterPerformer.state;if(!a.on||!a.rig){exit();return;}const rig=a.rig;rig.figure.updateMatrixWorld(true);const origin=rig.headP.localToWorld(V(0,-10,-12)),ahead=rig.headP.localToWorld(V(0,-10,-112));camera.position.copy(origin);camera.lookAt(ahead);camera.updateMatrixWorld(true);rig.figure.visible=false;}
 function enter(){const a=ButterPerformer.state;if(!a.on||!a.rig)return;if(S.tx){note('Release the brick, then tap the figure.','HELD');return;}ButterCornerTurns.end();eye.saved={position:camera.position.clone(),quaternion:camera.quaternion.clone(),fov:camera.fov,near:camera.near,target:controls.target.clone()};eye.active=true;camera.fov=70;camera.near=.5;camera.updateProjectionMatrix();back.hidden=false;closeDrawers();update();note('Tap the stage or Back to return.','EYE VIEW');}
 back.onclick=exit;
 window.addEventListener('keydown',e=>{if(eye.active&&e.key==='Escape'){exit();e.preventDefault();e.stopImmediatePropagation();}},true);
 window.addEventListener('pointerdown',e=>{if(e.target!==canvas)return;if(window.ButterScenes?.busy){e.preventDefault();e.stopImmediatePropagation();return;}if(window.ButterCast?.click(e)){e.preventDefault();e.stopImmediatePropagation();return;}if(eye.active){exit();e.preventDefault();e.stopImmediatePropagation();return;}const a=ButterPerformer.state;if(!a.on||!a.rig)return;const r=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const picked=window.ButterCast?.hit(ray);const solids=[];if(!window.ButterCast)a.rig.figure.traverse(o=>{if(o.isMesh)solids.push(o);});const hit=picked?.hit||ray.intersectObjects(solids,false)[0];if(!hit)return;const brick=ray.intersectObjects(S.parts.map(p=>p.mesh),true)[0];if(brick&&brick.distance<hit.distance)return;if(picked?.actor)ButterCast.select(picked.actor);enter();e.preventDefault();e.stopImmediatePropagation();},true);
 const frame=R.frame;R.frame=function(now){frame(now);update();};
 window.ButterEye={get active(){return eye.active;},enter,exit,update};
 $('#load').textContent='Open scene';$('#save').textContent='Save scene';$('#helpBtn').textContent='Start / help';
 $('#file').accept='.json,.ldr,.mpd,application/json,text/plain';
 $('#file').onchange=async e=>{let before=null;try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('Choose a scene smaller than 1 MB.');const data=parsePaste(await file.text());exit();if(S.tx)finish(false);before=checkpoint();restore(data);S.next=Math.max(S.next,...data.map(p=>+(p.id.match(/^p(\d+)$/)?.[1]||0)+1));S.selected.clear();record(before);persist();refresh();note('Scene opened. Use Undo to restore the previous scene.','OPENED');}catch(error){if(before){restore(JSON.parse(before));refresh();}note(error.message,'OPEN FAILED');}finally{e.target.value='';}};
 const help=$('#help'),credits=help.lastElementChild;help.replaceChildren();
 const steps=[['Start','Tap a brick. Drag it. Lift your finger to place it.'],['Use hands','Tap the camera icon. Allow camera access. Aim the claw at a brick. Pinch to pick up. Open that hand to release.'],['Recover','Tap ✓ to release a held brick. Tap × to cancel the move. Tap Undo to reverse the last edit.'],['Turn the floor','Make a fist near a floor corner for one quarter-turn. Open your hand before turning again.'],['Look from the figure','Tap the figure. Tap Back or tap the stage to return. Place any held brick before entering this view.'],['Open another scene','Open settings. Tap Open scene. Choose WAG JSON or LDraw using the included parts. Use Undo to restore the previous scene.'],['Keep your work','Tap Save scene to download your bricks. This file does not save camera footage or the actor pose.']];
 for(const [title,text]of steps){const p=document.createElement('p'),b=document.createElement('b');b.textContent=title+' · ';p.append(b,document.createTextNode(text));help.appendChild(p);}const close=document.createElement('button');close.textContent='Start building';close.onclick=()=>help.classList.remove('open');help.prepend(close);help.appendChild(credits);
 $('#helpBtn').onclick=()=>{const opening=!help.classList.contains('open');closeDrawers();$('#source').classList.remove('open');help.classList.toggle('open',opening);};
})();
