/* Repository parts are fetched before selection/scene state changes. */
(function(){
 const base='https://hartswf0.github.io/tractor-dce-gyo/ldraw/',inflight=new Map();
 async function ensure(name,seen=new Set()){
  name=name.replace(/\\/g,'/').toLowerCase();if(!/^[a-z0-9_./-]+\.dat$/.test(name)||name.includes('..'))throw Error('Invalid part path');if(seen.has(name))return;seen.add(name);if(seen.size>2000)throw Error('Part has too many dependencies');
  let source=ButterLDraw.parts[name];
  if(!source){let pending=inflight.get(name);if(!pending){pending=(async()=>{const paths=/^(parts|p)\//.test(name)?[name]:['parts/'+name,'p/'+name];for(const path of paths){const r=await fetch(base+path,{signal:AbortSignal.timeout(20000)});if(r.status===404)continue;if(!r.ok)throw Error('Part download failed: '+r.status);const text=await r.text();if(text.length>3e6||!/^0\s/m.test(text))throw Error('Invalid LDraw source: '+name);ButterLDraw.parts[path]=text;ButterLDraw.parts[name]=text;ButterLDraw.parts[path.replace(/^(parts|p)\//,'')]=text;return text;}throw Error('Part unavailable: '+name);})();inflight.set(name,pending);}try{source=await pending;}finally{inflight.delete(name);}}
  for(const line of source.split(/\r?\n/)){const a=line.trim().split(/\s+/);if(a[0]==='1'&&a.length>=15)await ensure(a.slice(14).join(' '),seen);}
 }
 const loading=new Map();
 async function load(id){if(catalog.has(id))return;const item=ButterMovieatorIndex.find(p=>p.id===id);if(!item)throw Error('Unknown repository part: '+id);if(loading.has(id))return loading.get(id);const task=(async()=>{await ensure('parts/'+id+'.dat');const group=await ButterMovieator.parse(id+'.dat',15);try{group.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(group),vertices=[],colors=[];if(box.isEmpty())throw Error('Empty part');group.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry,p=g.attributes.position,v=V();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i).applyMatrix4(o.matrixWorld);vertices.push(v.x,box.max.y-v.y,-v.z);const mat=Array.isArray(o.material)?o.material[g.groups.find(k=>i>=k.start&&i<k.start+k.count)?.materialIndex||0]:o.material;colors.push(mat.color.r,mat.color.g,mat.color.b);}});if(!vertices.length||vertices.length>6e6||!vertices.every(Number.isFinite))throw Error('Part geometry is too large or invalid');const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geometry.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geometry.computeVertexNormals();geometry.computeBoundingSphere();catalog.set(id,{id,name:item.name,h:Math.max(.1,box.max.y-box.min.y),offsetY:box.max.y,bounds:[box.min.x,box.max.x,-box.max.z,-box.min.z],geometry,repository:true});}finally{group.traverse(o=>{o.geometry?.dispose();for(const m of o.material?(Array.isArray(o.material)?o.material:[o.material]):[])m.dispose();});}})();loading.set(id,task);try{await task;}finally{loading.delete(id);}}
 const prior=create;create=function(row){const p=prior(row);if(catalog.get(row.part).repository){p.mesh.material.vertexColors=true;p.mesh.material.color.setHex(0xffffff);p.mesh.material.needsUpdate=true;}return p;};
 const panel=document.createElement('section');panel.id='repositoryParts';panel.innerHTML='<details><summary>Movieator parts & props</summary><div class="cast-row"><input id="repoSearch" type="search" placeholder="Search: sword, camera, Homer…" aria-label="Search Movieator parts"><select id="repoCategory" aria-label="Part category"><option>All</option><option>Props</option><option>Heads & headwear</option><option>Bodies</option></select></div><div class="cast-row"><select id="repoPart" aria-label="Repository part"></select><button id="repoAdd">＋ Add</button></div><p id="repoStatus" role="status">Choose a part. Tap Add. New parts require internet access.</p></details>';$('#shelf').appendChild(panel);
 function search(){const q=$('#repoSearch').value.toLowerCase(),cat=$('#repoCategory').value,items=ButterMovieatorIndex.filter(p=>(cat==='All'||p.category===cat)&&(p.name+' '+p.id).toLowerCase().includes(q)),select=$('#repoPart');select.replaceChildren();for(const p of items.slice(0,150)){const o=document.createElement('option');o.value=p.id;o.textContent=p.name+' · '+p.id;select.appendChild(o);}$('#repoAdd').disabled=!items.length;$('#repoStatus').textContent=items.length+' matches'+(items.length>150?' · Type more to narrow the list.':'.');}
 $('#repoSearch').oninput=search;$('#repoCategory').onchange=search;search();
 $('#repoAdd').onclick=async()=>{if(S.tx){note('Release the held part first.','HELD');return;}const id=$('#repoPart').value;$('#repoAdd').disabled=true;$('#repoStatus').textContent='Loading part…';try{await load(id);if(S.tx||window.ButterScenes?.busy)throw Error('Part loaded. Release your hold, then tap Add again.');addPart(id);$('#repoStatus').textContent='Part loaded. Drag the selected part to position it.';}catch(e){console.error('[BUTTER repository-part]',id,e);$('#repoStatus').textContent=e.message+' · Check the connection and retry.';}finally{$('#repoAdd').disabled=false;}};
 window.ButterRepository={load,ensure};
})();
