/* One bounded picker. Swipe changes the item; buttons perform the operation. */
(function(){
 const shelf=$('#shelf'),legacy=document.createElement('div');legacy.hidden=true;legacy.id='pickerLegacy';while(shelf.firstChild)legacy.appendChild(shelf.firstChild);shelf.appendChild(legacy);
 const ui=document.createElement('section');ui.id='operatorPicker';ui.innerHTML='<nav aria-label="Picker"><button data-tab="pieces">Pieces</button><button data-tab="cast">Cast</button><button data-tab="scenes">Scenes</button><button data-tab="placed">Placed</button><button id="pickerClose" aria-label="Close picker">×</button></nav><div class="picker-search"><input id="pickerSearch" type="search" placeholder="Find a piece" aria-label="Find picker item"><output id="pickerCount"></output></div><div id="pickerDeck"><button id="pickerPrev" aria-label="Previous item">‹</button><div id="pickerCard" tabindex="0" aria-label="Swipe left or right to browse"><img id="pickerImage" alt=""><div><strong id="pickerName"></strong><small id="pickerDetail"></small></div></div><button id="pickerNext" aria-label="Next item">›</button></div><div id="pickerActions"><button id="pickerAct">+ Add</button><div id="pickerColors"></div><button id="pickerTurn" hidden aria-label="Turn character 90 degrees">↻</button><button id="pickerEye" hidden>Eyes</button><button id="pickerRemove" hidden aria-label="Remove character">×</button></div><output id="pickerStatus" role="status">Swipe to choose. Tap Add.</output>';shelf.appendChild(ui);
 const style=document.createElement('style');style.textContent=`
 #shelf:not([hidden]){position:fixed!important;z-index:90!important;bottom:62px!important;left:50%!important;transform:translateX(-50%)!important;width:min(520px,100vw)!important;height:242px!important;max-height:none!important;overflow:hidden!important;display:block!important;padding:0!important;border:1px solid #40534c;border-radius:16px 16px 0 0!important;background:#131f23;box-shadow:0 -8px 24px #0005}#shelf[hidden],#pickerLegacy{display:none!important}
 #operatorPicker{height:100%;display:grid;grid-template-rows:42px 36px 88px 46px 24px;padding:0 8px;box-sizing:border-box;gap:0}#operatorPicker *{box-sizing:border-box;min-width:0}#operatorPicker nav{display:flex;gap:3px;align-items:center}#operatorPicker nav button{flex:1;padding:0 4px;min-height:36px;font-size:12px;border:0;background:transparent}#operatorPicker nav button[aria-selected=true]{background:#c4f46a;color:#142018}#operatorPicker nav #pickerClose{flex:0 0 36px;font-size:24px}#operatorPicker button{touch-action:manipulation}#operatorPicker [hidden]{display:none!important}.picker-search{display:flex;gap:8px;align-items:center}.picker-search input{flex:1;width:100%;height:32px;padding:4px 8px;border:1px solid #354844;background:#0e191c;color:#eef6ef;border-radius:7px;font-size:16px}.picker-search output{font:11px monospace;white-space:nowrap;color:#b4c7bd}#pickerDeck{display:grid;grid-template-columns:40px minmax(0,1fr) 40px;align-items:center;gap:4px}#pickerDeck>button{min-height:48px;padding:0;font-size:28px;background:transparent;border:0}#pickerCard{height:84px;display:flex;align-items:center;gap:8px;touch-action:none;user-select:none;overflow:hidden;border-radius:8px}#pickerImage{width:76px;height:72px;object-fit:contain;flex-shrink:0}#pickerName{font-size:14px;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}#pickerDetail{display:block;color:#a5b9af;font-size:10px;margin-top:3px;max-height:26px;overflow:hidden}#pickerActions{display:flex;align-items:center;gap:6px}#pickerActions button{min-height:42px;padding:4px 12px;font-size:13px}#pickerAct{background:#c4f46a;color:#142018;flex:1}#pickerColors{display:flex;gap:4px}#pickerColors button{min-width:22px;width:22px;min-height:28px;height:28px;border-radius:5px;padding:0;border:2px solid transparent}#pickerColors button[aria-pressed=true]{border-color:white}#pickerStatus{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#b7cdc1;line-height:24px}
 @media(max-height:500px){#shelf:not([hidden]){bottom:48px!important;width:min(620px,100vw)!important;height:194px!important}#operatorPicker{grid-template-rows:36px 30px 60px 42px 20px}#pickerCard{height:58px}#pickerImage{height:54px;width:64px}#pickerStatus{line-height:20px}#operatorPicker nav button{min-height:32px}#pickerActions button{min-height:38px}}
 `;document.body.appendChild(style);
 let tab='pieces',index=0,items=[],working=false,version=0;
 const status=t=>$('#pickerStatus').textContent=t;
 const icon=path=>'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80"><path d="'+path+'" fill="none" stroke="#c4f46a" stroke-width="4" stroke-linejoin="round"/></svg>');
 const fallback={pieces:icon('M12 30h56v34H12z M20 30V20h14v10 M46 30V20h14v10'),cast:icon('M28 12h24v22H28z M20 38h40l6 24H14z M26 64v12 M54 64v12'),scenes:icon('M8 56l32-18 32 18-32 18z M20 48V22h18v16 M44 40V12h18v36')};const previews=new Map();let tr,ts,tc;
 async function preview(item,v){const key=tab+':'+item.id;if(previews.has(key)){$('#pickerImage').src=previews.get(key);return;}if(tab==='scenes')return;let rig=null,mesh=null;try{if(tab==='cast')rig=await ButterMovieator.make(item);else if(tab==='placed')return;else if(!catalog.has(item.id))return;else mesh=new THREE.Mesh(catalog.get(item.id).geometry,material(S.color));if(v!==version)return;
 if(!tr){tr=new THREE.WebGLRenderer({alpha:true,antialias:true});tr.setSize(120,112);tr.outputEncoding=THREE.sRGBEncoding;ts=new THREE.Scene();ts.add(new THREE.HemisphereLight(0xffffff,0x65706a,1));const light=new THREE.DirectionalLight(0xffffff,.8);light.position.set(-60,100,80);ts.add(light);tc=new THREE.PerspectiveCamera(35,120/112,.1,4000);}
 const obj=rig?.figure||mesh;obj.position.set(0,0,0);ts.add(obj);obj.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(obj),c=bb.getCenter(V()),size=bb.getSize(V()).length();tc.position.copy(c).addScaledVector(V(.6,.35,1).normalize(),size*1.7);tc.lookAt(c);tr.render(ts,tc);const url=tr.domElement.toDataURL();previews.set(key,url);if(v===version)$('#pickerImage').src=url;ts.remove(obj);
 }catch(e){console.warn('[BUTTER preview]',item.id,e.message);}finally{if(rig)ButterCast.dispose(rig);mesh?.material.dispose();}}
 function collect(){const q=$('#pickerSearch').value.toLowerCase().trim();let all;if(tab==='cast')all=ButterAssetCatalog.characters;else if(tab==='scenes')all=ButterScenePresets;else if(tab==='placed')all=ButterCast.cast.map(a=>({id:a.id,name:ButterAssetCatalog.characters.find(c=>c.id===a.kind)?.name||a.kind,actor:a}));else{const bundled=[...catalog.values()];all=q?[...bundled,...ButterMovieatorIndex.filter(p=>!catalog.has(p.id))]:bundled;}items=all.filter(p=>(p.name+' '+(p.world||'')+' '+p.id).toLowerCase().includes(q));index=Math.min(index,Math.max(0,items.length-1));render();}
 function render(){const v=++version,item=items[index];for(const b of ui.querySelectorAll('[data-tab]'))b.setAttribute('aria-selected',String(b.dataset.tab===tab));$('#pickerCount').textContent=items.length?(index+1)+' / '+items.length:'0';$('#pickerName').textContent=item?.name||'No matches';$('#pickerImage').src=fallback[tab]||fallback.cast;$('#pickerDetail').textContent=item?(tab==='scenes'?item.actors.length+' characters · '+item.parts.length+' pieces':tab==='placed'?'Character '+item.id.replace('actor','')+' · position separately':tab==='cast'?(item.world||'Workshop')+(item.note?.includes('base')?' · base figure':''):catalog.has(item.id)?'Included · '+item.id:'Download · '+item.id):'Try another name.';$('#pickerAct').textContent=tab==='scenes'?'Load scene':tab==='placed'?'Move':'+ Add';$('#pickerAct').disabled=working||!item;$('#pickerPrev').disabled=working||items.length<2;$('#pickerNext').disabled=working||items.length<2;$('#pickerColors').hidden=tab!=='pieces';for(const id of ['pickerTurn','pickerEye','pickerRemove'])$('#'+id).hidden=tab!=='placed';if(item)preview(item,v);}
 function step(dir){if(working||!items.length)return;index=(index+dir+items.length)%items.length;render();}
 function setTab(next){if(working)return;tab=next;index=0;$('#pickerSearch').value='';$('#pickerSearch').placeholder=tab==='pieces'?'Find piece or prop':tab==='cast'?'Find character or cast':tab==='scenes'?'Find scene':'Find placed character';collect();status(tab==='placed'?'Choose a character. Tap Move, then tap the floor.':'Swipe to choose. '+(tab==='scenes'?'Tap Load scene.':'Tap Add.'));}
 ui.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#pickerSearch').oninput=()=>{index=0;collect();};$('#pickerPrev').onclick=()=>step(-1);$('#pickerNext').onclick=()=>step(1);$('#pickerClose').onclick=()=>closeDrawers();
 let start=null;const card=$('#pickerCard');card.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};card.setPointerCapture(e.pointerId);};card.onpointerup=e=>{if(start&&Math.abs(e.clientX-start.x)>30&&Math.abs(e.clientX-start.x)>Math.abs(e.clientY-start.y))step(e.clientX<start.x?1:-1);start=null;};card.onpointercancel=()=>start=null;card.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){step(e.key==='ArrowLeft'?-1:1);e.preventDefault();}};
 for(const c of COLORS){const b=document.createElement('button');b.style.background='#'+c.hex.toString(16).padStart(6,'0');b.setAttribute('aria-label','Color '+c.code);b.setAttribute('aria-pressed',String(S.color===c.code));b.onclick=()=>{S.color=c.code;for(const el of $('#pickerColors').children)el.setAttribute('aria-pressed',String(el===b));};$('#pickerColors').appendChild(b);}
 function selectActor(){const a=items[index]?.actor;if(a)ButterCast.select(a);return a;}
 $('#pickerAct').onclick=async()=>{if(working||!items[index])return;const item=items[index];working=true;render();status('Loading…');try{if(tab==='pieces'){if(!catalog.has(item.id))await ButterRepository.load(item.id);if(S.tx)throw Error('Release the held piece first.');addPart(item.id);closeDrawers();}else if(tab==='cast'){await ButterCast.add(item.id);closeDrawers();}else if(tab==='scenes')await ButterScenes.load({version:1,...item,plateAngle:0});else if(selectActor())$('#castMove').click();status('Ready.');}catch(e){status(e.message==='Failed to fetch'?'Download failed. Check internet and tap Add again.':e.message);console.error('[BUTTER picker]',e);}finally{working=false;collect();}};
 $('#pickerTurn').onclick=()=>{if(selectActor())$('#castTurn').click();};$('#pickerEye').onclick=()=>{if(selectActor())$('#castEyes').click();};$('#pickerRemove').onclick=()=>{if(selectActor())$('#castRemove').click();collect();};
 const open=$('#partsToggle').onclick;$('#partsToggle').onclick=()=>{open();if(!shelf.hidden)collect();};
 window.ButterPicker={open(next='pieces'){closeDrawers();shelf.hidden=false;$('#partsToggle').setAttribute('aria-expanded','true');setTab(next);}};
 const observer=new MutationObserver(()=>{if(!shelf.hidden&&!working)collect();});observer.observe(shelf,{attributes:true,attributeFilter:['hidden']});
 setTab('pieces');
})();
