/* Scene replacement prepares its cast before touching the current workspace. */
(function(){
 const key='wag-butter-scenes-v1';let busy=false,ready=false;
 const panel=document.createElement('section');panel.id='scenePicker';panel.innerHTML='<div class="cast-row"><label>Scene <select id="scenePreset" aria-label="Preloaded scene"></select></label><button id="sceneLoad">Load scene</button></div><p id="sceneDescription"></p><p id="sceneStatus" role="status">Load a scene with its parts and characters. Undo restores your work.</p>';
 $('#shelf').prepend(panel);for(const scene of ButterScenePresets){const option=document.createElement('option');option.value=scene.id;option.textContent=scene.name;$('#scenePreset').appendChild(option);}const describe=()=>$('#sceneDescription').textContent=ButterScenePresets.find(s=>s.id===$('#scenePreset').value).description;$('#scenePreset').onchange=describe;describe();
 const open=document.createElement('button');open.textContent='Scenes';open.onclick=()=>{if(window.ButterPicker){ButterPicker.open('scenes');return;}closeDrawers();$('#shelf').hidden=false;$('#partsToggle').setAttribute('aria-expanded','true');panel.scrollIntoView({block:'nearest'});};$('.advanced-buttons').appendChild(open);
 function snapshot(){return {version:1,parts:rows(),actors:ButterCast.snapshot(),plateAngle:ButterSpatialRuntime.plate.rotation.y};}
 function persistScene(){if(!ready||busy)return;try{localStorage.setItem(key,JSON.stringify(snapshot()));}catch{note('Storage is full. Use Save scene to keep your work.','SAVE');}}
 function check(doc){const parts=validateRows(doc),actors=doc.actors===undefined?[]:doc.actors;if(!Array.isArray(actors)||actors.length>12)throw Error('A scene supports up to 12 characters.');const angle=doc.plateAngle??0;if(!Number.isFinite(angle)||Math.abs(angle)>1e6)throw Error('Invalid plate angle.');return {parts,actors,angle};}
 async function load(doc,{history=true}={}){if(busy)throw Error('Wait for the current scene to finish loading.');if(S.tx)throw Error('Release the held brick before loading a scene.');busy=true;$('#sceneLoad').disabled=true;$('#castTools').inert=true;$('#sceneStatus').textContent='Loading parts and characters…';let prepared=null;try{if(!Array.isArray(doc?.parts)||doc.parts.length>200)throw Error('Invalid scene parts.');for(const id of new Set(doc.parts.map(p=>p.part)))if(!catalog.has(id))await ButterRepository.load(id);const valid=check(doc);prepared=await ButterCast.prepare(valid.actors);for(let i=0;i<prepared.length;i++){const rig=prepared[i].rig,radius=rig.radius*rig.figure.scale.x,p=rig.pos;if(Math.abs(p.x)+radius>400||Math.abs(p.z)+radius>400)throw Error('A character is outside the plate.');for(const part of valid.parts){const b=bounds(part);if(b.min.y>=rig.height*rig.figure.scale.y)continue;const x=Math.max(b.min.x,Math.min(p.x,b.max.x)),z=Math.max(b.min.z,Math.min(p.z,b.max.z));if(Math.hypot(x-p.x,z-p.z)<radius)throw Error('A character overlaps a part.');}for(const prior of prepared.slice(0,i))if(prior.rig.pos.distanceTo(p)<radius+prior.rig.radius*prior.rig.figure.scale.x)throw Error('Characters overlap.');}
 const before=snapshot();ButterEye.exit();ButterCornerTurns.end();ButterCast.cancel();S.selected.clear();restore(valid.parts);ButterCast.commit(prepared);prepared=null;S.next=Math.max(1,...S.parts.map(p=>+(p.id.match(/^p(\d+)$/)?.[1]||0)+1));ButterSpatialRuntime.spinPlate(valid.angle,true);if(history){S.history.push({butterScene:true,snapshot:before});if(S.history.length>60)S.history.shift();}refresh();closeDrawers();$('#sceneStatus').textContent='Scene loaded. Undo restores the previous scene.';note('Scene loaded. Pick a brick or tap a character.','READY');return true;
 }catch(e){if(prepared)prepared.forEach(a=>ButterCast.dispose(a.rig));$('#sceneStatus').textContent=e.message;console.error('[BUTTER scene-load]',e);throw e;}finally{busy=false;$('#sceneLoad').disabled=false;$('#castTools').inert=false;persist();}}
 $('#sceneLoad').onclick=()=>{const scene=ButterScenePresets.find(s=>s.id===$('#scenePreset').value);load({version:1,...scene,plateAngle:0}).catch(e=>note(e.message,'SCENE'));};
 const oldPersist=persist;persist=function(){oldPersist();persistScene();};
 const oldUndo=undo;undo=async function(){if(busy)return;if(S.tx)return oldUndo();const last=S.history.at(-1);if(!last?.butterScene)return oldUndo();try{await load(last.snapshot,{history:false});S.history.pop();refresh();note('Previous scene restored.','UNDO');}catch(e){note(e.message,'UNDO FAILED');}};$('#undo').onclick=()=>undo();
 save=function(){download(JSON.stringify(snapshot(),null,2),'wag-hand-scene.json','application/json');note('Scene saved with parts and character positions.','SAVED');};$('#save').onclick=save;$('#exportJson').onclick=save;
 $('#file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>1e6)throw Error('Choose a scene smaller than 1 MB.');const text=await f.text(),doc=text.trim().startsWith('{')?JSON.parse(text):{version:1,parts:parsePaste(text),actors:[]};await load(doc);}catch(e){note(e.message,'OPEN FAILED');}finally{e.target.value='';}};
 const frame=ButterSpatialRuntime.frame;ButterSpatialRuntime.frame=function(now){frame(now);if(!ready&&S.ready&&ButterCast.cast.length){ready=true;const requested=new URLSearchParams(location.search).get('scene'),preset=ButterScenePresets.find(s=>s.id===requested);let saved=null;try{saved=JSON.parse(localStorage.getItem(key)||'null');}catch{}if(preset)load({version:1,...preset}).catch(e=>note(e.message,'SCENE'));else if(saved)load(saved,{history:false}).catch(e=>note(e.message,'RESTORE FAILED'));}};
 window.addEventListener('pagehide',persistScene);document.addEventListener('visibilitychange',()=>{if(document.hidden)persistScene();});
 const help=document.createElement('p');help.textContent='Scenes · Open Parts, choose a scene and tap Load scene. Undo restores your previous parts and cast. Save scene downloads both.';$('#help').prepend(help);for(const p of $('#help').querySelectorAll('p'))if(p.textContent.includes('does not save camera footage or the actor pose'))p.textContent='Keep your work · Tap Save scene to download bricks and character positions.';
 window.ButterScenes={load,snapshot,persist:persistScene,get busy(){return busy;}};
})();
