"""tools/making/hop_script.py — Hearts of Plastic, the episodes' scripts (odyssey/writers-room/BIBLE.md). Read by tools/making/voices.py
through lego_script.py (CAST and SCENES are merged there), by tools/making/hop_keys.py and by the assembly (tools/making/hop_film.py).

Every gag is from the record; each episode's EVIDENCE lists what each one stands on (a camera note in odyssey/perform/camera.html, a
take in films/odyssey/takes/index.json, a commit). A line is (key, speaker, addressee, pause before it in seconds, text[, opts]).
Besides the cast, three speakers lay events on the clock and are not voices:
  'clap'     the clapperboard (a sound in the bed; text unused)
  'dailies'  the crew watch a real take on the monitor: text 'file@from+seconds|caption' (films/odyssey/...), cut in over the
             episode's picture by hop_film.py while the room is quiet; the clock waits for it
  'beat'     silence held for action, text 'seconds|what happens'
"""

# the Odyssey's actors, each in one Kokoro voice for every episode (the crew's voices are lego_script.py's). fx: 'giant' lowers the
# voice by resampling (a third slower and deeper); 'shade' the faint echo the restored Achilles line has (odyssey/kits/cut-restore.json)
CAST = {
    'polyphemus': dict(name='Polyphemus', face=None, voice='am_fenrir', speed=1.08, fx='giant', creature=True),
    'odysseus-as-beggar': dict(name='Odysseus', face='odysseus', voice='am_onyx', speed=0.92),   # Odysseus in the beggar's rags (OD-B17-S05's actor id), his voice
    'irus':       dict(name='Irus',       face=None, voice='bm_fable',  speed=1.0),
    'antinous':   dict(name='Antinous',   face=None, voice='am_puck',   speed=1.0),
    'anticleia':  dict(name='Anticleia',  face=None, voice='bf_isabella', speed=0.95, fx='shade'),
    'achilles':   dict(name='Achilles',   face=None, voice='am_onyx',   speed=0.9, fx='shade'),   # the voice his restored answer was made in (odyssey/kits/cut-restore.json)
    'calypso':    dict(name='Calypso',    face=None, voice='af_bella',  speed=0.95),
    'crew-at-the-oars-2': dict(name='A Rower', face=None, voice='am_eric', speed=1.0),
    'crew-at-the-oars-3': dict(name='Another Rower', face=None, voice='am_liam', speed=1.0),
    'crew-at-the-oars-5': dict(name='The Helmsman', face=None, voice='am_adam', speed=0.95),
    'the-sirens-4':       dict(name='A Siren', face=None, voice='af_nicole', speed=0.95),
}

SCENES = {
 'OD-B26-S01': dict(title='The Cave', episode=1, head=1.0, tail=2.6, location='OD-B09-S06',
  hypothesis='A camera goes where the heat is.',
  lines=[
    ('K1', 'firstad', 'director', 0.0, "Book nine. The Cyclops's cave. Escape beneath the rams. Take one."),
    ('K1', 'clap', None, 0.4, ''),
    ('K1', 'director', 'cinematographer', 0.5, "Action."),
    ('K1', 'beat', None, 0.3, '2.0|the rams go by; nothing else'),
    ('K1', 'director', 'cinematographer', 0.2, "Where is the camera?"),
    ('K1', 'cinematographer', 'director', 0.6, "In the ram."),
    ('K2', 'firstad', 'cinematographer', 1.6, "Why is the camera in the ram?"),
    ('K2', 'cinematographer', 'firstad', 0.6, "The ram was the hottest thing in the scene. I go where the heat is."),
    ('K2', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B09-S10/take1.mp4@10.6+3.4|DAILIES · Escape beneath the Rams, take 1 (1 Oct, 88b35af3): the lens in the wool'),
    ('K2', 'director', 'firstad', 0.5, "Wool."),
    ('K2', 'firstad', 'cinematographer', 0.6, "He means: get out of the sheep."),
    ('K2', 'cinematographer', 'firstad', 0.8, "New rule. No lens inside an animal."),
    ('K2', 'cinematographer', 'firstad', 0.9, "Or a face."),
    ('K3', 'firstad', 'director', 1.8, "The night wide. Take one."),
    ('K3', 'clap', None, 0.4, ''),
    ('K3', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B09-S10/take1.mp4@19.6+3.0|DAILIES · Escape beneath the Rams, take 1: the night wide'),
    ('K3', 'director', 'cinematographer', 0.5, "Is anyone in this shot?"),
    ('K3', 'cinematographer', 'director', 0.6, "Odysseus, six men, three rams, a ship and a giant."),
    ('K3', 'director', 'cinematographer', 0.9, "I'll take your word for it."),
    ('K3', 'cinematographer', 'director', 0.8, "New rule. A frame that is nearly black is refused."),
    ('K4', 'firstad', 'polyphemus', 2.0, "Polyphemus, your close-up."),
    ('K4', 'polyphemus', 'firstad', 0.8, "From below."),
    ('K4', 'firstad', 'director', 0.6, "He wants to be shot from below."),
    ('K4', 'cinematographer', 'director', 0.7, "From above, the eye was never where his head was."),
    ('K4', 'clap', None, 1.0, ''),
    ('K4', 'polyphemus', None, 0.6, "Strangers, who are you?"),
    ('K4', 'director', 'polyphemus', 1.2, "Half your face is in shadow."),
    ('K4', 'polyphemus', 'director', 0.8, "That is my good side."),
    ('K5', 'firstad', 'director', 1.8, "The stone. He seals the cave. Take one."),
    ('K5', 'clap', None, 0.4, ''),
    ('K5', 'director', 'polyphemus', 0.5, "Action."),
    ('K5', 'beat', None, 0.2, '3.2|the giant reaches for the stone; the cut; the stone is in the door'),
    ('K5', 'director', None, 0.3, "Did it move?"),
    ('K5', 'cinematographer', 'director', 0.6, "It was beside the door. Now it is in the door."),
    ('K5', 'director', 'odysseus', 0.9, "Did anyone see it move?"),
    ('K5', 'odysseus', 'director', 0.7, "Nobody."),
    ('K5', 'director', 'odysseus', 0.8, "Nobody?"),
    ('K5', 'odysseus', 'director', 0.6, "That's my name."),
    ('K5', 'firstad', None, 1.4, "Back to one."),
    ('K6', 'firstad', 'polyphemus', 2.6, "Take two. This time he carries it."),
    ('K6', 'clap', None, 0.4, ''),
    ('K6', 'director', 'polyphemus', 0.5, "Action."),
    ('K6', 'beat', None, 0.2, '5.0|the giant carries the great stone into the door, seen'),
    ('K6', 'director', 'firstad', 0.4, "Print it."),
    ('K7', 'firstad', 'director', 1.8, "The milking. We lit it again."),
    ('K7', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B09-S06/take1.mp4@24.0+2.6|DAILIES · Polyphemus Seals the Cave, take 1 (3 Oct, f46a0238)'),
    ('K7', 'dailies', None, 0.0, 'films/odyssey/OD-B09-S06-performed.mp4@24.0+2.6|DAILIES · take 2 (53c9b5e4): the fill up, the fire brighter'),
    ('K7', 'cinematographer', 'director', 0.5, "The background is still black."),
    ('K7', 'director', 'cinematographer', 1.2, "Keep it."),
  ],
  evidence=[
    ('the camera in the ram', 'films/odyssey/takes/index.json OD-B09-S10 take 1 (88b35af3): "some frames from inside a ram\'s body or a face"; take 2 (8c8d4374): "no frame inside a ram or a face"; tools/cinematographer/solve.js L1c (the lens out of a creature\'s sphere)'),
    ('the hottest thing in the scene', 'tools/cinematographer/plan.js R1 heat: the shot goes to the hottest figure'),
    ('is anyone in this shot?', 'OD-B09-S10 take 1: "a night wide almost black"; take 2: "the black night wide refused"; solve.js exposure: a frame nearly black is refused'),
    ('from below', 'camera note OD-B09-S06: "the giant\'s question is low and close, half his face in shadow"; plan.js R8: a shot on a creature is low; 1c64c8e6: "the Cyclops\'s eye centred on his head"'),
    ('the stone that was not seen to move', 'OD-B09-S06 take 1 (f46a0238): "the great stone did not read as the giant\'s doing"; take 2 (53c9b5e4): "carried into the doorway with the giant\'s heave (a new engine feature: a set piece carried by a body)"'),
    ('the milking still black', 'camera note OD-B09-S06: "the milking\'s background is still black"; take 2: "the sealed cave and the milking lit"'),
  ]),
 'OD-B26-S02': dict(title='The Hall', episode=2, head=1.0, tail=2.6, location='OD-B17-S05',
  hypothesis='A stool reads as thrown if it is seen in the air for more than half a second.',
  lines=[
    ('K1', 'firstad', 'director', 0.0, "Book eighteen. Odysseus drops Irus. Beggars, to your marks."),
    ('K1', 'beat', None, 0.3, '2.4|the two beggars walk in, side by side, and stop'),
    ('K1', 'director', 'firstad', 0.3, "Which one is Irus?"),
    ('K1', 'firstad', 'director', 0.7, "Irus is the one on the left."),
    ('K1', 'irus', 'firstad', 0.6, "I'm on the right."),
    ('K1', 'odysseus-as-beggar', 'director', 0.7, "I am the unknown beggar."),
    ('K2', 'cinematographer', 'director', 1.4, "Same head. Same grey beard. Same rags, same staff. Part for part, and colour for colour."),
    ('K2', 'director', 'firstad', 0.8, "Wardrobe."),
    ('K2', 'firstad', 'cinematographer', 0.6, "He means: can we tell them apart?"),
    ('K2', 'cinematographer', 'firstad', 0.7, "The camera note says: hard to tell apart."),
    ('K2', 'firstad', 'director', 0.7, "Noted. Still wrong."),
    ('K3', 'firstad', 'director', 1.8, "Book seventeen. Antinous throws the stool. Take two."),
    ('K3', 'clap', None, 0.4, ''),
    ('K3', 'antinous', 'firstad', 0.6, "Which beggar?"),
    ('K3', 'firstad', 'antinous', 0.6, "The one who isn't Irus."),
    ('K3', 'antinous', 'firstad', 0.6, "Which one is Irus?"),
    ('K3', 'director', 'antinous', 0.8, "Action."),
    ('K3', 'beat', None, 0.2, '2.6|Antinous throws the stool as take two had it: a third of a second in the air'),
    ('K3', 'director', 'cinematographer', 0.4, "Was that it?"),
    ('K3', 'cinematographer', 'director', 0.6, "A third of a second. And it landed outside the frame."),
    ('K3', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B17-S05/take2.mp4@45.7+2.6|DAILIES · Antinous Throws the Stool, take 2 (3 Oct, 8135f3e5): the flight, a third of a second'),
    ('K4', 'firstad', 'director', 0.8, "The experiment. A stool reads as thrown if it is in the air for more than half a second."),
    ('K4', 'cinematographer', 'firstad', 0.7, "The variable: the flight, a third of a second to six tenths. And smear bricks."),
    ('K4', 'director', 'cinematographer', 0.7, "Smear?"),
    ('K4', 'cinematographer', 'director', 0.6, "For two drawings the stool is drawn long, in bricks, along its path. The LEGO Movie does it. No blur."),
    ('K4', 'firstad', None, 0.7, "Held: the voices, the blocking, the lenses. Take three."),
    ('K4', 'clap', None, 0.4, ''),
    ('K4', 'director', 'antinous', 0.6, "Action."),
    ('K4', 'beat', None, 0.2, '3.2|Antinous throws again: six tenths of a second, the smear bricks on two drawings'),
    ('K4', 'odysseus-as-beggar', 'director', 0.6, "I stand like a rock. It's in the book."),
    ('K4', 'director', 'cinematographer', 0.8, "Was that it?"),
    ('K4', 'cinematographer', 'director', 0.6, "Six tenths of a second."),
    ('K5', 'dailies', None, 0.6, 'films/odyssey/OD-B17-S05-performed.mp4@45.4+3.2|DAILIES · Antinous Throws the Stool, take 3: six tenths of a second, two drawings of smear bricks'),
    ('K5', 'director', 'firstad', 0.6, "Print it."),
    ('K5', 'irus', 'firstad', 1.2, "Do I get a stool?"),
    ('K5', 'firstad', 'irus', 0.6, "You get dropped. Next week."),
  ],
  evidence=[
    ('the two beggars', 'odyssey/cards/OD-B18-S02.mpd: Irus and the beggar are the same minifigure part for part and colour for colour (973p3a, 3626bp4g, 3901, 93223, 3957a, 10169); camera note OD-B18-S02: "Odysseus and Irus are both white-bearded beggars and hard to tell apart" (still wrong)'),
    ('the unknown beggar', 'halfworld e55c649: the stage direction read aloud ("For news and enters the hut beside the unknown beggar?"), the making-of part two'),
    ('the suitor dressed as the beggar', 'camera note OD-B17-S05: "one of the rebuking suitors wears the same white beard and red vest as the beggar"'),
    ('a third of a second', 'camera note OD-B17-S05: "the stool\'s flight lasts a third of a second and lands out of the wide\'s frame"; tools/perform/scenes/OD-B17-S05.js FL = 0.33 (take 2, 8135f3e5)'),
    ('the experiment and the new throw', 'odyssey/experiments/OD-B17-S05.json; take 3 of OD-B17-S05 (tools/perform/keeptake.py): FL 0.6, the smear bricks (tools/forage/keyprops.js stoolSmear; film-readymades/choreo.js applyFlights)'),
  ]),
 'OD-B26-S03': dict(title='The Underworld', episode=3, head=1.0, tail=2.6, location='OD-B11-S04',
  hypothesis='The camera can only frame a face it can find.',
  lines=[
    ('K1', 'firstad', 'director', 0.0, "Book eleven. The shore of the dead. Anticleia and the three embraces. Embrace one."),
    ('K1', 'clap', None, 0.4, ''),
    ('K1', 'director', 'odysseus', 0.5, "Action."),
    ('K2', 'beat', None, 0.3, '2.6|Odysseus springs to hold his mother; his arms pass through her'),
    ('K2', 'anticleia', 'odysseus', 0.3, "Through me, dear. I'm a shade."),
    ('K2', 'director', 'firstad', 0.9, "Again."),
    ('K2', 'firstad', None, 0.6, "Embrace two."),
    ('K2', 'clap', None, 0.4, ''),
    ('K3', 'beat', None, 0.5, '2.6|the second embrace: through her again, and she is a step farther off'),
    ('K3', 'anticleia', 'odysseus', 0.3, "Still dead."),
    ('K3', 'odysseus', 'anticleia', 0.8, "In take one I could hold you."),
    ('K3', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B11-S04/take1.mp4@41.6+3.4|DAILIES · Anticleia and the Three Embraces, take 1 (3 Oct, 6d020c38): a solid mother'),
    ('K3', 'cinematographer', 'director', 0.5, "In take one she was drawn solid. Nothing to pass through."),
    ('K3', 'anticleia', 'cinematographer', 0.7, "I was very convincing."),
    ('K3', 'firstad', None, 0.9, "Embrace three."),
    ('K3', 'clap', None, 0.4, ''),
    ('K4', 'beat', None, 0.5, '2.6|the third embrace: through her'),
    ('K4', 'anticleia', 'odysseus', 0.3, "Take your time. I have eternity."),
    ('K4', 'odysseus', 'director', 0.9, "Once more?"),
    ('K4', 'director', 'odysseus', 0.7, "Three. It's in the book."),
    ('K4', 'anticleia', 'odysseus', 0.8, "I'll be here, dear. I'm not going anywhere."),
    ('K5', 'firstad', 'achilles', 1.6, "Achilles, you're on."),
    ('K5', 'beat', None, 0.2, '2.2|Achilles comes up the shore in the visored helmet'),
    ('K5', 'achilles', 'firstad', 0.3, "The fans want the helmet."),
    ('K5', 'cinematographer', 'director', 0.8, "I can't find his face."),
    ('K5', 'director', 'firstad', 0.8, "Helmet."),
    ('K5', 'firstad', 'achilles', 0.6, "He means: off. The visor hides every close."),
    ('K6', 'achilles', 'firstad', 0.8, "I am Achilles."),
    ('K6', 'firstad', 'achilles', 0.8, "You have no lines."),
    ('K6', 'achilles', 'firstad', 0.9, "I am ACHILLES."),
    ('K6', 'firstad', 'director', 1.0, "The script never gave him his answer. So we made one."),
    ('K6', 'dailies', None, 0.6, 'films/odyssey/OD-B11-S07-performed.mp4@29.2+4.4|DAILIES · Achilles Chooses Life, take 2 (3 Oct, 06ad18e7): the answer, bareheaded, in a made voice|audio'),
    ('K6', 'odysseus', 'achilles', 0.5, "That's my voice."),
    ('K6', 'cinematographer', 'odysseus', 0.7, "Same voice. Onyx, at nine tenths, with an echo."),
    ('K6', 'achilles', 'odysseus', 0.9, "I am Achilles."),
    ('K6', 'director', 'firstad', 0.9, "Print it."),
    ('K6', 'achilles', 'firstad', 0.8, "With the helmet?"),
    ('K6', 'firstad', 'achilles', 0.6, "Without."),
    ('K6', 'achilles', 'firstad', 0.7, "The fans..."),
    ('K6', 'firstad', 'achilles', 0.6, "will see your face."),
  ],
  evidence=[
    ('hugged through, take after take', 'OD-B11-S04 take 1 (6d020c38): "his mother looked alive; the embraces had nothing to pass through"; take 2 (0beb380f): "his arms closing through her three times" (a shade: the take\'s spec.shades)'),
    ('the fans want the helmet', '5d16363d: "Achilles and Ajax bareheaded (the visored helm hid every close of the shades)"; the helmet 95676 (Minifig Helmet Gladiator) on the card before it'),
    ('you have no lines', 'OD-B11-S07 take 1 (b2f7beca): "Achilles\'s answer is missing"; odyssey/kits/cut-restore.json: "the recording has no turn for it (the halfworld\'s script gives him none)"'),
    ('that\'s my voice', 'odyssey/kits/cut-restore.json: Achilles\'s added line is "Kokoro-82M voice am_onyx at 0.9, a faint echo"; tools/making/lego_script.py: Odysseus speaks in am_onyx'),
  ]),
 'OD-B26-S04': dict(title='The Sea', episode=4, head=1.0, tail=2.6, location='OD-B12-S03',
  hypothesis='A face is seen if nothing stands between it and the lens.',
  lines=[
    ('K1', 'firstad', 'director', 0.0, "Book twelve. The Sirens. Rowers, stroke."),
    ('K1', 'clap', None, 0.4, ''),
    ('K1', 'director', 'firstad', 0.5, "Action."),
    ('K1', 'beat', None, 0.3, '3.4|the four rowers pull on one clock'),
    ('K1', 'director', 'cinematographer', 0.2, "They look like a loop."),
    ('K1', 'cinematographer', 'director', 0.6, "One clock. A stroke every two point six seconds."),
    ('K1', 'crew-at-the-oars-2', 'director', 0.7, "I'm four hundredths of a stroke late."),
    ('K1', 'crew-at-the-oars-3', 'director', 0.6, "Three hundredths of a stroke early."),
    ('K1', 'crew-at-the-oars-5', 'director', 0.7, "I don't row. I steer."),
    ('K1', 'the-sirens-4', None, 0.8, "We sing on a clock of our own."),
    ('K1', 'director', 'firstad', 0.9, "Print it."),
    ('K1', 'crew-at-the-oars-2', 'firstad', 0.6, "What?"),
    ('K1', 'firstad', 'director', 0.7, "Wax in their ears. It's in the scene."),
    ('K1', 'firstad', None, 0.9, "I'll check on all of you at the top of the hour."),
    ('K2', 'firstad', 'calypso', 1.8, "Book five, on the same boat. Calypso, your trees. Odysseus, beside her."),
    ('K2', 'clap', None, 0.4, ''),
    ('K2', 'director', 'calypso', 0.5, "Action."),
    ('K2', 'beat', None, 0.2, '1.8|Odysseus steps in, between her and the lens'),
    ('K2a', 'calypso', 'odysseus', 0.2, "Here at the island's edge the tall trees stand: alder, and poplar, and sky-high fir."),
    ('K2a', 'director', 'cinematographer', 0.9, "Where is Calypso?"),
    ('K2a', 'cinematographer', 'director', 0.6, "Behind the back of his head."),
    ('K2a', 'odysseus', 'director', 0.8, "I'm the lead."),
    ('K2a', 'dailies', None, 0.6, 'films/odyssey/takes/OD-B05-S04/take1.mp4@7.0+3.6|DAILIES · The Raft, take 1 (2 Oct, 1f1e8e81): her lines behind his head'),
    ('K2a', 'cinematographer', 'director', 0.5, "Take one. Twenty-four seconds of her lines, behind his head."),
    ('K2a', 'calypso', 'director', 0.8, "Seven years I kept him. One take, and he's in front of me."),
    ('K2a', 'director', 'firstad', 0.9, "Apart."),
    ('K2a', 'firstad', 'odysseus', 0.6, "He means: a man's height apart."),
    ('K3', 'beat', None, 0.3, '1.8|Odysseus steps aside, a man\'s height from her'),
    ('K3', 'calypso', 'odysseus', 0.2, "Here at the island's edge the tall trees stand: alder, and poplar, and sky-high fir."),
    ('K3', 'cinematographer', 'director', 0.9, "Her face. And the bow on his back is still across the frame."),
    ('K3', 'director', 'cinematographer', 0.9, "Keep it."),
    ('K3', 'odysseus', 'calypso', 1.0, "Do I still get the raft?"),
    ('K3', 'calypso', 'odysseus', 0.7, "Four days. You build it yourself."),
    ('K3', 'firstad', None, 1.0, "That's a wrap on the sea."),
    ('K3', 'crew-at-the-oars-5', 'firstad', 0.8, "I'll steer us home."),
  ],
  evidence=[
    ('the rowers on one clock', 'tools/perform/scenes/OD-B12-S03.js: ROWING machinery, clock period 2.6 s, offsets (a fraction of the stroke, tools/perform/machinery.js ROWING) crew 2 +0.04, crew 3 -0.03 ("coordinated labour, not a loop copied five times"); crew 5 STEER "at the steering oar"; the Sirens "sing on a clock of their own"'),
    ('I\'m the lead', 'OD-B05-S04 take 1 (1f1e8e81): "Calypso and Odysseus stand pressed together at the trees ... her lines play partly behind his head and the bow on his back"; the takes index: "Calypso\'s lines were hidden behind Odysseus"'),
    ('a man\'s height apart', 'OD-B05-S04 take 2 (afa9b394): "re-staged: the two stand a man\'s height apart ... so her lines (6-30 s) are held on her own face" (24 seconds)'),
    ('wax in their ears', 'tools/perform/scenes/OD-B12-S03.js: "Odysseus softens the wax and seals each man\'s ears"'),
    ('the top of the hour', 'odyssey/writers-room/BIBLE.md (the parent session re-arms a check-in at the top of every hour)'),
    ('the bow still across the frame', 'camera note OD-B05-S04: "Still wrong: the opening insert (0-6 s) has the bow on Odysseus\'s back across the frame in front of her"'),
  ]),
}
