import {nativeCore,boreCheck,saveStill,saveJSON} from './native-core.mjs';
const cv=document.querySelector('#screen'),status=document.querySelector('#status'),N=await nativeCore(cv),groups={},heads={old:[],new:[]};
window.addEventListener('unhandledrejection',e=>status.textContent='ERROR '+e.reason);
async function p(parent,id,col,x,y,z,rx=0){const g=await N.part(id,col);g.position.set(x,y,z);g.rotation.x=rx;parent.add(g);return g;}
for(const name of ['old','new']){const g=groups[name]=new THREE.Group();N.scene.add(g);for(let i=0;i<12;i++){const z=-i*55;heads[name].push(await p(g,name==='old'?'6541':'3917',71,0,name==='old'?90:52,z));for(let y=24;y<=(name==='old'?72:48);y+=24)await p(g,'3062b',70,0,y,z);}}
for(let x=-1;x<=1;x++)for(let z=0;z>=-7;z--)await p(N.scene,'3031',19,x*80,-4,z*80);
const arrow=await p(N.scene,'18041',297,0,80,35,-Math.PI/2),audit={parts:{old:'6541',new:'3917',projectile:'18041'},heads:12,centreline:[0,80],nativeScale:1,probeRadius:7,projectileRadialEnvelope:6.75,probes:{},limitations:['Native 18041 is a harpoon-shaped flight candidate, not a final fletched arrow','3917 is an aperture core; final axe blades and connector design remain open','32 circumference rays plus centre are sampled clearance evidence, not complete swept-mesh collision certification']};
for(const name of ['old','new']){status.textContent='Checking '+name+' opening against the real tip envelope';const results=[];for(let i=0;i<32;i++){const a=i*Math.PI*2/32;results.push({angle:a,...boreCheck(heads[name],[7*Math.cos(a),80+7*Math.sin(a),120],[0,0,-1],850)});}results.push({axis:true,...boreCheck(heads[name],[0,80,120],[0,0,-1],850)});audit.probes[name]=results.map(({angle,axis,triangles,hits,clear})=>({angle,axis,triangles,hitCount:hits.length,firstHit:hits[0],clear}));}
let selected='new';function draw(name=selected,u=0,close=true){selected=name;Object.entries(groups).forEach(([k,g])=>g.visible=k===name);arrow.position.z=35-690*u;const target=close?[0,80,arrow.position.z-30]:[0,65,-250];N.render(close?[145,175,arrow.position.z+185]:[270,295,385],target,40);const c=N.ctx;c.fillStyle='rgba(7,12,20,.93)';c.fillRect(0,0,1280,68);c.fillRect(0,642,1280,78);c.fillStyle='#efcf91';c.font='bold 25px system-ui';c.fillText(name==='old'?'REJECT · 18041 head is wider than the old bore':'PROMOTE FOR TEST · 3917 aperture + 18041 projectile',24,42);c.fillStyle='#d5deea';c.font='18px system-ui';c.fillText('Twelve native-scale openings · 32 probes at radius 7 LDU + centre ray',24,673);c.fillText('Aperture-core study · final axe blades, fletching and bow release remain unbuilt',24,700);}
draw();await saveJSON('aperture-forage',{...audit,loaded:[...N.loaded],missing:N.missing});status.textContent='READY · '+audit.probes.old.filter(p=>!p.clear).length+' old probes blocked / '+audit.probes.new.filter(p=>!p.clear).length+' new probes blocked';document.querySelector('#old').onclick=()=>draw('old');document.querySelector('#new').onclick=()=>draw('new');document.querySelector('#seek').oninput=e=>draw(selected,+e.target.value);
document.querySelector('#capture').onclick=async()=>{for(const name of ['old','new'])for(const [label,u,close]of[['tip',0,true],['middle',.5,true],['wide',0,false]]){draw(name,u,close);await saveStill('aperture-'+name+'-'+label,cv);}status.textContent='COMPLETE · failed and passing aperture evidence saved';};
