import {nativeCore,saveStill,saveJSON} from './native-core.mjs';
const cv=document.querySelector('#screen'),status=document.querySelector('#status'),select=document.querySelector('#candidate'),N=await nativeCore(cv),list=await(await fetch('hero-items/forage-round2-candidates.json')).json(),models=[];
window.addEventListener('unhandledrejection',e=>status.textContent='ERROR '+e.reason);
const def={...Minifig.DEFS['odysseus-wet'],weapon:null},rig=Minifig.skeleton(40,def),body=[];for(const [slot,id,col]of Minifig.partsOf(def))body.push(await N.raw(id,col));Minifig.mount(rig,body,def,N.scene);Face.attach(rig,def.face);Minifig.pose(rig,{phase:0,gait:0,t:0,swing:null,aim:0});
function profile(g,axis){g.updateWorldMatrix(true,true);let maxRad=0,verts=0,extreme=[];const p=new THREE.Vector3();g.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld);verts++;const r=axis==='Z'?Math.hypot(p.x,p.y):Math.hypot(p.x,p.z);if(r>maxRad){maxRad=r;extreme=p.toArray();}}});return{axis:'native '+axis+' through origin',maxRadialEnvelopeLDU:maxRad,vertexCount:verts,extremePoint:extreme,insideRadius6Envelope:maxRad<=6};}
for(const [i,row]of list.entries()){status.textContent=`Foraging ${i+1}/28 · ${row.part} · ${row.title}`;const g=await N.part(row.part,row.color);row.bounds=N.measurements[row.part];if(row.family==='arrow')row.projectileProfile=profile(g,['53451','65611','3813'].includes(row.part)?'Z':'Y');const box=new THREE.Box3().setFromObject(g);g.position.y=-box.min.y;N.scene.add(g);g.visible=false;models.push(g);const o=document.createElement('option');o.value=i;o.textContent=row.part+' · '+row.title;select.append(o);}
let reversed=false;
function show(i,reverse=false){models.forEach((g,j)=>g.visible=i===j);const g=models[i],row=list[i];rig.pos.set(row.bounds.max[0]+54,0,0);rig.figure.rotation.y=-.2;const box=new THREE.Box3().setFromObject(g);box.union(new THREE.Box3().setFromObject(rig.figure));const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const radius=Math.max(size.y*1.4,size.x*.92,size.z*1.2,130);N.render([center.x+(reverse?-1:1)*radius*.7,center.y+radius*.47,center.z+(reverse?-1:1)*radius*1.35],center.toArray(),38);const c=N.ctx;c.fillStyle='rgba(7,12,20,.93)';c.fillRect(0,0,1280,85);c.fillRect(0,624,1280,96);c.fillStyle='#efcf91';c.font='bold 25px system-ui';c.fillText(row.part+' · '+row.title,24,38);c.font='18px system-ui';c.fillStyle='#cad5e0';c.fillText(row.family.toUpperCase()+' / ACTUAL LDRAW GEOMETRY / '+(reverse?'REVERSE':'FRONT THREE-QUARTER'),24,67);c.fillText('Dimensions: '+row.bounds.size.map(n=>n.toFixed(1)).join(' × ')+' LDU  ·  20 LDU = one stud',24,656);c.fillText(row.projectileProfile?''+row.projectileProfile.axis+' radial envelope: '+row.projectileProfile.maxRadialEnvelopeLDU.toFixed(2)+' LDU · old axe-bore target radius: 6 LDU':'Same-scale Odysseus reference · no resizing of the part or figure',24,686);}
show(0);status.textContent='READY · 28 native-scale candidates';select.onchange=()=>{reversed=false;show(+select.value)};document.querySelector('#reverse').onclick=()=>{reversed=!reversed;show(+select.value,reversed)};
document.querySelector('#capture').onclick=async()=>{for(let i=0;i<list.length;i++){show(i);await saveStill('forage2-'+list[i].part,cv);show(i,true);await saveStill('forage2-'+list[i].part+'-reverse',cv);status.textContent='Captured '+(i+1)+'/28';}await saveJSON('forage-round2',{candidates:list,missing:N.missing,loaded:[...N.loaded],nativeScale:true,profileCaveat:'Bounding envelope is a conservative fit check for the declared native Y-axis. It is not a complete moving-mesh collision test or connector validation.'});status.textContent='COMPLETE · 56 native renders + dimension/profile receipt';};
