import {nativeCore,saveStill,saveJSON,boreCheck} from './native-core.mjs';
import {renderAsset} from '/halfworld/engine/halfworld-engine.mjs';
const screen=document.querySelector('#screen'),status=document.querySelector('#status');
window.addEventListener('unhandledrejection',e=>status.textContent='ERROR '+e.reason);
const N=await nativeCore(screen);
const list=[['30131',70,'Hollow tree stump'],['14769p83',19,'Growth-ring cap'],['2423',330,'Olive foliage'],['93231',70,'Long bow with molded arrow'],['4499',70,'Small bow with molded arrow'],['11096',71,'Twin-bladed axe candidate'],['6541',71,'Open Technic bore'],['3062b',70,'Round trunk / stake brick'],['30374',70,'4L shaft']];
const groups=[];for(const [id,col,label] of list){status.textContent='Foraging '+id+' '+label;await saveJSON('forage-progress',{loading:id});const g=await N.grounded(id,col);N.scene.add(g);g.visible=false;groups.push(g);}
const roots=await Promise.all(['olive-tree-marriage-bed','olivewood-stake','twelve-axe-heads','odysseuss-bow','axis-shot-arrow'].map(async n=>(await import('/halfworld/assets/prop/'+n+'.mjs')).default));
function view(i){groups.forEach((g,j)=>g.visible=j===i);const g=groups[i],b=new THREE.Box3().setFromObject(g),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3()),radius=Math.max(...size.toArray())*1.45;N.render([center.x+radius*.65,center.y+radius*.6,center.z+radius],center.toArray(),38);const c=N.ctx;c.fillStyle='rgba(5,9,15,.85)';c.fillRect(0,0,1280,52);c.fillRect(0,666,1280,54);c.fillStyle='#f0d3a0';c.font='24px system-ui';c.fillText(`${list[i][0]} · ${list[i][2]}`,28,35);c.font='18px monospace';c.fillText('ACTUAL LDRAW GEOMETRY · '+size.toArray().map(v=>v.toFixed(1)).join(' × ')+' LDU · native scale',28,699);}
await saveJSON('forage-progress',{stage:'sources loaded',measurements:N.measurements});
const audits=[];for(const [id,y]of[['11096',0],['6541',-10]]){const g=await N.part(id,71);audits.push({part:id,...boreCheck([g],[0,y,100],[0,0,-1],200)});}
await saveJSON('forage-audits',{audits});
view(0);status.textContent='READY · '+groups.length+' native candidates';
document.querySelector('#capture').onclick=async()=>{for(let i=0;i<groups.length;i++){view(i);await saveStill('forage-'+list[i][0],screen);}const cv=document.querySelector('#source');for(const asset of roots){renderAsset(cv,asset,{pipeline:'MESH',card:true});await saveStill('source-'+asset.id.replace('prop.',''),cv);for(const [state,node]of Object.entries(asset.states?.nodes||{})){renderAsset(cv,asset,{pipeline:'MESH',card:true,state:node.preview});await saveStill('source-'+asset.id.replace('prop.','')+'-'+state,cv);}}await saveJSON('hero-forage-receipt',{candidates:list,measurements:N.measurements,boreAudits:audits,missing:N.missing,loaded:[...N.loaded],sourceArtifacts:roots.map(a=>({id:a.id,params:a.params,anchors:a.anchors,states:a.states,collision:a.collision,ownership:a.ownership}))});status.textContent='COMPLETE · candidate renders, actual bounds, bore audits and five source artifact plates saved';};
