import{nativeCore,saveStill,saveJSON}from'./native-core.mjs';
import{renderAsset}from'/halfworld/engine/halfworld-engine.mjs';
const cv=document.querySelector('#screen'),status=document.querySelector('#status'),N=await nativeCore(cv),T=THREE;
window.addEventListener('unhandledrejection',e=>status.textContent='ERROR '+e.reason);
const specs=await(await fetch('locations/blockouts.json')).json(),cache=new Map(),groups=[],receipts=[];
for(const s of specs){const group=new T.Group();N.scene.add(group);groups.push(group);const obstacles=[];
 for(const p of s.parts){const key=p.part+'-'+p.color;if(!cache.has(key))cache.set(key,await N.part(p.part,p.color));const g=cache.get(key).clone(true);g.position.fromArray(p.pos);group.add(g);if(!['sea','ground','spring','launch-edge','canopy','lintel'].includes(p.role))obstacles.push(g);}
 group.updateMatrixWorld(true);const boxes=obstacles.map(g=>new T.Box3().setFromObject(g));let samples=0,hits=[];for(let seg=0;seg<s.route.length-1;seg++){const a=new T.Vector3(...s.route[seg]),b=new T.Vector3(...s.route[seg+1]);for(let i=0;i<=20;i++){samples++;const p=a.clone().lerp(b,i/20),body=new T.Box3(new T.Vector3(p.x-20,4,p.z-20),new T.Vector3(p.x+20,84,p.z+20));boxes.forEach((box,j)=>{if(box.intersectsBox(body))hits.push({seg,i,obstacle:j});});}}
 receipts.push({id:s.id,partInstances:s.parts.length,route:s.route,routeTest:{method:'63 sampled upright 40x80x40 LDU AABBs against obstacle AABBs; excludes surface, canopy, lintel',samples,hits},limitations:['Route checks are conservative boxes, not articulated walking or terrain support tests','Open-backed portal, stylized trees and loom proxies; physical connection/stability not certified','No elevation tiles fetched; no exact geographic reconstruction']});group.visible=false;}
const def={...Minifig.DEFS['odysseus-wet'],weapon:null},rig=Minifig.skeleton(40,def),parts=[];for(const[slot,id,col]of Minifig.partsOf(def))parts.push(await N.raw(id,col));Minifig.mount(rig,parts,def,N.scene);Face.attach(rig,def.face);rig.pos.set(0,0,40);Minifig.pose(rig,{phase:0,gait:0,t:0,swing:null,aim:0});
let current=0,view='wide';function draw(){groups.forEach((g,i)=>g.visible=i===current);const s=specs[current];N.scene.background.set('#99b6bd');N.render(...s.views[view]);const c=N.ctx;c.fillStyle='#101b24ed';c.fillRect(0,0,1280,58);c.fillRect(0,652,1280,68);c.fillStyle='#dbeabc';c.font='bold 25px system-ui';c.fillText(s.id.toUpperCase()+' · '+view.toUpperCase()+' / NATIVE STAGE BLOCKOUT',24,38);c.font='17px system-ui';c.fillStyle='#fff';c.fillText('Blue = water / springs · clear centre = shore-to-interior route · all rigid parts at native scale',24,678);c.fillText('Authored dimensions; no surveyed terrain claim. Actor, route and proxy props require performance development.',24,706);
 if(view==='plan'){for(const[name,pos]of Object.entries(s.anchors)){const p=new T.Vector3(...pos).project(N.camera);const x=(p.x+1)*640,y=(1-p.y)*360;c.fillStyle='#101b24';c.fillRect(x-4,y-21,name.length*10+12,26);c.fillStyle='#ffe19a';c.fillText(name,x,y);}}}
draw();status.textContent='READY · two native location blockouts';document.querySelector('#cove').onclick=()=>{current=0;view='wide';draw()};document.querySelector('#grove').onclick=()=>{current=1;view='wide';draw()};document.querySelector('#plan').onclick=()=>{view='plan';draw()};document.querySelector('#actor').onclick=()=>{view='actor';draw()};document.querySelector('#capture').onclick=async()=>{for(current=0;current<2;current++){for(view of['wide','actor','plan']){draw();await saveStill('location-'+specs[current].id+'-'+view,cv);}const asset=(await import('/halfworld/assets/location/'+specs[current].source+'.mjs')).default;renderAsset(document.querySelector('#source'),asset,{state:asset.preview(),card:true,pipeline:'MESH'});await saveStill('location-source-'+specs[current].id,document.querySelector('#source'));}await saveJSON('location-tests',{receipts,loaded:[...N.loaded],missing:N.missing});current=0;view='wide';draw();status.textContent='COMPLETE · six native renders, two source cards, route checks saved';};
