const $=id=>document.getElementById(id),prefix='monkey-workshop-v1:',states=new Map();
let film,editor,cut,currentTime=0,editing=false,busy=false,ready=false;
const fmt=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
const status=t=>$('status').textContent=t;
function controls(){for(const id of ['shot','scrub','preview','edit','export'])$(id).disabled=!ready||busy;$('keep').disabled=!editing||busy;$('restore').disabled=!$('states').value||busy;}
async function run(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){status(e.message);}finally{busy=false;controls();}}
function chooseTime(t){currentTime=Math.max(0,Math.min(83,Number(t)||0));film.setTime(currentTime);const i=cut.shots.findIndex(s=>currentTime<s.start+s.duration);$('shot').value=Math.max(0,i<0?cut.shots.length-1:i);$('scrub').value=currentTime;$('time').textContent=`${fmt(currentTime)} / 1:23`;$('direction').textContent=cut.shots[$('shot').value].action;}
function list(){const selected=$('states').value;$('states').replaceChildren(new Option('Choose a saved state…',''));for(const [id,s]of [...states].sort((a,b)=>a[1].filmTime-b[1].filmTime||a[1].name.localeCompare(b[1].name)))$('states').append(new Option(`${fmt(s.filmTime)} · ${s.name}`,id));if(states.has(selected))$('states').value=selected;controls();}
async function stash(named=false){if(!editing)return;const doc=JSON.parse(JSON.stringify(editor.snapshot()));doc.film='monkey-business';doc.filmTime=currentTime;doc.shot=Math.min(cut.shots.length-1,cut.shots.filter(s=>s.start<=currentTime).length-1);doc.name=named?($('name').value.trim()||cut.shots[doc.shot].name+' variation'):'Draft / '+cut.shots[doc.shot].name;const id=prefix+(named?crypto.randomUUID():'draft-'+currentTime.toFixed(1));await SceneHandoff.put(id,doc);states.set(id,doc);list();return id;}
function showEditor(on){$('editor').hidden=!on;$('film').hidden=on;$('preview').classList.toggle('active',!on);$('edit').classList.toggle('active',on);if(on)editor.fit();}
async function preview(){await stash();editing=false;showEditor(false);status('Scrub the performance, then edit a moment.');}
$('scrub').oninput=()=>run(async()=>{if(editing)await preview();chooseTime($('scrub').value);});
$('shot').onchange=()=>{const i=Number($('shot').value);run(async()=>{if(editing)await preview();chooseTime(cut.shots[i].start);});};
$('preview').onclick=()=>run(preview);
$('edit').onclick=()=>run(async()=>{if(editing){status('Already editing this moment. Use Scrub film to select another.');return;}const id=prefix+'draft-'+currentTime.toFixed(1),doc=states.get(id)||film.snapshot();showEditor(true);await editor.load(doc);editing=true;status(`${fmt(currentTime)} · ${doc.objects.length} assemblies · editing${states.has(id)?' saved draft':''}`);});
$('keep').onclick=()=>run(async()=>{const id=await stash(true);$('states').value=id;status('Named state saved in this browser. Export project for a portable copy.');});
$('states').onchange=controls;
$('restore').onclick=()=>run(async()=>{const id=$('states').value;await stash();const doc=states.get(id);if(!doc)throw Error('Choose a saved state.');chooseTime(doc.filmTime);showEditor(true);await editor.load(doc);editing=true;status('Opened '+doc.name);});
$('export').onclick=()=>run(async()=>{await stash();const blob=new Blob([JSON.stringify({format:'monkey-business-workshop',version:1,states:[...states.values()]})],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='monkey-business-workshop.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);status(`Exported ${states.size} shot states.`);});
$('import').onclick=()=>$('file').click();$('file').onchange=()=>run(async()=>{const file=$('file').files[0];if(!file)return;if(file.size>150e6)throw Error('Project exceeds 150 MB.');const data=JSON.parse(await file.text());if(data.format!=='monkey-business-workshop'||data.version!==1||!Array.isArray(data.states)||data.states.length>100)throw Error('Use a Monkey Business workshop project.');for(const d of data.states)if(d.format!=='odyssey-butter-scene'||d.version!==1||d.film!=='monkey-business'||!Number.isFinite(d.filmTime)||d.filmTime<0||d.filmTime>83||!Array.isArray(d.objects)||d.objects.length<1||d.objects.length>200)throw Error('Invalid shot state. Nothing imported.');await stash();for(const d of data.states){const id=prefix+crypto.randomUUID();await SceneHandoff.put(id,d);states.set(id,d);}list();status(`Imported ${data.states.length} states. Choose one and Open state.`);$('file').value='';});
window.addEventListener('beforeunload',e=>{if(editing){e.preventDefault();e.returnValue='';}});
async function init(){try{const started=Date.now();while(!(film=$('film').contentWindow.MonkeyFilm)||!(editor=$('editor').contentWindow.ButterSceneLoader)?.ready){if(Date.now()-started>60000)throw Error('Film or workshop did not load. Reload to retry.');await new Promise(r=>setTimeout(r,150));}cut=film.cut;cut.shots.forEach((s,i)=>$('shot').append(new Option(`${String(i+1).padStart(2,'0')} · ${s.name}`,i)));for(const item of await SceneHandoff.list())if(String(item.id).startsWith(prefix)){const doc=await SceneHandoff.get(item.id);if(doc?.film==='monkey-business')states.set(item.id,doc);}ready=true;list();chooseTime(new URLSearchParams(location.search).get('time')||0);showEditor(false);controls();status('13 shots ready · scrub, edit, keep a state.');}catch(e){status(e.message);}}
init();

$('takes').onclick=()=>{$('saved').open=!$('saved').open;};
