import {nativeCore} from './native-core.mjs';
const $=s=>document.querySelector(s),T=THREE,cv=$('canvas');
try{
const cut=await(await fetch('monkey-cut.json')).json(),N=await nativeCore(cv),roots=[],rigs=[],lights=[];
N.scene.background.set('#07141d');N.renderer.toneMappingExposure=1.2;
const v=a=>new T.Vector3(...a),mix=(a,b,u)=>a.map((x,i)=>x+(b[i]-x)*u),clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x)};
function group(name,parent=N.scene){const g=new T.Group();g.name=name;parent.add(g);if(parent===N.scene)roots.push(g);return g;}
async function p(parent,id,col,x,y,z,ry=0){const g=await N.part(id,col);g.position.set(x,y,z);g.rotation.y=ry;parent.add(g);return g;}
const set=group('Data center / floor and consoles');
for(let x=-4;x<=4;x++)for(let z=-3;z<=3;z++)await p(set,'3031',72,x*80,-8,z*80);
const keys=[],screens=[];
for(const x of[-95,65]){for(const dx of[-30,30])await p(set,'3003',0,x+dx,16,-25);await p(set,'3032',71,x,24,-25);
for(const dx of[-15,15]){const key=await p(set,'3024',dx<0?1:4,x+dx,32,-13);keys.push(key);}
await p(set,'3003',0,x,48,-57);await p(set,'3010',0,x,72,-57);
const panel=document.createElement('canvas');panel.width=512;panel.height=256;const tex=new T.CanvasTexture(panel);const screen=new T.Mesh(new T.PlaneGeometry(66,34),new T.MeshBasicMaterial({map:tex}));screen.position.set(x,59,-45);set.add(screen);screens.push({panel,tex});}
const dressing=group('Break-room plant and bananas');await p(dressing,'3941',70,285,24,70);for(const y of[32,56,80])await p(dressing,'3062b',70,285,y,70);await p(dressing,'6148',2,285,80,70);for(let i=0;i<3;i++)await p(dressing,'33085',14,-165+i*12,6,60+i*8,i*.5);
for(const x of[-240,-120,0,120,240]){const rack=group('Server rack '+x);for(let y=24;y<=168;y+=24){for(const dx of[-30,30])await p(rack,'3003',0,x+dx,y,-170);await p(rack,'3010',71,x,y,-170);}
for(let y=36;y<170;y+=24){const led=await p(rack,'3024',2,x+38,y,-147);led.traverse(o=>{if(o.isMesh){o.material=(Array.isArray(o.material)?o.material:[o.material]).map(m=>{const c=m.clone();c.emissive?.setHex(0x27bd8e);return c;});}});lights.push(led);}}
// Articulated animal: same native body, arms and hands as 2550c01.
for(let i=0;i<3;i++){const root=group(['Alpha','Beta','Gamma'][i]),body=group('body',root),limbs=[];body.position.y=27;await p(body,'2550',0,0,0,0);for(let j=0;j<4;j++){const limb=group('limb-'+j,body);limb.position.set(j%2?10:-10,9,j<2?14:-14);const rear=j>=2;limb.rotation.y=rear?Math.PI:0;await p(limb,j%2?'3819':'3818',0,0,0,0);await p(limb,'3820',14,j%2?5:-5,-19,10);limbs.push(limb);}rigs.push({root,body,limbs});}
// Inspector from native minifigure components, with shoulder pivots.
const idef={...Minifig.DEFS.citizen,torso:71,arms:71,legs:0,hips:0,hat:['3901',0],weapon:null};
idef.parts=Minifig.partsOf(idef).map(p=>p[0]==='head'?[p[0],'3626bp01',p[2]]:p);
const irig=Minifig.skeleton(40,idef),iparts=[];for(const [slot,id,c]of Minifig.partsOf(idef))iparts.push(await N.raw(id,c));Minifig.mount(irig,iparts,idef,N.scene);const inspector=irig.figure;inspector.name='Inspector';roots.push(inspector);
const warning=new T.PointLight(0xff382c,0,700);warning.position.set(0,190,-60);N.scene.add(warning);
let time=0,playing=false,last=0,shotIndex=-1,sound=true,ctx,bus,dest,oscillators=[],recording=null,chunks=[];
function audio(){if(ctx)return;ctx=new AudioContext();bus=ctx.createGain();bus.gain.value=.24;bus.connect(ctx.destination);dest=ctx.createMediaStreamDestination();bus.connect(dest);}
function tone(freq,duration,type='sine',level=.12){if(!ctx||!sound)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(level,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);o.connect(g);g.connect(bus);o.start();o.stop(ctx.currentTime+duration);oscillators.push(o);o.onended=()=>oscillators=oscillators.filter(x=>x!==o);}
function hush(){oscillators.forEach(o=>{try{o.stop()}catch{}});oscillators=[];speechSynthesis.cancel();}
const voiceFiles=await Promise.all(cut.shots.map((s,i)=>s.line.includes(':')&&i!==0?fetch('monkey-audio/'+i+'.wav').then(r=>{if(!r.ok)throw Error('Missing voice '+i);return r.arrayBuffer();}):null));let voiceBuffers=[];
function speak(s){if(!sound||!$('#voice').checked)return;const b=voiceBuffers[cut.shots.indexOf(s)];if(!b)return;const o=ctx.createBufferSource();o.buffer=b;const g=ctx.createGain();g.gain.value=3;o.connect(g);g.connect(bus);o.start();oscillators.push(o);o.onended=()=>oscillators=oscillators.filter(x=>x!==o);}

const locate=t=>Math.max(0,cut.shots.findIndex(s=>t<s.start+s.duration));
function pose(t){const alarm=t>=19&&t<64,repair=ease((t-35)/8),climb=ease((t-38)/7),recovery=ease((t-57)/7),freeze=t>=45&&t<57;
const positions=[[-95,0,22],[65,0,22],mix([170,0,65],[120,0,-117],repair)];positions[2][1]=climb*125*(1-ease((t-65)/8));
rigs.forEach((r,i)=>{r.root.position.fromArray(positions[i]);r.root.rotation.y=Math.PI;r.body.rotation.z=0;r.body.position.y=27;r.limbs.forEach((l,j)=>{l.rotation.x=freeze?-.85:i<2&&j<2?-.85+.20*Math.cos(t*8+j*Math.PI+i):Math.sin(t*7+j)*.16;if(i===2&&climb>.1&&t<64)l.rotation.x=j<2?-1.7+Math.sin(t*6)*.25:Math.sin(t*8+j)*.65;if(t>=71)l.rotation.x=j<2?-2.1+Math.sin(t*9)*.25:0;});if(t>=50&&i<2)r.root.rotation.y=Math.PI-ease((t-50)/2)*1.1;if(t>=78&&i===1)r.limbs[0].rotation.x=-1.2;});
inspector.visible=t>=45;inspector.position.set(-280+ease((t-45)/5)*110,0,125-ease((t-64)/5)*70);inspector.rotation.y=.8;Minifig.pose(irig,{phase:t*8,gait:t<50?.7:0,t});
keys.forEach((k,i)=>{const press=Math.max(0,Math.cos(t*8+(i%2)*Math.PI+Math.floor(i/2)));k.position.y=32-press*2;});
screens.forEach(({panel,tex},i)=>{const c=panel.getContext('2d');c.fillStyle='#04191e';c.fillRect(0,0,512,256);c.fillStyle=alarm?'#ff7155':'#72ffc5';c.font='bold 32px monospace';c.fillText(alarm?'COOLING OFFLINE':'OPS / '+(i?'BETA':'ALPHA'),20,48);for(let j=0;j<5;j++){const w=80+Math.abs(Math.sin(t*1.7+j))*310;c.fillRect(20,75+j*29,w,10);}tex.needsUpdate=true;});
warning.intensity=alarm?(1+Math.sin(t*7))*.75:0;lights.forEach((g,i)=>{g.visible=!alarm||Math.sin(t*8-i)>.1;g.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material]){m.color.setHex(alarm?0xe33227:0x36dda0);m.emissive?.setHex(alarm?0x721108:0x064d28);}});});}
function draw(t){const i=locate(Math.min(t,cut.duration-.001)),s=cut.shots[i],u=ease((t-s.start)/s.duration);pose(t);N.render(mix(s.from_,s.to,u),s.target,i===3?35:42);const c=N.ctx;c.fillStyle='#03080be8';c.fillRect(0,0,1280,48);c.fillRect(0,634,1280,86);c.fillStyle='#c7ee86';c.font='bold 17px system-ui';c.fillText('NIGHT SHIFT  /  '+String(i+1).padStart(2,'0')+'  '+s.name.toUpperCase(),28,31);c.fillStyle='#fff';c.font='23px system-ui';c.textAlign='center';c.fillText(s.line,640,682);c.textAlign='left';if(t<4||t>79){const fade=t<4?1-ease(t/4):ease((t-79)/4);c.fillStyle=`rgba(3,8,11,${fade*.8})`;c.fillRect(0,48,1280,586);c.fillStyle=`rgba(235,247,230,${fade})`;c.font='bold 65px system-ui';c.textAlign='center';c.fillText('MONKEY',640,285);c.fillText('BUSINESS',640,355);c.font='19px system-ui';c.fillStyle=`rgba(199,238,134,${fade})`;c.fillText('N I G H T   S H I F T',640,405);c.textAlign='left';}$('#timeline').value=t;$('#time').textContent=`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')} / ${Math.floor(cut.duration/60)}:${String(cut.duration%60).padStart(2,'0')}`;$('#direction').textContent=s.action;$('#shots').value=i;return i;}
let beat=-1;function tick(now){if(playing){const prior=time;time+=(now-last)/1000;const i=locate(Math.min(time,cut.duration-.001));if($('#loop').checked&&shotIndex>=0&&i!==shotIndex){time=cut.shots[shotIndex].start;hush();}if(time>=cut.duration){time=cut.duration;pause();if(recording)recording.stop();}const n=draw(time);if(n!==shotIndex){shotIndex=n;speak(cut.shots[n]);}const b=Math.floor(time*2.8);if(b!==beat){beat=b;const tense=time>=19&&time<64;tone((tense?[110,116.54,164.81,146.83]:[130.81,164.81,196,261.63])[b%4],.3,'triangle',.13);if(b%4===0)tone(55,.3,'sine',.3);if(tense&&b%8===0)tone(880,.18,'square',.06);if(b%2===0&&time<45)tone(1800+b%7*100,.025,'square',.025);if(prior<64&&time>=64){tone(523,.8);tone(659,1);tone(784,1.2);}}}last=now;requestAnimationFrame(tick);}function pause(){playing=false;$('#play').textContent='▶ Watch film';hush();}async function play(){if(time>=cut.duration)time=0;audio();ctx.resume();if(!voiceBuffers.length)voiceBuffers=await Promise.all(voiceFiles.map(b=>b?ctx.decodeAudioData(b.slice(0)):null));playing=true;last=performance.now();shotIndex=-1;$('#play').textContent='Ⅱ Pause';}
$('#play').onclick=()=>playing?pause():play();$('#restart').onclick=()=>{pause();time=0;draw(0);};$('#timeline').max=cut.duration;$('#timeline').oninput=e=>{pause();time=+e.target.value;shotIndex=draw(time);};$('#sound').onclick=()=>{sound=!sound;if(bus)bus.gain.value=sound?.24:0;if(!sound)hush();$('#sound').textContent=sound?'♫ Sound on':'♫ Sound off';$('#sound').setAttribute('aria-pressed',sound);};$('#rehearse').onclick=()=>{$('#stage').hidden=!$('#stage').hidden;};cut.shots.forEach((s,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}. ${s.name} · ${s.duration}s`;$('#shots').append(o);});$('#shots').onchange=e=>{pause();shotIndex=+e.target.value;time=cut.shots[shotIndex].start;draw(time);};
$('#butter').onclick=async()=>{pause();const objects=roots.filter(g=>g.visible).map(g=>({name:g.name,kind:'assembly',object:g.toJSON()}));const id='monkey-'+Date.now();await SceneHandoff.put(id,{format:'odyssey-butter-scene',version:1,name:'Night Shift / '+cut.shots[locate(time)].name,source:location.href,objects});location.href='native/hand-butter-scenes.html?scene='+id;};
$('#record').onclick=()=>{if(recording){recording.stop();pause();return;}audio();ctx.resume();time=0;$('#loop').checked=false;draw(0);const stream=cv.captureStream(24);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));recording=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?'video/webm;codecs=vp9,opus':'video/webm'});chunks=[];recording.ondataavailable=e=>chunks.push(e.data);recording.onstop=async()=>{const blob=new Blob(chunks,{type:'video/webm'});if(location.hostname==='127.0.0.1'){const data=await new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(blob);});await fetch('/evidence/night-shift-recording.json',{method:'POST',body:JSON.stringify({data})});}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:'video/webm'}));a.download='night-shift-original-cut.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);recording=null;$('#record').textContent='Record film';$('#status').textContent='Film saved · recorded dialogue, music and effects';};recording.start();$('#record').textContent='Stop recording';$('#status').textContent='Recording · music & effects included; recorded dialogue, music & effects';play();};
if(location.hostname==='127.0.0.1'){const exportButton=document.createElement('button');exportButton.textContent='Render complete cut';$('#stage').append(exportButton);exportButton.onclick=async()=>{pause();exportButton.disabled=true;for(let f=0;f<cut.duration*12;f++){draw(f/12);const blob=await new Promise(r=>cv.toBlob(r,'image/jpeg',.9));await fetch('/capture/night-shift/'+String(f).padStart(5,'0'),{method:'POST',body:blob});if(f%12===0)$('#status').textContent='Rendering '+Math.floor(f/12)+' / '+cut.duration+' seconds';}$('#status').textContent='Complete cut rendered · 996 frames';exportButton.disabled=false;};}
// Same-origin workshop bridge: deterministic time and editable geometry snapshot.
window.MonkeyFilm={
 setTime(t){pause();time=Math.max(0,Math.min(cut.duration,Number(t)||0));draw(time);return time;},
 snapshot(){pose(time);return {format:'odyssey-butter-scene',version:1,name:'Monkey Business / '+cut.shots[locate(Math.min(time,cut.duration-.001))].name,film:'monkey-business',filmTime:time,shot:locate(Math.min(time,cut.duration-.001)),objects:roots.filter(g=>g.visible).map(g=>({name:g.name,kind:'assembly',object:g.toJSON()}))};},
 get time(){return time;},cut
};
if(N.missing.length)throw Error('Missing geometry: '+N.missing.join(', '));$('#status').textContent=`Ready · ${cut.duration} seconds · ${cut.shots.length} shots`;for(const id of ['play','record','butter'])$('#'+id).disabled=false;draw(0);requestAnimationFrame(tick);
}catch(e){$('#error').textContent='Could not assemble film: '+e.message;$('#status').textContent='Load failed';console.error(e);}
