import {nativeCore} from './iron-native-core.mjs';
import {clamp,mix,keysAt,locate,setKey,validate} from './iron-timeline.mjs';
const $=id=>document.getElementById(id),T=THREE,V=a=>new T.Vector3(...a),U=40,store='monkey-iron-undaunted-v1';
let N,doc,source,time=0,playing=false,editing=false,last=0,selected='Lewis',history=[],active=-1,ready=false,sound=true,audio,master,destination,voices=[],audioNodes=[],recording=null,look=null,drag=null;
const baseStates=new Map(),entities=new Map(),ropes=[],waterLines=[],rain=[],paddles=[],status=t=>$('status').textContent=t;
const duration=()=>doc.shots.reduce((n,s)=>n+s.duration,0),current=()=>locate(doc.shots,time),clone=v=>JSON.parse(JSON.stringify(v));
function backup(){history.push(clone(doc));if(history.length>30)history.shift();}
async function part(parent,id,color,pos=[0,0,0],yaw=0){const g=await N.part(id,color);g.position.fromArray(pos);g.rotation.y=yaw;parent.add(g);return g;}
async function build(){
 N=await nativeCore($('film'),{ldrawPath:location.pathname.includes('/odyssey-production/')?'../ldraw/':'native/ldraw/',progress:false});N.renderer.toneMappingExposure=1.0;N.scene.fog=new T.Fog(0x829998,650,2100);
 const sun=N.scene.children.find(o=>o.isDirectionalLight);sun.position.set(-420,600,-420);sun.intensity=1.7;
 const land=new T.Group();N.scene.add(land);land.name='River gorge / production terrain';
 // Layered brick banks, stepped rock silhouettes and native trees give the lens foreground/middle/background.
 const bankProto=await N.part('3031',28),rockProto=await N.part('3040b',72),treeProto=await N.part('3471',288);
 for(let side of [-1,1])for(let z=-1000;z<=650;z+=80){for(let x=0;x<13;x++){const g=bankProto.clone(true);g.position.set(side*(180+x*80),16,z);land.add(g);}for(let k=0;k<4;k++){if(side>0&&z>-500)continue;const g=rockProto.clone(true);g.position.set(side*(170+k*45),8+k*23+Math.sin(z*.017+k)*12,z+Math.sin(k+z)*22);g.scale.set(1.4+k*.2,1.4+Math.abs(Math.sin(z))*.7,1.8);g.rotation.y=(side<0?Math.PI:0)+Math.sin(z+k)*.25;land.add(g);}}
 for(let i=0;i<34;i++){const side=i%2?1:-1,g=treeProto.clone(true);g.position.set(side*(650+(i%4)*90),16,-1000+i*49);g.scale.setScalar(.85+(i%3)*.15);land.add(g);}
 // Large distant masses are brick assemblies rather than an empty black stage.
 for(let i=0;i<48;i++){const g=rockProto.clone(true);g.position.set((i%12-6)*110,80+Math.floor(i/12)*90,-1000-Math.floor(i/12)*90);g.scale.set(6,4,6);land.add(g);}
 const water=new T.Mesh(new T.PlaneGeometry(310,4000),new T.MeshStandardMaterial({color:0x365b63,roughness:.28,metalness:.3}));water.rotation.x=-Math.PI/2;water.position.set(0,4,-700);water.receiveShadow=true;N.scene.add(water);
 for(let i=0;i<60;i++){const line=new T.Mesh(new T.PlaneGeometry(15+i%5*8,1.4),new T.MeshBasicMaterial({color:0xbac9b4,transparent:true,opacity:.24}));line.rotation.x=-Math.PI/2;line.position.set(Math.sin(i*4)*130,4.3,i*30-1000);N.scene.add(line);waterLines.push(line);}
 const boat=new T.Group();boat.name='boat';N.scene.add(boat);const hull=await N.grounded('6021',70);boat.add(hull);entities.set('boat',{root:boat});
 for(const [i,name]of ['Lewis','Clark','Ordway','Scout'].entries()){
  status('Rigging '+name+' from separate native minifigure parts…');const def={...Minifig.DEFS.citizen,legs:i===3?70:19,hips:i===3?70:19,torso:[1,2,1,70][i],arms:[1,2,1,70][i],hat:[i===0?'2528a':'13788',i===3?70:0],weapon:null};def.parts=Minifig.partsOf(def).map(p=>p[0]==='head'?[p[0],'3626bp01',p[2]]:p);const rig=Minifig.skeleton(40,def),parts=[];for(const [slot,id,c] of Minifig.partsOf(def))parts.push(await N.raw(id,c));Minifig.mount(rig,parts,def,N.scene);rig.figure.name=name;entities.set(name,{root:rig.figure,rig});
  const oar=await N.raw('3841',70);oar.rotation.set(.5,0,Math.PI/2);oar.position.set(0,0,0);rig.slots.handR.add(oar);paddles.push(oar);entities.get(name).oar=oar;
 }
 const table=new T.Group();table.position.set(220,24,-205);N.scene.add(table);await part(table,'3001',70,[0,24,0]);await part(table,'3001',70,[0,48,0]);await part(table,'3032',70,[0,56,0]);
 const mapCanvas=document.createElement('canvas');mapCanvas.width=512;mapCanvas.height=256;const c=mapCanvas.getContext('2d');c.fillStyle='#d7bd83';c.fillRect(0,0,512,256);c.strokeStyle='#527875';c.lineWidth=9;c.beginPath();c.moveTo(30,230);c.bezierCurveTo(210,30,270,240,430,10);c.stroke();c.strokeStyle='#675536';c.lineWidth=2;for(let i=0;i<12;i++){c.beginPath();c.moveTo(230+i*17,150);c.lineTo(240+i*17,105-i%4*12);c.lineTo(255+i*17,150);c.stroke();}c.fillStyle='#493d2e';c.font='20px serif';c.fillText('A WAY THROUGH',30,36);const m=new T.Mesh(new T.PlaneGeometry(64,36),new T.MeshStandardMaterial({map:new T.CanvasTexture(mapCanvas),roughness:.9}));m.rotation.x=-Math.PI/2;m.position.y=65;table.add(m);entities.set('map-table',{root:table});
 for(let i=0;i<3;i++){const rope=new T.Line(new T.BufferGeometry().setFromPoints([V([0,0,0]),V([0,0,0])]),new T.LineBasicMaterial({color:0xc8b584}));N.scene.add(rope);ropes.push(rope);}
 const rainGeo=new T.BufferGeometry(),arr=[];for(let i=0;i<350;i++)arr.push(Math.sin(i*12.7)*600,(i%70)*9,Math.cos(i*4.6)*650-100);rainGeo.setAttribute('position',new T.Float32BufferAttribute(arr,3));const drops=new T.Points(rainGeo,new T.PointsMaterial({color:0xcadce1,size:1.7,transparent:true,opacity:.5}));N.scene.add(drops);rain.push(drops);
 for(const [id,e]of entities)baseStates.set(id,{pos:e.root.position.toArray(),yaw:e.root.rotation.y});for(const p of doc.props)await addProp(p);status('Ready · six connected shots / native articulated cast');
}
async function addProp(p){const root=await N.grounded(p.part,70);root.position.fromArray(p.pos);root.name=p.id;N.scene.add(root);entities.set(p.id,{root});}
function menus(){const keep=$('shot').value;$('shot').replaceChildren();doc.shots.forEach((s,i)=>$('shot').append(new Option(`${i+1} · ${s.name}`,i)));$('shot').value=current().i;$('scrub').max=duration();$('entity').replaceChildren();for(const id of entities.keys())$('entity').append(new Option(id,id));$('entity').value=selected;tracks();}
function tracks(){const {i}=current();$('tracks').replaceChildren();for(const [label,kind] of [['LENS','camera'],['ACTION','action'],['VOICE','line']]){const row=document.createElement('div');row.className='track';const span=document.createElement('span');span.textContent=label;row.append(span);doc.shots.forEach((s,j)=>{const b=document.createElement('button');b.className=j===i?'current':'';b.textContent=kind==='camera'?s.camera.length+' keys':kind==='action'?s.tracks[selected]?.action||'set':s.line?'●':'—';b.title=s.name+' · '+(kind==='action'?s.action:kind==='line'?s.line:'Camera keys');b.onclick=()=>seek(doc.shots.slice(0,j).reduce((n,s)=>n+s.duration,0));row.append(b);});$('tracks').append(row);}}
function fields(){const {i,local}=current(),s=doc.shots[i],track=s.tracks[selected],p=track?keysAt(track.keys,local):{pos:entities.get(selected).root.position.toArray(),yaw:0};['x','y','z'].forEach((id,j)=>$(id).value=(p.pos[j]/U).toFixed(2));$('yaw').value=Math.round(p.yaw*180/Math.PI);$('action').value=track?.action||'idle';$('title').value=s.name;$('duration').value=s.duration;$('line').value=s.line;$('light').value=s.light;$('weather').value=s.weather;$('fov').value=keysAt(s.camera,local).fov;}
function pose(s,t){const cache=new Map();function state(id,seen=new Set()){if(cache.has(id))return cache.get(id);if(seen.has(id))throw Error('Cyclic attachment');seen.add(id);const tr=s.tracks[id];if(!tr)return null;const p=keysAt(tr.keys,t);if(tr.parent){const parent=state(tr.parent,seen);if(!parent)throw Error('Missing parent '+tr.parent);const x=p.pos[0],z=p.pos[2];p.pos=[parent.pos[0]+x*Math.cos(parent.yaw)+z*Math.sin(parent.yaw),parent.pos[1]+p.pos[1],parent.pos[2]-x*Math.sin(parent.yaw)+z*Math.cos(parent.yaw)];p.yaw+=parent.yaw;}cache.set(id,p);return p;}
 for(const [id,e]of entities){const tr=s.tracks[id],p=state(id);const prop=doc.props.find(p=>p.id===id),base=prop?{pos:prop.pos,yaw:0}:baseStates.get(id);e.root.visible=!id.startsWith('prop-')||!!prop;if(p){e.root.position.fromArray(p.pos);e.root.rotation.y=p.yaw;}else if(base){e.root.position.fromArray(base.pos);e.root.rotation.y=base.yaw;}if(e.rig){const r=e.rig,a=tr?.action||'idle',phase=t*4;Minifig.pose(r,{gait:a==='walk'||a==='haul'?.55:0,phase,t,sit:a==='row'});r.headP.rotation.y=a==='point'?-.5:Math.sin(t)*.1;r.armRP.rotation.z=0;r.armLP.rotation.z=0;r.torsoP.rotation.x=0;if(a==='row'){r.armRP.rotation.x=-1.2+Math.sin(phase)*.35;r.armLP.rotation.x=-1.1+Math.sin(phase)*.25;r.torsoP.rotation.x=Math.sin(phase)*.1;}if(a==='haul'){r.armRP.rotation.x=-1.15;r.armLP.rotation.x=-1.05;r.torsoP.rotation.x=.16;}if(a==='point'){r.armRP.rotation.x=-1.5;r.armRP.rotation.z=-.25;}if(a==='map'){r.armLP.rotation.x=-1.05;r.armRP.rotation.x=-1.1;r.headP.rotation.x=.2;}else r.headP.rotation.x=0;e.oar.visible=a==='row';}}
 N.scene.updateMatrixWorld(true);['Lewis','Clark','Ordway'].forEach((id,i)=>{const e=entities.get(id);ropes[i].visible=s.tracks[id]?.action==='haul';if(ropes[i].visible){const a=e.rig.slots.handR.getWorldPosition(new T.Vector3()),b=entities.get('boat').root.localToWorld(V([28,26,-65+i*60]));ropes[i].geometry.setFromPoints([a,b]);}});
 waterLines.forEach((l,i)=>l.position.z=((i*30+t*18)%1800)-1100);rain[0].visible=s.weather==='rain';rain[0].position.y=-(t*130)%300;
}
function draw(){if(!ready)return;const {i,local}=current(),s=doc.shots[i];if(active!==i){active=i;look=null;$('shot').value=i;tracks();if(editing)fields();}pose(s,local);const colors={dawn:0x879b95,overcast:0x82949e,dusk:0x56616b};N.scene.background.setHex(colors[s.light]||colors.dawn);N.scene.fog.color.copy(N.scene.background);N.scene.fog.near=s.weather==='clear'?1600:650;N.scene.fog.far=s.weather==='clear'?3000:2000;N.renderer.toneMappingExposure=s.light==='dusk'?.65:s.light==='overcast'?.85:1.0;const k=editing&&look?look:keysAt(s.camera,local);N.render(k.pos,k.target,k.fov);const c=N.ctx;c.fillStyle='#081215';c.fillRect(0,0,1280,43);c.fillRect(0,650,1280,70);c.fillStyle='#d4c18a';c.font='16px system-ui';c.fillText('UNDAUNTED COURAGE / '+s.name.toUpperCase(),24,28);c.fillStyle='#f6edd7';c.textAlign='center';c.font='22px Georgia';const words=s.line.split(' ');let lines=[''];for(const w of words){const j=lines.length-1;if(c.measureText(lines[j]+w).width>1170)lines.push(w+' ');else lines[j]+=w+' ';}lines.slice(0,2).forEach((l,j)=>c.fillText(l.trim(),640,678+j*25));if(i===5&&local>4){c.fillStyle=`rgba(7,18,20,${clamp((local-4)/4)*.55})`;c.fillRect(0,43,1280,607);c.fillStyle='#f0dfb0';c.font='42px Georgia';c.fillText('UNDAUNTED COURAGE',640,280);c.font='18px system-ui';c.fillText('THE RIVER MAKES THE TERMS',640,320);}c.textAlign='left';$('scrub').value=time;$('time').textContent=time.toFixed(1)+' / '+duration()+'s';$('note').textContent=s.id+' · '+s.action+(editing?' · '+selected+' / '+local.toFixed(1)+'s':'');}
function seek(t){pause();time=clamp(t,0,duration()-.001);look=null;draw();if(editing)fields();}
function hush(){for(const n of audioNodes){try{n.stop();}catch{}}audioNodes=[];speechSynthesis.cancel();}
function pause(){playing=false;$('play').textContent='▶ Watch';hush();}
function audioInit(){if(!audio){audio=new AudioContext();master=audio.createGain();master.gain.value=sound?.5:0;master.connect(audio.destination);destination=audio.createMediaStreamDestination();master.connect(destination);}return audio.resume();}
function tone(f,t,gain=.07){const n=audio.createOscillator(),g=audio.createGain();n.type='triangle';n.frequency.value=f;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+t);n.connect(g);g.connect(master);n.start();n.stop(audio.currentTime+t);audioNodes.push(n);n.onended=()=>audioNodes=audioNodes.filter(v=>v!==n);}
function noise(length=.2,gain=.05){const b=audio.createBuffer(1,audio.sampleRate*length,audio.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=(Math.random()*2-1)*(1-i/a.length);const n=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain();filter.type='lowpass';filter.frequency.value=650;g.gain.value=gain;n.buffer=b;n.connect(filter);filter.connect(g);g.connect(master);n.start();audioNodes.push(n);n.onended=()=>audioNodes=audioNodes.filter(v=>v!==n);}
async function start(){if(!ready)return;editing=false;$('inspector').hidden=true;look=null;await audioInit();await refreshVoices();if(time>=duration()-.01)time=0;playing=true;last=performance.now();lastVoice=-1;beat=-1;$('play').textContent='Ⅱ Pause';}
let beat=-1,lastVoice=-1;const voiceCache=new Map();
async function refreshVoices(){voices=await Promise.all(doc.shots.map(async s=>{const url=s.audio||'undaunted-iron-audio/'+s.id+'.wav';if(voiceCache.has(url))return voiceCache.get(url);try{const r=await fetch(url),b=r.ok?await audio.decodeAudioData(await r.arrayBuffer()):null;voiceCache.set(url,b);return b;}catch{return null;}}));}

function tick(now){if(playing){time=Math.min(duration()-.001,time+Math.min(.1,(now-last)/1000));const {i}=current(),s=doc.shots[i];if(i!==lastVoice){hush();lastVoice=i;if(voices[i]&&(s.line===s.originalLine||s.audio)){const n=audio.createBufferSource();n.buffer=voices[i];n.connect(master);n.start();audioNodes.push(n);}}const b=Math.floor(time*2);if(b!==beat){beat=b;tone([98,130.81,146.83,196][b%4],.7,.065);if(b%4===0)tone(49,1.3,.12);noise(.32,i<3?.1:.045);}draw();if(time>=duration()-.01){pause();if(recording?.state==='recording')recording.stop();}}last=now;requestAnimationFrame(tick);}
$('play').onclick=()=>playing?pause():start();$('scrub').oninput=e=>seek(+e.target.value);$('shot').onchange=e=>seek(doc.shots.slice(0,+e.target.value).reduce((n,s)=>n+s.duration,0));for(const [id,d]of [['prev',-1],['next',1]])$(id).onclick=()=>seek(doc.shots.slice(0,clamp(current().i+d,0,doc.shots.length-1)).reduce((n,s)=>n+s.duration,0));
$('edit').onclick=()=>{if(!ready)return;pause();editing=!editing;$('inspector').hidden=!editing;$('edit').classList.toggle('on',editing);if(editing)fields();else look=null;draw();};$('sound').onclick=()=>{sound=!sound;if(master)master.gain.value=sound?.5:0;$('sound').textContent=sound?'♫ On':'♫ Off';};$('project').onclick=()=>$('projectPanel').hidden=!$('projectPanel').hidden;
for(const b of document.querySelectorAll('[data-pane]'))b.onclick=()=>{for(const id of ['blocking','lens','story'])$(id).hidden=id!==b.dataset.pane;};$('entity').onchange=()=>{selected=$('entity').value;fields();tracks();};
$('key').onclick=()=>{const p=['x','y','z'].map(id=>Number($(id).value)*U),yaw=Number($('yaw').value)*Math.PI/180;if(!p.every(Number.isFinite)||!Number.isFinite(yaw))return status('Enter finite coordinates');backup();const {i,local}=current(),s=doc.shots[i],tr=s.tracks[selected]||(s.tracks[selected]={action:'idle',keys:[{t:0,pos:entities.get(selected).root.position.toArray(),yaw:0}]});tr.action=$('action').value;setKey(tr,{t:local,pos:p,yaw});draw();tracks();status('Key saved at '+local.toFixed(2)+'s · undo available');};
$('undo').onclick=()=>{if(history.length){doc=history.pop();menus();draw();fields();status('Previous take restored');}};
$('cameraKey').onclick=()=>{backup();const {i,local}=current(),k=look||keysAt(doc.shots[i].camera,local);setKey({keys:doc.shots[i].camera},{...clone(k),t:local,fov:Number($('fov').value)});look=null;draw();tracks();status('Lens key captured');};$('focus').onclick=()=>{const p=entities.get(selected).root.position.toArray();look={pos:[p[0]+125,p[1]+95,p[2]+145],target:[p[0],p[1]+45,p[2]],fov:38};draw();};$('fov').oninput=()=>{look=look||keysAt(doc.shots[current().i].camera,current().local);look.fov=+$('fov').value;draw();};
$('film').onpointerdown=e=>{if(!editing||$('lens').hidden)return;look=look||keysAt(doc.shots[current().i].camera,current().local);drag={x:e.clientX,y:e.clientY,pos:[...look.pos]};$('film').setPointerCapture(e.pointerId);};$('film').onpointermove=e=>{if(!drag)return;const offset=V(drag.pos).sub(V(look.target)),sph=new T.Spherical().setFromVector3(offset);sph.theta-=(e.clientX-drag.x)*.008;sph.phi=clamp(sph.phi+(e.clientY-drag.y)*.006,.1,1.5);look.pos=V(look.target).add(new T.Vector3().setFromSpherical(sph)).toArray();draw();};$('film').onpointerup=()=>drag=null;$('film').onpointercancel=()=>drag=null;$('film').onwheel=e=>{if(!editing||$('lens').hidden)return;e.preventDefault();look=look||keysAt(doc.shots[current().i].camera,current().local);look.pos=V(look.target).add(V(look.pos).sub(V(look.target)).multiplyScalar(e.deltaY>0?1.08:.92)).toArray();draw();};
$('applyStory').onclick=()=>{const d=+$('duration').value;if(!Number.isFinite(d)||d<2||d>30)return status('Duration must be 2–30 seconds');backup();const {i,local}=current(),s=doc.shots[i],ratio=d/s.duration;for(const k of [...s.camera,...Object.values(s.tracks).flatMap(t=>t.keys)])k.t*=ratio;s.duration=d;s.name=$('title').value;s.line=$('line').value;s.light=$('light').value;s.weather=$('weather').value;time=doc.shots.slice(0,i).reduce((n,s)=>n+s.duration,0)+local*ratio;menus();draw();status(s.line!==s.originalLine?'New dialogue saved; original recording skipped.':'Shot and atmosphere updated');};$('speak').onclick=()=>{speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance($('line').value));};
$('add').onclick=async()=>{if(!ready)return;const b=$('add');pause();b.disabled=true;try{const p={id:'prop-'+Date.now(),part:$('part').value,pos:entities.get(selected).root.position.clone().add(V([80,0,0])).toArray()};await addProp(p);backup();doc.props.push(p);selected=p.id;menus();fields();draw();status('Native part placed · key its position');}catch(e){status(e.message);}finally{b.disabled=false;}};
$('save').onclick=async()=>{try{await SceneHandoff.put(store,clone(doc));status('Take saved in this browser · Export for backup');}catch(e){status(e.message);}};
function download(data,name,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('export').onclick=()=>download(JSON.stringify(doc,null,2),'undaunted-monkey-iron.json','application/json');$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{try{const f=$('file').files[0];if(!f)return;if(f.size>20e6)throw Error('Project limit 20 MB');const next=validate(JSON.parse(await f.text()));for(const p of next.props)if(!entities.has(p.id))await addProp(p);backup();doc=next;time=0;active=-1;menus();draw();fields();status('Project restored');}catch(e){status(e.message);}};
$('reset').onclick=()=>{pause();backup();doc=clone(source);time=0;active=-1;menus();draw();status('New source take · Undo keeps your previous cut');};
$('record').onclick=async()=>{if(recording?.state==='recording'){recording.stop();pause();return;}await audioInit();const stream=$('film').captureStream(24);destination.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')?'video/webm;codecs=vp8,opus':'video/webm';recording=new MediaRecorder(stream,{mimeType:mime});const chunks=[];recording.ondataavailable=e=>chunks.push(e.data);recording.onstop=()=>{download(new Blob(chunks,{type:mime}),'undaunted-iron.webm',mime);recording=null;status('Refilmed cut downloaded with recorded voices, music and effects');$('record').textContent='Record WebM';};time=0;active=-1;$('projectPanel').hidden=true;recording.start();$('record').textContent='Stop recording';await start();};
try{source=validate(await(await fetch('undaunted-iron-cut.json')).json());const saved=await SceneHandoff.get(store);doc=saved?validate(saved):clone(source);await build();audioInit();voices=await Promise.all(doc.shots.map(async s=>{try{const r=await fetch(s.audio||'undaunted-iron-audio/'+s.id+'.wav');return r.ok?await audio.decodeAudioData(await r.arrayBuffer()):null;}catch{return null;}}));ready=true;menus();draw();requestAnimationFrame(tick);}catch(e){status('Could not assemble: '+e.message);console.error(e);}

$('still').onclick=()=>{$('film').toBlob(blob=>download(blob,current().i+'-blocking.png','image/png'));};
$('attachVoice').onclick=()=>$('audioFile').click();$('audioFile').onchange=async()=>{try{const f=$('audioFile').files[0];if(!f)return;if(f.size>8e6)throw Error('Use an audio file under 8 MB');await audioInit();const buffer=await audio.decodeAudioData(await f.arrayBuffer()),url=await new Promise((r,j)=>{const fReader=new FileReader();fReader.onload=()=>r(fReader.result);fReader.onerror=j;fReader.readAsDataURL(f);});backup();const i=current().i;doc.shots[i].audio=url;voices[i]=buffer;status('Recorded line attached and included in refilming');}catch(e){status(e.message);}};

for(const [id,delta] of [['turnLeft',-15],['turnRight',15]])$(id).onclick=()=>{if(!ready)return;$('yaw').value=Number($('yaw').value)+delta;$('key').click();fields();};
