import {nativeCore,saveStill,saveJSON} from './native-core.mjs';
import {renderAsset} from '/halfworld/engine/halfworld-engine.mjs';
import source from '/halfworld/assets/prop/mast-ropes-and-beeswax.mjs';
const cv=document.querySelector('#screen'),status=document.querySelector('#status'),N=await nativeCore(cv),T=THREE;
window.addEventListener('unhandledrejection',e=>status.textContent='ERROR '+e.reason);
async function part(id,col,x,y,z){const g=await N.part(id,col);g.position.set(x,y,z);N.scene.add(g);return g;}
const mast=new T.Group();N.scene.add(mast);for(let y=24;y<=240;y+=24){const g=await N.part('3941',70);g.position.y=y;mast.add(g);}
for(let x=-1;x<=1;x++)for(let z=-1;z<=1;z++)await part('3031',19,x*80,-4,z*80);
const def={...Minifig.DEFS['odysseus-wet'],weapon:null},rig=Minifig.skeleton(40,def),parts=[];for(const [slot,id,col]of Minifig.partsOf(def))parts.push(await N.raw(id,col));Minifig.mount(rig,parts,def,N.scene);Face.attach(rig,def.face);rig.pos.set(0,0,28);Minifig.pose(rig,{phase:0,gait:0,t:0,swing:null,aim:0});
const templates=await N.part('71149k02',19),sets={},levels=[33,39,45,51,57,63],receipt={source:'prop.mast-ropes-and-beeswax',parts:{mast:'10 × 3941 round bricks; 2537 rejected at actor binding height',ropeSection:'71149k02'},rigidPartScale:1,states:{},limitations:['Six separate closed-loop fit samples, not one physically continuous knotted rope','No tightening animation or conservation-of-rope-length claim','No hand binding, knot, cut state or beeswax earplug choreography yet','Section centre lines follow offset convex cross-sections; this is not an exact mesh collision certificate']};
function cross(a,b,c){return(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);}
function hull(ps){ps.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const a=[],b=[];for(const p of ps){while(a.length>1&&cross(a.at(-2),a.at(-1),p)<=1e-8)a.pop();a.push(p);}for(const p of ps.slice().reverse()){while(b.length>1&&cross(b.at(-2),b.at(-1),p)<=1e-8)b.pop();b.push(p);}return a.slice(0,-1).concat(b.slice(0,-1));}
function section(y){const points=[];for(const root of [mast,rig.figure]){root.updateWorldMatrix(true,true);root.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position,ix=o.geometry.index,n=ix?ix.count:a.count;for(let i=0;i+2<n;i+=3){const v=[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(a,ix?ix.getX(i+k):i+k).applyMatrix4(o.matrixWorld));for(let k=0;k<3;k++){const p=v[k],q=v[(k+1)%3];if((p.y<=y&&q.y>=y)||(q.y<=y&&p.y>=y)){if(Math.abs(p.y-q.y)<1e-8)continue;const t=(y-p.y)/(q.y-p.y);points.push([p.x+(q.x-p.x)*t,p.z+(q.z-p.z)*t]);}}}});}return hull(points);}
function offset(poly,d){return poly.map((p,i)=>{const prev=poly[(i+poly.length-1)%poly.length],next=poly[(i+1)%poly.length];let a=[p[1]-prev[1],prev[0]-p[0]],b=[next[1]-p[1],p[0]-next[0]];const al=Math.hypot(...a),bl=Math.hypot(...b);a=a.map(v=>v/al);b=b.map(v=>v/bl);const den=1+a[0]*b[0]+a[1]*b[1];return[p[0]+(a[0]+b[0])*d/den,p[1]+(a[1]+b[1])*d/den];});}
function along(poly,s){const lengths=poly.map((p,i)=>Math.hypot(p[0]-poly[(i+1)%poly.length][0],p[1]-poly[(i+1)%poly.length][1])),len=lengths.reduce((a,b)=>a+b);s=(s%len+len)%len;for(let i=0;i<poly.length;i++){if(s<=lengths[i]){const u=s/lengths[i],p=poly[i],q=poly[(i+1)%poly.length];return[p[0]+u*(q[0]-p[0]),p[1]+u*(q[1]-p[1])];}s-=lengths[i];}return poly[0];}
const sections=levels.map(y=>({y,poly:section(y)}));
for(const [name,clearance]of[['secured',1.8],['loose',8]]){status.textContent='Fitting rope to native cross-sections · '+name;const group=new T.Group();N.scene.add(group);sets[name]=group;receipt.states[name]=[];for(const {y,poly}of sections){const loop=offset(poly,clearance),len=loop.reduce((n,p,i)=>n+Math.hypot(p[0]-loop[(i+1)%loop.length][0],p[1]-loop[(i+1)%loop.length][1]),0),count=Math.ceil(len/5.8);for(let i=0;i<count;i++){const s=(i+.5)*len/count,c=along(loop,s),a=along(loop,s-2.9),b=along(loop,s+2.9),g=templates.clone(true);g.position.set(c[0],y,c[1]);g.quaternion.setFromUnitVectors(new T.Vector3(1,0,0),new T.Vector3(b[0]-a[0],0,b[1]-a[1]).normalize());group.add(g);}receipt.states[name].push({height:y,hull:poly,centreline:loop,length:len,sections:count,offset:clearance});}}
function draw(state='secured',view='front'){Object.entries(sets).forEach(([k,g])=>g.visible=k===state);const views={front:[[160,125,250],[0,52,16],38],rear:[[-155,115,-215],[0,52,16],38],wide:[[290,260,570],[0,160,0],38]};N.render(...views[view]);const c=N.ctx;c.fillStyle='rgba(7,12,20,.9)';c.fillRect(0,0,1280,62);c.fillRect(0,652,1280,68);c.fillStyle='#efcf91';c.font='bold 25px system-ui';c.fillText('SIREN MAST · '+state.toUpperCase()+' / '+view.toUpperCase(),24,39);c.fillStyle='#d5deea';c.font='18px system-ui';c.fillText('3941 mast assembly + 71149k02 braided sections · native-scale actor-fit study',24,680);c.fillText('Six closed-loop samples · continuous rope, knots and cut state remain unbuilt',24,705);}
draw();status.textContent='READY · secured and loose actor-fit studies';document.querySelector('#tight').onclick=()=>draw();document.querySelector('#loose').onclick=()=>draw('loose');document.querySelector('#rear').onclick=()=>draw('secured','rear');document.querySelector('#capture').onclick=async()=>{for(const st of ['secured','loose'])for(const v of ['front','rear','wide']){draw(st,v);await saveStill('rigging-'+st+'-'+v,cv);}const sc=document.querySelector('#source');for(const [name,node]of Object.entries(source.states.nodes)){renderAsset(sc,source,{state:node.preview,card:true,pipeline:'MESH'});await saveStill('source-mast-ropes-'+name,sc);}await saveJSON('rigging-fit',{...receipt,loaded:[...N.loaded],missing:N.missing});status.textContent='COMPLETE · six fit renders + source states + measured paths';};
