# -*- coding: utf-8 -*-
"""The working paper: one argument the field can presently support.
Prose uses [@citekey] for citations (resolved by compile.py against the compiled
bibliography), {TABLE:x} and {FIGURE:x} for computed inserts. SOURCE_MAP traces
every substantive claim: PAPER CLAIM → ZETTEL → SOURCE → CITEKEY, or COMPUTED
(from measure-field.js) or COMPILER (connective prose).
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
F = json.load(open(os.path.join(HERE, 'work', 'field', 'field-results.json')))
K = {k['id']: k for k in F['kits']}
B = {b['id']: b for b in F['builds']}
kits = [k for k in F['kits'] if k['pieces']]
shares = sorted(k['openStructuralShare'] for k in kits)
BAND = (shares[0], shares[-1]); MED = shares[len(shares)//2]
c = B['card-castle']; s = B['gauntlet-shore-station']; fw = B['card-fallingwater']; hb = B['hms-beagle']
ctrl5935 = B['5935-island-hopper']; ctrl7140 = B['7140-xwing-fighter']
def wl(j): return f"{j['wins']} wins / {j['losses']} losses"
n_builds = len([b for b in F['builds'] if not b.get('control')])
below_band_A = sum(1 for b in F['builds'] if not b.get('control') and b['variants']['A-close-all']['openStructuralShare'] < BAND[0])
in_band_B = sum(1 for b in F['builds'] if not b.get('control') and BAND[0] <= b['variants']['B-ragged']['openStructuralShare'] <= BAND[1])
in_band_before = sum(1 for b in F['builds'] if not b.get('control') and BAND[0] <= b['before']['openStructuralShare'] <= BAND[1])

SLUG = 'the-field-not-the-window'
DATE = '2026-09-03'
PAPER = dict(
 slug=SLUG, date=DATE,
 title='The Field, Not the Window',
 subtitle='Open ports, solicitation, and the attention tax of LDraw as a language of assembly',
 author='W. Hartsoe (whartsoe3@gatech.edu), Georgia Institute of Technology',
 status='Working Paper · AI-augmented research process · Evidence, prompts, and making history preserved',
 abstract=(
  'Language models that assemble LEGO models in the LDraw format fail in characteristic ways: pieces that hover, pieces that interpenetrate, pieces placed off the stud lattice. The usual remedy is to put more of the model into the context window. This paper argues that the remedy is aimed at the wrong object. LDraw records where a piece is, not what it can connect to, so a model reading LDraw must recompute connectability from coordinates before it can act; that recomputation, not token count, is the attention tax. Following the distinction between a landscape of affordances and the field of affordances that currently solicit action, the paper proposes that the representation an assembling model should see is the small, changing field of open ports of the half-built object, and that the model should answer with a relation to a port rather than a coordinate. A cheap instrument makes the field measurable: a stud faces air when the point just above it lies inside no other piece. Sixteen real kits keep between ' + f'{BAND[0]:.0%} and {BAND[1]:.0%}' + ' of their structural studs open; of six generated builds in the same repository, ' + f'{n_builds - in_band_before}' + ' sit above that band and the rest inside it. A pass that closes every open stud drives ' + f'{below_band_A} of {n_builds}' + ' builds below the band and a twelve-axis critic calibrated on the kits barely registers the change, while a pass restricted to ragged surfaces moves one build from ' + wl(s['judgeBefore']) + ' to ' + wl(s['variants']['B-ragged']['judge']) + '. Applied to the kits themselves, the closing pass tiles over surfaces they leave open on purpose. The evidence therefore supports the field and refutes its naive reading: what must be routed to attention is solicitation, weighted by raggedness, reachability and intent, not the set of open ports. The paper closes with the seven prompt seeds this implies and with what remains unmeasured.'),
 keywords=['LDraw', 'assembly', 'affordances', 'attention', 'language models', 'stigmergy', 'LEGO', 'proprioception'],
)

SECTIONS = [
 ('1. Introduction', [
  'A castle of six thousand pieces will not fit in the head of anything that has to place the next piece. This is as true of a person with a manual as of a language model with a context window, and the two cope in different ways. The person never holds the castle; they hold the piece in hand and a few places it might go. The language model, given the castle as LDraw text, is asked to hold all of it, and it reads coordinates. Each line of an LDraw file says which part sits at which position under which rotation [@ldrawformatspec]. Nothing in the line says whether the part is seated on studs, hovering a plate above them, or passing through a wall. Those facts are recoverable from the coordinates, but only by recomputing the geometry of every neighbour. That recomputation is the tax this paper is about.',
  'The thesis is that the tax is representational rather than quantitative, and that it is paid whenever information which could stay implicit in the object is forced through a general-purpose description before action. The fix is not a larger window and not a shorter file. It is to show the model a different object: the field of open ports of the half-built model, ranked by how much each one currently solicits a piece, and to let the model answer with a relation to one of those ports. The argument borrows its central distinction from ecological psychology, where the landscape of affordances is what an environment offers in general and the field of relevant affordances is the small subset that stands out to a skilled agent in a concrete situation [@vandijk2017foregrounding]. The claim here is that an assembling model should be built to see the field.',
  'The paper then does what the argument invites: it measures the field. A stud faces air when the point just above it lies inside no other piece. Counted across sixteen real kits and six generated builds in one repository, the number puts the kits in a band and the builds inside or above it, and a placement pass routed by that number changes the builds in a way a kit-calibrated critic almost cannot see. The naive version of the field, treated as a to-do list, makes the builds less like kits, not more. That result is the paper\'s stepping stone: the field is a field of solicitations, and solicitation has to be weighted by something the open-port count does not contain. The last section names the prompt seeds that follow and says where the evidence stops.',
 ]),
 ('2. Where the argument comes from', [
  'Three literatures meet here. The first is the ecological account of action, in which perception delivers possibilities for action rather than descriptions of the world, and skill consists in responding to the few possibilities that matter now [@vandijk2017foregrounding]. Cisek\'s affordance competition hypothesis gives the account a mechanism: the brain specifies several currently possible actions in parallel and lets them compete, with attention operating as an early selector among candidate actions rather than as a better reader of the scene [@cisek2007affordance]. Kirsh adds that agents arrange space so that the geometry performs some of the reasoning [@kirsh1995space], and Brooks that a live world can answer questions a stored description would only approximate [@brooks1991intelligence]. These are arguments about biological and robotic agents. They transfer to an assembling language model because the model, too, has to choose among many possible next placements from a partial view.',
  'The second literature is about coordination through the built object. Grassé\'s stigmergy, reviewed for construction by Smith and colleagues, describes builders whose next act is cued by the state of what has already been built rather than by messages [@smith2018architecture]; Werfel, Bar-Yam and Nagpal extend the idea so that construction blocks themselves carry machine-readable state [@werfel2005stigmergy]; Wilsson\'s beavers repair where the sound of running water recruits them [@wilsson1962beaver]. Control theory supplies the formal version: an expensive controller need not run on every tick if it runs whenever an error crosses a threshold [@tabuada2007event], and an error should be weighted by how much the sensor reporting it can be trusted [@friston2011active]. Ashby\'s ultrastable system says when a deeper adaptation should be recruited at all: when an essential variable leaves its admissible region, not when the current step is merely hard [@ashby1960design].',
  'The third literature is the one the assembling model actually lives in. The LDraw file format is a recursive grammar: a type-1 line takes a reusable file, transforms it, and places an instance [@ldrawformatspec]. What it lacks is connectivity. Roland Melkert\'s shadow library for LDCad supplies snap metadata that the primary parts do not carry [@melkertldcadshadow], and BrickNet builds from LDraw a connector graph and a build tree so that a generative model predicts relations rather than absolute poses [@kulits2026bricknet]. LegoGPT shows a generator that guesses, tests physics, and rolls back [@pun2025legogpt]; CADCodeVerify closes a loop of generate, render, interrogate and correct [@alrashedy2025cadcodeverify]; State-CAD keeps an authoritative structured state apart from the transcript [@lin2026statecad]. OmniCAD reports that frontier multimodal agents still fail on assemblies averaging about twelve parts [@wang2026omnicad], which is the scale at which the argument of this paper begins to matter.',
 ]),
 ('3. The argument', [
  '3.1 LDraw knows where a piece is, not what it can connect to. The point deserves to be stated plainly because it is easy to mistake for a complaint about verbosity. An LDraw placement is complete as geometry and silent as assembly: it can describe a brick that floats, a brick inside another brick, or a brick that could never have been inserted, using exactly the syntax it uses for a seated one [@ldrawformatspec]. Community tooling knows this, which is why connection data lives in a separate shadow library [@melkertldcadshadow] and why BrickNet had to reconstruct a connector graph before a model could be trained to build [@kulits2026bricknet]. A language model reading raw LDraw is therefore asked to do at inference what BrickNet did at preprocessing: infer relations from positions. Every hovering brick in a generated model is that inference failing silently.',
  '3.2 The minimal representation for the next placement is the field of open ports. If the model is not to hold the castle, what should it hold? The ecological answer is: what currently solicits action. For a stud-and-tube system this has an unusually literal form. Each piece exposes ports; a port is open when nothing occupies it; the set of open ports on the half-built model, together with the piece in hand, is the complete set of currently possible seated placements. This set is small relative to the model, it changes with every placement, and it is exactly what the human builder attends to when they look for where the next brick goes. Cisek\'s framing is the useful one: rather than represent the scene and then derive actions, derive the candidate actions directly from local geometry and let them compete [@cisek2007affordance]. Deictic roles then do the rest of the work: the open stud beside the last window is a better name than instance 5291 for the purposes of the next move, as Agre argued for everyday activity [@agre1988dynamic] and Pook and Ballard for teleassisted manipulation [@pook1996deictic].',
  '3.3 A field is not a to-do list. Here the argument has to be careful, and the evidence in the next section shows why. An open port is a possibility, not an instruction. Real models leave surfaces open on purpose: a baseplate is a floor, a roof of studs is a roof, an open cavity is where the stair will go. A builder that treats every open port as a task to close will fill the cavity and make the stair impossible. This is the reward-shaping trap in its physical form: a local signal that looks like progress teaches a policy that changes which completions are reachable [@ng1999policy]. The field must therefore carry solicitation, not just openness. The candidates for what weights a port are the ones the stigmergy literature already names: raggedness (a surface partly covered solicits completion), adjacency to the working front (the beaver hears the leak, not the whole dam [@wilsson1962beaver]), the trust one has in the validator that reported the port [@friston2011active], and the intent of the current sub-assembly.',
  '3.4 Route the reasoner by the residual. If the field is what the model sees, the residual is what it hears back. A refused placement should say what was placed, what was wanted, and what it cost in clashes, floats and open ports, because the useful part of a correction is the difference it points to; scalar reward teaches preference without vocabulary [@lightman2023verify; @shinn2023reflexion]. And the expensive reasoner should be scheduled by that residual rather than by the clock: most placements in a castle are quiet repetitions, and event-triggered control says the controller runs when an error crosses a threshold, not on every step [@tabuada2007event]. Cook Ding\'s knife changes regime at the complicated joint and nowhere else [@zhuangziinner]. Put together, the four claims describe a builder whose prompt is not a sentence but the current field plus the last residual, and whose attention is spent where the object is ragged.',
 ]),
 ('4. Evidence', [
  '4.1 An instrument for the field. To test whether the field is measurable at all, the compiler of this package wrote a probe over the repository\'s own catalogue (bounding boxes for 16,910 buildable parts) and port index (44,329 studs and tubes over 7,831 parts). A stud faces air when the point two LDraw units above its base, along the stud\'s own axis, lies inside no other placement\'s bounding box. Structural studs exclude baseplates and the ground level, which are open by design. The share of structural studs facing air is the shadow number. It is an approximation: the bounding box of a slope or an arch covers the air above its face, so coverage is an upper bound for such parts; the probe uses studs only and never tests whether a tube actually grips. Every number below was counted by that script and re-counted from the emitted files.',
  '4.2 The kit band. Sixteen real kits with pieces (the seventeenth is a single window brick) keep between ' + f'{BAND[0]:.3f} and {BAND[1]:.3f}' + ' of their structural studs open, median ' + f'{MED:.3f}' + '. The two largest, the UCS AT-ST and the X-wing, sit at ' + f"{K['10174-imperial-atst-ucs']['openStructuralShare']:.3f} and {K['7140-xwing-fighter']['openStructuralShare']:.3f}" + '. The island hopper, which the repository uses as its default bar, is at ' + f"{K['5935-island-hopper']['openStructuralShare']:.3f}" + ', high because its hull is a plate field. Kits, in other words, are not closed objects; they are objects whose openness is placed.',
  '{TABLE:kits}',
  '4.3 The builds, before and after the field. Six generated builds from the same repository were measured, then run through two versions of a field-routed closing pass. The close-all pass tiles every open structural stud it can reach without clashing (2×2, 1×2 and 1×1 tiles in the host\'s colour). The ragged pass tiles only studs on pieces whose top is already partly covered. Before the pass, ' + f'{in_band_before} of {n_builds}' + ' builds are inside the kit band; the castle is, at ' + f"{c['before']['openStructuralShare']:.3f}" + ', and the crewed expedition ships are not, at ' + f"{hb['before']['openStructuralShare']:.3f}" + ' for the Beagle. The close-all pass takes ' + f'{below_band_A} of {n_builds}' + ' builds below the band (the sixth, the finch cactus, lands on its floor): the castle goes from ' + f"{c['before']['open']} open studs to {c['variants']['A-close-all']['open']}" + ', adding ' + f"{c['variants']['A-close-all']['added']['pieces']}" + ' tiles. The ragged pass leaves ' + f'{in_band_B} of {n_builds}' + ' inside the band.',
  '{TABLE:builds}',
  '{FIGURE:castle}',
  '4.4 What the critic saw. The repository judges builds against a kit on twelve axes, blind, per axis and never summed, with ties going to the kit. On the castle the verdict is ' + wl(c['judgeBefore']) + ' before the pass and ' + wl(c['variants']['A-close-all']['judge']) + ' after close-all: the same count, with colour flipping to a win and lattice flipping to a loss. On the shore station the ragged pass moves the verdict from ' + wl(s['judgeBefore']) + ' to ' + wl(s['variants']['B-ragged']['judge']) + '; on the fallingwater card the close-all pass moves it from ' + wl(fw['judgeBefore']) + ' to ' + wl(fw['variants']['A-close-all']['judge']) + '. A change that removes ' + f"{c['before']['open'] - c['variants']['A-close-all']['open']}" + ' open studs from a 182-piece model is nearly invisible to a critic that measures vocabulary, colour, rotation, symmetry and density. The critic has no proprioceptive axis.',
  '4.5 The control. Applied to two real kits, the close-all pass adds ' + f"{ctrl5935['variants']['A-close-all']['added']['pieces']} tiles to the island hopper and {ctrl7140['variants']['A-close-all']['added']['pieces']} to the X-wing" + ', tiling over hull plates and wing surfaces that the designers left open, and drives their open-stud ratio from ' + f"{ctrl5935['before']['openPerPiece']} to {ctrl5935['variants']['A-close-all']['openPerPiece']}" + ' per piece. The pass is wrong on the kits, and it is wrong in the way section 3.3 predicted: it reads possibility as obligation.',
 ]),
 ('5. Discussion', [
  'The evidence supports the field and refutes the to-do list, and the refutation is the more useful half. The naive field is the very error the affordance literature warns against: mistaking the landscape for the field. What the kits show is that openness is placed. A surface that is entirely open is a design decision; a surface that is half covered is a solicitation. The ragged rule is a crude approximation of that difference and already behaves better on the kits than the close-all rule, which is what one would expect if the weight on a port should come from the state of its neighbourhood rather than from the port itself. Werfel\'s extended stigmergy suggests the next step: let sub-assemblies declare their open interfaces and their do-not-close cavities, so that the field is partly authored by the object [@werfel2005stigmergy].',
  'The second finding is about the critic. A twelve-axis judge calibrated on kits is nearly blind to whether pieces are seated. That is not a flaw in those axes; it is a gap. The bar for legibility should carry at least one proprioceptive axis, and the shadow number is a candidate: the share of structural studs facing air, judged like the others, in a band, blind, with ties to the kit. An axis of that kind is also the first one that a placement policy routed by the field would move directly, which makes it the right place to test the prompt seeds that follow from the argument.',
  'The third implication is for the prompt. If the field is what the model should see and the residual is what it should hear, then the prompt at castle scale is not a sentence and not a serialised model. It is a small packet: the ranked open ports, the piece in hand as a body line, the card\'s intent for this region, and the last residual. Seven seed prompts built on that packet accompany this paper; only the first has been run, in its cheapest form, and its numbers are the ones above. The others are stated as hypotheses with their measures and mutation operators, so that they can be tested and evolved rather than believed.',
 ]),
 ('6. Limitations and unresolved territory', [
  'The probe is geometric, not mechanical. It says a stud is covered when something sits above it; it does not say that a tube grips it, and it cannot see hinges, clips, pins or bars, whose ports are absent from the index. A proper clutch test (a tube centre within the stud\'s ring, coplanar) has not been written. Bounding boxes overstate coverage under slopes and arches. Seventeen kits from one loader example are a small and biased bar. No language model was in the loop: the pass is a fixed rule, so the evidence bears on the representation, not yet on whether a model can use it. The earlier body-line and joints computation from the originating session is not preserved here and is treated as unverified.',
  'The card field this paper draws on is itself incomplete. Sixteen addresses it cites, among them the prompt-praxis cards that ground the language-game argument, are ghosts: named, linked to, and not present in the package. They are held open as questions. The assembly-theory cards in the field (whether LDraw\'s reuse is compression or construction, what counts as an elementary part, whether a threshold like fifteen means anything for bricks) are adjacent to this argument and were deliberately not pulled into it; the evidence here does not reach them.',
 ]),
 ('7. Conclusion', [
  'A model that assembles in LDraw pays a tax every time it recomputes from coordinates what the object already knows about itself. The tax is not paid in tokens; it is paid in floating and interpenetrating pieces. The way to stop paying it is to show the model the object\'s field of open ports and let it answer with a relation. Measured across real kits and generated builds, the field is real, cheap to compute, and it tells a placed openness from an accidental one. Treated as a list of things to close, it makes builds worse and would ruin the kits. Treated as a field of solicitations, weighted by how ragged and how reachable each port is, it is the smallest representation from which competent next action follows. That is the wager. The instrument, the numbers, the cards, and the seeds to test the wager are in the package this paper ships with.',
 ]),
]

# PAPER CLAIM → ZETTEL → SOURCE → CITEKEY   (kind: SOURCE | COMPUTED | COMPILER)
SOURCE_MAP = [
 dict(sec='1', claim='An LDraw type-1 line records part, position and rotation and nothing about seating', zettels=['Z-LDRAW-CONNECTION-GAP-001','Z-HOGWARTS-DEIXIS-001','Z-LDRAW-GRAMMAR-001'], cites=['ldrawformatspec'], kind='SOURCE'),
 dict(sec='1', claim='The attention tax is representational: information that could stay implicit is forced through a general description before action', zettels=['Z-CASTLE-ATTENTION-TAX-INVERSION-001'], cites=['cisek2007affordance','kirsh1995space','brooks1991intelligence'], kind='SOURCE'),
 dict(sec='1', claim='Landscape of affordances vs field of relevant affordances', zettels=['Z-CASTLE-FIELD-AFFORDANCES-001'], cites=['vandijk2017foregrounding'], kind='SOURCE'),
 dict(sec='2', claim='Affordance competition: attention as early action selector', zettels=['Z-CASTLE-AFFORDANCE-COMPETITION-001'], cites=['cisek2007affordance'], kind='SOURCE'),
 dict(sec='2', claim='Arrange space so geometry performs reasoning; the world as its own model', zettels=['Z-CASTLE-SPACE-AS-COMPUTATION-001','Z-CASTLE-WORLD-AS-MODEL-001'], cites=['kirsh1995space','brooks1991intelligence'], kind='SOURCE'),
 dict(sec='2', claim='Stigmergy: the built object cues the next act; blocks can carry state; beavers repair where water runs', zettels=['Z-CASTLE-STIGMERGIC-MEMORY-001','Z-CASTLE-EXTENDED-STIGMERGY-001','Z-CASTLE-BEAVER-ERROR-SURFACE-001'], cites=['smith2018architecture','werfel2005stigmergy','wilsson1962beaver'], kind='SOURCE'),
 dict(sec='2', claim='Event-triggered control; precision-weighted error; ultrastable escalation', zettels=['Z-CASTLE-EVENT-TRIGGERED-THOUGHT-001','Z-CASTLE-PRECISION-WEIGHTED-ERROR-001','Z-CASTLE-ULTRASTABLE-ESCALATION-001'], cites=['tabuada2007event','friston2011active','ashby1960design'], kind='SOURCE'),
 dict(sec='2', claim='LDraw is a recursive grammar; connectivity lives in the LDCad shadow library; BrickNet predicts relations over a connector graph', zettels=['Z-LDRAW-GRAMMAR-001','Z-LDRAW-CONNECTION-GAP-001','Z-BRICKNET-HOGWARTS-001'], cites=['ldrawformatspec','melkertldcadshadow','kulits2026bricknet'], kind='SOURCE'),
 dict(sec='2', claim='LegoGPT rollback; CADCodeVerify loop; State-CAD explicit state; OmniCAD fails at ~12 parts', zettels=['Z-LEGOGPT-ROLLBACK-001','Z-CADCODEVERIFY-GAUNTLET-001','Z-STATECAD-STRUCTURED-STATE-001','Z-OMNICAD-AGENTIC-ASSEMBLY-001'], cites=['pun2025legogpt','alrashedy2025cadcodeverify','lin2026statecad','wang2026omnicad'], kind='SOURCE'),
 dict(sec='3.1', claim='A model reading raw LDraw must infer relations from positions at inference', zettels=['Z-LDRAW-CONNECTION-GAP-001','Z-BRICKNET-HOGWARTS-001'], cites=['kulits2026bricknet','melkertldcadshadow'], kind='COMPILER'),
 dict(sec='3.2', claim='The open-port set is the complete set of currently possible seated placements (stud/tube systems)', zettels=['Z-CASTLE-FIELD-AFFORDANCES-001','Z-CASTLE-AFFORDANCE-COMPETITION-001'], cites=[], kind='COMPILER'),
 dict(sec='3.2', claim='Deictic roles beat stable ids for the next move', zettels=['Z-CASTLE-DEICTIC-BINDING-001'], cites=['agre1988dynamic','pook1996deictic'], kind='SOURCE'),
 dict(sec='3.3', claim='Closing every open port is the reward-shaping trap in physical form', zettels=['Z-HOGWARTS-REWARD-SHAPING-TRAP-001','Z-CASTLE-FIELD-AFFORDANCES-001'], cites=['ng1999policy'], kind='SOURCE'),
 dict(sec='3.3', claim='Candidate weights for solicitation: raggedness, adjacency to the front, validator trust, intent', zettels=['Z-CASTLE-BEAVER-ERROR-SURFACE-001','Z-CASTLE-PRECISION-WEIGHTED-ERROR-001'], cites=['wilsson1962beaver','friston2011active'], kind='COMPILER'),
 dict(sec='3.4', claim='The useful part of a correction is the difference it points to; scalar reward lacks vocabulary', zettels=['Z-HOGWARTS-ERROR-RESIDUAL-001','Z-HOGWARTS-REWARD-TWO-CHANNELS-001'], cites=['lightman2023verify','shinn2023reflexion'], kind='SOURCE'),
 dict(sec='3.4', claim='Schedule the reasoner by the residual (event-triggered); Cook Ding changes regime at the joint', zettels=['Z-CASTLE-EVENT-TRIGGERED-THOUGHT-001','Z-CASTLE-COOK-DING-SCHEDULER-001'], cites=['tabuada2007event','zhuangziinner'], kind='SOURCE'),
 dict(sec='4.1', claim='Catalogue 16,910 buildable parts; port index 44,329 ports over 7,831 parts; probe definition', zettels=[], cites=[], kind='COMPUTED', note='nabugo-parts.json count field; nabugo-ports.json ports/parts fields; measure-field.js'),
 dict(sec='4.2', claim=f'Kit band {BAND[0]:.3f}–{BAND[1]:.3f}, median {MED:.3f}; per-kit values', zettels=[], cites=[], kind='COMPUTED', note='field-results.json → kits[].openStructuralShare'),
 dict(sec='4.3', claim='Per-build before/close-all/ragged shares, pieces and added tiles', zettels=[], cites=[], kind='COMPUTED', note='field-results.json → builds[].before / variants'),
 dict(sec='4.4', claim='Twelve-axis blind verdicts before/after on castle, shore station, fallingwater', zettels=[], cites=[], kind='COMPUTED', note='field-results.json → builds[].judgeBefore / variants[].judge (NabugoGauntlet.Critic.judge against 5935-island-hopper)'),
 dict(sec='4.5', claim='Control: tiles added to two kits and their open/piece before/after', zettels=[], cites=[], kind='COMPUTED', note='field-results.json → builds[] where control=true'),
 dict(sec='5', claim='Sub-assemblies should declare open interfaces and do-not-close cavities', zettels=['Z-CASTLE-EXTENDED-STIGMERGY-001'], cites=['werfel2005stigmergy'], kind='SOURCE'),
 dict(sec='5', claim='The critic lacks a proprioceptive axis; the shadow number is a candidate thirteenth axis', zettels=[], cites=[], kind='COMPILER', note='inference from 4.4'),
 dict(sec='5', claim='Seven seed prompts; only S01 run', zettels=[], cites=[], kind='COMPILER', note='_PROMPTS/README.txt status table'),
 dict(sec='6', claim='Sixteen ghost addresses in the field, including the Z-PROMPT-* cards', zettels=[], cites=[], kind='COMPUTED', note='_SLIPCASE/NODES.jsonl type=GHOST'),
]

# ordered citekeys as they should appear; compile.py checks each exists in the compiled bibliography
CITEKEYS_USED = ['ldrawformatspec','vandijk2017foregrounding','cisek2007affordance','kirsh1995space','brooks1991intelligence',
 'smith2018architecture','werfel2005stigmergy','wilsson1962beaver','tabuada2007event','friston2011active','ashby1960design',
 'melkertldcadshadow','kulits2026bricknet','pun2025legogpt','alrashedy2025cadcodeverify','lin2026statecad','wang2026omnicad',
 'agre1988dynamic','pook1996deictic','ng1999policy','lightman2023verify','shinn2023reflexion','zhuangziinner']
