const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
global.THREE=require(process.env.THREE_PATH||'/tmp/alley-three.js');global.window=global;global.localStorage={getItem(){return null},setItem(){}};
vm.runInThisContext(fs.readFileSync(process.env.BUILD_PATH||require('node:path').join(__dirname,'../world/build.js'),'utf8'));require('./placement.js');
const geom=new THREE.BoxGeometry(80,24,40);geom.translate(0,12,0);
const B=new Build.Build({scene:new THREE.Scene(),M:40,geoms:new Map([['3001',{geom,bb:[-40,40,-20,20,24]}]]),colours:()=>new THREE.Color('red'),groundH:()=>0,buildings:()=>[],cap:20});
const base=B.add({id:'base',part:'3001',col:4,x:0,y:0,z:0,rot:0}),p={id:'moving',part:'3001',col:4,x:160,y:0,z:0,rot:0};B.add(p);
let t=AlleyPlacement.resolve(B,p,{x:0,y:24,z:0},p.id);assert.equal(t.y,24);assert.equal(t.blocked,false);
B.add({...p,id:'top',...t});assert.equal(B.supported(B.pieces.get('top')),true);
t=AlleyPlacement.resolve(B,p,{x:0,y:48,z:0},p.id);assert.equal(t.y,48);assert.equal(t.blocked,false);
assert.equal(AlleyPlacement.resolve(B,p,{x:0,y:0,z:0},p.id).blocked,true);
assert.equal(AlleyPlacement.resolve(B,p,p,p.id).blocked,false);
t=AlleyPlacement.resolve(B,p,{x:160,y:80,z:200},p.id);assert.equal(t.y,80);assert.equal(t.z,200);assert.equal(t.blocked,false);
assert.equal(AlleyPlacement.resolve(B,p,{x:160,y:-80,z:200},p.id).y,0);
const offset={...p,part:'off'};B.register('off',geom,[0,80,0,40,24]);t=AlleyPlacement.resolve(B,offset,{x:151,y:40,z:9},p.id);assert.equal(t.x,160);assert.equal(t.z,0);
console.log('PASS: stack, second level, supported top, blocked overlap, self exclusion, independent depth/height, ground clamp, off-centre origin');
const source=fs.readFileSync(__dirname+'/gestures.js','utf8');const moveSource=source.slice(source.indexOf('function movePiece('),source.indexOf('function moveProp('));
const ctx={W:{build:B},AlleyPlacement,state:{},sayLine(){},Date,Math};vm.createContext(ctx);vm.runInContext(moveSource,ctx);
const moving=B.pieces.get('moving');assert.equal(ctx.movePiece({id:moving.id},{x:200,y:80,z:200},false),true);assert.equal(B.pieces.get('moving').y,80);
B.target={x:400,y:0,z:400,blocked:false};const newer=B.place();B.undo();assert.equal(B.pieces.has(newer.id),false);assert.equal(B.pieces.get('moving').y,80);B.undo();assert.equal(B.pieces.get('moving').y,0);
assert.equal(ctx.movePiece({id:'moving'},{x:0,y:0,z:0},false),false);assert.equal(B.pieces.get('moving').x,160);
console.log('PASS: actual gesture move, placement then move Undo order, blocked move preserves original');
