#!/usr/bin/env node
/* tools/halfworld-face.js — the halfworld's close-up puppet as one classic script.

   node tools/halfworld-face.js --halfworld <clone> [--out world/halfworld-face.js]

   Reads assets/character/_close/face.mjs (the twelve faces and drawCloseup), the handful of palette and math
   helpers it imports from engine/halfworld-engine.mjs, and the direction table's EMOTIONS from scenes/_direction.mjs,
   and writes them as one file that defines window.HalfFace = { SURFACE, FACES, EMOTIONS, drawCloseup, idleFace,
   INKLAW, CLOSE, VERSION, source }. Nothing is changed in the drawing: the same function draws the same face; the
   only edits are the import line and the export keywords. Run it again when the halfworld's faces change. */
const fs = require('fs'), path = require('path');
const args = process.argv.slice(2), opt = (k, d) => { const i = args.indexOf('--' + k); return i >= 0 ? args[i + 1] : d; };
const HW = opt('halfworld', '/home/user/hartswf0/odyssey-halfworld'), OUT = opt('out', path.join(__dirname, '..', 'world', 'halfworld-face.js'));
const read = f => fs.readFileSync(path.join(HW, f), 'utf8');
const face = read('assets/character/_close/face.mjs'), engine = read('engine/halfworld-engine.mjs'), direction = read('scenes/_direction.mjs');

// the helpers: the palette and math block of the engine, up to the render pipelines
const helpers = engine.slice(engine.indexOf('/* ---------------- palette + math'), engine.indexOf('/* ---------------- render pipelines')).replace(/^export /gm, '');
const inklaw = engine.slice(engine.indexOf('export const INKLAW = {'), engine.indexOf('export function dotifyField')).replace(/^export /gm, '');
// the face module without its import, exports stripped
const body = face.replace(/^import [^\n]*\n/m, '').replace(/^export /gm, '');
// the direction table's EMOTIONS object
const em = direction.slice(direction.indexOf('export const EMOTIONS = {')); const emotions = em.slice(0, em.indexOf('\n};') + 3).replace(/^export /gm, '');
const names = [...face.matchAll(/^  ([a-z]+): \{ hairDrop/gm)].map(m => m[1]), emoNames = [...emotions.matchAll(/^  ([a-z]+):\s*\{/gm)].map(m => m[1]);
const version = (face.match(/FACE_VERSION = "([^"]+)"/) || [])[1] || 'unknown';
let sha = ''; try { sha = require('child_process').execFileSync('git', ['-C', HW, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' }).trim(); } catch (e) { }
const out = `/* world/halfworld-face.js — generated by tools/halfworld-face.js from the odyssey-halfworld clone${sha ? ' at ' + sha : ''}; do not edit by hand.
   The halfworld's close-up puppet (assets/character/_close/face.mjs, ${version}): the twelve faces of the Odyssey as measured specs and the one
   drawing function, drawCloseup(ctx, spec, state, {cx, cy, R}), with the direction table's EMOTIONS as face states. face.js paints it on
   the LEGO head as a decal: the same strokes, dotted the same way, masked to the print area. */
(function (root) {
${helpers}
${inklaw}
${body}
${emotions}
root.HalfFace = { SURFACE, FACES, EMOTIONS, drawCloseup, idleFace, INKLAW, CLOSE, closeGeom, SPEAKER_FACE, VERSION: FACE_VERSION, PAPER, INK, source: ${JSON.stringify({ halfworld: sha || null, faces: names, emotions: emoNames })} };
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(OUT, out);
console.log(`${OUT}: ${names.length} faces (${names.join(', ')}), ${emoNames.length} emotions, ${(out.length / 1024).toFixed(0)} KB`);
