import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {LDrawLoader} from 'three/addons/loaders/LDrawLoader.js';
import {LDrawConditionalLineMaterial} from 'three/addons/materials/LDrawConditionalLineMaterial.js';
import {makePlan,stateFor,hear,commit,unresolved,signalLoad,weatherMissing,toLDraw,simulate,DESIGN} from './model-fixed.js';
const $=s=>document.querySelector(s),delay=ms=>new Promise(r=>setTimeout(r,ms));let state=stateFor(makePlan()),running=false,last=null,lastContacts=[],audioCtx=null;
const dry=simulate(makePlan(),5000),selfTest={ok:dry.remaining.length===0&&dry.weatherMissing.length===0&&dry.clicks>=1800,detail:`${dry.moves} placements · ${dry.clicks} verified contacts · weather cracks ${dry.weatherMissing.length}`};
function audio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}function clickOne(t){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='square';o.frequency.setValueAtTime(1250,t);o.frequency.exponentialRampToValueAtTime(300,t+.04);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.002);g.gain.exponentialRampToValueAtTime(.0001,t+.05);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+.055)}function clicks(n){if(!audioCtx)return;for(let i=0;i<Math.min(n,5);i++)clickOne(audioCtx.currentTime+i*.032)}function fitSound(){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=130;g.gain.setValueAtTime(.025,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.12);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.13)}
const host=$('#threeHost'),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0xf1efe8);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,24000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;scene.add(new THREE.HemisphereLight(0xffffff,0x657080,2.7));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(600,900,500);scene.add(sun);const grid=new THREE.GridHelper(1500,75,0x777777,0xd3d0c7);grid.visible=false;scene.add(grid);const loader=new LDrawLoader();loader.setConditionalLineMaterial(LDrawConditionalLineMaterial);loader.setPartsLibraryPath('../../ldraw/');let ready=false,root=null,serial=0,markers=[];
function resize(){const w=Math.max(1,host.clientWidth),h=Math.max(1,host.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}function animate(t){requestAnimationFrame(animate);resize();controls.update();for(const m of markers)m.scale.setScalar(.75+.25*Math.sin(t*.007+m.userData.p));renderer.render(scene,camera)}requestAnimationFrame(animate);function dispose(r){r?.traverse(o=>{o.geometry?.dispose?.();(Array.isArray(o.material)?o.material:[o.material]).filter(Boolean).forEach(m=>m.dispose?.())})}function clear(){if(root){scene.remove(root);dispose(root)}root=null;markers=[];grid.visible=false}
const colors={WATER:0x168dff,GRAVITY:0xff4938,STRUCTURE:0xffa31a,ACCESS:0x20bb70,RAIN_ENTRY:0x00a8b5,VENT:0x916bd0,GUARD:0xffd62b};function signalMarkers(){const g=new THREE.Group(),h=hear(state);markers=[];for(const [i,a] of h.open.slice(0,24).entries()){const m=new THREE.Mesh(new THREE.SphereGeometry(a===h.raw?4.5:2.2,12,8),new THREE.MeshBasicMaterial({color:colors[a.signal]||0xff372b,transparent:true,opacity:a===h.raw?.95:.55,depthTest:false}));m.position.set(a.t[0],a.t[1]-10,a.t[2]);m.userData.p=i*.4;m.renderOrder=30;g.add(m);markers.push(m)}for(const c of lastContacts.slice(0,16)){const m=new THREE.Mesh(new THREE.SphereGeometry(2.1,10,7),new THREE.MeshBasicMaterial({color:0x00cf72,depthTest:false}));m.position.set(...c.p);g.add(m)}return g}
function fitModel(r){const b=new THREE.Box3().setFromObject(r);if(b.isEmpty())return;const s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z,500);controls.target.copy(c);camera.position.set(c.x+d*1.05,c.y+d*.68,c.z+d*1.35);camera.far=d*40;camera.updateProjectionMatrix();grid.position.y=b.min.y-.8;grid.visible=true}async function render(refit=false){if(!ready)return;const n=++serial,text=toLDraw(state);return new Promise(resolve=>loader.parse(text,g=>{if(n!==serial){dispose(g);resolve();return}clear();root=new THREE.Group();root.rotation.x=Math.PI;root.add(g);root.add(signalMarkers());scene.add(root);if(refit)fitModel(root);resolve()},e=>{console.error(e);$('#geom').textContent='LDRAW ERROR';resolve()}))}
try{const r=await fetch('../../ldraw/LDConfig.ldr',{cache:'no-store'});if(!r.ok)throw Error(`LDConfig ${r.status}`);await loader.preloadMaterials('../../ldraw/LDConfig.ldr');ready=true}catch(e){console.error(e);$('#geom').textContent='LDRAW INIT ERROR'}
function preset(name){const target=new THREE.Vector3(0,170,0);controls.target.copy(target);if(name==='front')camera.position.set(0,210,1150);if(name==='court')camera.position.set(0,500,-700);if(name==='roof')camera.position.set(850,850,850);controls.update()}
async function move(show=true){const h=hear(state);if(!h.raw){last={phase:'QUIET',text:'All programmed conditions are quiet.',proof:`weather cracks ${weatherMissing(state).length}`};ui();return'complete'}if(!h.choice){last={phase:'BLOCKED',text:`${h.raw.signal} · ${h.raw.label}`,proof:'no physically seatable prerequisite'};ui();return'blocked'}const {action,seat}=h.choice;last={phase:'TEST',text:`${action.file} · ${action.label}`,proof:`${seat.contacts.length}/${seat.need} live contacts · span ${Math.round(seat.spread||0)} LDU`};ui();if(show)await delay(60);const rec=commit(action,state);if(!rec)return'retry';lastContacts=rec.contacts.map(c=>({p:c.p}));if(rec.clicks){clicks(rec.clicks);last={phase:`CLICK ×${rec.clicks}`,text:`${action.file} committed`,proof:action.label}}else{fitSound();last={phase:'FIT / SEAL',text:`${action.file} inserted`,proof:`${action.label} · no fake stud click`}}ui();if(show){await render(false);await delay(38)}return'acted'}
async function run(){if(running||!selfTest.ok)return;audio();running=true;toggle(true);for(let i=0;i<5000;i++){const r=await move(false);if(r==='retry')continue;if(r!=='acted')break;if(i%7===0){await render(false);await delay(20)}}running=false;toggle(false);ui();await render(true)}function toggle(v){for(const id of ['runBtn','stepBtn','resetBtn'])$(id).disabled=v}function reset(){state=stateFor(makePlan());lastContacts=[];last={phase:'HEAR',text:'Rain, gravity and access find an empty 64×32 site.',proof:'two real baseplates; nothing else assumed'};ui();render(true)}
function ui(){const h=hear(state),left=unresolved(state),miss=weatherMissing(state),placed=state.placements.length;$('#selftest').textContent=selfTest.ok?'SELF TEST PASS':'SELF TEST FAIL';$('#selftest').className=selfTest.ok?'chip pass':'chip fail';$('#placed').textContent=`${placed}/${placed+left.length}`;$('#water').textContent=`WATER ${signalLoad(state,'WATER')}`;$('#gravity').textContent=`GRAV ${signalLoad(state,'GRAVITY')}`;$('#cracks').textContent=`CRACKS ${miss.length}`;$('#cracks').className=`chip ${miss.length?'fail':'pass'}`;$('#geom').textContent=ready?`REAL LDRAW · ${placed} PIECES · ${state.clicks} VERIFIED CONTACTS`:'INITIALIZING…';if(!h.raw){$('#hear').className='quiet';$('#hearLabel').textContent='QUIET';$('#hearText').textContent='Environment stopped finding failure.'}else{const blocked=!h.choice||h.choice.action!==h.raw;$('#hear').className=blocked?'blocked':'loud';$('#hearLabel').textContent=blocked?'LOUD / BLOCKED':'HEAR';$('#hearText').textContent=`${h.raw.signal} · ${h.raw.label}${blocked&&h.choice?` → prerequisite ${h.choice.action.signal}`:''}`}$('#phase').textContent=last?.phase||'HEAR';$('#decision').textContent=last?.text||'';$('#proof').textContent=last?.proof||'';$('#signals').innerHTML=h.open.slice(0,36).map(a=>`<div class="sig ${h.raw===a?'raw':h.choice?.action===a?'act':''}"><b>${a.signal}</b><span>${a.label}</span><small>${a.file}</small></div>`).join('')||'<div class="sig quiet"><b>QUIET</b><span>ALL CONDITIONS CLOSED</span></div>';$('#pieces').innerHTML=state.placements.slice(-60).reverse().map(a=>`<div class="piece"><b>${a.kind==='structure'?'CLUTCH':'FIT'}</b><span>${a.file}</span><small>${a.label}</small></div>`).join('')||'<div class="piece"><b>SITE</b><span>2 × 3811.dat</span><small>64×32 stud substrate</small></div>'}
$('#runBtn').onclick=run;$('#stepBtn').onclick=async()=>{if(running||!selfTest.ok)return;audio();toggle(true);await move(true);toggle(false)};$('#resetBtn').onclick=reset;$('#exportBtn').onclick=()=>{const b=new Blob([toLDraw(state)],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='beaver-court-house-ii.mpd';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#frontBtn').onclick=()=>preset('front');$('#courtBtn').onclick=()=>preset('court');$('#roofBtn').onclick=()=>preset('roof');$('#testDetail').textContent=selfTest.detail;$('#designDetail').textContent=`${DESIGN.ground} · ${DESIGN.upper} · ${DESIGN.pavilion}`;if(!selfTest.ok){$('#runBtn').disabled=true;$('#stepBtn').disabled=true}reset();
