export const ID=[1,0,0,0,1,0,0,0,1],RY90=[0,0,1,0,1,0,-1,0,0],RY180=[-1,0,0,0,1,0,0,0,-1],RY270=[0,0,-1,0,1,0,1,0,0];
export const DESIGN={name:'BEAVER COURT HOUSE II',site:'64×32 studs · two real 3811 baseplates',ground:'44×22 studs · two-stud bonded exterior · seven brick courses',upper:'32×8 atelier bar · six courses',pavilion:'12×8 roof room · four courses',principle:'No likeness completion. Every structural piece must seat on live studs; every exterior weather cell must end covered by masonry, glazing, or a closed door.'};
const X=i=>-630+i*20,Z=i=>-310+i*20,CX=(a,b)=>(X(a)+X(b))/2,CZ=(a,b)=>(Z(a)+Z(b))/2,range=(a,b)=>Array.from({length:b-a+1},(_,i)=>a+i),key=p=>p.map(v=>Math.round(v*1000)).join('|');
let serial=0;const P1={1:['3005.dat','Brick 1 x 1'],2:['3004.dat','Brick 1 x 2'],4:['3010.dat','Brick 1 x 4'],6:['3009.dat','Brick 1 x 6'],8:['3008.dat','Brick 1 x 8']},P2={1:['3004.dat','Brick 1 x 2'],2:['3003.dat','Brick 2 x 2'],3:['3002.dat','Brick 2 x 3'],4:['3001.dat','Brick 2 x 4']};
const cells=(x0,x1,z0,z1,y)=>{const a=[];for(let x=x0;x<=x1;x++)for(let z=z0;z<=z1;z++)a.push([X(x),y,Z(z)]);return a};
const aBase=o=>({placed:false,requires:[],signal:'WATER',severity:50,weight:1,color:15,cover:[],...o,id:o.id||`p${++serial}`});
function rect({id,file,name,x0,x1,z0,z1,topY,height=24,r=ID,color=15,minContacts,spread=0,signal='WATER',severity=60,weight=1,label,requires=[],cover=[]}){const bottom=cells(x0,x1,z0,z1,topY+height),top=cells(x0,x1,z0,z1,topY);return aBase({id,file,name,t:[CX(x0,x1),topY,CZ(z0,z1)],r,color,bottom,top,minContacts:minContacts??bottom.length,minSpread:spread,signal,severity,weight,label,requires,cover,kind:'structure'});}
function contiguous(vals){if(!vals.length)return[];const a=[...vals].sort((a,b)=>a-b),out=[];let s=a[0],p=a[0];for(let i=1;i<a.length;i++){if(a[i]===p+1){p=a[i];continue}out.push([s,p]);s=p=a[i]}out.push([s,p]);return out}
function tile(a,b,course,max=4){const out=[];let p=a,first=course%2?3:4;while(p<=b){let n=[first,max,4,3,2,1].find(n=>n<=max&&p+n-1<=b);if(!n)n=1;out.push([p,p+n-1]);p+=n;first=max}return out}
const weatherKey=(level,side,course,i)=>`${level}|${side}|${course}|${i}`;
function thickWall({level,b,course,baseY=0,openings={},skip={},color=15,signal='WATER',severity=80,label='ENVELOPE'}){
 const out=[];for(const side of ['front','back','left','right']){
  let start,end,x0,x1,z0,z1,axis;if(side==='front'||side==='back'){axis='x';start=b.x0;end=b.x1;if(course%2===0){start+=2;end-=2}z0=side==='front'?b.z0:b.z1-1;z1=z0+1}else{axis='z';start=b.z0;end=b.z1;if(course%2===1){start+=2;end-=2}x0=side==='left'?b.x0:b.x1-1;x1=x0+1}
  const blocked=new Set((openings[side]||[]).filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b)));for(const h of (skip[side]||[]).filter(h=>course===h.course))for(const v of range(h.a,h.b))blocked.add(v);
  const vals=range(start,end).filter(v=>!blocked.has(v));for(const [s,e] of contiguous(vals))for(const [u,v] of tile(s,e,course,4)){
   const len=v-u+1,part=P2[len],outer=side==='front'?b.z0:side==='back'?b.z1:side==='left'?b.x0:b.x1,cover=range(u,v).map(i=>weatherKey(level,side,course,i));
   if(axis==='x'){out.push(rect({file:part[0],name:part[1],x0:u,x1:v,z0,z1,topY:baseY-course*24,r:ID,color,signal,severity,weight:len*2,label:`${label} · ${side} · course ${course}`,cover}))}
   else{out.push(rect({file:part[0],name:part[1],x0,x1,z0:u,z1:v,topY:baseY-course*24,r:RY90,color,signal,severity,weight:len*2,label:`${label} · ${side} · course ${course}`,cover}))}
  }
 }
 return out;
}
function thinWall({idPrefix='SPINE',z0,x0,x1,course,baseY=0,holes=[],color=71,severity=88}){const blocked=new Set(holes.filter(h=>course>=h.from&&course<=h.to).flatMap(h=>range(h.a,h.b))),vals=range(x0,x1).filter(x=>!blocked.has(x)),out=[];for(const [a,b] of contiguous(vals))for(const [s,e] of tile(a,b,course,8)){const n=e-s+1,p=P1[n];out.push(rect({id:`${idPrefix}-${z0}-${course}-${s}`,file:p[0],name:p[1],x0:s,x1:e,z0,z1:z0,topY:baseY-course*24,color,signal:'GRAVITY',severity,weight:n,label:`${idPrefix} · z${z0} · course ${course}`}))}return out}
function lintelRow({id,x0,x1,z,course,baseY=0,color=15,label='LINTEL',level=null,side=null}){const n=x1-x0+1,p=P1[n];const cover=level&&side?range(x0,x1).map(i=>weatherKey(level,side,course,i)):[];return rect({id,file:p[0],name:p[1],x0,x1,z0:z,z1:z,topY:baseY-course*24,color,signal:'GRAVITY',severity:112,weight:n,minContacts:4,spread:(n-1)*20,label,cover})}
function windowPair({level,id,side,a,b,bounds,bottomY,baseCourse=2}){const out=[];let outerT,innerT,r,outerBottom,outerTop,innerBottom,innerTop;
 if(side==='front'){r=ID;outerT=[CX(a,b),bottomY-72,Z(bounds.z0)];innerT=[CX(a,b),bottomY-72,Z(bounds.z0+1)];outerBottom=cells(a,b,bounds.z0,bounds.z0,bottomY);outerTop=cells(a,b,bounds.z0,bounds.z0,bottomY-72);innerBottom=cells(a,b,bounds.z0+1,bounds.z0+1,bottomY);innerTop=cells(a,b,bounds.z0+1,bounds.z0+1,bottomY-72)}
 if(side==='back'){r=RY180;outerT=[CX(a,b),bottomY-72,Z(bounds.z1)];innerT=[CX(a,b),bottomY-72,Z(bounds.z1-1)];outerBottom=cells(a,b,bounds.z1,bounds.z1,bottomY);outerTop=cells(a,b,bounds.z1,bounds.z1,bottomY-72);innerBottom=cells(a,b,bounds.z1-1,bounds.z1-1,bottomY);innerTop=cells(a,b,bounds.z1-1,bounds.z1-1,bottomY-72)}
 if(side==='left'){r=RY90;outerT=[X(bounds.x0),bottomY-72,CZ(a,b)];innerT=[X(bounds.x0+1),bottomY-72,CZ(a,b)];outerBottom=cells(bounds.x0,bounds.x0,a,b,bottomY);outerTop=cells(bounds.x0,bounds.x0,a,b,bottomY-72);innerBottom=cells(bounds.x0+1,bounds.x0+1,a,b,bottomY);innerTop=cells(bounds.x0+1,bounds.x0+1,a,b,bottomY-72)}
 if(side==='right'){r=RY270;outerT=[X(bounds.x1),bottomY-72,CZ(a,b)];innerT=[X(bounds.x1-1),bottomY-72,CZ(a,b)];outerBottom=cells(bounds.x1,bounds.x1,a,b,bottomY);outerTop=cells(bounds.x1,bounds.x1,a,b,bottomY-72);innerBottom=cells(bounds.x1-1,bounds.x1-1,a,b,bottomY);innerTop=cells(bounds.x1-1,bounds.x1-1,a,b,bottomY-72)}
 const outer=aBase({id:`${id}-outer-frame`,file:'60593.dat',name:'Window 1 x 2 x 3',t:outerT,r,color:71,bottom:outerBottom,top:outerTop,minContacts:2,signal:'STRUCTURE',severity:94,weight:4,label:`${id} OUTER FRAME`,kind:'structure'}),inner=aBase({id:`${id}-inner-frame`,file:'60593.dat',name:'Window 1 x 2 x 3',t:innerT,r,color:71,bottom:innerBottom,top:innerTop,minContacts:2,signal:'STRUCTURE',severity:92,weight:4,label:`${id} INNER FRAME`,kind:'structure'});out.push(outer,inner);
 const cover=[];for(let c=baseCourse;c<baseCourse+3;c++)for(const i of range(a,b))cover.push(weatherKey(level,side,c,i));out.push(aBase({id:`${id}-outer-glass`,file:'60602.dat',name:'Window Glass 1 x 2 x 3',t:outerT,r,color:47,bottom:[],top:[],minContacts:0,signal:'WATER',severity:124,weight:26,label:`${id} OUTER GLASS`,kind:'closure',requires:[outer.id],cover}),aBase({id:`${id}-inner-glass`,file:'60602.dat',name:'Window Glass 1 x 2 x 3',t:innerT,r,color:47,bottom:[],top:[],minContacts:0,signal:'WATER',severity:110,weight:10,label:`${id} INNER GLASS`,kind:'closure',requires:[inner.id]}));return out}
function doorAssembly({level='G',id='front-door',a=30,b=33,bounds,frameY=-144}){const frameT=[CX(a,b),frameY,Z(bounds.z0)],frame=aBase({id:`${id}-frame`,file:'60596.dat',name:'Door 1 x 4 x 6 Frame',t:frameT,r:ID,color:71,bottom:[],top:[],minContacts:0,signal:'ACCESS',severity:120,weight:28,label:'FRONT DOOR FRAME · exact opening',kind:'closure',requires:['door-lintel-outer','door-lintel-inner']}),cover=[];for(let c=1;c<=6;c++)for(const i of range(a,b))cover.push(weatherKey(level,'front',c,i));const leaf=aBase({id:`${id}-leaf`,file:'60616b.dat',name:'Door 1 x 4 x 6 Smooth',t:[frameT[0]-32,frameY,frameT[2]+5],r:ID,color:4,bottom:[],top:[],minContacts:0,signal:'WATER',severity:132,weight:44,label:'FRONT DOOR LEAF · aligned to 60596 frame',kind:'closure',requires:[frame.id],cover});return[frame,leaf]}
function plate48({id,x0,x1,z0,z1,topY,signal='GRAVITY',severity=96,weight=28,label='DIAPHRAGM',color=4,minContacts=10,spread=120,r=RY90}){return rect({id,file:'3035.dat',name:'Plate 4 x 8',x0,x1,z0,z1,topY,height:8,r,color,signal,severity,weight,label,minContacts,spread})}
function column22({id,x,z,course,baseY=0,color=71,label='COLUMN'}){return rect({id,file:'3003.dat',name:'Brick 2 x 2',x0:x,x1:x+1,z0:z,z1:z+1,topY:baseY-course*24,color,signal:'GRAVITY',severity:84,weight:4,label:`${label} · course ${course}`})}
function weatherTargets(level,b,courses){const set=new Set;for(let c=1;c<=courses;c++){for(const x of range(b.x0,b.x1)){set.add(weatherKey(level,'front',c,x));set.add(weatherKey(level,'back',c,x))}for(const z of range(b.z0,b.z1)){set.add(weatherKey(level,'left',c,z));set.add(weatherKey(level,'right',c,z))}}return set}
export function makePlan(){serial=0;const a=[],G={x0:10,x1:53,z0:5,z1:26},go={front:[{a:30,b:33,from:1,to:6},{a:16,b:17,from:2,to:4},{a:23,b:24,from:2,to:4},{a:40,b:41,from:2,to:4},{a:47,b:48,from:2,to:4}],back:[{a:14,b:15,from:2,to:4},{a:22,b:23,from:2,to:4},{a:32,b:33,from:2,to:4},{a:44,b:45,from:2,to:4}],left:[{a:10,b:11,from:2,to:4},{a:20,b:21,from:2,to:4}],right:[{a:11,b:12,from:2,to:4},{a:20,b:21,from:2,to:4}]},skip={front:[{course:7,a:28,b:35}]};
 for(let c=1;c<=7;c++)a.push(...thickWall({level:'G',b:G,course:c,openings:go,skip,label:'GROUND 2-STUD ENVELOPE'}));a.push(lintelRow({id:'door-lintel-outer',x0:28,x1:35,z:G.z0,course:7,label:'DOOR OUTER LINTEL · both jambs',level:'G',side:'front'}),lintelRow({id:'door-lintel-inner',x0:28,x1:35,z:G.z0+1,course:7,label:'DOOR INNER LINTEL · both jambs'}));
 const gw=[['gf1','front',16,17],['gf2','front',23,24],['gf3','front',40,41],['gf4','front',47,48],['gb1','back',14,15],['gb2','back',22,23],['gb3','back',32,33],['gb4','back',44,45],['gl1','left',10,11],['gl2','left',20,21],['gr1','right',11,12],['gr2','right',20,21]];for(const [id,s,x0,x1] of gw)a.push(...windowPair({level:'G',id,side:s,a:x0,b:x1,bounds:G,bottomY:-24}));a.push(...doorAssembly({bounds:G}));
 const spineH=[{a:22,b:25,from:1,to:6},{a:38,b:41,from:1,to:6}];for(const z of [12,13,19,20])for(let c=1;c<=7;c++){const holes=(z<=13?spineH:[{a:28,b:31,from:1,to:6}]);a.push(...thinWall({idPrefix:z<=13?'FRONT SPINE':'REAR SPINE',z0:z,x0:12,x1:51,course:c,holes}))}
 for(const z of [12,13])for(const [n,s,e] of [['A',20,27],['B',36,43]])a.push(lintelRow({id:`spine-lintel-${z}-${n}`,x0:s,x1:e,z,course:7,color:71,label:'INTERNAL PASSAGE LINTEL'}));
 // Front diaphragm and rear roof: each 4x8 plate must touch two separated support lines.
 for(let x=10;x<=50;x+=4)a.push(plate48({id:`front-deck-${x}`,x0:x,x1:x+3,z0:5,z1:12,topY:-176,signal:'GRAVITY',severity:116,weight:38,label:'FRONT UPPER FLOOR / TERRACE',minContacts:12,spread:140}));for(let x=10;x<=50;x+=4)a.push(plate48({id:`rear-roof-${x}`,x0:x,x1:x+3,z0:19,z1:26,topY:-176,signal:'WATER',severity:122,weight:42,label:'REAR FLAT ROOF',minContacts:12,spread:140}));
 // Upper atelier bar, two studs thick, ten double-glazed windows.
 const U={x0:14,x1:45,z0:5,z1:12},uo={front:[{a:18,b:19,from:2,to:4},{a:25,b:26,from:2,to:4},{a:34,b:35,from:2,to:4},{a:41,b:42,from:2,to:4}],back:[{a:18,b:19,from:2,to:4},{a:27,b:28,from:2,to:4},{a:36,b:37,from:2,to:4},{a:41,b:42,from:2,to:4}],left:[{a:8,b:9,from:2,to:4}],right:[{a:8,b:9,from:2,to:4}]};for(let c=1;c<=6;c++)a.push(...thickWall({level:'U',b:U,course:c,baseY:-176,openings:uo,label:'UPPER ATELIER ENVELOPE',severity:98}));const uw=[['uf1','front',18,19],['uf2','front',25,26],['uf3','front',34,35],['uf4','front',41,42],['ub1','back',18,19],['ub2','back',27,28],['ub3','back',36,37],['ub4','back',41,42],['ul1','left',8,9],['ur1','right',8,9]];for(const [id,s,m,n] of uw)a.push(...windowPair({level:'U',id,side:s,a:m,b:n,bounds:U,bottomY:-200}));
 for(let x=14;x<=42;x+=4)a.push(plate48({id:`upper-roof-${x}`,x0:x,x1:x+3,z0:5,z1:12,topY:-328,signal:'WATER',severity:132,weight:50,label:'UPPER WEATHER ROOF',minContacts:12,spread:140}));
 // Roof pavilion / third level.
 const P={x0:24,x1:35,z0:5,z1:12},po={front:[{a:27,b:28,from:1,to:3},{a:31,b:32,from:1,to:3}],back:[{a:27,b:28,from:1,to:3},{a:31,b:32,from:1,to:3}],left:[],right:[]};for(let c=1;c<=4;c++)a.push(...thickWall({level:'P',b:P,course:c,baseY:-328,openings:po,label:'ROOF ROOM ENVELOPE',severity:106,color:71}));for(const [id,s,m,n] of [['pf1','front',27,28],['pf2','front',31,32],['pb1','back',27,28],['pb2','back',31,32]])a.push(...windowPair({level:'P',id,side:s,a:m,b:n,bounds:P,bottomY:-328,baseCourse:1}));for(let x=24;x<=32;x+=4)a.push(plate48({id:`pavilion-roof-${x}`,x0:x,x1:x+3,z0:5,z1:12,topY:-432,signal:'WATER',severity:140,weight:62,label:'ROOF ROOM CAP',minContacts:12,spread:140}));
 // Balcony into courtyard: six columns, three 8x4 plates, guard wall.
 for(const x of [18,28,38])for(const z of [13,15])for(let c=1;c<=7;c++)a.push(column22({id:`bal-col-${x}-${z}-${c}`,x,z,course:c,label:'COURTYARD BALCONY COLUMN'}));for(const x of [18,26,34])a.push(rect({id:`balcony-${x}`,file:'3035.dat',name:'Plate 4 x 8',x0:x,x1:x+7,z0:13,z1:16,topY:-176,height:8,r:ID,color:4,signal:'GRAVITY',severity:108,weight:32,label:'COURTYARD BALCONY',minContacts:8,spread:140}));for(const [s,e] of [[18,25],[26,33],[34,41]])a.push(lintelRow({id:`bal-guard-${s}`,x0:s,x1:e,z:16,course:1,baseY:-176,color:71,label:'BALCONY GUARD',level:null}));
 // Entrance porch: six real 2x2 columns, canopy, stepped approach.
 for(const x of [26,31,36])for(const z of [1,3])for(let c=1;c<=7;c++)a.push(column22({id:`porch-${x}-${z}-${c}`,x,z,course:c,label:'ENTRY PORCH COLUMN'}));a.push(rect({id:'porch-canopy-a',file:'3035.dat',name:'Plate 4 x 8',x0:26,x1:33,z0:1,z1:4,topY:-176,height:8,r:ID,color:4,signal:'RAIN_ENTRY',severity:106,weight:34,label:'ENTRY CANOPY LEFT',minContacts:8,spread:100}),rect({id:'porch-canopy-b',file:'3035.dat',name:'Plate 4 x 8',x0:34,x1:41,z0:1,z1:4,topY:-176,height:8,r:ID,color:4,signal:'RAIN_ENTRY',severity:106,weight:34,label:'ENTRY CANOPY RIGHT',minContacts:8,spread:100}));for(const [id,x0,x1,z0,z1,y,file,name] of [['step1',29,34,3,4,-8,'3020.dat','Plate 2 x 4'],['step2',30,33,4,4,-16,'3710.dat','Plate 1 x 4'],['threshold',30,33,5,5,-8,'3710.dat','Plate 1 x 4']])a.push(rect({id,file,name,x0,x1,z0,z1,topY:y,height:8,color:71,signal:'ACCESS',severity:72,weight:8,label:'ENTRY STEP / THRESHOLD'}));
 // Chimney: real 2x2 bricks stacked from upper roof.
 for(let c=1;c<=5;c++)a.push(rect({id:`chimney-${c}`,file:'3003.dat',name:'Brick 2 x 2',x0:38,x1:39,z0:8,z1:9,topY:-328-c*24,height:24,color:1,signal:'VENT',severity:70,weight:5,label:`CHIMNEY · course ${c}`}));
 // Weather target sets are stored on plan for CI; closures supply the opening cells.
 Object.defineProperty(a,'weatherTargets',{value:new Set([...weatherTargets('G',G,7),...weatherTargets('U',U,6),...weatherTargets('P',P,4)]),enumerable:false});return a}
export function baseSupports(){const m=new Map;for(let x=0;x<64;x++)for(let z=0;z<32;z++){const p=[X(x),0,Z(z)],s={id:`BASE-${x}-${z}`,p,used:false};m.set(key(p),s)}return m}
export function stateFor(actions){return{actions,placements:[],supports:baseSupports(),placedIds:new Set,clicks:0}}
function depOK(a,s){return(a.requires||[]).every(id=>s.placedIds.has(id))}
function seat(a,s){if(!depOK(a,s))return{ok:false,contacts:[],need:a.minContacts||0,reason:'DEPENDENCY'};if(a.kind==='closure')return{ok:true,contacts:[],need:0,spread:0,protocol:'fit'};const contacts=[];for(const p of a.bottom||[]){const q=s.supports.get(key(p));if(q&&!q.used)contacts.push({support:q,p})}let spread=0;for(let i=0;i<contacts.length;i++)for(let j=i+1;j<contacts.length;j++)spread=Math.max(spread,Math.hypot(contacts[i].p[0]-contacts[j].p[0],contacts[i].p[2]-contacts[j].p[2]));const need=a.minContacts??a.bottom.length;return{ok:contacts.length>=need&&spread>=(a.minSpread||0),contacts,need,spread,protocol:'stud-clutch'}}
export function unresolved(s){return s.actions.filter(a=>!a.placed)}
export function hear(s){const open=unresolved(s).sort((a,b)=>(b.severity*b.weight)-(a.severity*a.weight)),raw=open[0]||null;let choice=null;for(const action of open){const st=seat(action,s);if(st.ok){choice={action,seat:st};break}}return{open,raw,choice}}
export function commit(a,s){const st=seat(a,s);if(!st.ok)return null;if(a.kind==='structure'){for(const c of st.contacts)c.support.used=true;for(const p of a.top||[]){const k=key(p);if(!s.supports.has(k))s.supports.set(k,{id:`${a.id}:${k}`,p,used:false,owner:a.id})}s.clicks+=st.contacts.length}a.placed=true;s.placedIds.add(a.id);s.placements.push(a);return{contacts:st.contacts,clicks:a.kind==='structure'?st.contacts.length:0,protocol:st.protocol}}
export function signalLoad(s,signal){return unresolved(s).filter(a=>a.signal===signal).reduce((n,a)=>n+a.weight,0)}
export function weatherMissing(s){const targets=s.actions.weatherTargets||new Set,cov=new Set;for(const a of s.placements)for(const c of a.cover||[])cov.add(c);return[...targets].filter(k=>!cov.has(k))}
export function simulate(actions=makePlan(),limit=3000){const s=stateFor(actions);let moves=0;while(moves<limit){const h=hear(s);if(!h.raw||!h.choice)break;commit(h.choice.action,s);moves++}return{state:s,moves,remaining:unresolved(s),clicks:s.clicks,weatherMissing:weatherMissing(s)}}
const fmt=n=>Math.abs(n)<1e-9?'0':Number(n.toFixed(6)).toString();export function toLDraw(s,title='BEAVER-COURT-HOUSE-II'){const lines=[`0 ${title}`,`0 Name: ${title}.mpd`,`0 !LDRAW_ORG Model`,`0 // 64x32 site · piece-level support graph · envelope continuity tested`,`1 2 -320 0 0 1 0 0 0 1 0 0 0 1 3811.dat`,`1 2 320 0 0 1 0 0 0 1 0 0 0 1 3811.dat`];for(const a of s.placements)lines.push(`1 ${a.color??16} ${fmt(a.t[0])} ${fmt(a.t[1])} ${fmt(a.t[2])} ${(a.r||ID).map(fmt).join(' ')} ${a.file}`);return lines.join('\n')+'\n'}
